### ISSUE TITLE
实际使用发现误差极大

### ISSUE THREAD

**Issue by chocolatesir** [wangshub/wechat_jump_game#1]
从第一格开始，每一次跳跃距离鼠标点的起始位置相差非常大，所以跳个4,5格就完了。。

**Comment by wangshub** [comment]
昨晚上写的不太完善，后面再加上图像识别就好了，
原因是因为不同手机的分辨率不一样，所以距离与时间的系数需要调整一下 @chocolatesir

**Comment by gaorongchao** [comment]
楼主很给力，自己搞搞，随便搞个1000多分，可以霸屏一段时间了

**Comment by liyue201** [comment]
很给力，已经上1000多，故意输掉的

**Comment by crazyxhz** [comment]
@wangshub 能否指点下 主要调整那几个参数啊？小米6， 1920*1080 分辨率，误差比较大，大部分情况下得1分，很少能算到完全中心的，

**Comment by chocolatesir** [comment]
@crazyxhz 系数调小一点试试，默认是1.35，你改成1.05到1.1试试

**Comment by MrLevo520** [comment]
0. 请使用最新版代码
1. 使用adb免配置版本
2. 使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
下次请规范提交issue，谢谢
