### ISSUE TITLE
落脚点y坐标问题

### ISSUE THREAD

**Issue by sqlce** [wangshub/wechat_jump_game#100]
现在的board_y是利用角度求解，测试发现board_x可以求解的相对很好，所以对x=board_x这条线进行循环，利用类似求解board_x的方法求中点，虽然费时些，但是感觉效果更好

**Comment by Delete1994** [comment]
我也是这样做的，但是下面的阴影会有影响
```
 #x，竖线扫描 
    for i in range(300,piece_y+50):
        last_pixel = pixels[w*i]  #背景色
        pixel = pixels[board_x+i*w]
        #阴影也计算了
        if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 50:
            board_y_sum += i
            board_y_c += 1
    board_y = board_y_sum / board_y_c 
```

**Comment by sqlce** [comment]
我是比对相同的颜色，棋子的位置piece_y已经算出来了，新盒子不太可能出现在小于piece_y的部分。rgb是计算board_x时rgb = im.getpixel((board_x, i)) 
#---------------------------------------------
    board_y_sum = 0
    board_y_c = 0
    for i in range(h): #截图像素纵坐标循环
        if i < piece_y:  #因为新盒子不太可能出现在该部分，跳过以下像素
            continue
        pixel = im.getpixel((board_x, i))  #在竖线上找像素     
        if abs(pixel[0] - rgb[0]) + abs(pixel[1] - rgb[1]) + abs(pixel[2] - rgb[2]) < 10:
            board_y_sum += i
            board_y_c += 1
    if board_y_sum:
        board_y = board_y_sum / board_y_c

**Comment by sqlce** [comment]
@Delete1994

**Comment by wangshub** [comment]
已优化
