### ISSUE TITLE
小米Note3成绩不佳，270以内，大多86和176步挂

### ISSUE THREAD

**Issue by wqw547243068** [wangshub/wechat_jump_game#1001]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 440
Device: jason
Phone OS: 7.1.1
Host OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
**********

遇到问题：小米Note3成绩不佳，基本在200以内挂掉，缺少配套配置

改进和建议：无

**Comment by robot527** [comment]
@wqw547243068 
#DEBUG 开关，需要调试的时候请改为 True，不需要调试的时候为 False
DEBUG_SWITCH = False
将调试开关改为 True ，运行后看看 screenshot_backups   目录下的图片，可能会找到原因。

**Comment by Marcello168** [comment]
我的小米note3 也是啊

**Comment by Marcello168** [comment]
怎么改参数呢?
