### ISSUE TITLE
iphone7 第一个方块正中中心，第二个就歪了，试了好几次没有超过10分过

### ISSUE THREAD

**Issue by y6821552** [wangshub/wechat_jump_game#1003]
程序版本号：x.x.x
iphone7，10.3.3
Screen: Physical size: 4.7
Density: Physical density: 1334 x 750
Override density: x
DeviceType: iphone7
OS: Mac osx10.13.2
Python: 3.6.4

最多跑了6分，是怎么回事呢？

**Comment by kiminiuso** [comment]
config修改"press_coefficient“的参数

**Comment by MrLevo520** [comment]
尝试使用nightly版本

**Comment by y6821552** [comment]
好的，我试下。感谢！
