### ISSUE TITLE
小米5   可能是连接不上

### ISSUE THREAD

**Issue by Earl-chen** [wangshub/wechat_jump_game#1006]
![default](https://user-images.githubusercontent.com/29749997/34650451-87b40ac6-f3fc-11e7-8554-615ac600fc54.png)

**Comment by ctrysbita** [comment]
There is nothing wrong with my MI5. You may check your settings.

**Comment by Earl-chen** [comment]
@ctrysbita 
![default](https://user-images.githubusercontent.com/29749997/34650591-859216fa-f3fe-11e7-9d19-c659800b7f58.png)


一直连接不上，两个调试都打开了，还有哪些需要注意的啊？

**Comment by edwardfang** [comment]
Please check your USB debugging Security Setting

**Comment by Robertccl** [comment]
我当时遇到这个问题是因为，我之前改了防火墙，后面发现了，adb添加进去，就好了

**Comment by minifive** [comment]
小米5  系统miui9.1   开两个调试能正常跑 ，参数需要修改

**Comment by huqianshan** [comment]
@minifive 参数是多少呀
