### ISSUE TITLE
谁给一个魅族Pro6Plus的参数啊

### ISSUE THREAD

**Issue by 00why00** [wangshub/wechat_jump_game#1007]
魅族Pro6Plus直接第一次飞出去了
自己跳了几次也不行

**Comment by MrLevo520** [comment]
请使用nightly版本做尝试

**Comment by ore-lingyu** [comment]
魅族Pro6Plus直接第一次飞出去了
自己跳了几次也不行

**Comment by ore-lingyu** [comment]
最新版的，如果调用的wechat_jump_auto.py，修改config\2560x1440文件夹下config.json文件，"press_coefficient": 1.0355，目前最高分1890
