### ISSUE TITLE
wechat_jump_auto.py代码在运行，为什么小游戏中的小棋未跳？

### ISSUE THREAD

**Issue by Suera** [wangshub/wechat_jump_game#1009]
<!--
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。
请说清楚自己遇到了什么问题，不然可能被 close。
还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。

### 如果代码不能启动，执行的时候直接报错

请贴出：
1. 代码版本号，代码中的 VERSION 变量
2. 使用环境（操作系统、Python 版本）
3. 尽量完整的代码执行命令，和打印的错误信息

### 如果代码能运行，但是达不到想要的效果

请贴出：
1. 代码版本号，代码中的 VERSION 变量
2. 使用环境 (运行脚本中已包含自动识别功能，复制即可)
3. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）
具体实例如下，按照该例进行提交 issue

程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：
wechat_jump_auto.py代码在自动运行，手机和电脑也连接无误，然而手机上的小游戏里的小棋子始终在
游戏开始后的第一的小方块上不动
电脑和手机连接无误

- 
![image](https://user-images.githubusercontent.com/23256429/34650747-197a9e44-f401-11e7-87b6-7c77e51ad486.png)

- 

改进和建议：无

**Comment by robot527** [comment]
[issues-472](https://github.com/wangshub/wechat_jump_game/issues/472)
可能是这个问题的原因。

**Comment by htccc** [comment]
在开发者选项里找找 启用模拟点击功能

**Comment by Suera** [comment]
嗯，好的，，问题已解决谢谢 @robot527 @htccc
