### ISSUE TITLE
android 4.2.2 系统有adb命令能模拟这个长按吗？

### ISSUE THREAD

**Issue by robot527** [wangshub/wechat_jump_game#1011]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题： swipe 命令控制不了足够长的时间
```
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad] tap <x> <y>
       input [touchscreen|touchpad] swipe <x1> <y1> <x2> <y2>
       input trackball press
       input trackball roll <dx> <dy>
```

改进和建议：无

**Comment by Yuecuize** [comment]
adb shell input touchscreen swipe {x1} {y1} {x2} {y2} {duration}
试过了吗，加个touchscreen

**Comment by robot527** [comment]
@Yuecuize  试过了，没用。
提示的命令用法表明 swipe 后只能跟4个参数， 而{duration}是第5个了。

**Comment by Yuecuize** [comment]
我上次试安卓机，就是这么搞定的，但是安卓版本号我忘记了。
一开始提示我swipe不能5个参数，我就用了 touchscreen swipe
