### ISSUE TITLE
已被和谐 分数被腾讯自动清零

### ISSUE THREAD

**Issue by qianzhujun** [wangshub/wechat_jump_game#1013]
windows 
荣耀9真机
分数777，再次进来后，分数为0

**Comment by scc897577** [comment]
@qianzhujun  貌似都不行了....不知道该怎么去反处理

**Comment by SbyXlmm** [comment]
我这边3000分没问题，刷一会儿要停一下

**Comment by peach-djf** [comment]
应该可以把，坐标不设置那么精准，不能每次都击中中心，正常人的能力，就是2,4,6,8这样的分数，如果连续多次中会被判定，应该改1,2,4,6，然后随机1,2,4，6这样应该比较安全。我刷的1000+就被清空了。多次击中后一次到20+分

**Comment by scc897577** [comment]
@SbyXlmm 你3000分没被和谐呐,排行榜能显示出来?

**Comment by peach-djf** [comment]
有老铁知道，现在修改了代码，怎么重新打包成exe吗

**Comment by MrLevo520** [comment]
@ peach-djf 今日会完成版本更新的打包工作

**Comment by Bleoo** [comment]
`
press_time += random.randint(-20, 20)
`
jump函数中 增加噪点 使跳跃失去一点精准度，可以通过tx。

**Comment by qianzhujun** [comment]
亲测，精度不要太准，分数不要太逆天的情况下，不会被清零。可以手动跳几下。
