### ISSUE TITLE
建议添加加分图标的识别后停留，这样分多

### ISSUE THREAD

**Issue by htccc** [wangshub/wechat_jump_game#1015]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by htccc** [comment]
添加加分图标的识别并停留以加分

**Comment by hebiao141907** [comment]
？？？

**Comment by 6324up** [comment]
不会啊，叠加中心后随便一跳就20，30分

**Comment by BMlovePanda** [comment]
你可以考虑延长sleep的时间，我的是1s到1.5s，反正停留的时间够加分图标加分了。

**Comment by htccc** [comment]
延长时间的话，是不是要刷很久

**Comment by Ash-zd** [comment]
延长sleep时间吧。原来是0.9-1.2，只要比1大特殊建筑就能够计分了，没比原来慢太多。
