### ISSUE TITLE
iPhoe6程序自动刷分,分数上去后,再次进入跳一跳分数清零

### ISSUE THREAD

**Issue by HanMR** [wangshub/wechat_jump_game#1016]
用程序自动或手动跳,分数都要被和谐,是不是监测到了

**Comment by peach-djf** [comment]
win 版本在wechat_jump_auto.py 文件中，修改78行，把按压的时间调整下        duration=press_time+30，我这里增加了30毫秒，每次跳跃就1分2分这样，安全起飞

**Comment by cwwise** [comment]
我是把 时间乘一个随机数 0.98-1.02  点击的位置也随机 刷到1000分没有问题，再高还没有试过。。

**Comment by mousehaow** [comment]
苹果的代码太老了，需要自己改很多地方

**Comment by xiaopiandao** [comment]
感觉上午刷了几次都是不得行的
