### ISSUE TITLE
你好，我想问问，小米5 plus 的配置怎么改啊，配置文件那几个参数是什么啊？

### ISSUE THREAD

**Issue by lyb-nullthink** [wangshub/wechat_jump_game#1017]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by MrLevo520** [comment]
请直接尝试使用nightly版本，下次提交请注意issue规范
