### ISSUE TITLE
小米note3 参数怎么配置

### ISSUE THREAD

**Issue by lixing2017** [wangshub/wechat_jump_game#102]

**Comment by mjzcyhp** [comment]
大神，我的手机和你一样的，我运行的时候说“”plt“”is not defined，这怎么回事啊，而且界面也不动

**Comment by wangshub** [comment]
@lixing2017 @mjzcyhp 请发到这个下面，该issue关闭
https://github.com/wangshub/wechat_jump_game/issues/62
