### ISSUE TITLE
现在是不是能刷了？刷完会被清零

### ISSUE THREAD

**Issue by mingxin-yang** [wangshub/wechat_jump_game#1020]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by xiaopiandao** [comment]
上午刷了，是被清零了的

**Comment by Charltsing** [comment]
可以刷分，但不要太高

**Comment by duenyuduenyu** [comment]
1000以上应该是不行的
