### ISSUE TITLE
2018-01-08中午还可以用

### ISSUE THREAD

**Issue by mrmoll** [wangshub/wechat_jump_game#1023]
我是苹果手机，所以安装了安卓模拟器,  跑了400多分就停了，没敢多跑，感觉这个挺好的，并不是一直跳到中间，偶尔会有得1分的时候，
模拟器的分辨率啥得 我是直接鼠标调小的 也不知道多少，然后执行代码 就可以跳了  ，一次就成功了

**Comment by MrLevo520** [comment]
请提交代码版本，或者release版本，谢谢

**Comment by ShawnKwins** [comment]
2018-1-9下午两点 已经不能用了

**Comment by saminlu** [comment]
@ShawnKwins 你还能预言

**Comment by Muller7z** [comment]
@mrmoll 试了好几个安卓模拟器都不行，打开跳一跳会闪退

**Comment by zhuweiyou** [comment]
我就想知道你用的什么模拟器，试了几个都是闪退或者直接提示不支持

**Comment by mrmoll** [comment]
@Muller7z 我用的是雷电模拟器

**Comment by mrmoll** [comment]
@zhuweiyou 雷电模拟器

**Comment by mrmoll** [comment]
@ShawnKwins 刚试了 可以用
