### ISSUE TITLE
三星S6 edge 第一次起跳落点就不准，第二次起跳直接失败，有没有解决方案，或者或微信采取了什么措施吗。

### ISSUE THREAD

**Issue by keaifan** [wangshub/wechat_jump_game#1024]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by wangtun** [comment]
是不是屏幕分辨率不一样

**Comment by MrLevo520** [comment]
请尝试使用nightly版本

**Comment by keaifan** [comment]
nightly
