### ISSUE TITLE
2018/1/8 下午两点。测试不可以。程序在跑，小程序没有任何反应

### ISSUE THREAD

**Issue by ShawnKwins** [wangshub/wechat_jump_game#1026]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by c475570815** [comment]
我也是

**Comment by MrLevo520** [comment]
请按规范提交issue，什么版本号，手机型号分辨率都没有，无法提供的任何帮助
