### ISSUE TITLE
有人有三星note8参数吗

### ISSUE THREAD

**Issue by bingtanguan** [wangshub/wechat_jump_game#103]

**Comment by F5F5** [comment]
### 没有，太难调了

**Comment by bingtanguan** [comment]
我也调了好一会儿了，调好了分享一下啊

**Comment by wangshub** [comment]
请发到这个issue下面哈
https://github.com/wangshub/wechat_jump_game/issues/62

**Comment by wangshub** [comment]
@bingtanguan @F5F5

**Comment by rocskyfly** [comment]
you can try:
"under_game_score_y": 460,
"press_coefficient": 1.0935,
"piece_base_height_1_2": 70,
"piece_body_width": 75
}

make sure setting screen resolution is the largest.

**Comment by slowguy** [comment]
{
    "under_game_score_y": 460,
    "press_coefficient": 1.125,
    "piece_base_height_1_2": 70,
    "piece_body_width": 75
}
samsung s8
大部分时间可以跳到中心，经测试到800手动自杀了，怕被封。

**Comment by mai-kuraki** [comment]
{
    "under_game_score_y": 460, 
    "press_coefficient": 1.046, 
    "piece_base_height_1_2": 70, 
    "piece_body_width": 75
}
差不多能跳到中间
