### ISSUE TITLE
小米5跳不了

### ISSUE THREAD

**Issue by Robertccl** [wangshub/wechat_jump_game#1030]
我用小米5,之前跳一跳可以成功，最多跳过1000多，这几天又试发现一个都跳不了，第一个就直接跳过了，失败
而且之前感觉那个参数改了没啥用，1.3------3.0我都试过，差不太多

有人遇到和我一样的问题吗

**Comment by hold-baby** [comment]
我小米5能跳 但是最多只能跳100左右

**Comment by liveiu** [comment]
我的小米5也跳不了了，一跳adb就断了

![dd](https://user-images.githubusercontent.com/19245900/34663059-9f941e72-f48f-11e7-976d-dd0a66ecde55.png)

**Comment by MrLevo520** [comment]
请尝试使用最新版或者nightly版本，或者release的app版本

**Comment by Sopcce** [comment]
我的小米5可以跳 但是只能到200分 不知道为什么

**Comment by Robertccl** [comment]
用 @MrLevo520 ，可以了

**Comment by Robertccl** [comment]
感觉好像只会调用default.json,config.py里面没执行一样
