### ISSUE TITLE
iPhone6   ，都能运行起来，但是不准确，第一步就挂掉了

### ISSUE THREAD

**Issue by cryboyofyu** [wangshub/wechat_jump_game#1032]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

iPhone6   ，都能运行起来，但是不准确，第一步就挂掉了

**Comment by 3ompact** [comment]
应该是config里的参数问题，调整或者是修改看看

**Comment by cryboyofyu** [comment]
这里面的参数{
    "under_game_score_y": 200,
    "press_coefficient": 2.0,
    "piece_base_height_1_2": 13,
    "piece_body_width": 49,
    "swipe": {
        "x1": 375,
        "y1": 1055,
        "x2": 375,
        "y2": 1055
    }
}
具体调整哪个呢？现在跑了几步就挂

**Comment by byljbdh** [comment]
看看是不是打开了悬浮球
