### ISSUE TITLE
iPhone + Windows

### ISSUE THREAD

**Issue by Liangmp** [wangshub/wechat_jump_game#1034]
我用Android(华为)+windows7成功跑了起来，但是Wiki上貌似没有说iPhone+windows怎么跑
请问如何在Windows上连iPhone来跑代码呢？
我的是iPhone6, Windows7

**Comment by ZYSzys** [comment]
iOS需要wda，Windows上跑不起来…你可以试试在虚拟机里装Mac OS跑…

**Comment by Liangmp** [comment]
原来是这样，谢谢你的回复~
