### ISSUE TITLE
分数被清零了！

### ISSUE THREAD

**Issue by qdyubebe** [wangshub/wechat_jump_game#1035]
用了辅助后打到800+，结果分数被清零，目前无法恢复。
如何 是好？
现在打多少分数都被清零！

**Comment by 3ompact** [comment]
修改按压时间，不要让他一直连击中心

**Comment by iamjiangyong** [comment]
怎么修改乐

**Comment by journeyly** [comment]
我修改按压时间也没用，可能是设备被拉黑了

**Comment by hu-qi** [comment]
最好别超过1000

**Comment by tyl210110** [comment]
1000以上一定被清零，刷个四五百分装个逼就差不多了

**Comment by jackPanyj** [comment]
我521都被清了。。。

**Comment by hu-qi** [comment]
我不确定跟我手动操作了两三次有没有关系  两周都是刷到800多分然后手动搞挂的，理论上是没关系的。

**Comment by yang-va** [comment]
昨天玩了个七百多，当时有分，今天看就没了，刚才玩了个五百多，被清了。
估计是检测玩的时间了，程序设置的每个板停留的时间都一样的，为了得到音乐板，超市，井盖那些停留的分，所以每个板的时间都挺久的，正常人玩一般没特殊功能的板就会立马跳过去的。我估计这个跳一跳官方是用这个跳板个数来计算玩一局的总用时，如果不正常就清零，不知道对不对，今天有空搞一下看看

**Comment by duenyuduenyu** [comment]
修改按压位置 不要一直按一个地方 亲测有效
