### ISSUE TITLE
小米note2 分数太低，，最高101分。无法装X啊

### ISSUE THREAD

**Issue by SuezhouAndroid** [wangshub/wechat_jump_game#1036]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by regular1024** [comment]
小米6最好跳了一次200+，还没有我手动跳的好=，=

**Comment by maoturing** [comment]
我的设备管理器中就找不到我的手机啊，你是怎么做到的？

**Comment by George-fu** [comment]
小米6 ，装逼老是失败
