### ISSUE TITLE
我们真的没办法了吗？

### ISSUE THREAD

**Issue by yulincoder** [wangshub/wechat_jump_game#1039]
### 现在刷分会被ban掉，只能自己看，好友里面都不会出现你了。

我个人尝试过
* 修改参数（不跳中间），失败。
* 替朋友（iso用户）用我的安卓刷，发现刷完需要重新安装微信。一开始成功，后来失败。

不知各路大神还有什么招，_挺挫败感的._

目前我个人的问题主要以下几点：
腾讯如何发现使用本项目刷分：
 1.  是否会检测adb连接？
 2.  是否分数与上次相比突然变大，则判断为刷分？

针对第一点，我尚无对策，我不是做这一块的，对adb的机制不了解，如果这个问题不解决，我们似乎只有物理外挂一条路可走了。
针对第二点，是否可以设置程序每次刷分刷到一定程度自动死掉，然后重新开始，每次进步个几十分。

不爽的是腾讯不给测试机会，ban掉了就木的机会了。

**Comment by WangDanpeng** [comment]
目前看来是不行了
1. 不跳中间, 没有用, 我用手动点的照样不行.
2. 分数突然变大, 即使比上次多了一点也是不行的.

**Comment by ls19491314** [comment]
分高真爽，称霸武林！

**Comment by MerlinFeng** [comment]
还说晚上试试 看来不能上天了

**Comment by ZYSzys** [comment]
下午测试了下，把按压点和按压时间都用random函数随机处理下，500+没被ban。 
#1025

**Comment by ls19491314** [comment]
有办法，直接干翻！

**Comment by youwatchbonjovi** [comment]
random number 不要从uniform里面取值，做触屏fat-finger按压矫正的时候，一般偏差服从正态分布的。被ban以后持续玩个一二十次（不论手动还是代码玩），第二天就会从小黑屋被放出来了。

**Comment by hj7020580** [comment]
@youwatchbonjovi  请教一下radom不从uniform取值有什么好的办法么,做正太分布的具体步骤改怎么搞,还有持续玩个一二十次就放出来是什么意思...

**Comment by zhqingyong** [comment]
模拟的没事

**Comment by youwatchbonjovi** [comment]
@hj7020580    
我看到好多代码都是 random <- runif，按我以前做按压校正的经验，不论间隔时间，还是按压偏差，正态分布都更符合真人使用习惯，所以改成random <-rnorm 更合理，但是具体参数你可以在如下多试试。

以前因为刷分被拉进小黑屋，我猜测封禁的机制是在之后几十次游戏（不论分数高低）成绩都不会上榜，解决的方法就是再持续玩上几十次，解禁后成绩就会上榜了，我已经验证过了，又玩了大概2、30次左右。这个过程既可以调试正态分布的参数，又玩了游戏。

**Comment by yulincoder** [comment]
我后来做了一个图像识别加单片机舵机的物理外挂，不过感觉没啥意思了。
