### ISSUE TITLE
运行代码的时候微信小程序没有运行，但是有看到生成了一张截图了

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#104]
显示：NameError :name 'plt' is not defined;
这个错误是怎么回事啊，哪位大神说说啊？

**Comment by zerokisss** [comment]
运行pip install image或pip install image

**Comment by mjzcyhp** [comment]
@zerokisss 
好的，正在下

**Comment by zerokisss** [comment]
最好 安装一下 项目里面的 pip install -r requirements.txt

**Comment by mjzcyhp** [comment]
@zerokisss 项目里面的怎么安装啊？我就是运行这个代码的时候，显示安装不了，然后看到下面四行

生成requirements.txt文件
pip freeze > requirements.txt
安装requirements.txt依赖
pip install -r requirements.txt


之后pip install -r requirements.txt这个代码才能够运行，是这样吗？

**Comment by zerokisss** [comment]
先把这个项目下载下来 在终端打开项目所在地  然后在运行

**Comment by mjzcyhp** [comment]
@zerokisss /项目是说这个wecate_jump_auto .py 文件吗？我pip install -r requirements.txt之后，还是显示NameError :name 'plt' is not defined;。。。是不是需要下载plt什么的？

**Comment by zerokisss** [comment]
你看原作者上传的文件中有一个 requirements.txt

**Comment by mjzcyhp** [comment]
@zerokisss 这个文件我刚才已经改为作者的了
