### ISSUE TITLE
跪求增加ios inspector刷新按钮, 这样可以手动+鼠标连用,防止被清零分数了,谢谢

### ISSUE THREAD

**Issue by UniqHu** [wangshub/wechat_jump_game#1040]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by coderchaser** [comment]
这样好像也没用。
