### ISSUE TITLE
华为荣耀v9直接跳出去了

### ISSUE THREAD

**Issue by lifei1245** [wangshub/wechat_jump_game#1043]
```python
程序版本号：1.1.1
**********
Screen: Physical size: 1440x2560
Density: Physical density: 640
Device: HWDUK
Phone OS: 7.0
Host OS: win32
Python: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
```

设备为华为荣耀v9，这个些参数都自动检测到了，我就没有拖那个json，跳的过程中直接跳出屏幕了，1分都没

**Comment by lollipopnougat** [comment]
我也是V9，但是使用的是第二种方法，手动运行脚本

**Comment by albertofwb** [comment]
v8 表示一炮打响，排行榜荣登第二。 ps: 不敢弄得太高，怕ban

**Comment by wenxini234** [comment]
是不是加速球的影响

**Comment by lifei1245** [comment]
就是执行的脚本,第一跳就跳很远.  手机没下加上求

**Comment by wenxini234** [comment]
DEBUG_SWITCH =True 设置成true，看看screenshot_backups下的截图 @lifei1245

**Comment by lifei1245** [comment]
截图正常，跳的太用力 @wenxini234

**Comment by wenxini234** [comment]
"press_coefficient": 1.475, 这个系数改小一点试试

**Comment by Z1min** [comment]
参数如下 :  实测1000+
{
"under_game_score_y": 300,
"press_coefficient": 1.035,
"piece_base_height_1_2": 28,
"piece_body_width": 110,
"swipe": {
"x1": 320,
"y1": 410,
"x2": 320,
"y2": 410
}
}

**Comment by gudukuaile** [comment]
荣耀6
把按压时间设置成这样了 press_time = distance * 1.85，手动的才能玩起来。
不修改的话，一跳就掉下去了。每次跳完后，差不多三四秒才能刷新截图
