### ISSUE TITLE
跳一跳的反外挂措施是否加入了对adb连接状态的检测？？？

### ISSUE THREAD

**Issue by mohanyu** [wangshub/wechat_jump_game#1047]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by Charltsing** [comment]
目前没有

**Comment by fengqiangboy** [comment]
跳一跳只是个小程序，微信应该不会给小程序获取adb的权限。

**Comment by MrLevo520** [comment]
你真的是我们这一边的？😂😂

**Comment by sxl47** [comment]
目前会被封么？

2018-01-09 


---------------------------------------------------------------
姓名：宋小龙
电话：15198088521
公司：成都好房通科技有限责任公司



发件人：Willam <notifications@github.com>
发送时间：2018-01-09 11:21
主题：Re: [wangshub/wechat_jump_game] 跳一跳的反外挂措施是否加入了对adb连接状态的检测？？？ (#1047)
收件人："wangshub/wechat_jump_game"<wechat_jump_game@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

你真的是我们这一边的？😂😂

**Comment by Yggdrasill-7C9** [comment]
真当鹅厂不玩 gayhub 啊
