### ISSUE TITLE
谁有红米5plus的配置，太近的箱子容易掉下去

### ISSUE THREAD

**Issue by menglingqian0218** [wangshub/wechat_jump_game#1048]
求配置

**Comment by hurricanedjp** [comment]
同求

**Comment by SuperwangNo1** [comment]
同求

**Comment by JavaLuSir** [comment]
同求

**Comment by GeorgeBin** [comment]
{
    "under_game_score_y": 420,
    "press_coefficient": 1.373,
    "piece_base_height_1_2": 25,
    "piece_body_width": 85,
}

def jump(distance):
    """
    跳跃一定的距离
    """
    # 算法更新，旧算法：
    # press_time = distance * press_coefficient

    # 更新后
    if distance > 400:
        press_time = distance * press_coefficient * 1.05
    elif distance > 300:
        press_time = distance * press_coefficient * 1.19
    elif distance > 200:
        press_time = distance * press_coefficient * 1.23
    elif distance > 100:
        press_time = distance * press_coefficient * 1.19
    else:
        press_time = distance * press_coefficient * 1.18

**Comment by iljyya** [comment]
请问改那个配置文件呢？default.json ?

**Comment by terry520go** [comment]
不行
