### ISSUE TITLE
请教一个问题，距离和时间的关系是怎么得来的？

### ISSUE THREAD

**Issue by wjzhangcsu** [wangshub/wechat_jump_game#105]

**Comment by wjzhangcsu** [comment]
具体就是怎么得出来的时间和距离的线性关系？

**Comment by mjzcyhp** [comment]
@wjzhangcsu 大神，能够运行，但是显示错误：’NameError :name 'plt' is not defined;是怎么回事啊。
代码最后有个plt.show()

**Comment by wangshub** [comment]
之关系是线性的，拟合一下就出来了 @wjzhangcsu

**Comment by wangshub** [comment]
你没有import 这个库文件 @mjzcyhp

**Comment by mjzcyhp** [comment]
@wangshub 
怎么import 这个库文件啊

**Comment by wjzhangcsu** [comment]
具体如何你和呢？@wangshub

**Comment by wjzhangcsu** [comment]
具体是怎么拟合的，我在我手机上自己瞎试，但是就是找不到一个比较好的参数。@wangshub

**Comment by hakrtt** [comment]
@wangshub 你们安装的是哪个ADB包
