### ISSUE TITLE
使用两点距离算法造成转弯偏差【请求验证】

### ISSUE THREAD

**Issue by zr67800** [wangshub/wechat_jump_game#1050]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

似乎跳一跳中棋子从当前位置到下一个位置的跳跃距离（即正比于时间的距离）不是起落点之间的两点间距。棋子只在两个固定的轴向上跳跃。棋子在起跳格上的相对位置，只有在当前跳跃方向纵向的才被用来计算距离，而另一个方向的偏移会被忽略。而当前自动脚本算法直接使用两点距离，导致在变换跳跃方向的时候，如果棋子不是恰好在中心点，那计算出的跳跃距离会比实际需要的偏长（或者也有可能偏短，因为透视角度），导致下一个落点不在中心点。在同一方向连续跳跃是偏差可以被修正，但如果转换方向，遇到比较小的块就会掉下去。

改进和建议：

在计算跳跃距离的时候不是用两点间距，而是计算起落点在当前跳跃方向上的距离，也许有助于更准确的跳跃。

**Comment by SaneBow** [comment]
根据js代码来看是算的欧氏距离，在游戏世界坐标中，每次跳跃的方向向量为：目标块坐标-旗子坐标，向量长度与根据按压时间确定出。
