### ISSUE TITLE
能否提供辅助瞄准器，让玩家自己眺，而不是使用adb模拟命令

### ISSUE THREAD

**Issue by agan123** [wangshub/wechat_jump_game#1052]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：
在手机屏幕或电脑上提供瞄准器，比如实时提供当前落点，或者提供当前按压时间与所需时间进度条。来让玩家自己眺，而不使用adb命令来模拟按压动作

**Comment by Charltsing** [comment]
完全不准嘛，你哪有那么快的反应速度，给你进度条也不行

**Comment by agan123** [comment]
比自己凭感觉要强很多啦

**Comment by cmt2001** [comment]
想要直接在游戏上面显示东西不是adb命令能做到的，需要在安卓有客户端，工程量太大

**Comment by agan123** [comment]
可以在电脑上显示，获取按压事件，开始计时
