### ISSUE TITLE
【好消息】防ban成功 上周黑名单已解锁 继续燥起来～

### ISSUE THREAD

**Issue by Erimus-Koo** [wangshub/wechat_jump_game#1053]
刚才在安卓模拟器上跑了一遍，一千出头手动停掉。  
## 之后到iphone上查看，分数同步成功！  

> 此前安卓模拟器抓包，也都是没有errcode。
> 如果ban的话，安卓刷的分，换个设备是看不到的。

## 我的具体防ban措施如下：

- 间隔时间随机（具体看我代码）。
- 点击位置随机。
- 点击后位移随机。

我改的脚本提交PR还没通过，可以直接来 [我的页面](https://github.com/Erimus-Koo/wechat_jump_game) 看。
核心算法iOS安卓通用的，但iOS我没测试，所以就没整合。但算法是通用的。

PS: 黑名单大概持续一周。各位自己估摸下时间，可以试起来了。

![_20180109040723](https://user-images.githubusercontent.com/17139670/34690170-0befb23a-f4f3-11e7-8587-fb3fe3fe5cc4.jpg)

特意隔了段时间，并且抹掉分数，希望腾讯放我一马。( ͡° ͜ʖ ͡°)

**Comment by bobtoworld** [comment]
你确定你被拉进黑名单过吗？为什么我还在黑名单里。

**Comment by Leohc92** [comment]
你确定看过你在别人那里的分数？ 被BAN的帐号自己看分数正常，在别人那没分数的

**Comment by Erimus-Koo** [comment]
@bobtoworld 我被拉黑大概一周左右 可能你时间还没到？

**Comment by Erimus-Koo** [comment]
@Leohc92
跨设备分数同步了。

被ban的时候安卓分数在缓存不更新，只有自己看到。iOS同步到0分。

**Comment by LeaderXinjianSun** [comment]
怎么看自己有没有被拉黑？

**Comment by eMe-404** [comment]
自己的分数过几分钟就被清零了，然后完全手动玩也被清零了怎么破。。

**Comment by Erimus-Koo** [comment]
@LeaderXinjianSun 抓包。获得好友分数那里，被ban的话，自己分数同步下来是0。

**Comment by Erimus-Koo** [comment]
@eMe-404 就是被黑名单了，等一周左右。

**Comment by Kyle-Kyle** [comment]
1000多的不会被ban的。我用的是最简单的tap_hold random位置的算法。用相同的算法1000多分没问题。跑了一次1w多。就被发现了。分数没有被同步

**Comment by Erimus-Koo** [comment]
no zuo no die……

Erimus
