### ISSUE TITLE
为啥我用python3.6会报函数不存在的问题

### ISSUE THREAD

**Issue by fyk941127** [wangshub/wechat_jump_game#1054]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by fyk941127** [comment]
![wq1](https://user-images.githubusercontent.com/23652487/34706071-d9b27fee-f53f-11e7-93d3-d6cdc81ac953.png)
请问这个是怎么回事啊

**Comment by wenxini234** [comment]
没有配置文件吗

**Comment by z6269773** [comment]
请给python配置环境变量

**Comment by zhqingyong** [comment]
没把python路径加到环境吧
