### ISSUE TITLE
iOS自动脚本的优化，防ban和跳跃点选取

### ISSUE THREAD

**Issue by mousehaow** [wangshub/wechat_jump_game#1056]
## 自己测试了一下iphone7 跳跃系数1.96 刷到2101
tap_hold 改成了swipe同时根据随机的滑动距离求出动态的跳跃系数
同时跳跃点加入了白点判断，如果有白点直接跳到白点
iOS很多失败都是因为跳跃点选的有问题。。。。
### jump函数
`def jump(distance):`
    `# 随机的滑动距离，这样提交时steps字段就不为空`
    `randomX = random.uniform(5, 10)`
    `randomY = random.uniform(5, 10)`
    `random_length = (randomX * randomX + randomY * randomY) ** 0.5`
    `print('random length: {}'.format(random_length))`
    `# 求出动态的跳跃系数`
    `random_time_coefficient = random_length * (-0.011094) + time_coefficient`
    `print('random time coefficient: {}'.format(random_time_coefficient))`
    `press_time = distance * (random_time_coefficient)  / 1000`
    `print('press time: {}'.format(press_time))`
    `x1 = 218 + random.random() * 10`
    `y1 = 515 + random.random() * 10`
    `# s.tap_hold(x1, y1, press_time)`
    `# 改为swipe来操作`
    `s.swipe(x1, y1, x1 -  randomX, y1 + randomY, press_time)`
### 在find_piece_and_board函数里找到求board_x和board_y的地方修改成如下代码
`getBox = 0`
    `topPoint = 0`
    `for i in range (int (h / 3), int (h * 2 / 3)):
        last_pixel = im_pixel[0, i]
        if board_x or board_y:
            break
        board_x_sum = 0
        board_x_c = 0

        for j in range(w):
            pixel = im_pixel[j, i]
            # 修掉脑袋比下一个小格子还高的情况的 bug
            if abs(j - piece_x) < piece_body_width:
                continue

            # 修掉圆顶的时候一条线导致的小 bug，这个颜色判断应该 OK，暂时不提出来
            if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 50:
                if getBox:
                    board_x_sum += j
                    board_x_c += 1
                else: 
                    getBox = 1
                    topPoint = i
                    i += 5
                    continue

        if board_x_sum:
            board_x = board_x_sum / board_x_c - 5
    
    # 添加了有白点的情况判断，如果有白点直接跳跃至白点
    # iOS很多失败都是因为跳跃点选取有问题。。。。
    for l in range(topPoint, topPoint + 200):
        pixel = im_pixel[board_x, l]
        if abs(pixel[0] - 245) + abs(pixel[1] - 245) + abs(pixel[2] - 245) == 0:
            board_y = l + 5
            break
    # 按实际的角度来算，找到接近下一个 board 中心的坐标 这里的角度应该是30°,值应该是tan 30°, math.sqrt(3) / 3
    if board_y == 0:
        board_y = piece_y - abs(board_x - piece_x) * math.sqrt(3) / 3`

**Comment by Charltsing** [comment]
你这代码不能保证可靠啊，识别方块顶点应该从中间向一侧进行扫描，这样就躲开小人了

**Comment by mousehaow** [comment]
@Charltsing 刷过很多次，没碰到过小人干扰的问题

**Comment by iaMeteor** [comment]
方便格式化一下吗？

**Comment by doubleJJJJ** [comment]
运行好像有错误 能写清楚点吗？

**Comment by YAMsunshine** [comment]
第一处:
```
def jump(distance): 
    # 随机的滑动距离，这样提交时steps字段就不为空 
    randomX = random.uniform(5, 10)
    randomY = random.uniform(5, 10) 
    random_length = (randomX * randomX + randomY * randomY) ** 0.5 
    print('random length: {}'.format(random_length)) 
    # 求出动态的跳跃系数 
    random_time_coefficient = random_length * (-0.011094) + time_coefficient 
    print('random time coefficient: {}'.format(random_time_coefficient)) 
    press_time = distance * (random_time_coefficient) / 1000 
    print('press time: {}'.format(press_time)) 
    x1 = 218 + random.random() * 10 
    y1 = 515 + random.random() * 10 
    # s.tap_hold(x1, y1, press_time) # 改为swipe来操作 
    s.swipe(x1, y1, x1 - randomX, y1 + randomY, press_time)
```
第二处:
```
def find_piece_and_board(im):
    w, h = im.size

    print("size: {}, {}".format(w, h))

    piece_x_sum = piece_x_c = piece_y_max = 0

    board_x = board_y = 0
    scan_x_border = int(w / 8)  # 扫描棋子时的左右边界
    scan_start_y = 0  # 扫描的起始 y 坐标
    im_pixel = im.load()

    # 以 50px 步长，尝试探测 scan_start_y
    for i in range(under_game_score_y, h, 50):
        last_pixel = im_pixel[0, i]
        for j in range(1, w):
            pixel = im_pixel[j, i]

            # 不是纯色的线，则记录scan_start_y的值，准备跳出循环
            if pixel != last_pixel:
                scan_start_y = i - 50
                break

        if scan_start_y:
            break

    print("scan_start_y: ", scan_start_y)

    # 从 scan_start_y 开始往下扫描，棋子应位于屏幕上半部分，这里暂定不超过 2/3
    for i in range(scan_start_y, int(h * 2 / 3)):
        # 横坐标方面也减少了一部分扫描开销
        for j in range(scan_x_border, w - scan_x_border):
            pixel = im_pixel[j, i]
            # 根据棋子的最低行的颜色判断，找最后一行那些点的平均值，这个颜
            # 色这样应该 OK，暂时不提出来
            if (50 < pixel[0] < 60) \
                    and (53 < pixel[1] < 63) \
                    and (95 < pixel[2] < 110):
                piece_x_sum += j
                piece_x_c += 1
                piece_y_max = max(i, piece_y_max)

    if not all((piece_x_sum, piece_x_c)):
        return 0, 0, 0, 0
    piece_x = piece_x_sum / piece_x_c
    piece_y = piece_y_max - piece_base_height_1_2  # 上移棋子底盘高度的一半


    #modified by wht
    getBox = 0
    topPoint = 0
    for i in range (int (h / 3), int (h * 2 / 3)):
        last_pixel = im_pixel[0, i]
        if board_x or board_y:
            break
        board_x_sum = 0
        board_x_c = 0

        for j in range(w):
                pixel = im_pixel[j, i]
                # 修掉脑袋比下一个小格子还高的情况的 bug
                if abs(j - piece_x) < piece_body_width:
                    continue

                # 修掉圆顶的时候一条线导致的小 bug，这个颜色判断应该 OK，暂时不提出来
                if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 50:
                    if getBox:
                        board_x_sum += j
                        board_x_c += 1
                    else: 
                        getBox = 1
                        topPoint = i
                        i += 5
                        continue

        if board_x_sum:
            board_x = board_x_sum / board_x_c - 5

    # 添加了有白点的情况判断，如果有白点直接跳跃至白点
    # iOS很多失败都是因为跳跃点选取有问题。。。。
    for l in range(topPoint, topPoint + 200):
        pixel = im_pixel[board_x, l]
        if abs(pixel[0] - 245) + abs(pixel[1] - 245) + abs(pixel[2] - 245) == 0:
            board_y = l + 5
            break
    # 按实际的角度来算，找到接近下一个 board 中心的坐标 这里的角度应该是30°,值应该是tan 30°, math.sqrt(3) / 3
    if board_y == 0:
        board_y = piece_y - abs(board_x - piece_x) * math.sqrt(3) / 3
        
    # if not all((board_x, board_y)):
    #     return 0, 0, 0, 0

    return piece_x, piece_y, board_x, board_y
```

**Comment by doubleJJJJ** [comment]
@YAMsunshine 运行脚本提示这样的错误喔：
wechat_jump_game doublejj$ python3 wechat_jump_auto_iOS.py
  File "wechat_jump_auto_iOS.py", line 198
    break
    ^
IndentationError: unexpected indent

**Comment by jiwuming** [comment]
缩进问题吧 我是能正常运行的

**Comment by WangDanpeng** [comment]
感觉不该连续跳白点, 很容易被检测出来, 我跳了600多没被ban, 跳了1000分就不行了

**Comment by MemoryReload** [comment]
@YAMsunshine  兄弟你的图像扫描优化的不错，但是，你的时间、距离拟合方程太水了。试试这个：

```
def jump(distance):
    # press_time = distance * time_coefficient / 1000
    press_time = math.pow(distance,0.85)*press_coefficient_pow / 1000
    print('press time: {}'.format(press_time))
    s.tap_hold(200*random.uniform(1,1.5), 200*random.uniform(1,1.5), press_time)

```
`press_coefficient_pow`这个是一个系数，你需要具体不同的设备去调节。
我的设备是6 plus，这个值是`3.08`。
Good luck！

**Comment by YAMsunshine** [comment]
@MemoryReload 呃,我只是把题主的代码整理了一下哦!

**Comment by MuyanZhao** [comment]
我遇到的问题是tan 30°在某些情况下无法计算出正确的Y值，导致目标点选择错误，不知道能不能也通过扫描像素的方法去确定？

**Comment by liujianying** [comment]
太准了容易被检测出来吧

**Comment by mousehaow** [comment]
@MemoryReload 加入滑动的话不好弄，而且滑动距离越长越不稳定

**Comment by jifferent** [comment]
实测200多分还是会被封，而且iphone 8p 会有小圈错位的情况，但是还是会被封号。

**Comment by MemoryReload** [comment]
@mousehaow   并没有滑动～，仔细看，长按，只是每次长按的位置进行随机～  分数提交已成功～
