### ISSUE TITLE
nexus6所有参数不适用，手动和自动都用不了

### ISSUE THREAD

**Issue by cbuemc** [wangshub/wechat_jump_game#1057]
程序版本号：1.1.1
**********
Screen: Physical size: 1440x2560
Density: Physical density: 560
Device: shamu
Phone OS: 6.0.1
Host OS: darwin
Python: 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

**Comment by MrLevo520** [comment]
试试nightly版本，然后有什么问题可以反馈

**Comment by JackHuangTec** [comment]
设置default.Json 第二个参数为1就行
