### ISSUE TITLE
ios版特别好用, 求弄个ios冲顶大会的辅助, 截图然后阿里云汉王OCR,感谢

### ISSUE THREAD

**Issue by UniqHu** [wangshub/wechat_jump_game#1059]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by zoujun3281** [comment]
冲顶大会抓包就行了，关键你获取到题目怎么解题

**Comment by Erimus-Koo** [comment]
同求。想要个支付宝的辅助，让余额变多的那种。

**Comment by Skyexu** [comment]
@UniqHu https://github.com/Skyexu/TopSup 简单做了一个 IOS 还没有测试，可以参照试试看
