### ISSUE TITLE
求小米Max的参数，老跳到边缘上？？

### ISSUE THREAD

**Issue by englishyj** [wangshub/wechat_jump_game#1060]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by LingJingYing** [comment]
你是不是开了悬浮球，如果是的话，把悬浮球拖到下方，越底下越好，我的就是应为悬浮球，所以老跳到最边上。
