### ISSUE TITLE
右边可以跳跃 左边的时候就跳不了了

### ISSUE THREAD

**Issue by UsingMisz** [wangshub/wechat_jump_game#1061]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by Liangmp** [comment]
我也是，用wechat_jump_auto.py跳左边的会严重跳过了

**Comment by UsingMisz** [comment]
你解决问题了吗？

**Comment by Liangmp** [comment]
解决了，居然是屏幕上的360加速球的问题，程序把360加速球当成目标了。。。我把360加速球关掉就能正常跳了，不知道你的问题是不是跟我相同。
