### ISSUE TITLE
跳右边可以正常跳，跳左边会严重跳出到外面

### ISSUE THREAD

**Issue by Liangmp** [wangshub/wechat_jump_game#1063]
程序版本号：wechat_jump_auto.py
**********
Screen: Physical size: 1080x1920
Density: Physical density:  480
Override density: x
Device: HUAWEI NXT-DL00
Phone OS: x
Host OS: x
Python: 3.5.2  | Anaconda 4.2.0 (64-bit)
**********

遇到问题：跳右边可以正常跳，跳左边会严重跳出到外面。昨天用同一部安卓机子跑还是能正常跑的，今天再跑就出现这个问题了。windows7 + 华为mate

改进和建议：无

**Comment by MrLevo520** [comment]
试试使用nightly是否解决问题

**Comment by Liangmp** [comment]
![_20180109135555](https://user-images.githubusercontent.com/24666470/34707016-fd616760-f545-11e7-8dbc-1828cfc560eb.png)
后来发现原来是悬浮的360加速球的问题，程序向左跳的时候将目标探测成了左侧的360加速球了。。。

**Comment by wenxini234** [comment]
确实是加速球的问题
