### ISSUE TITLE
小米5配置分享-实测800+

### ISSUE THREAD

**Issue by sugarfishes** [wangshub/wechat_jump_game#1066]
config.json
{
	"under_game_score_y": 300,
	"press_coefficient": 3.80,
	"piece_base_height_1_2": 25,
	"piece_body_width": 80,
    "swipe": {
        "x1": 540,
        "y1": 1514,
        "x2": 540,
        "y2": 1514
    }
}

wechat_jump_auto.py 第70行修改为：
press_time = math.pow(distance,0.85) * press_coefficient

为了保险起见到了800分以上后直接叉掉了控制台，手动跳死结束了游戏，在朋友的手机上可以看到我已经霸榜了。以上参数参考了多位答友的分享，不胜感激。

**Comment by debbbbie** [comment]
霸气！

**Comment by zicanli** [comment]
改的是default.json吗，我的不行

**Comment by sugarfishes** [comment]
@zicanli 如果你的手机屏幕也是1920x1080像素，那就修改/config/1920x1080/config.json，其他分辨率同理。

**Comment by CrazyBoyXTF** [comment]
确实厉害，之前从没能过500，现在已经破千了，还不知道极限是多少，谢谢

**Comment by CrazyBoyXTF** [comment]
三千多了，估计还能更高

随着分数破三千，一切都变得索然无味 ：）

**Comment by Tonyliang27** [comment]
正在尝试

**Comment by zza123** [comment]
真的吗

**Comment by CrazyBoyXTF** [comment]
谢谢，11120了，不知道上限是多少，已经删游戏了
![autoju-](https://user-images.githubusercontent.com/32487989/34906519-2dca1ebc-f8aa-11e7-8360-15e41104ff1a.png)

**Comment by leoarty** [comment]
太强了。。。求问参数是怎么得到啊？以及改的那段代码的思路是什么啊？

**Comment by hey-bruce** [comment]
**牛**。就你这个是有用的。按照默认的，一般都到不了200。赞👍

**Comment by Gary8682** [comment]
为啥这个我直接就飞出去了
