### ISSUE TITLE
小米5s稳定600+ 只需修改一行参数

### ISSUE THREAD

**Issue by sunxuejian** [wangshub/wechat_jump_game#1069]
231行： jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2)*1.06)，
可以吧等待的时间那段代码注释，无影响，可提速

**Comment by zjbztianya** [comment]
小米6表示，每次两百左右就挂了。。。

**Comment by sunxuejian** [comment]
尝试修改参数都一个稳定的状态

**Comment by kevinofsias** [comment]
改了这个，时间是多少

**Comment by kevinofsias** [comment]
去掉延迟后原地跳一下就挂了，注释掉哪个休息时间啊，是不是我注释错了

**Comment by sunxuejian** [comment]
不是延迟，是那个跳了很多次需要休息的代码，不需要休息可以一直跳

**Comment by kevinofsias** [comment]
跳了547，还不错啊

**Comment by sunxuejian** [comment]
你可以修改等待时间，这样就可以吃到加分的箱子，分会更高

**Comment by kevinofsias** [comment]
等待几秒可以加分啊

**Comment by sunxuejian** [comment]
一般的箱子加分需要等多久自己算一下
