### ISSUE TITLE
No module named 'PIL'网上所有的解决方法我都试了

### ISSUE THREAD

**Issue by Shurrik13** [wangshub/wechat_jump_game#107]
解决方法都试了，也都装好了。但是就是还是出现这个问题，用的py3.6
![image](https://user-images.githubusercontent.com/34955638/34453794-ca2e5782-ed97-11e7-9bfc-2a61bbd50e75.png)

**Comment by mjzcyhp** [comment]
老兄，我也是，你搞好了别忘了告诉我一声啊

**Comment by Chen-Hu** [comment]
输入python2 wechat_jump_auto.py 试试

**Comment by Lloyd0577** [comment]
pip install Pillow    用python2.7

**Comment by F-loat** [comment]
改成 `import Image` 试试，参考[这个](https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil)

**Comment by WendyMin** [comment]
`pip install pillow`，试试这个

**Comment by SbyXlmm** [comment]
这个命令绝对行。我就是用这个吃皮的。
`python -m pip install Pillow`

**Comment by SbyXlmm** [comment]
@Shurrik13

**Comment by Lemniscate317** [comment]
http://blog.csdn.net/u012050154/article/details/50828911

**Comment by LeungEr** [comment]
pip3 install Pillow
