### ISSUE TITLE
防黑名单测试成功案列

### ISSUE THREAD

**Issue by WhySRZ** [wangshub/wechat_jump_game#1071]
都知道目前脚本刷分成功率低，所以测试了一晚上得到了些小结论。
链接: https://pan.baidu.com/s/1pMsDhu7 密码: mupr
这个文件添加了随机，和近点判断，需根据机型修改随机参数

# 模拟按压的起始点坐标，需要自动重复游戏请设置成“再来一局”的坐标
if config.get('swipe'):
    swipe =  random.uniform(1.46,1.48)  

这边的1.46和1.48是根据config的配置参数"press_coefficient"适当修改的，我手机是米5，所以文件参数调成了米5，最好开始用手动跳几下，然后控制别一直连中中心点拿32分就好了。最后最好别把分刷超过
过1000分

**Comment by MagicSaring** [comment]
x1=swipe['x1'],
        y1=swipe['y1'],
        x2=swipe['x2'],
        y2=swipe['y2'],

       x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
要改成这个,不然编译通不过
