### ISSUE TITLE
为什么一下都跳不了

### ISSUE THREAD

**Issue by aqnaruto** [wangshub/wechat_jump_game#1072]
![image](https://user-images.githubusercontent.com/9067159/34726004-b36da892-f58d-11e7-9763-0091c0eaf60a.png)
我跑的那个 stop_jump_beta1

**Comment by RunningPikaxiu** [comment]
把手机的悬浮球关了

**Comment by pluieciel** [comment]
hhh我也被悬浮球坑了几次

**Comment by aqnaruto** [comment]
close
