### ISSUE TITLE
昨天刷了下，今天早上微信恢复到上一次的分数了。不能刷了，哈哈哈哈哈。

### ISSUE THREAD

**Issue by shizhidi** [wangshub/wechat_jump_game#1075]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by WhySRZ** [comment]
我测试的都成功了，也是昨天刷的，777没问题，别超过一千通常问题不大

**Comment by Travisss** [comment]
1000出头 被消了

**Comment by pashawowi** [comment]
疯狂被ban，心很累(手动滑稽)
