### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by GwYL** [wangshub/wechat_jump_game#1077]
我是坚果pro，现在的情况是打开程序直接闪退，貌似提示CMD还是AMD未安装什么的，还有配置环境什么的，一直闪退，根本截不到图。求大佬指导！！

**Comment by GwYL** [comment]
另外，早上的时候能打开的。中午的时候也一直闪退，然后打开了一次，跳到200分又自动关闭了。。。

**Comment by GwYL** [comment]
截图成功：
![error](https://user-images.githubusercontent.com/25656592/34757569-127e7c56-f60d-11e7-8361-31b455cce254.png)

**Comment by eeechoo** [comment]
不懂   我也是这个原因   我看说明说是适配win10 64位    不知道是不是因为我是win7的

**Comment by GwYL** [comment]
呃，我这个重新启动USB调试就可以用了，虽然我依旧没搞明白是为什么，而且之前也没断开。

**Comment by eeechoo** [comment]
@GwYL 你是什么系统

**Comment by GwYL** [comment]
我是锤子系统 Smartisan OS 最新版本

**Comment by MrLevo520** [comment]
我开发的时候用的是pro2，1w分没有问题的，试试使用nightly版本，前提关闭大爆炸
