### ISSUE TITLE
关于通过sendevent防ban的一个构想

### ISSUE THREAD

**Issue by Yuandiaodiaodiao** [wangshub/wechat_jump_game#1078]
程序版本号：1.1.1
**********

改进和建议：看了下最新release的源码似乎用的是swipe模拟的触摸移动 但是实际上使用在手机上感觉像是先按下 然后延迟 然后瞬间移动到终点  不知道这种操作会不会被查出来
至少我是在前天刷到800多的时候被ban了一天
于是想到了sendevent
使用adb shell sentevent 后面加一大堆参数
大概弄了一个滑动一下的在我的机器上
event1还是event2似乎每个机器都有差别 但是能通过读取adb shell getevent获知
./adb shell sendevent /dev/input/event2 0003 0057 ‭20365‬   EV_ABS       ABS_MT_TRACKING_ID +莫名其妙的id 
./adb shell sendevent /dev/input/event2 0001 330 1         EV_KEY       BTN_TOUCH            DOWN   手指按下
./adb shell sendevent /dev/input/event2 3    53  731     EV_ABS       ABS_MT_POSITION_X  +x坐标
./adb shell sendevent /dev/input/event2 3    54  436     EV_ABS       ABS_MT_POSITION_Y  +y坐标
./adb shell sendevent /dev/input/event2 3    48  6       EV_ABS       ABS_MT_TOUCH_MAJOR  
./adb shell sendevent /dev/input/event2 3    49  5      EV_ABS       ABS_MT_TOUCH_MINOR    这两个是触摸直径(大概吧)
./adb shell sendevent /dev/input/event2 0    0   0
./adb shell sendevent /dev/input/event2 3    53  50    
./adb shell sendevent /dev/input/event2 3    54  50
./adb shell sendevent /dev/input/event2 0    0   0    每次修改之后要send 0 0 0
./adb shell sendevent /dev/input/event2 3    57  ‭4294967295‬             EV_ABS       ABS_MT_TRACKING_ID
./adb shell sendevent /dev/input/event2 1    330 0             EV_KEY       BTN_TOUCH            UP     手指抬起
./adb shell sendevent /dev/input/event2 0    0   0
然后神奇的是 通过swipe模拟的滑动在机器上是不显示开发者选项的那个显示触摸位置的(正常手指触摸会出白色的小圈圈)
然后用这个sendevent就能出现白色的小圈圈代表手指位置
所以我在想通过sendevent实现是不是能够更真实
然后具体实现方法 可以写一个进程 进程运行时开始胡乱在屏幕上滑动 然后 按压时间到了之后进程通讯 结束胡乱滑动(py学的不好 不知道怎么操作(其实是肛肛入门))
对 就是这样233 如果开发者们能够采纳的话我就写一个swipe模块然后合并进去/手动滑稽
  另外从这里学的event教程http://blog.csdn.net/fxdaniel/article/details/45846333

**Comment by Yuandiaodiaodiao** [comment]
想了想不是特别现实  adb发送命令的速度出翔

**Comment by Yuandiaodiaodiao** [comment]
不过好奇怪 我在1.1.2release下的zip是1.1.1的源码 望修复

**Comment by Yuandiaodiaodiao** [comment]
开发者群满了 蓝瘦

**Comment by MrLevo520** [comment]
@Yuandiaodiaodiao你好，因为1.1.1的源码其实是1.1.2的，协作开发的小伙伴忘记更改了。谢谢反馈

**Comment by littlepinecone** [comment]
我觉得可以考虑用这个,swipe和真实的长按确实不一样

**Comment by littlepinecone** [comment]
测试了下没办法模拟滑动,命令太慢了,长按还是可以...
