### ISSUE TITLE
window平台下，打开USB调试链接上电脑，点击执行文件知己闪退了。

### ISSUE THREAD

**Issue by smartleizi** [wangshub/wechat_jump_game#1082]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by xinxijishuwyq** [comment]
网站上的包包含的adb老了，使用最新版替换即可
