### ISSUE TITLE
每次都会跳到中间，微信会不会捕捉到为作弊

### ISSUE THREAD

**Issue by lixworth** [wangshub/wechat_jump_game#1083]
程序版本号：1.1.2

貌似每次都会跳到方块中间部分 这样微信会不会被认为是作弊
有一次跳到2000分的时候就没有被微信记录
希望改进

**Comment by zhudan** [comment]
我现在用工具是100%被抓，不用工具就不会，坑爹啊

**Comment by morainzh** [comment]
@wangshub 请问您能否加一个“降落点随机”的功能呢？我认为这样每次跳到中间虽然上分快，但是如楼上所说，容易被捕捉到。（我不太会pyQAQ

**Comment by pluieciel** [comment]
@morainzh 在代码的里distance或者按压时间加个随机量就行吧
