### ISSUE TITLE
关于ios手机如何连接还是没有看的明白，还希望大神给我指教一二

### ISSUE THREAD

**Issue by big-hunter** [wangshub/wechat_jump_game#1086]
我下载了 wda模块启动的时候回默认的连接到 localhost：8100，那我如何才能连接到我的手机呢？

**Comment by cuihee** [comment]
同问 苹果手机如何使用脚本

**Comment by billy5477** [comment]
必须用mac

**Comment by KasunaStony** [comment]
Xcode 要是test环境

**Comment by cloverapp1** [comment]
脚本里的这行c = wda.Client() 括号里面写上你的IP和端口号，比如 c = wda.Client('http://192.168.0.163:8100')

**Comment by big-hunter** [comment]
如何知道自己的手机的地址和端口号？

**Comment by syagj** [comment]
不需要知道地址和端口 只需要确定链接上了就行了 用Xcode 进行了test 自动会链接到手机 然后在终端输入iproxy 8100 8100就可以了

**Comment by billy5477** [comment]
test开始之后，可以在控制台看到手机的ip和端口号
