### ISSUE TITLE
最高才104分。

### ISSUE THREAD

**Issue by wingsrao** [wangshub/wechat_jump_game#1088]
程序版本号：1.1.2 release版 
**********
Screen: Physical size: 1920x1080 红米note4X
Phone OS: MIUI9.0
**********

遇到问题：最高才104分。。。是计算错误吗？配置是1920*1080的配置

改进和建议：

**Comment by Charltsing** [comment]
https://www.52pojie.cn/thread-682011-1-1.html 这个呢
