### ISSUE TITLE
老铁们来看看这是怎么回事

### ISSUE THREAD

**Issue by hakrtt** [wangshub/wechat_jump_game#109]
![_20171230145328](https://user-images.githubusercontent.com/34955698/34453832-c00f81d0-ed98-11e7-9283-83e737e933e5.png)
![_20171230145012](https://user-images.githubusercontent.com/34955698/34453835-c15d7b28-ed98-11e7-883d-89c7aab1c141.png)
![_20171230152752](https://user-images.githubusercontent.com/34955698/34453836-c1b62160-ed98-11e7-8471-b2aaf20ce10f.png)
![_20171230192727](https://user-images.githubusercontent.com/34955698/34453837-c29d23b2-ed98-11e7-9d02-9f82b609c810.png)
![default](https://user-images.githubusercontent.com/34955698/34453856-205634f8-ed99-11e7-8fd5-e6b5e4cb8bec.png)

哪里的问题呢，adb安装成功了，就是点开wechat_jump_auto.py这个不行，心好累啊

**Comment by wangshub** [comment]
注意把ADB添加进环境变量里面 @hakrtt

**Comment by hakrtt** [comment]
@wangshub adb该怎么添加呢

**Comment by hakrtt** [comment]
百度说那个什么androin sdk 目录找不到

**Comment by mjzcyhp** [comment]
设置下环境变量就好了，然后接下来应该还会出现个问题，那就需要安装java运行环境了，再然后下载个installer_r24.4.1-windows.exe.

**Comment by wangshub** [comment]
可以参考一下网上教程哦 @hakrtt 

[http://www.cnblogs.com/cnwutianhao/p/6557571.html](http://www.cnblogs.com/cnwutianhao/p/6557571.html)

**Comment by F-loat** [comment]
你是不是直接运行python.exe，然后执行脚本的

**Comment by hakrtt** [comment]
我有java 环境了 @mjzcyhp

**Comment by hakrtt** [comment]
@F-loat不是

**Comment by F-loat** [comment]
那是比较奇怪了。。你cmd里直接执行adb是可以的吧

**Comment by hakrtt** [comment]
@F-loat 是啊

**Comment by hakrtt** [comment]
![default](https://user-images.githubusercontent.com/34955698/34453971-3a141d5e-ed9b-11e7-96c9-cb3544523b61.png)
cmd里运行没问题 @wangshub

**Comment by WendyMin** [comment]
把安装adb的adb.exe，AdbWinApi.dll，AdbWinUsbApi，fastboot.exe，cmd.exe都放进这个项目文件夹中，试试看`adb`可不可以了
