### ISSUE TITLE
iOS端防止分数无法提交

### ISSUE THREAD

**Issue by icofans** [wangshub/wechat_jump_game#1091]
1.按压位置设为随机
需要改动jump函数

def jump(distance):
    press_time = distance * time_coefficient / 1000
    print('press time: {}'.format(press_time))
    s.tap_hold(random.randint(60,350), random.randint(60,350), press_time)

2.等待时间随机数

def main():
    while True:
        pull_screenshot()
        im = Image.open("./1.png")

        # 获取棋子和 board 的位置
        piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
        ts = int(time.time())
        print(ts, piece_x, piece_y, board_x, board_y)
        if piece_x == 0:
            return

        set_button_position(im)
        distance = math.sqrt(
            (board_x - piece_x) ** 2 + (board_y - piece_y) ** 2)
        jump(distance)

        save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y)
        backup_screenshot(ts)
        # 为了保证截图的时候应落稳了，多延迟一会儿，随机值防 ban
       time.sleep(random.uniform(1, 5.1))

**Comment by luhuafei** [comment]
我的iPhone前几天还可以跑几百分, 今天打开, 不能用啦, 第一跳就跳错了, 需要更新什么嘛?
