### ISSUE TITLE
ADB环境变量已配置，os.popen("adb xxx").read()却返回空。

### ISSUE THREAD

**Issue by vcen2** [wangshub/wechat_jump_game#1092]
请问各位：调用os.popen("ping xxx").read() 能返回成功，调用os.popen("adb xxx").read()却返回空。
windows的ADB环境变量已经配置，已经试过，可以在任意目录调用ADB命令，是什么原因导致的呢？

**Comment by wyf0912** [comment]
改成GDK编码

**Comment by vcen2** [comment]
请问具体是改哪个文件呢？

**Comment by askar882** [comment]
手机打开设置，进入"开发者选项",打开"USB调试"和"USB调试(安全设置)"

**Comment by vcen2** [comment]
不是呢，使用CMD命令可以在任意目录调用ADB命令

**Comment by wyf0912** [comment]
我用的是pycharm 更改Project Encoding和IDE Encoding为GBK
抱歉 前几天考试没有回复

**Comment by vcen2** [comment]
没关系啦，谢谢你的回复，有时间我再试一下。
