### ISSUE TITLE
macOS解压后并没有 .unix 可执行文件啊？

### ISSUE THREAD

**Issue by wyfang** [wangshub/wechat_jump_game#1093]
macOS解压后并没有 .unix 可执行文件啊？

**Comment by MrLevo520** [comment]
@wyfang 有的，就那个能双击执行的

**Comment by wyfang** [comment]
@MrLevo520 打开后没反应：
Last login: Fri Jan 12 10:05:29 on ttys000
WiFiMacBook-Pro:~ wifi$ /Users/wifi/Desktop/STOP_jump_macOS/stop_jump1_1_2 ; exit;
Load config file from /Users/wifi/Desktop/STOP_jump_macOS/config/2560x1440/config.json
----make sure your device connet with computer and open developer mode----
--------------------------Download Brew--------------------------
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 02591bdf3 Merge pull request #3662 from MikeMcQuaid/curl-executable
