### ISSUE TITLE
大佬能不能在彩蛋上停留5秒钟,就是遇到井盖,魔方,便利店,音乐盒上面停留

### ISSUE THREAD

**Issue by zhangkun0625** [wangshub/wechat_jump_game#1094]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by ddc391565320** [comment]
def main():
    while True:
        pull_screenshot()
        im = Image.open("./1.png")

        # 获取棋子和 board 的位置
        piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
        ts = int(time.time())
        print(ts, piece_x, piece_y, board_x, board_y)
        if piece_x == 0:
            return

        set_button_position(im)
        distance = math.sqrt(
            (board_x - piece_x) ** 2 + (board_y - piece_y) ** 2)
        jump(distance)

        save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y)
        backup_screenshot(ts)
        # 为了保证截图的时候应落稳了，多延迟一会儿，随机值防 ban
        time.sleep(random.uniform(3, 5.1))

**Comment by ddc391565320** [comment]
最后一句time.sleep(random.uniform(3, 5.1))就是随机设置延迟时间的  你可以设置长一点，比如2-4秒 就可以了意思最短停2秒 最长停4秒

**Comment by zhangkun0625** [comment]
我发现了的.上次跑了600+分过了一会后来被清理掉了,微信做了反作弊的

**Comment by ddc391565320** [comment]
回答里有人做了放ban的处理

**Comment by ddc391565320** [comment]
def jump(distance):
    press_time = distance * time_coefficient / 1000
    print('press time: {}'.format(press_time))
    s.tap_hold(random.randint(60,350), random.randint(60,350), press_time)

**Comment by ddc391565320** [comment]
触摸点位置随机 我试了下 暂时记录还没清楚

**Comment by aqnaruto** [comment]
@ddc391565320 所以你这个方法 能防被清吗
