### ISSUE TITLE
关于防ban的若干建议

### ISSUE THREAD

**Issue by Coder-JJ** [wangshub/wechat_jump_game#1096]
1. 每次跳停留时间不要过长，放弃加分块
2. 连击不要太长，太长了故意中断
2. 对于大块，落地点随机浮动，对于小块，小于3个最小跳跃单位的，直接跳中间点

**Comment by jifferent** [comment]
这都不是问题，问题是wda的hold和swipe可以被检测出来，和物理压按有区别
