### ISSUE TITLE
小米note很容易失败，基本不超过200分

### ISSUE THREAD

**Issue by starry0819** [wangshub/wechat_jump_game#1097]
### 程序版本号：1.1.1
**********
Screen: Physical size: 1080*1920
Density: Physical density: 440
Override density: x
Device: virgo
Phone OS: 6.0.1
Host OS: win32
Python: 2.7.14
**********
### 遇到问题：
一遇到药瓶就基本失败了。就会跳出去。请大神指点一下。

改进和建议：无

**Comment by dreamsuifeng** [comment]
我也是这样，是不是随机放ban导致的

**Comment by white-007** [comment]
小米Note配置文件，跳到800多分不敢继续了，手动跳崖。
{
    "under_game_score_y": 300,
    "press_coefficient": 1.445,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}

**Comment by CANONYANG** [comment]
电脑直接执行的exe文件，请问怎么修改参数？

**Comment by jisaber** [comment]
小米4同样问题，到130左右上不去
