### ISSUE TITLE
发送adb shell input swipe x y x y time 未实现奋力一跳

### ISSUE THREAD

**Issue by hypo1208** [wangshub/wechat_jump_game#11]
(1514559142, 338, 1109, 788, 1369)
adb shell input swipe 500 1600 500 1601 723

**Comment by hypo1208** [comment]
是不是必须root手机呢？我的猜测可能没权限不能输入

**Comment by MyGitHubCHENJIAN** [comment]
开启虚拟输入

**Comment by wowlusitong** [comment]
`500 1600 500 1601` 坐标超出了？ 范围改小点，比如0 0 0 0

**Comment by ingShen** [comment]
虚拟输入怎么开启
？

**Comment by MyGitHubCHENJIAN** [comment]
开发者选项中

**Comment by mjzcyhp** [comment]
我是小白，具体怎么做啊？我连python都不会的，需不需要连接电脑啊？

**Comment by binderclip** [comment]
用这个代码之前，先手动去试试 adb 命令吧！
试试能不能拿到图片，然后 `swipe` 的值小一些试试。

**Comment by QuincyJiang** [comment]
如果MIUI9 需要打开开发者选项 USB调试（安全设置）

**Comment by WenshyDreamPenta** [comment]
python typeError:("image data cannot be converted to float")

**Comment by binderclip** [comment]
@WenshyDreamPenta 提供完整的错误堆栈

**Comment by traim304** [comment]
测试用的是什么分辨率的？

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
