### ISSUE TITLE
跳的不准了 有的时候第一步就错了

### ISSUE THREAD

**Issue by jesenzhang** [wangshub/wechat_jump_game#1100]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by wangxj524** [comment]
1.1.2
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4
OS: win32
Python: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
**********

**Comment by zhudan** [comment]
iphone6 也不行了。。。跳不准了

**Comment by Charltsing** [comment]
https://www.52pojie.cn/thread-682011-1-1.html 这个肯定行
