### ISSUE TITLE
ios刷榜成功

### ISSUE THREAD

**Issue by wangzidaren** [wangshub/wechat_jump_game#1104]
iPhone6ps刷榜成功，5百多分

**Comment by jifferent** [comment]
@wangzidaren 请截图看一下，然后看一下朋友那边是否显示。

**Comment by CainLuo** [comment]
我也是有500+分, 但在别的好友里看是0分的, 你修改了些什么?

**Comment by icofans** [comment]
849分的路过

**Comment by Jackxiaojiahuo** [comment]
@wangzidaren iphone可以在windows下操作吗

**Comment by aqnaruto** [comment]
请问您们装webdriveragent 在xcode 8上能装成功吗，我这总是提示xcuiscreen找不到

**Comment by wangzidaren** [comment]
@CainLuo ，修改了下代码

**Comment by wangzidaren** [comment]
@Jackxiaojiahuo ,要在mac下

**Comment by CainLuo** [comment]
@wangzidaren 求代码
