### ISSUE TITLE
如果你进过黑名单，还在想方设法防止ban的可以放弃了

### ISSUE THREAD

**Issue by BMlovePanda** [wangshub/wechat_jump_game#1106]
我进过黑名单，出现过（按照出现顺序排列）提交网络超时（游戏结束提交提示网络连接异常），刷新分数提交不成功（显示提交成功，但是无法刷新排行榜，不管是自己的还是朋友的。），分数被清零等问题。
然后等到第二周，发现可以提交分数了，手动完了100多分，然后又玩到200多分，都可以显示在朋友的排行榜，我天真的以为我被剔除黑名单了。
然后某天无聊，用脚本刷到了233（本周仅此一次脚本刷，其余全是自己玩），还是提交成功并且正确显示了，然后某天我手动玩到了267分，发现并没有提交成功，历史最好纪录，仍旧是233（这个刷出来的分数）。所以，已经进过黑名单的人，该干啥还是干啥去吧。别人再研究怎么防止ban，对你的用处也不大了。

**Comment by BMlovePanda** [comment]
我是安卓。

**Comment by lqxue** [comment]
想用辅助吧还不注意肯定被清分啊,如果这么容易被拉黑那就直接拉黑好了,反正关注这个项目的有1万多,那就损失一万多用户呵呵,小游戏不会这么傻的,所谓的清零只是吓唬人而已.
我想说的是模拟最真实的跳一跳,我一般的都是用手玩到200左右,然后直接用辅助,当然所谓的修改随机按压时间和所谓的系数那就不用我说了,直接根据自己的经验改下作者的代码就可以了,连中中心不要太多,超过3次赶快停止自动跳,如果距离进那就直接用手点一下,如果距离远那就改成手动模式点击坐标实现跳一跳,本人亲测目前是1200多分  维持了一周了没毛病

**Comment by Mutefish0** [comment]
感觉和连中心没关系，试了一下PR里加入按压点随机和按压时间随机的版本，成功防ban。

**Comment by BMlovePanda** [comment]
@lqxue 我最高刷过1900，不过没给我更新。进了黑名单，根本就不知道他后面的具体机制，我上周就用了一次脚本，随机按压，随机sleep，270多分，没给我提交。今天直接连170多分、200多分以及300多分的手玩都不更新了，你非用自己的情况来给出结果，这不合适吧？讨论组里已经有多少人任何分数都被清了。

**Comment by Mutefish0** [comment]
@BMLovePanda 我经过测试发现根本没有所谓的黑名单，分数不更新的原因：第一，你打的分数比缓存里的最高分数（包括你之前刷的）要低，不触发更新（可以删除小程序然后重新添加来解决）。第二，触发更新后，服务端才会检查你刚刚的action数据，不合法则更新失败（本地缓存依旧会更新）。
