### ISSUE TITLE
腾讯的程序员请不要窥屏了

### ISSUE THREAD

**Issue by jifferent** [wangshub/wechat_jump_game#1109]
目前没有很好的放ban方法，是因为我们不知道ban的机制。
这是一个open source project，跳一跳的开发部能不知道这个project吗？

你们设想一下你们是跳一跳的程序开发员，老板开会：我们游戏做了几天就被脚本刷的满天飞，你们还想不想干了？马上给我补上。

然后他们一搜Github，就找到了，我们每次更新的代码都呈现在腾讯程序员的面前，他们想ban还不是容易的要死。

俗话说得好知己知彼，百战不殆。

**Comment by liweijia33** [comment]
支持，大家都是过来人，git上第一个就是，确实太明目张胆

**Comment by Charltsing** [comment]
超过1000分才删除吧，1000以下肯定是没问题的

**Comment by Leihungjyu** [comment]
先一点一点来   不要一下就刷很多分   先两三百   然后五六百  一次多个一两百   我现在1980手动停止的    刷到3300没显示

**Comment by BMlovePanda** [comment]
黑名单，我自从进了黑名单，分数就没正常提交过，上周还提交了一次手动，一次脚本的分数（都是200多分），这周，我tmd刚自己玩了3局，178、283、316，三个分数都没给我提交。

**Comment by Leihungjyu** [comment]
我也进过黑名单的啊。有一周不管多少成绩，是不是刷的都全清零。然后那周就没玩了    下一周一点一点刷到1900，每次手动停  然后自己点几下

**Comment by dq7532183** [comment]
张小龙都说了,会研究生长曲线,这样我们可以一天多跳几次,每周多跳几天,人工模拟防ban

**Comment by LicoCode** [comment]
如果有每次跳跃的准确度曲线，该怎么办？
