### ISSUE TITLE
运行程序时，opencv中出现异常

### ISSUE THREAD

**Issue by ZhaoGuojing** [wangshub/wechat_jump_game#111]
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "wechat_jump.py", line 13, in <module>
    template = cv2.resize(template, (0, 0), fx=scale, fy=scale)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

**Comment by F-loat** [comment]
不兼容windows吧可能，用 `wechat_jump_auto.py` 试试

**Comment by ZhaoGuojing** [comment]
恩，可用运行。但是跳第二下就出错。请问不通的手机和分辨率需要调哪里的参数？

**Comment by F-loat** [comment]
主要是 `under_game_score_y` 这个，和1920对比把差值除以二加上去就行，其他的也会有影响

**Comment by RichardWeiYang** [comment]
我换了auto也不行，

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\PIL\Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

**Comment by F-loat** [comment]
@RichardWeiYang 新版的auto应该没问题了
