### ISSUE TITLE
是否有误差累计？如何消去？小米mix2

### ISSUE THREAD

**Issue by Eacaen** [wangshub/wechat_jump_game#1114]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x2160
Density: Physical density: 440
Device: chiron
Phone OS: 7.1.1
Host OS: linux2
Python: 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 2
**********
我自己修改了识别部分的代码，比原来的感觉能分数高一点，小米mix２运气好能有１５０００＋，但是貌似极限也在这里了。
我猜想可能的情况就是小人中心点每次跳跃的误差和识别出的物体中心点的存在误差，每次跳都差那么几个像素点，步数多了误差就累积了。事实也是我只能连击１０－１５下左右就会落到旁边一次。有没有好的消除误差的方法，谢谢。

**Comment by Charltsing** [comment]
这个是算法问题，直接点对点计算距离会有偏差，另外跳一跳本身也有偏差

**Comment by goldEli** [comment]
@Eacaen 每次跳的时候都是重新开始计算，不会有累计误差吧。
