### ISSUE TITLE
2560x1440的分辨率一直不对不是跳一下就掉，或者跳两下就掉了

### ISSUE THREAD

**Issue by hhu-cs433216** [wangshub/wechat_jump_game#1115]
Load config file from config\2560x1440\config.json
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]:
程序版本号：1.1.2
**********
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: vivo Xplay3S
OS: win32
Python: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
**********
采用方式 1 获取截图
scan_start_y: 803
1515913649 451 1478 1000.0 926
adb shell input swipe 745 2121 745 2121 580
scan_start_y: 803
1515913654 457 1474 1003.0 985
adb shell input swipe 735 2115 735 2115 546
scan_start_y: 803
1515913658 376 1521 962.5 947
adb shell input swipe 704 2114 704 2114 611
scan_start_y: 803
1515913662 897 1422 16.0 860
adb shell input swipe 700 2105 700 2105 779
然后就掉了，

**Comment by Charltsing** [comment]
https://www.52pojie.cn/thread-682011-1-1.html  看看这个能不能正常跳，可能需要调整跳跃参数

**Comment by EricShui** [comment]
配置文件中的press_coefficient 值改为1
