### ISSUE TITLE
ImportError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by Lingling0408** [wangshub/wechat_jump_game#1116]
程序版本号：1.1.2
**********
Host OS: Linux Debian 8.x
Python: 3.5.3
**********

遇到问题：
**ImportError: No module named 'matplotlib'**
改进和建议：无

**Comment by Leihungjyu** [comment]
sudo pip install matplotlib

or

sudo pip3 install matplotlib

**Comment by Lingling0408** [comment]
thanks
