### ISSUE TITLE
数据归零

### ISSUE THREAD

**Issue by miwoy** [wangshub/wechat_jump_game#1117]
我要说的是，我已经成功运行起了这个工具，感谢作者的天才让我的分数有幸达到了2018，可是仅仅在我手机上显示了五分钟，我的好友们都看不到我的成绩，然后我的分数竟然直接变成了0分。是不是你们的工具已经可以被检测出来了？还是说这其实就是一个归零分数的往事拂袖去，深藏功与名的工具？

**Comment by BMlovePanda** [comment]
这东西根本没法说，我还是不觉得腾讯能检测出来随机按压和随机间歇的程序，但是他有黑名单（因为我进黑名单了，讨论组里还有很多人都进了黑名单，但是这个黑名单的程度貌似不一样？有人能提交一两次，之后被ban，有人一次也不能提交，啥分数都被ban），也有异常高分检测程序（这个是我猜的，没证据）。已经有人反馈，刷个三五百来分没问题了，也有人刷1000分也没问题，问题是已经有人随机提交分数不成功了（不管是自己玩还是程序玩），所以，不知道你在服务器端到底处于一个什么状态的情况下，根本没办法判断，服务器ban的检测手段，因为这个变量不控制，很多结论都经不起推敲。

**Comment by MaoScut** [comment]
个人的解决方法，不需要修改程序，只要分数达到预期，2000分这种，就结束程序，自己手动跳几步，就能提交成功了。
安卓手机。

**Comment by Charltsing** [comment]
张小龙已经在演讲里面说了，要检测成绩曲线，不能突发提高，慢慢刷，一次提一点

**Comment by chenzeng11** [comment]
我的也是过几分钟就没有成绩了（只剩手动玩的成绩），即使成绩仅提高了几十分。我觉得是不是可能对玩的过程中的时间或者截屏进行了检测。已经完全无法刷成绩<sad>
