### ISSUE TITLE
Image close err

### ISSUE THREAD

**Issue by getagitman** [wangshub/wechat_jump_game#1120]
hi,

我是2018年1月15日取的版本，代码中的 VERSION = "1.1.1"

运行提示如下信息
--------------
  File "wechat_jump_auto.py", line 251, in <module>
    main()
  File "wechat_jump_auto.py", line 235, in main
    im.close()
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: close
--------------

将代码中下句删除后，没有问题提示
#im.close()

其他环境信息如下：
**********
Screen: Physical size: 1920 x 1080
Device: Huawei honor7
Phone OS: android6.0
Host OS: ubuntu14.04
Python: 2.7.6
**********

期待作者解答。。。

**Comment by estalent** [comment]
ubuntu 12.04同样的问题

**Comment by wisdom-lin** [comment]
改下代码，亲自可以跳过错误。
224行修改：
        fp = open('./autojump.png')
        im = Image.open(fp)
235行修改为：
        fp.close()
