### ISSUE TITLE
iPhone SE 只跳了不到100就挂了

### ISSUE THREAD

**Issue by Gx952743985** [wangshub/wechat_jump_game#1122]
谁有没有好的参数让我穿进去

**Comment by Gx952743985** [comment]
ios +Mac 求大神帮助

**Comment by KorwinBanana** [comment]
{
    "under_game_score_y": 190,
    "press_coefficient": 2.3,
    "piece_base_height_1_2": 12,
    "piece_body_width": 50,

    "swipe" : {
        "x1": 375,
        "y1": 1055,
        "x2": 375,
        "y2": 1055
    }

**Comment by Gx952743985** [comment]
楼上这个老弟,不行啊,还是活不过100

**Comment by leon332157** [comment]
@Gx952743985 你就自己不停的试啊

**Comment by Gx952743985** [comment]
谢谢你的发的机器学习,是安卓的教程,本人小白,会的不多.我只是问问大家看看看看有没有谁跟我一样有更好的参数,我想跟大家交流一下经验.

**Comment by leon332157** [comment]
@Gx952743985 有训练好的数据，你直接看文档，有中文

**Comment by leon332157** [comment]
@Gx952743985 我感觉试参数太烦了

**Comment by Gx952743985** [comment]
@leon332157 我擦!我就是说我安装好了,用的就是教程上带的参数,跳的还是不准,问问谁有没有更好的参数

**Comment by leon332157** [comment]
python nn_play.py --phone IOS --sensitivity 2.045

**Comment by leon332157** [comment]
@Gx952743985 那你自己试啊
😅

**Comment by leon332157** [comment]
@Gx952743985 反正我的红米Note没问题

**Comment by Gx952743985** [comment]
@leon332157  你这不是跟我废话么?我弄得安卓的没事,参数也很对.苹果SE的不行.参数不是很对,我试了一下不行,想跟大家交流一下参数,你每次回答都是答非所问,但是我也很感谢你,

**Comment by leon332157** [comment]
@Gx952743985 抱歉啊，我只是觉得试参数太烦了
