### ISSUE TITLE
wda报错

### ISSUE THREAD

**Issue by JamesXu007222** [wangshub/wechat_jump_game#1130]
xcode 上运行wda的test时报错说少文件，console里面什么东西都没有，求解
<img width="1277" alt="2018-01-18 9 55 49" src="https://user-images.githubusercontent.com/35492889/35076991-f4e7b4bc-fc35-11e7-800c-d7eb9ef4505e.png">

**Comment by leon332157** [comment]
你可以试试不在Xcode里运行？

**Comment by leon332157** [comment]
你先cd到这个文件夹，然后再试试clang运行？

**Comment by JamesXu007222** [comment]
那个怎么弄，不太懂
