### ISSUE TITLE
反ban机制失效了吗？

### ISSUE THREAD

**Issue by linxiaojialin** [wangshub/wechat_jump_game#1137]
【程序版本号】
最新版本
**********
Screen: Physical size: x
Density: Physical density: 720*1280
Override density: x
Device: 酷派
Phone OS: Android5.1
Host OS: win10
Python: 3.5.3
**********

【遇到问题】
2018-01-18号（周四）跳了1024分，2018-01-19（周五）发现被刷为0分了
是官方出了新的ban规则，还是反ban机制失效了吗？

【改进和建议】
无

**Comment by YunLambert** [comment]
官方有成绩曲线检测的。如果前几次是100多跳，后面一下子成了1000多跳，就会被判定为作弊处理(一般的人进步不可能这么快......)，成绩会作废。要想刷分，要尽可能的和自己的成绩曲线相吻合才可以，一次加一点。

**Comment by 1-kai** [comment]
@YunLambert 你现在还有刷到1000+的办法吗，我一点一点往上刷，会显示“可疑操作”

**Comment by 17816873589** [comment]
我刷到650左右就显示可疑操作了。。

**Comment by MaverickMei** [comment]
我刷到650左右就显示可疑操作了...

**Comment by TNEYangMingyu** [comment]
慢慢地刷，一天跳一次，每次加10分。应该可以解决问题。辅助程序不只是提分数，重要是跑代码

**Comment by TNEYangMingyu** [comment]
享受代码的乐趣
