### ISSUE TITLE
老哥们，为啥我就突破不了100步！！！

### ISSUE THREAD

**Issue by DevXue** [wangshub/wechat_jump_game#114]
我刚刚看到作者40分钟前更新了代码，我把代码重新覆盖了一下，保证最新的， 你们突破100步了吗？ 我始终到92步那就GG了，  然后我没有关闭命令窗口 继续点击重新开始游戏！   接着 他就开始蹦跶了  结果 连10都上不了了   有时候20几 。。。   我发现了个问题  就是只要出现一只蓄力的声音之后  跳几步  肯定挂！ 我是不是要修改哪里的代码才能让他蹦跶的久一些？  我不会Python  还请各位大神指教！！！谢谢

**Comment by wangshub** [comment]
我刚刚试了一下是可以准确运行的，你试试
https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py

如果有问题的话，麻烦提供一下手机的分辨率，型号，出错的截图信息哦
@897902334

**Comment by 897902334** [comment]
哈哈  老哥  回答太迅速了！   没有报错信息，  试了好多次了  就是上不去高分，最多125  然后就GG了   手机分辨率  1080*1090   5.6寸   小米Note Android6.0    MUI8   ，  代码我看也改了 看到你换成了load方法 我又重新把代码覆盖了一遍！   还是突破不上去，  是不是我需要修改哪里的值了？？  求指教！

**Comment by 897902334** [comment]
解决了  press_coefficient这个参数，改成1.45   终于突破130分了！！！  现在还在蹦跶中 300多了  作者太棒了    开源改变世界。
