### ISSUE TITLE
随机点按在哪提现的？

### ISSUE THREAD

**Issue by Beyond-Chao** [wangshub/wechat_jump_game#1142]
根据微信抓包数据分析，生成随机按压点跳跃防 ban， 
def jump(distance):
    press_time = distance * time_coefficient / 1000
    print('press time: {}'.format(press_time))
    s.tap_hold(200, 200, press_time)

最新版本的代码，貌似点按是固定的。

**Comment by F-loat** [comment]
wechat_jump_auto.py 是加入了的，其他没加入的可以先自行修改
