### ISSUE TITLE
装matplotlib是要求安装freetype和png

### ISSUE THREAD

**Issue by dujinyu** [wangshub/wechat_jump_game#1151]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：
![image](https://user-images.githubusercontent.com/33440141/35274539-59d4aaa2-0077-11e8-8dae-ff52900babc1.png)

改进和建议：无

**Comment by leon332157** [comment]
是windows吗

**Comment by dujinyu** [comment]
是的，Windows10

**Comment by leon332157** [comment]
Use Conda or virtual enviorment

**Comment by zilijing** [comment]
[https://github.com/facebook/WebDriverAgent/tree/0243c1cfeb80dfadb649f8e18969ead0a0b50dae](0123)

**Comment by zilijing** [comment]
#https://github.com/facebook/WebDriverAgent/tree/0243c1cfeb80dfadb649f8e18969ead0a0b50dae
