### ISSUE TITLE
使用mac+iPhone 编译wda时出错，求大神解救，卡了两天了。

### ISSUE THREAD

**Issue by memorylikun** [wangshub/wechat_jump_game#1154]
前两天试了mac+android ，爽歪歪。于是想尝试下mac+iPhone的。

wiki里面说免费的个人证书也可以，我就兴高采烈的搞起。然而- -

Xcode 编译出错   Command /usr/bin/codesign failed with exit code 1
## **模拟器编译成功，连接真机就出错，搞不懂。**

![image](https://user-images.githubusercontent.com/21035135/35334554-c69bcb30-014d-11e8-83ad-f7541f6ba8c7.png)

**按照wiki里的教程，一步步走下来。有一处不是很明白，我自己改成了
PRODUCT_BUNDLE_IDENTIFIER = com.facebook.WebDriverAgentLib.likun
真机编译还是出错，崩溃！无助，找遍资料，还是不知所措**

![image](https://user-images.githubusercontent.com/21035135/35334485-8abd8ac2-014d-11e8-801a-a46ab8953d63.png)

**Comment by cetcjinjian** [comment]
这个id 就是你的app id 你填错了

**Comment by memorylikun** [comment]
![image](https://user-images.githubusercontent.com/21035135/35389183-afa23594-0211-11e8-84a1-2d7b95733d8c.png)

![image](https://user-images.githubusercontent.com/21035135/35389209-d0a18fce-0211-11e8-9f12-ddf77b8ef31b.png)
@cetcjinjian  我把BundleID 改成了 appid ，还是一样报错。

**Comment by memorylikun** [comment]
已经搞定，成功运行起来了。  其实我所有的配置都正确，我重启下mac，一切都好了。
