### ISSUE TITLE
运行辅助程序，手机屏幕无反映，分数0

### ISSUE THREAD

**Issue by viger** [wangshub/wechat_jump_game#1157]
程序版本号：1.1.2
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
Device: PD1624
Phone OS: 7.1.1
Host OS: linux
Python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
**********
采用方式 3 获取截图
scan_start_y: 690
1516930154 338 1109 788.5 849
adb shell input swipe 559 1585 559 1585 724
scan_start_y: 690
1516930157 338 1109 788.5 849
adb shell input swipe 563 1590 563 1590 724
scan_start_y: 690
1516930159 338 1109 788.5 849
adb shell input swipe 552 1590 552 1590 724
scan_start_y: 690
1516930162 338 1109 788.5 849
adb shell input swipe 502 1588 502 1588 724
scan_start_y: 690
![autojump](https://user-images.githubusercontent.com/170866/35421165-9c658376-027c-11e8-8cc8-ef560eb131c5.png)

**Comment by 1-kai** [comment]
我没使用iPhone手机的习惯，不太清楚
但是android手机不仅有【usb调试】选修，还有一个【允许模拟位置】这个选项，也在【开发者选项】里面，“adb shell input swipe 559 1585 559 1585 724”这个程序就是模拟控制屏幕按压带来的效果
感觉大多数android手机用户在第一步卡住都没发现这个问题，你试试iPhone有没有这个选项
