### ISSUE TITLE
我已经安装了adb，启动那个app却一直让我配置adb这是怎么回事？

### ISSUE THREAD

**Issue by happyuanhao** [wangshub/wechat_jump_game#1158]

**Comment by happyuanhao** [comment]
![tim 20180126151331](https://user-images.githubusercontent.com/25651702/35428699-7ddf84f4-02ab-11e8-8b2b-8f6249537428.png)

**Comment by leon332157** [comment]
Please plug your device and turn development mode.

**Comment by leon332157** [comment]
And PLEASE read the doc carefully!

**Comment by leon332157** [comment]
Plug your device in usb and turn on dev mode and usb debugging.

**Comment by hu-qi** [comment]
adb有沒有配置環境變量

**Comment by leon332157** [comment]
@hu-qi 有了，他执行命令有输出，只是手机没连接好。。。

**Comment by happyuanhao** [comment]
我手机也连接好了啊。。。打开usb调试了，电脑上都能搜到了。

**Comment by happyuanhao** [comment]
并且用adb都可以直接连接设备了。

**Comment by leon332157** [comment]
@happyuanhao 那你现在再试试啊，不行的话用python源码吧

**Comment by zxpdegb** [comment]
手机开发者选项中的选择USB配置设为MIDI就可以了
