### ISSUE TITLE
装逼失败，刷到2k左右，过了不久微信就清0了，看来不能刷的太明显

### ISSUE THREAD

**Issue by ouyangmingzhuanyong** [wangshub/wechat_jump_game#1159]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by zilijing** [comment]
0243c1cfeb80dfadb649f8e18969ead0a0b50dae

**Comment by cetcjinjian** [comment]
感觉不是成绩问题 你刷500试试 应该也会被ban

**Comment by dujinyu** [comment]
你们是自己搭建的环境么？不是用的onestep的东西？我只能刷到几十分，而且遇到白色的块，识别不出来

**Comment by ouyangmingzhuanyong** [comment]
@dujinyu 我是用的onestep，我可以刷到2000多分，但是只能自己本地看看，很快又会恢复上一次的数据，所以只能刷1000以下就不刷了，才能保证好友可以正常看到你的排行

**Comment by ouyangmingzhuanyong** [comment]
@cetcjinjian 刷到1000以下可以，，超过1000分数就会清0，具体原因不知道，可能是1000以上的可以瓜分10万现金吧，，，所以审核机制相对严格，而且不可能玩一下子就突然到1000多，应该是有个进步的过程，，，我也不知道，反正我是这样理解的

**Comment by dujinyu** [comment]
我自己的最多只能到100多一点，很多时候二三十分就挂掉了，感觉有问题。

**Comment by ouyangmingzhuanyong** [comment]
@dujinyu 可能是腾讯还没有加入机检的时候，我就有900多的记录了吧，所以并不是突然一下子直接调到900的，，，再加上，我是游戏开始，游戏中间，游戏结束都自己手动操作了一部分

**Comment by echotrue** [comment]
我是手动跳一会儿然后再用脚本跳一会儿,不过大部分是我手动跳的.以前最高分190,昨天刷到330,分数更新了.全靠脚本刷200多,分数依然不会更新到排行榜.所以感觉还是还是对于过程的检测比较严格
