### ISSUE TITLE
ImportError: cannot import name _imaging

### ISSUE THREAD

**Issue by HomeBaby** [wangshub/wechat_jump_game#116]
报错如下：
D:\python\python.exe "D:/wechat_jump_game-master (1)/wechat_jump_game-master/wechat_jump_auto.py"
Traceback (most recent call last):
  File "D:/wechat_jump_game-master (1)/wechat_jump_game-master/wechat_jump_auto.py", line 5, in <module>
    from PIL import Image, ImageDraw
  File "D:\python\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: cannot import name _imaging

Process finished with exit code 1
adb devices显示设备已连接

**Comment by HomeBaby** [comment]
![image](https://user-images.githubusercontent.com/33224913/34454028-bd65e600-ed9c-11e7-93f6-858a18a9749f.png)

**Comment by HomeBaby** [comment]
![image](https://user-images.githubusercontent.com/33224913/34454045-3a804b3a-ed9d-11e7-8c3d-cb1d51fe34d5.png)

**Comment by Mebigger** [comment]
尝试在cmd窗口 pip install pillow 试试，是不是因为没有安装这个库

**Comment by HomeBaby** [comment]
@Mebigger 依赖都没问题
![image](https://user-images.githubusercontent.com/33224913/34454131-ec867498-ed9e-11e7-8cde-4ac4c121aff9.png)

**Comment by Mebigger** [comment]
@HomeBaby 
希望对你有帮助
http://blog.csdn.net/fanoluo/article/details/42528169

**Comment by HomeBaby** [comment]
@Mebigger  哈哈哈，确实是这个问题，昨晚出的版本没有讲依赖，我照着报错添加的依赖，先装了PIL，今天看见了依赖的汇总直接pip了 
现在的问题是程序跑了但是手机没反应

![image](https://user-images.githubusercontent.com/33224913/34454374-0f636178-eda5-11e7-8b8c-6bfc1bd451a4.png)

**Comment by Mebigger** [comment]
@HomeBaby  如多是win10你以管理员身份运行你的软件，尝试一下

**Comment by HomeBaby** [comment]
@Mebigger 完美解决，多谢啦

**Comment by Mebigger** [comment]
@HomeBaby 我是新手，互相进步
