### ISSUE TITLE
小米MIX，无法连续跳跃，跳一步后程序报错。

### ISSUE THREAD

**Issue by cgp0001** [wangshub/wechat_jump_game#1161]
程序版本号：1.1.2
**********
Screen: Physical size:1080x2040
Density: Physical density: 440
Override density: x
Device: lithium
Phone OS: 7.0
Host OS: win32
Python: 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
**********

遇到问题：
Traceback (most recent call last):
  File "C:\Python27\wechat_jump_game-master\wechat_jump_auto.py", line 251, in <module>
    main()
  File "C:\Python27\wechat_jump_game-master\wechat_jump_auto.py", line 235, in main
    im.close()
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: close
改进和建议：无

**Comment by leon332157** [comment]
@cgp0001 能不能把整个终端的报错全部发过来，这个貌似是没有获取到截图

**Comment by cgp0001** [comment]
Load default config
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: y
绋嬪簭鐗堟湰鍙凤細1.1.2
**********
Screen: Physical size: 1080x2040
Density: Physical density: 440
Device: lithium
Phone OS: 7.0
Host OS: win32
Python: 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
**********
采用方式 2 获取截图
scan_start_y: 730
1517209200 338 1169 788.5 909
adb shell input swipe 549 1686 549 1686 724

Traceback (most recent call last):
  File "C:\Python27\wechat_jump_game-master\wechat_jump_auto.py", line 251, in <module>
    main()
  File "C:\Python27\wechat_jump_game-master\wechat_jump_auto.py", line 235, in main
    im.close()
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: close

**Comment by cgp0001** [comment]
@leon332157 以下是全部的错误信息
Load default config
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: y
绋嬪簭鐗堟湰鍙凤細1.1.2
**********
Screen: Physical size: 1080x2040
Density: Physical density: 440
Device: lithium
Phone OS: 7.0
Host OS: win32
Python: 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
**********
采用方式 2 获取截图
scan_start_y: 730
1517209200 338 1169 788.5 909
adb shell input swipe 549 1686 549 1686 724

Traceback (most recent call last):
  File "C:\Python27\wechat_jump_game-master\wechat_jump_auto.py", line 251, in <module>
    main()
  File "C:\Python27\wechat_jump_game-master\wechat_jump_auto.py", line 235, in main
    im.close()
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: close

**Comment by leon332157** [comment]
@cgp0001 可以使用python3试试吗

**Comment by cgp0001** [comment]
@leon332157 没为问题，我今天就装python3，调试之后再告知你结果。

**Comment by leon332157** [comment]
@cgp0001 好的

**Comment by cgp0001** [comment]
@leon332157 我应该装3.几呢？

**Comment by leon332157** [comment]
@cgp0001 当然3.6啊

**Comment by cgp0001** [comment]
@leon332157 哈哈，刚刚装好，等待我胜利的消息吧 YEAH!!

**Comment by leon332157** [comment]
@cgp0001 其实我不确定

**Comment by cgp0001** [comment]
@leon332157 提示：请安装 ADB 及驱动并配置环境变量

**Comment by cgp0001** [comment]
@leon332157 我已经装了ADB的驱动啊，在python2.7的时候还可以正常跑的。

**Comment by leon332157** [comment]
@cgp0001 你用的python源码？

**Comment by cgp0001** [comment]
@leon332157 我改用 CMD试试

**Comment by leon332157** [comment]
@cgp0001 你python3 auto.py

**Comment by cgp0001** [comment]
@leon332157 'adb' 不是内部或外部命令，也不是可运行的程序，郁闷，我明明可以使用adb devices并且连接成功了啊

**Comment by leon332157** [comment]
@cgp0001 你有没有unix之类的，windows环境变量很烦，或者你就直接在源码里吧adb的路径改掉

**Comment by cgp0001** [comment]
@leon332157 哈哈，重新弄了一下PATH搞定了，可以连续跳跃了，不过 114分就挂了。看来我需要好好调整一下设置

**Comment by leon332157** [comment]
@cgp0001 其实如果你不嫌烦，这里还有个机器学习的外挂你想试试不

**Comment by cgp0001** [comment]
@leon332157 好哇，我特别喜欢研究这些东西，哈哈哈哈

**Comment by cgp0001** [comment]
@leon332157 对了，我要求教一下，Magic Number是参考什么设置的啊？

**Comment by leon332157** [comment]
@cgp0001 手机屏幕大小，机器学习链接在[这] (https://github.com/Prinsphield/Wechat_AutoJump)

**Comment by leon332157** [comment]
@cgp0001 你先close吧，你可以进我的repo和我提issue，在这不太合适

**Comment by cgp0001** [comment]
@leon332157 收到。
