### ISSUE TITLE
查找右边界的效果比下边界更好

### ISSUE THREAD

**Issue by q381528589** [wangshub/wechat_jump_game#1162]
1. 代码版本号，代码中的 VERSION 变量
2. 使用环境 (运行脚本中已包含自动识别功能，复制即可)
3. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）
具体实例如下，按照该例进行提交 issue
-->

程序版本号：1.1.1
**********
Screen: Physical size: 1080*1920
Density: Physical density: 480
Device: MI 5
Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
**********

将寻找下边界的代码改为寻找右边界：
    # 从上顶点往下 +274 的位置开始向上找颜色与上顶点一样的点，为下顶点
    # 该方法对所有纯色平面和部分非纯色平面有效，对高尔夫草坪面、木纹桌面、药瓶和非菱形的碟机（好像是）会判断错误
    '''for k in range(i+274, i, -1): # 274 取开局时最大的方块的上下顶点距离
        pixel = im_pixel[board_x, k]
        if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) < 10:
            break
    board_y = int((i+k) / 2)'''
    #从上顶点开始找右顶点，顶点颜色与背景色不一致为止
    Prev_x = 0
    Prev_y = 0
    CurX = int(board_x)
    CurY = i+1
    #隔一行扫描
    for ky in range(i+1, i+274, 2):
        for kx in range(CurX, CurX+274, 1):
            pixel = im_pixel[kx, ky]
            #不是框线
            if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 10:
                #去掉碟机的bug
                avg = (pixel[0]+pixel[1]+pixel[2]) / 3
                if (abs(pixel[0]-avg)<5 and abs(pixel[1]-avg)<5 and abs(pixel[2]-avg)<5):
                    pass
                else:
                    CurX = kx-1
                    CurY = ky
                    break

        #找到右顶点，则退出（顶点x值始终大于等于第二个值）
        if (Prev_x >= CurX):
            break
        else:
            Prev_x = CurX
            Prev_y = CurY
        
    #临时修改代码，所以还是需要board_y这个参数
    board_y = CurY

目前这个代码可以去掉药瓶和碟机的bug，不过还有以下问题：
1.木纹桌面偶尔会出现问题（大约在1%）
2.433天经常出问题（约80%）
3.蓝色礼品盒颜色不一致导致的寻找错误（100%）

后续有时间将继续改进

**Comment by q381528589** [comment]
另外：
1080*1920的机型最佳按压系数press_coefficient目前是1.476
press_time最小按压时间建议调整到300ms

**Comment by F-loat** [comment]
可以提pr
