### ISSUE TITLE
鹅厂还是能知道作弊了。咋弄。。。

### ISSUE THREAD

**Issue by HaganHao** [wangshub/wechat_jump_game#1163]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by chengjunchao** [comment]
一点一点刷好像可以，，

**Comment by 1-kai** [comment]
@chengjunchao 求指教，用的是哪个源代码可以躲避bug

**Comment by F-loat** [comment]
dev 分支的 wechat_jump_auto_curves.py 这个目前应该可以，
