### ISSUE TITLE
执行时出现乱码是怎么回事？

### ISSUE THREAD

**Issue by bazingadyh** [wangshub/wechat_jump_game#1164]
![u9qyy48 o3g0 6 h 3zuhjh](https://user-images.githubusercontent.com/35158268/35498509-9a51bf70-0509-11e8-856e-55d5d4f5b1c1.png)
璇风‘淇濇墜鏈烘墦寮€浜?ADB 骞惰繛鎺ヤ簡鐢佃剳锛岀劧鍚庢墦寮€璺充竴璺冲苟銆愬紑濮嬫父鎴忋€戝悗鍐嶇敤鏈▼搴忥紝纭 畾寮€濮嬶紵 y/n [y]:
修改参数之后还是这个样子   。。。求   解答

**Comment by leon332157** [comment]
@bazingadyh 用python3
