### ISSUE TITLE
还是被封了，

### ISSUE THREAD

**Issue by chengjunchao** [wangshub/wechat_jump_game#1165]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by SionFu** [comment]
玩代码才是重点，封了是早晚的事情

**Comment by 1-kai** [comment]
最近使用auto程序进行跳跃，都不到100分，成绩也被删掉了；
手动单次执行程序，跳一次，执行一次程序，还是被pass了；
比较想知道这个防bug程序到底是什么原理？

**Comment by mousehaow** [comment]
手动玩和脚本刷每一次跳跃上传的数据一眼就能看出差别，想不被封可以自己diy一个物理设备

**Comment by pengdingyun** [comment]
现在到600分就会被封，越来越不想玩了。

**Comment by 1-kai** [comment]
@pengdingyun 玩这个游戏只是为了增加对学习的兴趣而已，别说这种丧气话
