### ISSUE TITLE
请问需要设置的参数具体要参照什么地方呢？

### ISSUE THREAD

**Issue by cgp0001** [wangshub/wechat_jump_game#1168]
"under_game_score_y": 300（这个300是怎样的出来的）,
"press_coefficient": 1.4665（这个弹力系数又是如何得知的）,
"piece_base_height_1_2": 25（这个不是很清楚怎样算出来的）,
"piece_body_width": 80（这个好理解一些是旗子的宽度）,
"swipe" （这个参数又是怎样得知的呢）:

**Comment by leon332157** [comment]
@cgp0001 你仔细看一下文档吧

**Comment by cgp0001** [comment]
@leon332157 好的，非常抱歉。

**Comment by leon332157** [comment]
@cgp0001 干嘛抱歉？

**Comment by cgp0001** [comment]
@leon332157 我怕文档中有明确描述啊。  小米MIX  114 最高。

**Comment by cgp0001** [comment]
@leon332157 所以想自己设置一下参数，不过苦于不知道，参数的参照规则。

**Comment by leon332157** [comment]
@cgp0001 你先看吧，我不确定。。。

**Comment by leon332157** [comment]
@cgp0001 貌似是按照屏幕大小

**Comment by leon332157** [comment]
@cgp0001 #62

**Comment by cgp0001** [comment]
@leon332157 感谢

**Comment by wanghoppe** [comment]
主要是press_coefficient 你看它是跳远了还是跳近了，远了就减一点。最后把文件替换到config下的分辨率文件夹下面。
