### ISSUE TITLE
报错，retry to connect, error: 

### ISSUE THREAD

**Issue by codingories** [wangshub/wechat_jump_game#1176]
Xcode 无法显示出ip但是连接succeed.
在 terminal 里 iproxy 8100 8100 报错

Last login: Sun Feb  4 15:30:39 on ttys000
zhu:~ ories$ iproxy
usage: iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT [UDID]
zhu:~ ories$ iproxy 8100 8100
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: c724e9db759f10f832d59745b7117d4416e8c1ec), port 8100
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: c724e9db759f10f832d59745b7117d4416e8c1ec), port 8100
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: c724e9db759f10f832d59745b7117d4416e8c1ec), port 8100
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: c724e9db759f10f832d59745b7117d4416e8c1ec), port 8100
Error connecting to device!

**Comment by leon332157** [comment]
@codingories 2087739264加微信搞定
