### ISSUE TITLE
你们是如何用matplot显示截图的？

### ISSUE THREAD

**Issue by 1programmer2dfg3** [wangshub/wechat_jump_game#118]

**Comment by wangshub** [comment]
```python
def show_bmp(img):
    # BMP 的读取与显示
    plt.figure("LenaRGB.bmp")
    plt.title("LenaRGB.bmp")
    plt.imshow(img)
    plt.show()
```

@1programmer2dfg3

**Comment by wangshub** [comment]
读取图片

```
img = np.array(Image.open('LenaRGB.bmp'))
```
@1programmer2dfg3

**Comment by wangshub** [comment]
我先关闭issue了哦 @1programmer2dfg3

**Comment by 1programmer2dfg3** [comment]
你这代码是在这个项目上写的么？

**Comment by wjzhangcsu** [comment]
安装玩依赖然后在当前文件夹中放一张名为“1.png”和一张名为“character.png”的图片可以直接运行，最好是在linux下运行，因为楼主是在linux弄的应该。

**Comment by 1programmer2dfg3** [comment]
不是用adb直接截图上传了么？还要把截图放在本地啊？

**Comment by wangshub** [comment]
@wjzhangcsu 是的，最先是在linux上运行的，后面ios和windows都是各路大牛上传

**Comment by 1programmer2dfg3** [comment]
我1.png 和character.png 2张截图一样的，然后放到项目E:\WeCharGamePython\wechat_jump_game-master\wechat_jump_game-master中，运行一直显示(1514637031, 338, 1109, 788, 1369)
adb shell input swipe 500 1600 500 1601 723，一直在走，一闪闪的，打不开，这是哪里出错了？ @wangshub
