### ISSUE TITLE
[维护] 关闭过时且不需要的issue

### ISSUE THREAD

**Issue by leon332157** [wangshub/wechat_jump_game#1182]
@F-loat @wangshub 麻烦有空帮我整理一下issue，现在太多了，我一个人关不过来，尽量把参数设置的留着...最好写在要求里，提完问题自己close，另外，GitHub貌似没有批量关issue 😭

**Comment by F-loat** [comment]
可以同时关闭某一页或者某一类 issue

**Comment by leon332157** [comment]
@F-loat 怎么批量关闭啊...

**Comment by F-loat** [comment]
列表页全选然后有个关闭的

**Comment by leon332157** [comment]
@F-loat 啊啊我看到了 😃
