### ISSUE TITLE
[完全优化] 1.1.4版本问题

### ISSUE THREAD

**Issue by leon332157** [wangshub/wechat_jump_game#1184]
@F-loat 现在差不多了，我准备吧整个东西只放在python3上了。还有就是手动跳的还要不要啊...

**Comment by leon332157** [comment]
@F-loat @binderclip @wangshub 另外debug保存时的ts是做什么作用的？我现在直接把文件名保存成时间没问题吧？

**Comment by F-loat** [comment]
不要删现有的东西

**Comment by leon332157** [comment]
@F-loat 好的

**Comment by leon332157** [comment]
@F-loat 那么迁移到py3已经可以了

**Comment by leon332157** [comment]
@F-loat py2问题太多

**Comment by F-loat** [comment]
py2目前有什么问题啊

**Comment by leon332157** [comment]
@F-loat 编码和导入问题

**Comment by leon332157** [comment]
@F-loat 别的目前还没发现

**Comment by leon332157** [comment]
@F-loat 还有就是我觉得ai是真的没有必要，不是每个人的电脑可以训练并且跑起来的

**Comment by F-loat** [comment]
编码windows下之前不是有个pr解决了说。。其他的能兼容还是尽量兼容吧

**Comment by leon332157** [comment]
@F-loat 那么import会出问题的...

**Comment by F-loat** [comment]
这个项目总的来说是个示例，又不是真的为了刷分用

**Comment by leon332157** [comment]
@F-loat 我想写 🤣

**Comment by leon332157** [comment]
@F-loat py2还有就是subprocess输出问题

**Comment by F-loat** [comment]
哪儿的import啊，现在的版本好像py2可以用的

**Comment by leon332157** [comment]
@F-loat win默认编码是ascii，py3是utf8

**Comment by leon332157** [comment]
from common.auto_adb import auto_adb

**Comment by F-loat** [comment]
subprocess好像就截图用了吧，无效也不妨事

**Comment by leon332157** [comment]
这行

**Comment by leon332157** [comment]
py2不支持

**Comment by leon332157** [comment]
@F-loat 我pr给你开

**Comment by F-loat** [comment]
#788 编码这个
