### ISSUE TITLE
华为荣耀X1机型分辨率问题，调不准出错

### ISSUE THREAD

**Issue by pblh123** [wangshub/wechat_jump_game#1186]
程序版本号：stop_jump1_1_2
**********
Screen: Physical size: 1200x1920
Density: Physical density:400
Override density: x
Device: X1 7.0
Python: 3.6
**********

遇到问题：
跳一会就死了，经常在10分一下就死掉

改进和建议：
建议README中添加怎么调整config.json的说明方法

**Comment by leon332157** [comment]
@pblh123 在考虑加入，现在确实有很多人想自己设置参数
