### ISSUE TITLE
使用方法1— app 进行1键操作，在运行.exe文件后显示：请安装adb及驱动并配置环境变量

### ISSUE THREAD

**Issue by mohanyu** [wangshub/wechat_jump_game#1187]
在win10电脑（64位）上运行wangshub/wechat_jump_game此项目的

_-  方法 1：使用 app 进行一键操作。目前已适配 Win10 64位/macOS 平台 Android 一键操作，下载请移步 _STOP_jump_
 STOP_jump_win.rar   8.13 MB时，出现下图这种情况：
https://photos.app.goo.gl/3Sucli1n6N5JQD4y2

（与之相悖的是图片的左下的cmd输入adb devices，已经显示成功了）
- 我的电脑以前配置过环境变量，手机已经连接电脑

- 打开了开发者usb调试和微信跳一跳游戏运行界面

- 在使用cmd运行adb devices并且显示的daemon started successfully，

问题：为何运行了stop_jump1_1_2.exe后cmd窗口显示error：device not found   请安装usb驱动并配置环境变量呢？什么方法可以解决？
（尝试过把原先的adb环境变量删除后，重启电脑后运行stop_jump1_1_2.exe，结果依旧）

 @wangshub
@MrLevo520

**Comment by kongdesheng** [comment]
运行adb devices后显示的应该是你手机驱动列表才对呢吧。
你可以这样试试：cd 到你adb的路径，然后运行adb devices。

**Comment by mohanyu** [comment]
我已经解决了这个问题，大家不必费心了..........................................我已经解决了！我已经解决了！我已经解决了！我已经解决了！我已经解决了！我已经解决了！我已经解决了！
