### ISSUE TITLE
adb获取手机截图更好的办法

### ISSUE THREAD

**Issue by myzcl** [wangshub/wechat_jump_game#1190]
改进和建议：
关于获取手机截屏

os.system('adb shell screencap -p //sdcard//src.png')
os.system('adb pull //sdcard//src.png')
这种方法每次需要手机截屏，然后在上传，感觉对手机有影响

下面这种方法，直接可以读取手机图片到电脑
os.system('adb exec-out screencap -p > src.png')

**Comment by keytuff** [comment]
你把screenshot.py改好，我们测试看看，我手机是方式2截图，耗时1秒左右。

**Comment by myzcl** [comment]
你也是第二种方法？那个方法主要是，不用手机先截图再上传，直接上传到电脑。
