### ISSUE TITLE
每次都跳到一百多就挂了，而且没法识别中间的小白点……只能一分一分的跳

### ISSUE THREAD

**Issue by Gary8682** [wangshub/wechat_jump_game#1195]
程序版本号：1.1.2
**********
Screen: Physical size: 1080p
Density: Physical density: x
Override density: x
Device: mi5
Phone OS: x
Host OS: x
Python: 3.6
**********

遇到问题：

改进和建议：无

**Comment by crucialize** [comment]
打个广告。看我repo。昨天刚开发的。

**Comment by F-loat** [comment]
master 分支还是 dev 分支的程序，dev 分支 1080p 的手机可能需要微调下参数

**Comment by F-loat** [comment]
@leon332157 哈哈哈 新年新气象😂

**Comment by leon332157** [comment]
@F-loat 你赶紧帮我试试路径

**Comment by leon332157** [comment]
@F-loat 你直接吧传进去的/改成\\

**Comment by F-loat** [comment]
@leon332157 好的

**Comment by leon332157** [comment]
@Gary8682 ai版本刚刚发布，你可以试试
