### ISSUE TITLE
有三星note8的参数么

### ISSUE THREAD

**Issue by tihssiefiL** [wangshub/wechat_jump_game#1198]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by leon332157** [comment]
@tihssiefiL 屏幕大小？

**Comment by tihssiefiL** [comment]
6.3
