### ISSUE TITLE
物体较小时，即使正确识别中心点，也会跳失败

### ISSUE THREAD

**Issue by goldEli** [wangshub/wechat_jump_game#1199]
程序版本号：VERSION = "1.1.4"
**********
Screen: Physical size: 1080x1920
Density: Physical density: 440
Device: jason
Phone OS: 7.1.1
Host OS: darwin
Python: 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
**********

遇到问题：物体较小时，即使正确识别中心点，也会跳失败
![](https://goldeli.github.io/miaoYu/image/1.png)
![](https://goldeli.github.io/miaoYu/image/2.png)

改进和建议：无

**Comment by Gary8682** [comment]
我也是这样。每次都是倒在又细又长的东西上，得不了高分。

**Comment by leon332157** [comment]
这个不懂，具体是什么现象呢? 有没有正确跳上去？还是跳歪了掉下来了？

**Comment by goldEli** [comment]
@leon332157 跳歪了掉下来了

我猜测：为了防ban，不能每次跳到中心点，所以基于中心半径x为小人的随机着陆范围。如果x是个固定值，当x大于物体的的半径时，就有很大的几率掉下来。

如果是这样的话把x设为动态的，取物体最大半径的百分比（x小于物体最大半径）。

**Comment by leon332157** [comment]
@goldEli 这个还没遇到过，我研究一下

**Comment by goldEli** [comment]
@leon332157 @Gary8682 我找到问题了，我提了pr #1204。
之前每次跳都会短一点，所以小物体容易掉下来。
我看了下代码发现 press_coefficient 并未用于press_time的计算。
现在每次都能跳到正中心，哈哈。
