### ISSUE TITLE
请教红米5A的参数，谢谢！

### ISSUE THREAD

**Issue by zorowzorro** [wangshub/wechat_jump_game#1202]
程序版本号：x.x.x
**********
Screen: Physical size: 720*1080
{
    "under_game_score_y": 200,
    "press_coefficient": 2.325,
    "piece_base_height_1_2": 13,
    "piece_body_width": 45,
    "swipe" : {
      "x1": 374,
      "y1": 1060,
      "x2": 374,
      "y2": 1060
    }
}
**********

遇到问题：

改进和建议：无

**Comment by leon332157** [comment]
#362
