### ISSUE TITLE
请教红米5A（1280*720）的参数设置，谢谢！

### ISSUE THREAD

**Issue by zorowzorro** [wangshub/wechat_jump_game#1203]
{
    "under_game_score_y": 300,
    "press_coefficient": 2.325,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,

    "swipe" : {
      "x1": 540,
      "y1": 1514,
      "x2": 540,
      "y2": 1514
    }
}

**Comment by leon332157** [comment]
#362

**Comment by zorowzorro** [comment]
请教一下代码在哪里改？
