### ISSUE TITLE
现在用自动脚本刷的分数不能上传了吗？？

### ISSUE THREAD

**Issue by doubleJJJJ** [wangshub/wechat_jump_game#1205]
![img_9092](https://user-images.githubusercontent.com/12195436/36469972-22cd5a18-1724-11e8-91d3-eee665666e72.PNG)
如图示

**Comment by XueTeng2** [comment]
要自己先跳一百多二百，再用自动跳，最后拔了自己跳。注意不要比上一次的成绩增加太多，否则不符合进步曲线会取消成绩。

**Comment by leon332157** [comment]
@doubleJJJJ 这个确实没办法，我们能做的防禁已经做了...

**Comment by Jack-Kingdom** [comment]
一次增加一点还是可以的

**Comment by F-loat** [comment]
目前使用 wechat_jump_auto_curves.py 是可以的
