### ISSUE TITLE
棋盘中心点识别错误

### ISSUE THREAD

**Issue by goldEli** [wangshub/wechat_jump_game#1209]
程序版本号：VERSION = "1.1.4"
**********
Screen: Physical size: 1080x1920
Density: Physical density: 440
Device: jason
Phone OS: 7.1.1
Host OS: darwin
Python: 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
**********

遇到问题：

棋盘中心点识别错误。
昨天都是好的，每次都是正中心，今天每次计算出的中心点都在最右侧，请问下是什么原因导致的呢？

![](https://goldeli.github.io/miaoYu/image/3.png)

改进和建议：无

**Comment by JasonKhew96** [comment]
![?](https://user-images.githubusercontent.com/29531167/36534257-fe37f3ec-1800-11e8-94cd-c6215b51d0e4.png)
这个?

**Comment by goldEli** [comment]
@JasonKhew96 非常感谢！我还以为见鬼了 ：）
