### ISSUE TITLE
红米 Note3 参数不行

### ISSUE THREAD

**Issue by GangZiGe** [wangshub/wechat_jump_game#1211]
我用红米note3 怎么修改中心点参数最高直跳140  求准确参数

**Comment by leon332157** [comment]
@GangZiGe 你看看 #61 #62 里面有没有

**Comment by GangZiGe** [comment]
不行

**Comment by GangZiGe** [comment]
没有

**Comment by GangZiGe** [comment]
没有啊

**Comment by leon332157** [comment]
@GangZiGe 屏幕尺寸？

**Comment by GangZiGe** [comment]
5.5

**Comment by leon332157** [comment]
@GangZiGe 分辨率

**Comment by GangZiGe** [comment]
1920*1080

**Comment by GangZiGe** [comment]
![572a55765e1aca860817236f930145e2](https://user-images.githubusercontent.com/20942839/36709232-c48a4ba4-1bb1-11e8-92ea-70d415285b2b.png)
![15f66847110007cb63577f62e0c6dd80](https://user-images.githubusercontent.com/20942839/36709241-d13b97b8-1bb1-11e8-8fb0-4063b1dfc78b.png)
![6da1fb0b6a22ae7d3eaa3977d9bf5cc1](https://user-images.githubusercontent.com/20942839/36709246-d786ae28-1bb1-11e8-85a9-1ac2c987a811.jpg)

![b8dd054aa4c7b8947524ba12e17f2f25](https://user-images.githubusercontent.com/20942839/36709308-2036778e-1bb2-11e8-8f79-cd1220f03db9.jpg)

**Comment by leon332157** [comment]
@GangZiGe 把debug swich 改为True

**Comment by GangZiGe** [comment]
已经设置了

**Comment by leon332157** [comment]
@GangZiGe 那你应该会看到线划在上面

**Comment by leon332157** [comment]
@GangZiGe 要不就是我们编写出问题了

**Comment by GangZiGe** [comment]
那怎么办

**Comment by leon332157** [comment]
@GangZiGe 你看看有没有画线的图？

**Comment by GangZiGe** [comment]
没有

**Comment by leon332157** [comment]
@F-loat 你之前测试debug的时候没有问题吧

**Comment by F-loat** [comment]
没问题啊，我不是还发过一张，这个用的是最新版的不，他这样很可能是截图间隔时间太短

**Comment by leon332157** [comment]
@GangZiGe 我不确定，应该是最新版本

**Comment by leon332157** [comment]
@GangZiGe 你这个是最新版本？

**Comment by GangZiGe** [comment]
嗯呢

**Comment by F-loat** [comment]
把截图间隔时间调大点

**Comment by GangZiGe** [comment]
加了

**Comment by leon332157** [comment]
@GangZiGe #61 #62 好像有了

**Comment by GangZiGe** [comment]
他说的还是不行
