### ISSUE TITLE
更改按压时间参数conf.json文件后不能正常运行脚本。

### ISSUE THREAD

**Issue by Tearslovefu** [wangshub/wechat_jump_game#1212]
尝试修改C:\wechat_jump_game-master\config\1920x1080\conf.json文件中的"press_coefficient": 1.392参数；使用notepad++修改后保存，然后运行python wechat_jump_auto.py脚本，这时不能正常运行程序。
![exw53wqug6n1 jlg bavdj](https://user-images.githubusercontent.com/26314831/36632004-9bead5bc-19bb-11e8-875f-dbb23afc5e03.png)
问题：从github下载的conf.json文件不能用notepad修改吗？如果修改press_coefficient参数，该用哪种工具，修改哪个配置文件里的参数？因为有好多文件里都有press_coefficient。本人：win7X64  小米5 1920X1080 python3.6 运行默认的脚本第一步总是按压时间超时，
![des 5k lze jubn ipl](https://user-images.githubusercontent.com/26314831/36632100-f7593a1e-19bc-11e8-862f-ece5f082dbfe.png)

**Comment by leon332157** [comment]
@Tearslovefu 仔细检查一下json格式
