### ISSUE TITLE
荣耀9在执行wechar_jump_auto.py脚本时出现issue

### ISSUE THREAD

**Issue by defychen** [wangshub/wechat_jump_game#1224]
荣耀9在执行wechar_jump_auto.py脚本时出现:
error: device not found.
在使用adb devices检测设备时只出现"List of devices attached",并没有具体的"ID attached".
请问是不是什么设置没有正确,辛苦麻烦解答下.

Thanks a lot！

**Comment by defychen** [comment]
补充下:现在手机是Android 8,是不是有什么支持?

**Comment by leon332157** [comment]
@defychen 这是有可能的，可能adb还没有支持，不然就是你手机设定不对

**Comment by defychen** [comment]
@leon332157 问题已经搞定了，是华为手机有些设置需要设定.
