### ISSUE TITLE
remote object '/sdcard/autojump.png' does not exist

### ISSUE THREAD

**Issue by lffsonic** [wangshub/wechat_jump_game#1225]
基本上每次都是0，感觉是图片延时造成的，日志一直提示
remote object '/sdcard/autojump.png' does not exist
使用wechat_jump_py3.py图像测试，发现Figure图片总比微信图片慢一步

程序版本号：x.x.x
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
Device: OnePlus3T
Phone OS: 6.0.1
Host OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********

**Comment by lffsonic** [comment]
貌似是手机存储文件发现相同文件没有被覆盖，而是重新命名了 autojump_时间戳.png，导致adb pull到本地电脑，发现手机没有autojump.png,  
修改common/screenshot.py 42行
filename = datetime.datetime.now().strftime("%H%M%S") + '.png'
adb.run('shell screencap -p /sdcard/autojump_{}.png'.format(filename))
adb.run('pull /sdcard/autojump_{}.png ./autojump.png'.format(filename))
可以正常运行，可以跑到300多分，不过这样会导致手机图片激增啊，还有要调整下config.json参数才能达到高分

**Comment by leon332157** [comment]
所以你的问题是？

**Comment by morainzh** [comment]
这不应该pull request吗……
