### ISSUE TITLE
无法通过微信作弊检测

### ISSUE THREAD

**Issue by Burlesque1** [wangshub/wechat_jump_game#1226]
程序版本号：1.1.1
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: Android
Host OS: x
Python: x
**********

遇到问题：防禁代码不起作用，随机的间隔完成操作似乎并不能奏效

改进和建议：尝试新的防ban方法，仅供交流学习之用

**Comment by leon332157** [comment]
@Burlesque1 要是你能把微信的检测代码搞出来就太感谢了

**Comment by leon332157** [comment]
😸
