### ISSUE TITLE
请问有一加5T的参数文件吗？

### ISSUE THREAD

**Issue by yicx** [wangshub/wechat_jump_game#1231]
![notrun](https://user-images.githubusercontent.com/38092527/38471092-eb81b636-3b9e-11e8-924b-2323046faeb4.jpg)

系统提示暂不支持此设备。

**Comment by F-loat** [comment]
手机端没有授权吧应该是

**Comment by yicx** [comment]
@F-loat 是的，后来调整了授权后可以用了，谢谢
