### ISSUE TITLE
为何全部更新成了python3

### ISSUE THREAD

**Issue by whbing** [wangshub/wechat_jump_game#1233]
当前版本全是python3的脚本，python2的脚本是删除了吗

**Comment by leon332157** [comment]
@whbing Py2理论可以运行，建议你用py3

**Comment by whbing** [comment]
所有脚本的的打印均为 print("****")，python2必报错。
另外，加的这么复杂，看起来也并不太实用，Py3还额外下几个包。

**Comment by leon332157** [comment]
@whbing 麻烦你用PY2.7运行了再来说报错吧

**Comment by leon332157** [comment]
@whbing 现在除了py2还有极少数人用，几乎都是py3
