### ISSUE TITLE
为什么我的 程序运行不了

### ISSUE THREAD

**Issue by CODEHLK** [wangshub/wechat_jump_game#124]
ImportError: No module named PIL
>>>

**Comment by yuanjingsong** [comment]
先运行了pip -r requirements 如果仍有，应该是路径问题

**Comment by CODEHLK** [comment]
请问这个是在命令窗口运行吗，还是在python的命令行里。我都试了，，都不行，能具体说一下吗

**Comment by WendyMin** [comment]
+1

**Comment by yuanjingsong** [comment]
楼上不会的 建议百度一下 python如何导入第三方模块

**Comment by CODEHLK** [comment]
requirements这个文件放在python27文件夹里吗？

**Comment by CODEHLK** [comment]
虚心求问，，，百度不到

**Comment by CODEHLK** [comment]
C:\Users\dell>pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

C:\Users\dell>pip install PTL
Collecting PTL
  Could not find a version that satisfies the requirement PTL (from versions: )
No matching distribution found for PTL

**Comment by yuanjingsong** [comment]
requirements.txt肯定是在你放这个文件夹里面啊 而且是PIL麻烦打对了
