### ISSUE TITLE
运行成功了，不会跳动，一直弹出这些

### ISSUE THREAD

**Issue by df71012** [wangshub/wechat_jump_game#127]
![image](https://user-images.githubusercontent.com/23538906/34454201-2851d63c-eda1-11e7-800b-64ee5ef4455e.png)

**Comment by wangshub** [comment]
请看下adb是否安装成功，并且添加进了环境变量，具体可以百度一下 @df71012

**Comment by mjzcyhp** [comment]
@wangshub 大神看下我发的帖子，我运行代码的时候还是不行，但是电脑跳出了手机跳一跳游戏的截图了，怎么回事啊

**Comment by mjzcyhp** [comment]
@wangshub w我差不多也是这样的

**Comment by ilewseu** [comment]
我是直接把adb可执行文件直接放到程序根目录，不要加环境变量也可以运行

**Comment by df71012** [comment]
成功了，感谢你们

**Comment by peanutA** [comment]
@df71012 我也是这个问题，你是怎么处理的啊？
