### ISSUE TITLE
很容易在圆盘挂掉

### ISSUE THREAD

**Issue by 1026742642** [wangshub/wechat_jump_game#129]
机型:xiaomi5s
分辨率:1080x1920

![1514637324_d](https://user-images.githubusercontent.com/16112685/34454217-b0d8f4d6-eda1-11e7-9416-dc6b6049c01e.png)

**Comment by 1026742642** [comment]
![1514637328_d](https://user-images.githubusercontent.com/16112685/34454235-ed1a082c-eda1-11e7-9189-fefb6d71a114.png)

**Comment by ShiftCtrlAlt** [comment]
你好，你在运行的时候有没有遇到这个错误
error: device offline
error: device offline
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 153, in <module>
    main()
  File "wechat_jump_auto.py", line 141, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

**Comment by ilewseu** [comment]
@ShiftCtrlAlt  应该是设备没有连上的问题，看看手机驱动是否正常安装
