### ISSUE TITLE
横向的跳跃正常，纵向跳跃时会变成最大力量，求解啊

### ISSUE THREAD

**Issue by the378** [wangshub/wechat_jump_game#13]
我的安卓设备是2k分辨率，我将时间系数变成了2.5，横跳可以，纵跳总是最大力气跳出

**Comment by mjzcyhp** [comment]
怎么弄啊，手把手教一下啊？

**Comment by the378** [comment]
你要安装python 及opencv numpy matplotlib adb等，环境设置好，就可以了

**Comment by binderclip** [comment]
“横跳”和“纵跳”分别是啥意思？

**Comment by the378** [comment]
就是当新方块在右侧就算横跳，在上方的就是纵跳

**Comment by binderclip** [comment]
@the378  应该是左跳、右跳吧？

**Comment by the378** [comment]
![1](https://user-images.githubusercontent.com/34943874/34442065-a00ba452-ecfa-11e7-9c6d-a4ffc5f763c3.png)
![2](https://user-images.githubusercontent.com/34943874/34442068-a15548a4-ecfa-11e7-86a1-5ebba04e111e.png)
1这样的就是横跳了，这个设置2.5我的机器正好跳到中心，但是2这种就不行了，直接大力飞出屏外了

**Comment by binderclip** [comment]
@the378 可以把程序打印出来的坐标贴一下吗？

**Comment by the378** [comment]
或者2k屏还需调整哪些参数？
88757 KB/s (90888 bytes in 0.001s)
(1514566075, 451, 1486, 208, 1626)
adb shell input swipe 320 410 320 410 701
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
5872 KB/s (93805 bytes in 0.015s)
(1514566088, 504, 1455, 242, 1606)
adb shell input swipe 320 410 320 410 755
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by the378** [comment]
也不太对，第二下无论横竖都会跳飞

**Comment by binderclip** [comment]
@the378 你先把代码里的 300 改成 500 吧。。那样应该就暂时行了。
那个代码是基于 1080 的屏幕写的。你的 2K 屏的 300 还在那个分数的数字上。

**Comment by mjzcyhp** [comment]
哪位大神教下呗，什么都不懂的。或者提示下要了解什么，学点什么知识能做到啊？

**Comment by the378** [comment]
500还是不太行，需要慢慢调试了……

**Comment by binderclip** [comment]
@the378 下面这些地方可能都要调整。。。

1.393 https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py#L19
500 1600 1601 https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py#L23
20 https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py#L50
300 https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py#L53
70 https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py#L64

**Comment by the378** [comment]
好的，感谢，我会慢慢尝试的

**Comment by sztanyi** [comment]
adb shell input swipe 500 1600 500 1600 610
时间参数大于610直接变成按住不动了，小于610可以，单独运行adb命令也这样

**Comment by binderclip** [comment]
试试 `adb shell input swipe 500 1600 500 1610 610` 呢？
毕竟 swipe，起点和终点可能有点区别比较合适。

**Comment by sztanyi** [comment]
@binderclip 
谢谢回复，有设置起点和终点，命令为adb shell input swipe 500 1600 600 1500 700
图中的红线为wipe的路径
![screenshot_2017-12-30-01-32-43-340_](https://user-images.githubusercontent.com/3962263/34443106-cd0c487e-ed01-11e7-92e9-ea26e3e2c7fa.png)

**Comment by binderclip** [comment]
@sztanyi 请问你的是啥手机？

**Comment by Allianzcortex** [comment]
安卓适配的机型和屏幕太多了...不能 hard coded 啊quq

**Comment by sztanyi** [comment]
@binderclip 坚果pro，感觉有毒。adb swipe命令时间超过600左右没有释放动作了。。

**Comment by the378** [comment]
我的2k屏实验成功了。。。待我回家后上传相应调整的参数

**Comment by liuchonggao** [comment]
@binderclip 坚果 pro2 怎么配置呢？

**Comment by HsingPeng** [comment]
@sztanyi 锤子 T1 也是，超过600不能释放。

**Comment by sztanyi** [comment]
@HsingPeng 320 410 620 310用这几个坐标可以，你试一下？

**Comment by HsingPeng** [comment]
@sztanyi 非常感谢，可以了，排行榜刷起来了噜。
