### ISSUE TITLE
怎么我现在一运行，电脑就跳出一张手机的截图啊

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#130]
怎么回事啊？哪里出错了啊

**Comment by wangshub** [comment]
可以稍微消息一点吗？ @mjzcyhp

**Comment by mjzcyhp** [comment]
@wangshub 我在根目录下运行   python wechat_jump_auto.py,点回车后，就弹出了Figure的一个框。里面是游戏跳一跳的截图，还带有坐标。点击图片上的盒子，cmd的黑框里面的数据就会变动。但是手机上还是没什么动静，于是我就手动玩了，过了一会，电脑上Figure框里面的图片也变得和跳一跳游戏的一样了。所以我就没玩了，但是手机上还是没有自动运行

**Comment by mjzcyhp** [comment]
@wangshub 手机相册上也会出现游戏的一张截图

**Comment by wangshub** [comment]
如果是这个程序，是不需要点击的
https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py

**Comment by mjzcyhp** [comment]
@wangshub 那我把这里面的代码替换到原来的文件下运行下？

**Comment by mjzcyhp** [comment]
@wangshub 还是不行，现在图片都不跳出来了，而且一直报错

**Comment by superwzlx** [comment]
你是不是运行成wechat_jump_py3这个了，这个是要手动撸的，auto那个才会自动
