### ISSUE TITLE
落点计算误差|简略修正|300+分

### ISSUE THREAD

**Issue by AmosLee94** [wangshub/wechat_jump_game#131]
![image](https://user-images.githubusercontent.com/33691772/34454284-207c578c-eda3-11e7-9f71-0546ec0d2a7b.png)
图中黑点为计算出来的落点，明显有落差
我随手点了，修正了y-=10
然后又改了长按时间系数

改之前我的测试只有30分左右
现在200+吧

![image](https://user-images.githubusercontent.com/33691772/34454278-1796695a-eda3-11e7-81cf-ea39db4a5653.png)

**Comment by AmosLee94** [comment]
跳跃到正确的位置之后，奖励分很高
2,4,6,8,10~
很恐怖的

**Comment by DingTianCheng** [comment]
什么手机呀

**Comment by DingTianCheng** [comment]
顶
