### ISSUE TITLE
android 是自动跳的么，需要手动点击么？

### ISSUE THREAD

**Issue by localjc** [wangshub/wechat_jump_game#133]

**Comment by xinghee** [comment]
运行这个wechat_jump_auto.py，自动跳。

**Comment by localjc** [comment]
![image](https://user-images.githubusercontent.com/10279703/34454466-15cdbef8-eda7-11e7-95a0-4fc2b57e0802.png)
为啥我的运行没有报错还是不会自动跳

**Comment by wangshub** [comment]
是自动跳，请看readme.md @localjc

**Comment by KivyGogh** [comment]
scan_start_y:  700
1514640398 338.54135338345867 1104 788.5 845.1932366716314
/Users/kivygogh/tools/platform-tools/adb shell input swipe 540.0 1514.5 540.0 1514.5 722
scan_start_y:  700
1514640403 338.54135338345867 1104 788.5 845.1932366716314
/Users/kivygogh/tools/platform-tools/adb shell input swipe 540.0 1514.5 540.0 1514.5 722
scan_start_y:  700
1514640407 338.54135338345867 1104 788.5 845.1932366716314
/Users/kivygogh/tools/platform-tools/adb shell input swipe 540.0 1514.5 540.0 1514.5 722
scan_start_y:  700
1514640412 338.54135338345867 1104 788.5 845.1932366716314
/Users/kivygogh/tools/platform-tools/adb shell input swipe 540.0 1514.5 540.0 1514.5 722
scan_start_y:  700
1514640417 338.54135338345867 1104 788.5 845.1932366716314
/Users/kivygogh/tools/platform-tools/adb shell input swipe 540.0 1514.5 540.0 1514.5 722
scan_start_y:  700
1514640423 338.54135338345867 1104 788.5 845.1932366716314
/Users/kivygogh/tools/platform-tools/adb shell input swipe 540.0 1514.5 540.0 1514.5 722

**Comment by KivyGogh** [comment]
自动运行了，但是每次数据都一样，不跳

**Comment by localjc** [comment]
我知道了，模拟点击的权限问题。。。。。

**Comment by KivyGogh** [comment]
这个权限怎么调? 作者说不用root

**Comment by mahong125** [comment]
红米 Note4X MUI 9系统，运行后不会自动跳。。
