### ISSUE TITLE
一个圆盘挂掉的问题

### ISSUE THREAD

**Issue by chenliuchun** [wangshub/wechat_jump_game#136]
如图所示，在542分挂掉的，不知道这个问题的原因是什么。应该不是明显的参数设置bug。
小米6,，1920*1080，press_coefficient = 1.445，其他参数没变。
![1514639060_d](https://user-images.githubusercontent.com/15866964/34454450-d799f6d8-eda6-11e7-9134-e947361a4615.png)

**Comment by Cp0204** [comment]
终点识别算法的问题

**Comment by wangshub** [comment]
已经改正
