### ISSUE TITLE
无语了，一整天都在搞这玩意，晚饭还没吃

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#137]
关键是还弄不好

**Comment by F5F5** [comment]
人才啊，我知道自己肯定搞不定，都是玩一会再回来看看有没有更新

**Comment by mjzcyhp** [comment]
@F5F5 现在是一肚子火啊

**Comment by GhostClock** [comment]
@mjzcyhp 我就卡在这儿了🤣  `requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100)`

**Comment by yuanjingsong** [comment]
@GhostClock  看看是否需要开启端口转发 (不是安卓 胡乱分析

**Comment by GhostClock** [comment]
@yuanjingsong 我是iOS呀，开启了端口转发 `iproxy 8100 8100` ，可是还是不行

**Comment by wangshub** [comment]
大兄弟，辛苦了 @mjzcyhp 我挖的坑，希望能玩的开心

**Comment by likantour** [comment]
@wangshub 玩的可开心了呢O.o

**Comment by jack80342** [comment]
@GhostClock 遇到相同的坑。同样还没有吃晚饭，午饭都没吃
