### ISSUE TITLE
auto.py运行成功，但是每次都是相同的数据，不跳

### ISSUE THREAD

**Issue by KivyGogh** [wangshub/wechat_jump_game#138]
<img width="570" alt="2017-12-30 9 29 43" src="https://user-images.githubusercontent.com/8515579/34454551-9cfef3dc-eda8-11e7-8503-f334906b0ba8.png">

五十块钱真难赚啊

**Comment by KivyGogh** [comment]
好像手机没root,adb shell input swipe不能正常跑

**Comment by wangshub** [comment]
手机不需要root， 你的swipe里面怎么有小数点呢

不要用来赌博哦 @KivyGogh

**Comment by KivyGogh** [comment]
不是赌博的，我给一个小白调试程序，能跑起来他就给我50人工费……
现在就是我打开游戏，小人不动，log里自动更新数据，每次都一样，小数点我也不清楚

**Comment by KivyGogh** [comment]
adb那个命令，单独放到终端里跑，也没变化，应该就是命令没调用起来

**Comment by 524119574** [comment]
如果是小米的话 打开 usb调试（安全设置）应该可以解决这个问题

**Comment by KivyGogh** [comment]
跟MIUI差不多的情况~是vivo，要同时打开usb调试和usb调模拟点击。（建议作者大大把这些信息整理一下放到readme @wangshub ）
VIVO Xplay6 原始数据完美运行。
