### ISSUE TITLE
调试成功，注意小米设备要开启【USB调试】和【USB调试（安全设置）】，现在review代码;

### ISSUE THREAD

**Issue by A11en0** [wangshub/wechat_jump_game#139]
MIUI将USB安装和USB调试（安全设置）从usb调试中分离了出来, 会影响adb shell 执行自动化脚本如本项目中的adb shell input;部分其他国产手机可能也存在这种机制,无法调试成功的可以在开发者选项中查看下是否有类似选项;

**Comment by Superbsco** [comment]
有没有小米5参数，大佬

**Comment by Windsmild** [comment]
就是这个 小米 USB调试（安全设置）里限制了模拟触摸

**Comment by MRdoulestar** [comment]
有用 感谢

**Comment by ToastYang** [comment]
你好  我想知道 USB调试（安全设置）这个有没有能够判断用户是否开启的方法
