### ISSUE TITLE
三星S7edge 设置的参数 大家可以参考一下吗··

### ISSUE THREAD

**Issue by ipengyo** [wangshub/wechat_jump_game#140]
现在玩的全是0分

"press_coefficient": 2.582,

**Comment by alanhsun** [comment]
用包里带的S7e的系数，把按压系数调为1.05，分辨率2560 x 1440，亲测1k+是没问题的，没试过最高可以到多少，朋友圈装逼足够了；）

{
    "under_game_score_y": 384,
    "press_coefficient": 1.05,
    "piece_base_height_1_2": 95,
    "piece_body_width": 102
}

**Comment by astatinede** [comment]
alanhsun,

我按照你的参数把2560 x 1440下面的config改了，可是还是就最多跳两个。
还有哪里需要改么?

**Comment by alanhsun** [comment]
@astatinede 起作用的是程序根目录下的config.json，分辨率是在你手机的设置>显示>屏幕分辨率里面改的，我用的是WQHD(2560x1440)

还有，有没有关掉侧边栏？会影响图像识别
