### ISSUE TITLE
终于成功了，不过不过100啊

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#144]
忘了还要加上个json数据的，我的是小米note3，有谁一样的吗

**Comment by yingke** [comment]
我的也是  最高95 还在看代码 不知道改哪里····

**Comment by mjzcyhp** [comment]
是小米note3的有参数了记得分享下啊

**Comment by pavilion2t** [comment]
有时成功有时不成功……想问 json数据 大概在第多少行

**Comment by mjzcyhp** [comment]
@pavilion2t 大概在29吧

**Comment by wjzhangcsu** [comment]
我的过1000了，我主要是修改press_coefficient参数，手机分辨率为540*980

**Comment by yingke** [comment]
@wjzhangcsu   什么手机呢

**Comment by chenjiandongx** [comment]
请使用最新版本的代码
