### ISSUE TITLE
请大家评论反馈死掉时的截图

### ISSUE THREAD

**Issue by andy1247008998** [wangshub/wechat_jump_game#147]
大家好，我也刚看到这个项目，发现它还不够完美。
主要存在2个问题：
1. 某些场景识别错误，导致挂掉。
2. 32分奖励特别容易中断。

我也看到很多人乱发issue，有的甚至只是一句标题的抱怨，对与优化项目并没有帮助。

希望大家都在这里贴图，看看是哪些情况下会死掉，我有思路以后会帮忙改改代码。

**Comment by andy1247008998** [comment]
![1514643349_d](https://user-images.githubusercontent.com/7299189/34454915-c9e1825a-edaf-11e7-8fdc-7b1f781cfb89.png)
判定的距离太近。看起来判定依据是上下两个顶点与跳跃方向的焦点，但是似乎应该是跳跃方向的这条边的中点(也就是稍微远一点的位置)会比较好。

**Comment by pavilion2t** [comment]
想请问知不知道为什么我的截图都没有白线？ 小米6

**Comment by andy1247008998** [comment]
> 识别棋盘：靠底色和方块的色差来做，从分数之下的位置开始，一行一行扫描，由于圆形的块最顶上是一条线，方形的上面大概是一个点，所以就用类似识别棋子的做法多识别了几个点求中点， 这时候得到了块中点的 X 轴坐标，这时候假设现在棋子在当前块的中心，根据一个通过截图获取的固定的角度来推出中点的 Y 坐标

找到了问题所在：
根据一个通过截图获取的**固定的角度**来推出中点的 Y 坐标
当棋子不在当前块的中心，这个假设就不成立了。

解决方案：
无论棋子在当前块跳远了还是近了，它都在跳跃方向这条边的中点位置。目标位置也在那条边的中点位置。

**Comment by nicky918** [comment]
你说的我早想过了，实现思路也有，不过不改也能刷到1万分。。。这种反而是小问题。
想解决就是改变Y值的计算，去图上做图形的计算

**Comment by andy1247008998** [comment]
我刚才仔细看了大图，感觉“固定的角度”和跳转方向不是平行的。这个固定的角度是按照什么计算的？

**Comment by nicky918** [comment]
@andy1247008998 经验得的。算一下刚好30度

**Comment by Sowevo** [comment]
![1514644579_d.png](https://i.loli.net/2017/12/30/5a47a662dd6d4.png)
![1514645049_d.png](https://i.loli.net/2017/12/30/5a47a662f170f.png)
![1514645049_d.png](https://i.loli.net/2017/12/30/5a47a9bfb214d.png)
A点只知道纵向坐标,横向坐标是根据D点求出来的,所以当前坐标会对计算出来的结果有影响,而且会造成恶性循环,

**Comment by ace0109** [comment]
为什么我的截图里面的线都是一个方向？
![image](https://user-images.githubusercontent.com/18433582/34455260-3dc968d0-edb6-11e7-9b14-1e6a97c9492c.png)

**Comment by andy1247008998** [comment]
我们能否拿到A点下面的另一个顶点呢？
从A点往正下方继续扫描，当色差大于某个值，计为C点。

**Comment by Sowevo** [comment]
@andy1247008998 你是没见过花花绿绿的目标点奥

**Comment by andy1247008998** [comment]
对哦，我看到了张木头桌子。。。

我再想想

**Comment by yushaw** [comment]
![1514645316_d](https://user-images.githubusercontent.com/1041928/34455865-4a173a1a-edc3-11e7-8fac-51a3b4b98eab.png)
之前遇到这种场景都没问题，不知道为什么失败了。


然后感觉“334天”那个深色木头的地方也容易出问题

**Comment by 10o0** [comment]
这个是什么原因呢
![1514690185](https://user-images.githubusercontent.com/25453146/34458895-26a220da-ee1e-11e7-8bdd-ed81f59337ff.png)
![1514690185_d](https://user-images.githubusercontent.com/25453146/34458896-26d2e5e4-ee1e-11e7-9e52-b142be3103d1.png)

**Comment by Sowevo** [comment]
@10o0 是的，这个音符是他找到的第一个与背景有差异的像素这个情况也能遇到，人品不错😊

**Comment by zsluedem** [comment]
![image](https://user-images.githubusercontent.com/13496262/34474807-388d9070-efbf-11e7-9c39-dab1a9382f9a.png)

**Comment by zsluedem** [comment]
![image](https://user-images.githubusercontent.com/13496262/34474874-56b3fbe2-efc0-11e7-94c2-52c2786c6ec2.png)
红米note5A

{
    "under_game_score_y": 200,
    "press_coefficient": 2.36,
    "piece_base_height_1_2": 13,
    "piece_body_width": 47,
    "swipe" : {
      "x1": 374,
      "y1": 1060,
      "x2": 374,
      "y2": 1060
    }
}

**Comment by zsluedem** [comment]
![image](https://user-images.githubusercontent.com/13496262/34474961-4a7e73a6-efc1-11e7-94e9-babdb76bbb07.png)

红米note5A

{
"under_game_score_y": 200,
"press_coefficient": 2.36,
"piece_base_height_1_2": 13,
"piece_body_width": 47,
"swipe" : {
"x1": 374,
"y1": 1060,
"x2": 374,
"y2": 1060
}
}
