### ISSUE TITLE
看了下，三星曲面屏好像测试都不成功

### ISSUE THREAD

**Issue by peekabooovo** [wangshub/wechat_jump_game#149]
三星s8调了参数，发现横着跳还行，竖着跳一直蓄力

**Comment by michelle6147** [comment]
加油 来自plus的鼓励

**Comment by peekabooovo** [comment]
能给下你的参数吗？

**Comment by goldkeyber** [comment]
S8还在调,只能调一格~

**Comment by michelle6147** [comment]
S8+ 2220*1080 跑出 3000+

under_game_score_y = 619
press_coefficient = 1.40
swipe_x1, swipe_y1, swipe_x2, swipe_y2 = 320, 410, 320, 410
piece_base_height_1_2 = 20
piece_body_width = 70
sample_board_x1, sample_board_y1, sample_board_x2, sample_board_y2 = 463, 1692, 1047, 1364

这是别人发的 ，我测试了不行，你们试一下

**Comment by stepforward** [comment]
@michelle6147 按你说的试了...一个都跳不过....

**Comment by stepforward** [comment]
@michelle6147 莫非我们是不一样的s8+?

**Comment by michelle6147** [comment]
@stepforward 我就觉得那个人发的是错的 我的也不行

**Comment by NoBey** [comment]
@michelle6147  这个不行

**Comment by goldkeyber** [comment]
s8跳出2000多就会自杀~

**Comment by gshcly** [comment]
@goldkeyber 大兄弟，能发下你的参数和分辨率吗，我的S8+屡试不爽

**Comment by hzwgis** [comment]
@goldkeyber  发下参数呀，我的s8最多就40多，还很不稳定。

**Comment by ccldvv** [comment]
@michelle6147   把长按系数调到1.0几  可以跳  但定位不准

**Comment by NoBey** [comment]
s8 需要关闭曲面侧屏 不然怎么都不行 上面配置应该是可以的 1.3+ 的基本是1080p   1左右的是1440的

**Comment by gshcly** [comment]
三星S8+，2960*1440测试成功
"under_game_score_y": 619, 
"press_coefficient": 1.05, 
"piece_base_height_1_2": 20, 
"piece_body_width": 70
务必关闭曲面侧屏（设置-显示-曲面侧屏-曲面侧屏面板[关]）

**Comment by hzwgis** [comment]
s8（2220*1080）关闭曲面侧屏后测试成功。
`{
    "under_game_score_y": 619, 
    "press_coefficient": 1.392, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70,
	"swipe" : {
      "x1": 530,
      "y1": 1730,
      "x2": 530,
      "y2": 1730
    }
}`
