### ISSUE TITLE
谁能手把手教下啊

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#15]
不会python的，it小白鼠，不过手机好像可以运行python了，谁手把手教下啊，要不提示下也好啊！需要手机连电脑的吗？

**Comment by guanghuizhao** [comment]
不是用手机执行的python脚本，我刚也有跟你一样的疑惑，不过现在弄好了。
1、先在电脑上安装adb，mac上建议参考 https://www.jianshu.com/p/1b3fb1f27b67
2、使用usb连接手机跟电脑。
3、如果adb devices命令显示不了手机，参考这个  https://www.jianshu.com/p/9e2ecb79acfa
4、把项目代码clone下来，按照教程使用就好了。

**Comment by windbeijing** [comment]
小白教程：

![qscode](https://user-images.githubusercontent.com/34977008/34459723-7bf68c14-ee33-11e7-91d6-76c66ae31afa.jpeg)

**Comment by F-loat** [comment]
B站UP主的视频教程 [【微信跳一跳】教你如何不用双手还能霸占排行榜第一名](https://www.bilibili.com/video/av17796840/?redirectFrom=h5)
