### ISSUE TITLE
How to open????????????

### ISSUE THREAD

**Issue by zakirhossen23** [wangshub/wechat_jump_game#1509]
How to open?????????

**Comment by save666666** [comment]
open what



---Original---

**Comment by zakirhossen23** [comment]
How to edit this project????????????????????

**Comment by zakirhossen23** [comment]
I can't open and run this project!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bang919** [comment]
install "adb" and "python3",
then use "python3 wechat_jump_auto.py",
you can get help from: https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4
