### ISSUE TITLE
三星Note 5 分辨率调到1920×1080，代码无修改，4555分

### ISSUE THREAD

**Issue by Francis-G** [wangshub/wechat_jump_game#151]
三星Note 5 分辨率调到1920×1080，4555分
最后失败的截图
![1514635728_d -](https://user-images.githubusercontent.com/24939944/34454939-5120da4a-edb0-11e7-9a9a-133a0483ec64.jpg)

**Comment by ipocky** [comment]
请问截图白线是本来就有么
我的截图没白线..

**Comment by wangshub** [comment]
棒 @Francis-G
