### ISSUE TITLE
确实不是线性的，应该是二次函数

### ISSUE THREAD

**Issue by sunnanphp** [wangshub/wechat_jump_game#152]
本人红米note4x参数设置的为1.4812发现重合度比较高，有时可以到中心。有圆点的到中心的机率比较大！

**Comment by F-loat** [comment]
``` javascript
var n = new o.Vector3(t.nextBlock.obj.position.x - t.bottle.obj.position.x, 0, t.nextBlock.obj.position.z - t.bottle.obj.position.z)
t.direction = new o.Vector2(t.nextBlock.obj.position.x - t.bottle.obj.position.x, t.nextBlock.obj.position.z - t.bottle.obj.position.z)
t.bottle.jump(n.normalize())
```
跳一跳小程序源码中和跳动相关的部分代码，虽然压缩了，但是还是能看个大概的。

`Vector3` 和 `Vector2` 都是 `three.js` 的函数，
`nextBlock` 是跳转目标，`bottle` 是棋子，根据这两者的坐标，计算出方向及距离，
最后执行 `jump` 函数进行跳转，主要是完成一些动画

**Comment by DemoJameson** [comment]
@F-loat 主要是看 checkHit2 函数吧，里面计算到 `this.direction.setLength(bottle.velocity.vz * r)` 的这个值相当于往上跳的距离

**Comment by sonnyhcl** [comment]
我也试了这个参数1.4812，但是效果不是很好。我git clone的最新版，会不会是其它的参数改动了。请问你测试的时候其它的参数是多少呢？可以一起晒一下么？ @sunnanphp

**Comment by sunnanphp** [comment]
@sonnyhcl   有一个哥们晒了一个distance的一段代码，我用的他的，跳了有2000多。就在评论里，你找下

**Comment by sunnanphp** [comment]
@F-loat 感谢分享，受教了
