### ISSUE TITLE
我的小米note3

### ISSUE THREAD

**Issue by lovebluedan** [wangshub/wechat_jump_game#153]
就最多自己改了参数跑了230+然后就挂了

**Comment by yingke** [comment]
一样手机 我改press_coefficient": 1.45,   现在455  还在跑··

**Comment by yingke** [comment]
486  挂了···

**Comment by mjzcyhp** [comment]
我也是小米note3，10多分到100分左右

**Comment by lovebluedan** [comment]
现在吧 press_coefficient": 1.45 可以跑到四百多了

**Comment by wangshub** [comment]
有些特殊机器需要自己摸索一下参数哦 @lovebluedan

**Comment by lovebluedan** [comment]
@wangshub 哈哈 我还是没有个好点的参数~ 小米note3 要是有合适的参数 透露下哈~
