### ISSUE TITLE
小米note3跑10多分就死掉了，屏幕同样的联想能跑到几百

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#158]

**Comment by wangshub** [comment]
note3可能参数需要优化一些，没有测试机器，要是找到最优配置麻烦分享一下哦 @mjzcyhp

**Comment by mjzcyhp** [comment]
@wangshub 小米note3和联想的手机屏幕和分辨率都是一样的，不过联想的稳定，都是能够好几百，而小米note3有个位数就掉了的，也有140多才掉的。联想的比较稳定，大多是在中间的小白点上。感觉小米note3的比较迟钝一点，如果能再跳大力一点的话应该也没什么问题了。搞完后索然无味了
