### ISSUE TITLE
我运行的速度挺慢的，你们的咋样？

### ISSUE THREAD

**Issue by bordf** [wangshub/wechat_jump_game#16]
是不是我电脑太破了啊

**Comment by mjzcyhp** [comment]
大神怎么弄啊，

**Comment by binderclip** [comment]
是很慢的，可以考虑像 https://github.com/wangshub/wechat_jump_game/issues/17 里调小 sleep 的值，或者不知道 adb 截图那边还有没有优化的空间。

**Comment by bordf** [comment]
我已经调小了 休眠时间，但是还是很慢，后来我调高了我的CPU速度，稍微快了一些，我觉得是 图形处理那块执行效率有点慢。。

**Comment by binderclip** [comment]
@bordf 可能需要测试一下 pil 的图片操作消耗的时间，那块儿好像也很慢，直接用了没有细测

**Comment by bordf** [comment]
@binderclip 建议每次都打印下耗时。我这几乎要十秒钟才能跳一下，有点蒙，我承认我电脑用了八年了。

**Comment by binderclip** [comment]
@bordf 等今天白天了可能去做一下优化吧。

**Comment by bordf** [comment]
@binderclip 差不多一个小时了，刷到了八百多分，我还录了个小视频，哈哈

**Comment by binderclip** [comment]
@bordf 赞！

**Comment by bordf** [comment]
@binderclip 其实看到你的代码挺巧合的，我今天正好心血来潮研究了下adb来模拟点击，打算刷点火山小视频的互动和点赞呢，晚上刷脉脉就看到了你的代码，我其实都没玩过这个游戏，只是知道小程序出了这个demo，本来都要准备睡觉了，快十二点了洗个脚又回来玩了下你的代码，哈哈，不错

**Comment by bordf** [comment]
1001分了~

**Comment by bordf** [comment]
(1514569492, 793, 1110, 336, 1374)
D:\adt\platform-tools\adb shell input swipe 500 1600 500 1601 735
25
2925 KB/s (289407 bytes in 0.096s)
(1514569515, 719, 1067, 401, 1250)
D:\adt\platform-tools\adb shell input swipe 500 1600 500 1601 511
21
3075 KB/s (370312 bytes in 0.117s)
(1514569541, 477, 1024, 645, 1121)
D:\adt\platform-tools\adb shell input swipe 500 1600 500 1601 270
25
2336 KB/s (335913 bytes in 0.140s)
(1514569567, 810, 1122, 315, 1408)
D:\adt\platform-tools\adb shell input swipe 500 1600 500 1601 796
25
2000 KB/s (191758 bytes in 0.093s)
(1514569594, 710, 1063, 400, 1242)
D:\adt\platform-tools\adb shell input swipe 500 1600 500 1601 498
25
2946 KB/s (192500 bytes in 0.063s)
(1514569619, 828, 1131, 300, 1436)
D:\adt\platform-tools\adb shell input swipe 500 1600 500 1601 849
24
3129 KB/s (199973 bytes in 0.062s)

**Comment by binderclip** [comment]
@bordf 不不，我是 Contributor 不是 Owner，Owner 是 @wangshub
我是在原有的基础上加了一个简单版本的自动识别。

**Comment by gunten** [comment]
主要是计算下一步坐标慢啊 兄弟 @bordf
