### ISSUE TITLE
S7 Edge分享的配置文件

### ISSUE THREAD

**Issue by xxxuuu** [wangshub/wechat_jump_game#163]
{
    "under_game_score_y": 384,
    "press_coefficient": 1,
    "piece_base_height_1_2": 95,
    "piece_body_width": 102
}

只要把截图拖进PS里根据注释算一下就好了

**Comment by wangshub** [comment]
感谢分享 @xxxuuu

**Comment by F5F5** [comment]
有没有S8 S8+ NOTE8大佬分享个配置啊😭

**Comment by wangshub** [comment]
已添加 @xxxuuu
