### ISSUE TITLE
不要分数刷太高，我跑到4000多分排行被官方给删了。。

### ISSUE THREAD

**Issue by ABadCandy** [wangshub/wechat_jump_game#164]

**Comment by 897902334** [comment]
微信那帮鸟人 是不是以为咱们开挂了？

**Comment by SbyXlmm** [comment]
什么意思？分太高了不能用？

**Comment by 897902334** [comment]
分太高  就给清0 了

**Comment by wangshub** [comment]
**注意**，不要刷太高，容易排名清零

**Comment by 897902334** [comment]
嗯嗯，我现在500多  稳居排行榜第一位！  这个分数就可以了

**Comment by SbyXlmm** [comment]
我其实在想，大佬怎么想到用这个方法的呢？真的太好玩了。

**Comment by Superbsco** [comment]
哎

**Comment by wangshub** [comment]
@SbyXlmm 灵光一闪

**Comment by DevXue** [comment]
@Superbsco   400的分数 在排行榜也能拿第一了吧   可以了。

**Comment by wangshub** [comment]
@SbyXlmm 灵光一闪

**Comment by DevXue** [comment]
@wangshub    老哥  你简直超神了，  我辈之楷模啊！

**Comment by Superbsco** [comment]
@DevXue 可以，但是我有一同学，手动340，很不稳

**Comment by DevXue** [comment]
@Superbsco    他那是体力劳动，  你在想想咱们   哈哈哈哈

**Comment by superwzlx** [comment]
脑力活，贼累哈 @DevXue

**Comment by Hackxiaoya** [comment]
看来官方知道你是开挂的了。

**Comment by haozhou0327** [comment]
@wangshub 路人甲刷到了10w，最后也被清零了。刷到10w对参数要求很高吧？

**Comment by AugustXY** [comment]
微信官方已经开始针对调整了，刷几盘就会出现“玩了这么久了，请休息一下吧”提示。

**Comment by coolwolfqs** [comment]
清零后，经常遇到失败，没超过200

**Comment by Leelour** [comment]
@haozhou0327 十万的是直接改最后的post的 当然在榜上很快就会消失

**Comment by Fibird** [comment]
运行的时候，手机上会显示在自动操作吗？我这个什么反应都没有，只看到电脑屏幕一直在滚动命令。

**Comment by LoYoPP** [comment]
最高55分！！！mi 4用 auto 脚本不太准了。。

**Comment by ysy950803** [comment]
这是物理挂，不是内存挂，不改内存不改网络数据，天然无公害。

**Comment by wangshub** [comment]
是的，只要图像识别就可以，不行就加个摄像头机械臂

**Comment by ronanhardiman** [comment]
刚刷到四百多分，坚持住。

**Comment by blackreger** [comment]
为什么会有一样的参数今天跑跟昨天跑差距很大的情况，而且用同样的参数下，原来可以判断准确的距离都判断不准了，是什么原因？

**Comment by RichardWeiYang** [comment]
哈哈哈，还好，我只刷到了1000多

**Comment by Yuibooo** [comment]
600多也被清零了。。。什么情况

**Comment by DevXue** [comment]
@Yuibooo   老哥 ，你别吓我，  我刚刷到633，   你多长时间发现被清理了？？

**Comment by zh-h** [comment]
@DevXue 周一清零啊，六百多很多人手动都有这个分的。

建议你们给跳跃距离加个随机的偏差，不然上传到服务器的数据那么规整就被识别出来。

**Comment by Yuibooo** [comment]
@DevXue 我sb了，周一自动清零，虚惊一场

**Comment by EricBrownz** [comment]
能否加入暂停功能
在近距离情况下使用不理想

**Comment by jousonren** [comment]
刚才试了试发现圆形的就容易掉下去，我好想就没到过200分。。。。难道要让他自己刷一宿？？？

**Comment by Yggdrasill-7C9** [comment]
目前手动刷不会被清零。
自动刷的话记得最后提前 control +C 退出脚本，然后手动跳几下，就可以了。
总结了几个朋友刷分清零的情况，都是刷完最后没有正常退出程序。

**Comment by Slodezzm** [comment]
如何不连跳中心，修改了1.3几的参数跳到20多会失败

**Comment by zyxbcde** [comment]
今早刷到2000多成了，用的昨天的程序，跳的比较外还需要人看着修正，可能更像个人的操作。今天更新了全自动跳到笔记本没电关机，分被清了。

**Comment by IanSmith123** [comment]
直接post最后的结果给微信的哥们还是强啊

**Comment by Yudezhi** [comment]
仰望高端玩家

**Comment by MrLevo520** [comment]
安全界限 3900未被清零，1.2w被清零

**Comment by AlexiaChen** [comment]
我都没有用这个辅助来玩，完全自己手动来玩，刷到250.  结果就被清零了

**Comment by zhaoweihaoChina** [comment]
有清零后可以恢复的小伙伴吗，我清0后怎么玩别人都看不见了

**Comment by radius-yf** [comment]
每周一凌晨会刷新，楼上的看看是不是昨天清零的。。。

**Comment by luopan007** [comment]
是撒，每周都会清零的。，

**Comment by raoweijian** [comment]
之前我用POST作弊过一次，然后发现现在不管是手动玩，还是用脚本模拟，分数都会被清零！1分也清零！估计是上了黑名单了。大家且刷且珍惜

**Comment by zhaoweihaoChina** [comment]
@raoweijian 和你的情况一模一样，大家不要刷太高，现在我怎么玩都是自己能看见

**Comment by hero708** [comment]
我昨天晚上刷到1000分还没有被清零，但是中午帮别人刷300多都被清零，难道我这台设备上了黑名单了？

**Comment by MoliLisa** [comment]
为何我手机上一断开开发模式 分数就从排行榜上清了，（是control c退出 并继续玩了一会）

**Comment by amberwest** [comment]
别啊,我还没开始玩呢就要被清了吗

**Comment by leegang** [comment]
我刷到700多分，然后就被清零了

**Comment by xuxinzhen** [comment]
我跳600多分就被清了，但还保存了我上次手工跳的280分。600多只比第二名多200分而已。

**Comment by DevXue** [comment]
就是不知道微信官方的清零规则是怎么来指定的！ 怎么个原理

**Comment by Gentlehuwei** [comment]
模拟器上不行了吗？

**Comment by findfz** [comment]
只能自己看了，上传不到微信的服务器。

**Comment by Laciel** [comment]
只有自己的排行榜里有这个分数了。
我现在更改了跳跃的随机时间，但是还是没什么卵用了。。。
估计是检测是否用了辅助控制的端口。
大家活在自己的高分里吧...

**Comment by MoliLisa** [comment]
刚刚二百分成功上传服务器了 但是分数再高就不行， 说明不是辅助控制端口的事?

**Comment by leeven1992** [comment]
不要封啊，我还在配环境呢

**Comment by xuxinzhen** [comment]
448上传成功，先自己玩了100分，但448还只能排第二。。。。。

**Comment by Laciel** [comment]
@MoliLisa 200分饰纯用auto跑的么？

**Comment by DevXue** [comment]
我见作者9分钟前更新的代码，  你们都是用最新的代码跳的吗？

**Comment by jousonren** [comment]
我改了参数结果时间长的时候跳的比中心点远，时间短的时候跳的近，，，，不是应该只是远或近吗

**Comment by leeven1992** [comment]
File "wechat_jump_auto.py", line 248, in <module>
    main()
  File "wechat_jump_auto.py", line 225, in main
    op = yes_or_no('请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳游戏再用本程序，确定开始？')
  File "wechat_jump_auto.py", line 209, in yes_or_no
    i = raw_input(prompt)
NameError: name 'raw_input' is not defined

这个是为什么，adb连上了，也打开游戏了

**Comment by MoliLisa** [comment]
@Laciel  当时我试了好几次 记不清了， 不过我发现手机开发者模式下是有两个微信的（一个运行了很久的 一个是是跟开发者模式刚打开的）有没有可能和这个有关系呢 就是猜测？  
就在刚刚 五百多分 成功上传（先自己玩了几下  电脑跑了两次 又自己玩了几下）然后在开发者模式下按顺序把运行的微信关了 再然后 重新打开 分数仍然在。yeah。     贡献下我的经历 找出问题~

**Comment by lewis617** [comment]
我刷了一个600多的也被删了

**Comment by iamldj** [comment]
微信删排行是有规律的，如果你连续不断的跳在中心点上，而且分数超过500，极大可能会被删除。

**Comment by lewis617** [comment]
@iamldj 你说的这个规律是官方的吗？

**Comment by cuteonion** [comment]
@leeven1992  因为你的python版本不对

**Comment by SefaZeng** [comment]
历史最高分是有得 但是排行榜上面不显示是什么原因 有人知道吗

**Comment by Laciel** [comment]
第一次没调跳跃的时间间隔，time.sleep(1)，手动点了几下，大部分是自动跑的，700分，排行榜不显示。
第二次后来换了时间间隔，（1，1.5）随机，825分，还是排行榜不显示，只能本地看到。
第三次，连跳和手动交替，最后几次拔了usb，手动跳，1001。显示了。。最久连跳中心不超过12次。
以上给需要帮助的朋友。

**Comment by zaaach** [comment]
可以设置不让跳正中心位置吗？我刷400分也给删了

**Comment by zhengxianjun** [comment]
我的排行榜里有个人纯手动玩到1115。。。。

**Comment by ai970993296** [comment]
我刷到750就被清空了，是不是在代码中加入随机的落点偏差和随机的起跳时间会好一点。。。大神们。。。。。

**Comment by xianfeng92** [comment]
刷了三个分数段～～400,600,700～～～目前木有遇到清零的情况～～～

**Comment by liuyajian** [comment]
华为荣耀9 : 1600清零 ， 1000清零 ， 700清零 装逼失败，生无可恋

**Comment by LoseRecall** [comment]
300多清零

**Comment by SkyWalkerZC** [comment]
昨天中午刷300+还在，晚上刷了2000+清零了，然后又刷了300+又清零了

**Comment by iamldj** [comment]
如果想要随机跳不准 把
`press_time = distance * time_coefficient / 1000`
改成
`press_time = (distance+random.uniform(-2, 2)) * time_coefficient / 1000`
试试，具体的随机数范围（-2，2）自己调一下。

**Comment by MakeBigWorldSmall** [comment]
如果碰到一些很近的有把握的可以ctrl+c退出程序自己跳，没把握的就让脚本跳，这样被清零的概率会低很多。

**Comment by cjzhangchn** [comment]
华为荣耀V8，2000分清零；再跑，1500分清零；再跑，1000分清零；再跑，500清零；再跑。。。我不跑了，投降还不行吗。。。

**Comment by shengpj** [comment]
我怎么200就清掉了

**Comment by TianYuan1998** [comment]
利用脚本自动跳一跳它每次起跳的间隔是相同的，而手动跳每次的时间间隔是不一样的。腾讯可能以这个为依据检测是否作弊

**Comment by shengpj** [comment]
![image](https://user-images.githubusercontent.com/13343566/34511477-db379ed8-f096-11e7-875f-723bee08256b.png)
应该不是的，我改成这样还是会被清零。

**Comment by SkyWalkerZC** [comment]
应该不是吧，现在的间隔不都是设置的一定范围的随机数了

**Comment by ChenDuBUAA** [comment]
魅族MX5，手动版，667成功，本来想刷666的，最后一跳没把握好，+2了。。。

**Comment by fgksgf** [comment]
源代码里面按压屏幕的位置是固定的，间隔时间也是固定的，我把这两些参数都改成了随机数，跳到490+，没有被清零：
```
def set_button_position():
    global swipe_x1, swipe_y1, swipe_x2, swipe_y2
    left = random.randint(10,1000)
    top = random.randint(200,1500)
    swipe_x1, swipe_y1, swipe_x2, swipe_y2 = left, top, left, top

def main():
    dump_device_info()
    check_screenshot()
    while True:
        pull_screenshot()
        im = Image.open('./autojump.png')
        # 获取棋子和 board 的位置
        piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
        ts = int(time.time())
        print(ts, piece_x, piece_y, board_x, board_y)
        set_button_position()
        jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
        save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y)
        backup_screenshot(ts)
        time.sleep(random.randint(2,8))   # 为了保证截图的时候应落稳了，多延迟一会儿
```

**Comment by SkyWalkerZC** [comment]
楼上方法亲测有效

**Comment by SkyWalkerZC** [comment]
又试了一次跳到1000+ 没有记录了

**Comment by lihuangshuaige** [comment]
感觉还是不能连续跳中心点啊

**Comment by lfc100412** [comment]
前天用模拟器刷到2000出头没问题，今天别人说刷到500多都没用，还是显示之前的分数，然后我自己又刷了一遍，发现也是显示之前的分数，新刷的分数无效。

**Comment by SkyWalkerZC** [comment]
前面先自己玩儿一会儿，玩儿到几十分 然后开启程序，最后觉得分数够了，关掉程序再自己玩儿会儿

**Comment by Ace--Qi** [comment]
源码已经更新了 把tap位置改成随机
s.tap_hold(random.randint(150, 250), random.randint(728, 850), press_time)

**Comment by DevXue** [comment]
@Ace--Qi    666   我回去试试！！！

**Comment by lewis617** [comment]
@Ace--Qi 已经测试通过，可行！

**Comment by hero708** [comment]
大家要赶快刷，说不定看评论区的有腾讯的人。

**Comment by cwwise** [comment]
自动 700多 可以

**Comment by zaaach** [comment]
@Ace--Qi 这行代码在哪个地方？

**Comment by Ace--Qi** [comment]
@zaaach 设置press time代码块

**Comment by middlexu** [comment]
@Ace--Qi 源码没有s.tap_hold，
源码是
cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
需要两个坐标一共是四个随机数

**Comment by xiaochongzit** [comment]
手动刷到400分就出问题了
<img width="253" alt="capture" src="https://user-images.githubusercontent.com/17757981/34546268-a588fe02-f12d-11e7-94a2-b6631f9fa99c.PNG">

**Comment by Ace--Qi** [comment]
@middlexu 忘了说我的是auto ios 原理都差不多  把按压位置随机化

**Comment by lihuangshuaige** [comment]
安卓的好像已经是随机的了  也不是很懂  只不过看到了random

**Comment by SkyWalkerZC** [comment]
分数清零了，怎么玩儿都是0分。。。。

**Comment by cwwise** [comment]
@SkyWalkerZC 哈哈 我也是。看看下周一吧

**Comment by zhaoweihaoChina** [comment]
@SbyXlmm 我周日也这样，今天恢复了，可以有分数了

**Comment by Larry955** [comment]
@xiaochongzit 我和你一样的情况，刷到200+就网络错误。。

**Comment by zhuyx808** [comment]
刷到多少都会被清0……

**Comment by Welding** [comment]
前天晚上刷到1000，今早发现清零，在好友排行榜里还消失了，垫底的机会都不给。。。

**Comment by yangfangqun** [comment]
@Welding 看来只有 默默的把跳一跳删除了，哈哈哈哈哈，我也是这种情况

**Comment by andrewforxcf** [comment]
清零了 ，gg，多少分都清，自己玩的也被清零了

**Comment by destiny85** [comment]
微信的封号好变态的，还不是清零的问题 自己的排行旁上自己分还在，其他好友里的都看不到了，在手动玩成绩都无效了

**Comment by Welding** [comment]
看来到我们团结起来，刚一波微信了。。。

**Comment by luopan007** [comment]
微信这个吧，太他妈的萨比

**Comment by SkyWalkerZC** [comment]
果断不玩儿了

**Comment by yangfangqun** [comment]
把游戏删了散了吧，哈哈哈哈哈

**Comment by CallBackMe** [comment]
怎么刷 都是0分  纯手动 、脚本手动、脚本自动  装b宣告失败  大家且刷且珍惜吧 ～

**Comment by zhuyx808** [comment]
好像发现原因了：
1、启动脚本前，请先将微信给完全关闭，直接停止掉，连上电脑后，再启动微信。
2、按压位置请随机一下，不要老是正中心。-2~2的随机。
3、每一跳的间隔时间请随机一下。我是按2~8秒随机的。
试了2次，未被清0……

**Comment by edwardju1010** [comment]
@zhuyx808 随机的地方看不懂？可否具体指示小白

**Comment by yongqiu** [comment]
还有就是，不要在聊天中或者朋友圈说你用脚本的事情，you know，微信并没有那么隐私~

**Comment by xunshuideyu096** [comment]
哈哈哈，苍天饶过谁

**Comment by MyFirmament** [comment]
2000+成功上传，感觉和设备有关系。我用一台旧的小米三几乎没失败过，其他设备就各种问题。

**Comment by az255** [comment]
就是黑名单，我现在手刷1分都被删，微信太小家子气。所以我把小程序删了。不玩还不行吗？

**Comment by lewis617** [comment]
周一来看，依然无法上排行榜，我觉得微信这个规则有点过……

**Comment by chaozhangpower** [comment]
ios 你们有修改吗？

**Comment by lfc100412** [comment]
大概是被加入黑名单了吧，自己玩的才跳了一百多分也被清零了。

**Comment by RyneHuang** [comment]
修改成随机等待时间与随机按键位置，没有被ban

**Comment by zaaach** [comment]
@RyneHuang 在哪修改的？哪行代码

**Comment by MeyZhou** [comment]
无敌是多么寂寞😂

**Comment by Lingling0408** [comment]
emmm我1000多就被清掉了。。。

**Comment by oldrev** [comment]
黑莓 DTEK50，超不过 2000 就会死

**Comment by zdx1012** [comment]
如何刷到1000分，现在感觉来个7-8百分就被微信屏蔽了

**Comment by mypicko** [comment]
再也不用苦呵呵的刷排名了

>

**Comment by zknyy** [comment]
我觉得吧。。。
🐶日的TX程序员是很有可能根据现在的代码来制定屏蔽规则的，即使是随机数计算出来的结果也会有特定的数学分布，所以也不是很有用。
我的想法是在整个过程中尽量模糊/混淆程序和手工跳的方式。
1，用更好的多重分布的随机算法，随机用这些随机算法产生数(包括按键位置和时长，另外在跳的过程中你要盯着手机，因为这个时候后台程序可能会进行人脸识别)
2，整个过程中多次手动跳几次

最后，根据自古以来敌我斗争的经验总结来看，这是一个长期切漫长的过程，但总归是魔高一尺道高一丈(参考计算机病毒和杀毒软件)。什么时候TX下架了这个小程序就是我们最终胜利之时。
革命尚未成功，同志们还需继续努力。
