### ISSUE TITLE
各位大佬有小米5x的参数吗

### ISSUE THREAD

**Issue by superwzlx** [wangshub/wechat_jump_game#165]

**Comment by xu42** [comment]
#278 可以看看这个，已经2500+了

**Comment by skylinebin** [comment]
注意看加载的config.json参数，默认加载的是1920*1080文件夹的参数，要换成一下。

**Comment by xu42** [comment]
@skylinebin @superwzlx 是的，这是一个坑。
另外更新了新的mi5x，已合并到master，实测3500+了。 #292
