### ISSUE TITLE
我自己修改的小米5参数跑不过400分，求各位大佬给一个小米5的参数上500-600的

### ISSUE THREAD

**Issue by Superbsco** [wangshub/wechat_jump_game#166]
`
这是自己修改的参数，跑不过400分.
press_coefficient = 1.495    # 长按的时间系数，请自己根据实际情况调节

piece_body_width = 82       # 棋子的宽度，比截图中量到的稍微大一点比较安全，可能要调节
求上500-600分的参数

`

**Comment by chenjiandongx** [comment]
参见 config
