### ISSUE TITLE
小米Max 6.4寸参数1.393，打到6666分

### ISSUE THREAD

**Issue by tarvos21** [wangshub/wechat_jump_game#168]
```
def jump(distance):
    press_time = distance * 1.393
    press_time = int(press_time)
```
6.4寸屏幕，1920*1080，用1.393，还是很稳定的，但我是手撸，不是自动，自动识别精度还是太低。
手动一个小时大约能刷到6000分。试了好几个程序脚本，就这个 python3 手动版好用，因为它稳定。

祝各位2018年6666大顺！

![img_1812 copy](https://user-images.githubusercontent.com/18745870/34455554-56820a70-edbc-11e7-9d29-fbcda8513483.PNG)

（想代刷的可联系我。。。）

**Comment by wangshub** [comment]
可以分享小米MAX配置文件吗 @tarvos21

**Comment by yemengsky** [comment]
高手，我这么设置自动跳也可以

**Comment by tarvos21** [comment]
@wangshub 
系统是macOS，安装了 adb，可以连接安卓手机，用的小米 Max 6.4寸，**1920*1080**分辨率。

macOS安装adb软件的命令是：`brew cask install android-platform-tools`
测试是否检测出手机： `adb devices`

安装好后，git clone 代码，首先安装依赖库，因为使用 python3，所以安装的时候，用 pip3:
`pip3 install -r requirement.txt`
挂代理会快很多

修改 `wechat_jump_py3.py`，第14行，distance后面的数字改为 **1.393**

最后运行脚本：
`python3 wechat_jump_py3.py`

在电脑上点击起点和终点。

**Comment by yemengsky** [comment]
直接修改根目录下的config.json就行了：
`{
    "under_game_score_y": 300, 
    "press_coefficient": 1.5, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70
}`

**Comment by tarvos21** [comment]
@yemengsky 试了下，不到50分就跳飞了，你是全自动，每次能调到中心点？怎么配置的？

**Comment by yemengsky** [comment]
@tarvos21 实测至少270，没有别的修改，纯自动。

**Comment by keytodoor** [comment]
同 mac 为何运行phthon3 点击图片上的起点和终点没有反应呢

**Comment by yemengsky** [comment]
@keytodoor https://github.com/wangshub/wechat_jump_game/issues/139

**Comment by fried-muscle** [comment]
为啥我MAX2，用的1.393两百多就不行了
