### ISSUE TITLE
其实time.sleep(0.5)完全没问题

### ISSUE THREAD

**Issue by cn0xroot** [wangshub/wechat_jump_game#17]
如题，0.5秒完全足够落稳了~

**Comment by mjzcyhp** [comment]
大神具体怎么弄啊，能详细写个教程吗？不会python

**Comment by binderclip** [comment]
0.5 能行的话自然小一点比较好。
记得当时测试的时候时间太短的话一些极端情况落不稳好像，就功亏一篑了。。所以最后用了很保险的数字。

**Comment by Bingshuli** [comment]
1秒是最保险的。。我试过0.2秒的，过一会就跳出来了

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
