### ISSUE TITLE
adb驱动有人给个链接吗？另外 安卓的电脑同时装了2和3有影响吗？

### ISSUE THREAD

**Issue by guoqing-tang** [wangshub/wechat_jump_game#175]
我网上找不到大佬能给一点详细的教程吗？

**Comment by StephenHuge** [comment]
as 和eclipse都自带有adb的

**Comment by 524119574** [comment]
https://adb.clockworkmod.com/

**Comment by tjuyy** [comment]
安装Android SDK Platform-Tools 
https://developer.android.com/studio/releases/platform-tools.html
Android SDK Platform-Tools is a component for the Android SDK. It includes tools that interface with the Android platform, such as adb, fastboot, and systrace.
