### ISSUE TITLE
淘宝有商家在卖上分神器，高度怀疑是在售卖本项目

### ISSUE THREAD

**Issue by F-loat** [wangshub/wechat_jump_game#177]
![tim 20171231005340](https://user-images.githubusercontent.com/16759376/34455941-11c9d6c0-edc5-11e7-896b-4a8e40c53de8.jpg)

**Comment by cschencs** [comment]
这就没意思了

**Comment by F-loat** [comment]
很没意思了，还拿他们没什么办法

**Comment by Lujango** [comment]
倒过来想，没有本项目也有其他项目出来在淘宝上卖的

**Comment by geekliuyq** [comment]
淘宝上的不是这个，你以为会玩python的人很多吗，再说了这个项目也不适合卖，毕竟要用电脑，淘宝那个我有，加我免费给你
WX790686902

**Comment by xiaoyi484** [comment]
加不上啊

**Comment by F-loat** [comment]
我是觉得卖的是自己开发出来的技术的商家，也无可厚非，但是售卖开源项目就不太好了

**Comment by NoBey** [comment]
@F-loat  你可以去搜搜叉叉助手，里面有也有不少脚本，我估计原来都差不多

**Comment by F-loat** [comment]
嗯，各种版本的实现有好多了现在，

**Comment by NoBey** [comment]
不过那种直接手机跑的还是挺方便的不用开电脑，我看那个叉叉助手是写了一套底层，用lua来做的api调用的有点意思

**Comment by F-loat** [comment]
js的也有，什么AutoJs好像
