### ISSUE TITLE
项目对圆形区域对中心识别不太准确

### ISSUE THREAD

**Issue by yemengsky** [wangshub/wechat_jump_game#178]
![1514652707_d](https://user-images.githubusercontent.com/6263404/34455943-1bb498c8-edc5-11e7-8378-27ddd028aeef.png)
![1514650087_d](https://user-images.githubusercontent.com/6263404/34455944-1be6f25a-edc5-11e7-85c1-cf4a142b83a2.png)

**Comment by VitalyAnkh** [comment]
的确，我也遇到了

![1514652956_d](https://user-images.githubusercontent.com/24508452/34456344-c989eb02-edce-11e7-8c18-75f61e77cbc8.png)

**Comment by VitalyAnkh** [comment]
![default](https://user-images.githubusercontent.com/24508452/34456595-2ead57f2-edd5-11e7-8b69-98a8759b451f.png)
![default](https://user-images.githubusercontent.com/24508452/34456600-5a441c34-edd5-11e7-8fad-b52bc5678e8c.png)

该改进中心识别算法了

**Comment by wjllance** [comment]
他本来就没有识别中心- -他求了棋子的中心和下一个board的横坐标中心，board的纵坐标是用角度算的，所以如果你的棋子在中心，那你算出来的board也是中心，如果你的棋子偏了，那board的中心也会偏。。所以他这个算法目前最大的缺陷就是累积误差导致的board中心不精确，所以会GameOver，如果解决了board中心的识别问题那理论上就可以无限刷了
对于这个问题目前的解决方案只有不断调整另外两个参数使得每次棋子尽量落到中间、、
