### ISSUE TITLE
in set_data     raise TypeError("Image data cannot be converted to float")

### ISSUE THREAD

**Issue by WenshyDreamPenta** [wangshub/wechat_jump_game#18]
in set_data     raise TypeError("Image data cannot be converted to float")
有人出现这个类型错误么

**Comment by WenshyDreamPenta** [comment]
wechat_jump.py 33行

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
