### ISSUE TITLE
有用小米5s玩的的吗？

### ISSUE THREAD

**Issue by likantour** [wangshub/wechat_jump_game#181]
这是我用的参数，最多到300，但是很不稳定，最多连跳中心10+次，有其他更好的参数吗？   
 "under_game_score_y": 300, 
    "press_coefficient": 1.46, 
    "piece_base_height_1_2": 25, 
    "piece_body_width": 80

**Comment by NullYing** [comment]
小米5s加1，不稳定

**Comment by guoqing-tang** [comment]
我用你们的参数现在烧的可怜。基本上不超过40

**Comment by likantour** [comment]
@guoqing-tang 300是最多，10次有一次差不多吧，大部分都是两位数，有些固定情景误差会大，多步后会放大误差。我再试试其他大神的修正方案

**Comment by HumFei** [comment]
{
    "under_game_score_y": 300, 
    "press_coefficient": 1.472, 
    "piece_base_height_1_2": 25, 
    "piece_body_width": 80
}
小米5s 已经到了500多了，还在跳

**Comment by HumFei** [comment]
![1514687665_d](https://user-images.githubusercontent.com/26295263/34458683-7a0202ca-ee16-11e7-94ce-05f36bb22eda.png)
停在这了 T_T

**Comment by likantour** [comment]
反复测试发现，参数"press_coefficient"对整体结果的影响不是特别大。失败原因分为两种情况：
a.两个底座特别近的情况。
问题原因已经清楚了，是非线性按压导致的，楼上有大神的详细分析。
b.连续变向3次以上
这种情况基本上必死，第3次变向回吧前两次误差最大程度放大。原因貌似还不是很清楚。

**Comment by yuan1** [comment]
同 

{
    "under_game_score_y": 300,
    "press_coefficient": 1.472,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}

**Comment by yuan1** [comment]
目前 我这儿这个还可以 400+了
