### ISSUE TITLE
针对按压不是线性的特点的修改

### ISSUE THREAD

**Issue by VitalyAnkh** [wangshub/wechat_jump_game#182]
之前提过一个issue，https://github.com/wangshub/wechat_jump_game/issues/64 ，这个问题我本以为要设置为比较复杂的函数再拟合，比较麻烦。后来想了想其实用二分之一次函数就好了。然后通过调参改为0.8次函数。把press_time那里改成了0.8次函数。调整时，在config.json里把press_coeffcient改为5，相应代码第86行为
`press_time = math.pow(distance,0.8) * press_coefficient`
效果比用一次函数好多了。具体参数还需要再调整，大家可以试试。

**Comment by zack624** [comment]
根据老哥说的，我红米5a的手机成功到1000了，而且大部分连击，不错。

**Comment by qtvspa** [comment]
老哥，为何我改了press_coeffcient和press_time，一步都跳不出来了呢

**Comment by stonyw** [comment]
补充一个细节：
换方向的时候，棋子在原方向上一跳着陆点的偏差不会带入换方向的距离计算。
作为比较，不换方向的时候，棋子在上一跳着陆点的偏差会带入下一跳距离的计算。

代码应用：
换方向时，应该用当前地盘的中心点和下一个中心点的距离来计算按压时间。

解释原因：
两个方向，可以认为是正交的x和y。当在x方向跳跃的时候，着陆点和中心点的偏差，永远只有x存在正负，y是始终为0。更换方向往y方向跳跃时，x方向偏差不会带入到下一跳的着陆点，只有y存在偏差，而x为0.

因而在计算按压时间的拟合共识，我不管是否线性，在更换方向后，应该用两个中心点来作为计算输入参数而不是棋子和目标中心点。
