### ISSUE TITLE
from PIL import Image   这个引用报错【wechat_jump_iOS_py3.py】第五行，不知道是PIL库的原因还是什么

### ISSUE THREAD

**Issue by hopesala** [wangshub/wechat_jump_game#185]
bogon:wechat_jump_game-master caochenghua$ python3
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.so, 2): Symbol not found: _PyInt_AsLong
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.so

bogon:wechat_jump_game-master caochenghua$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 5, in <module>
    from PIL import Image
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.so, 2): Symbol not found: _PyInt_AsLong
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.so

**Comment by anhilo** [comment]
pip3 install Pillow 
href :https://stackoverflow.com/questions/35929306/how-to-install-pil-to-python-3-5-on-a-mac

**Comment by hopesala** [comment]
thanks, I will have a try @anhilo

**Comment by hopesala** [comment]
It works! I pip3 uninstall it and install it again!
