### ISSUE TITLE
adb版本问题

### ISSUE THREAD

**Issue by talent2333** [wangshub/wechat_jump_game#186]
兄弟们，谁有可以用的adb_driver发个下载链接谢谢，我的1.0.29不能用。
看网上说可以在andrioid sdk manager中更新adb驱动，
有大佬教学一下么，谢谢！

**Comment by lly2016** [comment]
在Google上下载

**Comment by mjzcyhp** [comment]
installer_r24.4.1-windows.exe 下载这个软件，然后再安装这个软件里面的包就可以运行adb了
