### ISSUE TITLE
我直接运行的wechat_jump_auto.py，结果还没我跳的分数高呢，是我什么地方错了么

### ISSUE THREAD

**Issue by mg459046365** [wangshub/wechat_jump_game#19]
我直接运行的wechat_jump_auto.py，然后界面上会自己去跳，结果得分还没我高呢，就二三十分就挂了，没明白啊

**Comment by darrenfantasy** [comment]
需要改参数 我改成press_time = distance * 1.45，一直没挂

**Comment by mg459046365** [comment]
我试试，牛逼了，大半夜的！

**Comment by Donng** [comment]
我运行自动的脚本，挑一下就挂了... 没用过python ，迷...

**Comment by mg459046365** [comment]
@darrenfantasy 你是怎么算的，改成1.45

**Comment by mg459046365** [comment]
@Donng 哈哈，我的还在跑，不过太慢了

**Comment by mg459046365** [comment]
跳了107分，就挂了

**Comment by binderclip** [comment]
@mg459046365 @darrenfantasy 你们的屏幕分辨率是多少？

**Comment by mg459046365** [comment]
@binderclip 1920x1080

**Comment by mg459046365** [comment]
@binderclip 1920 X 1080应该改成多少啊

**Comment by wangcode** [comment]
@binderclip 我分辨率2160*1080，不是每次必中中心点，只看明白貌似是逐个像素判断rgb区间，然后做一个除法求出X轴中心点。。但是Y轴没看懂。。能大概讲解一下你的思路吗

**Comment by binderclip** [comment]
@mg459046365 代码就是基于 1920x1080 写的，按理说不怎么需要改的，你不然根据实际情况微调一下吧

**Comment by mg459046365** [comment]
@binderclip 微调这个参数么，如果是的话，我调一下试试

**Comment by binderclip** [comment]
@wangcode Y 轴是这样的，首先我先确定了那个图形的 X 轴的顶点的坐标，这样 X 是准的了。
假设棋子现在就在当前块儿的中间，那么应该算到下一个块儿中心的距离。
所以就先 PS 截图找了两个点的中心点坐标，把那个角度下的三角形的 X Y 轴的长度比求出来，这样一算就能算出那边 Y 的中心坐标了。

**Comment by binderclip** [comment]
@mg459046365 是的，其他是和坐标相关的，因为分辨率相同所以应该不用改。这个按下的时间可能和机型有关系所以调一下吧。

**Comment by mg459046365** [comment]
@binderclip 好的，现在看来，每次跳的力度不够，我调一下按下时间

**Comment by Donng** [comment]
@binderclip  坚果Pro2 在mac下寸步难行啊...

**Comment by mg459046365** [comment]
@Donng 我是小米note2,也是用的mac

**Comment by binderclip** [comment]
@Donng 分辨率多少？

**Comment by Donng** [comment]
@binderclip   2160x1080分辨率  ，什么参数都没改

**Comment by binderclip** [comment]
@Donng 方便传一张游戏截图上来吗？

**Comment by mg459046365** [comment]
@binderclip 小米note2参数改成1.47会好一点，即便连续跑偏，后面也会被纠正，而且命中中心的概率相对来说，会高一些。不知道小数点精度如果调的高一点会不会更准确

**Comment by Donng** [comment]
@binderclip  是我手机屏幕的游戏截图吗？

**Comment by mg459046365** [comment]
@Donng 应该是让你上传游戏屏幕截图

**Comment by Donng** [comment]
![screenshot_2017-12-30-02-23-40-316_](https://user-images.githubusercontent.com/14989733/34444366-a99b7d22-ed08-11e7-89dd-04fb48e5e6da.png)

**Comment by mg459046365** [comment]
@Donng 最简单的方法，观察一下，落脚点距离中心点的偏移，如果感觉力度不够的话，增加一点时间以0.1为单位调整，如果力度过大就减少一点时间同样以0.1为单位调整

**Comment by Donng** [comment]
@mg459046365  调distance相乘的那个数没用，还是第一下就掉下来了。

**Comment by darrenfantasy** [comment]
@mg459046365 就是微调时间参数吧。我就试了一些数据。

**Comment by chocolatesir** [comment]
@Donng 2160*1080调成1.05到1.1就很准了

**Comment by malatachehongbin** [comment]
1080x2220  手动点击参数为1.36 

自动的继续使用这个参数第一次就挂了，  能说说原理吗？

**Comment by binderclip** [comment]
@Donng 已知问题，把 300 改成 500

**Comment by Donng** [comment]
@binderclip  还是只跳一下。

**Comment by binderclip** [comment]
@Donng 代码已经更新了，用一下新的，里面有需要修改的参数。还不行自己 debug 下，思路也写了。

**Comment by Donng** [comment]
@binderclip  train_data文件夹加到.gitignore里吧，pull下来一堆图片

**Comment by binderclip** [comment]
@Donng 这应该是 OpenCV 版本需要的，就先留着吧

**Comment by Donng** [comment]
@binderclip 每次跳跃的  时间都是 200 .... find_piece_and_board()函数第一跳返回的都是 0 0 0 0

**Comment by binderclip** [comment]
@Donng 上游戏截图吧

**Comment by se4** [comment]
三星S6 G920F 实测通过

under_game_score_y = 500
press_coefficient = 1.04

**Comment by binderclip** [comment]
@se4 方便的话也写屏幕分辨率吧，方便其他人参考，多谢！

**Comment by binderclip** [comment]
@Donng 哦，截图有了，你有改参数吗？
比如 `under_game_score_y = 500`

**Comment by Donng** [comment]
![1514612903782](https://user-images.githubusercontent.com/14989733/34451658-2537b2a2-ed68-11e7-8f1e-93e468893e1e.jpg)
这里一直都是返回零，前面两层for循环的代码都有点看不明白了。

**Comment by binderclip** [comment]
@Donng 这个是没找到棋子，你在棋子稳的时候再开始游戏试试

**Comment by 790396054** [comment]
1080P 屏幕，press_coefficient长按的时间系数，调1.45 确实是一个很好的系数

**Comment by binderclip** [comment]
@790396054  似乎和机型也有关系 [好用的参数以及晒分发到这里 · Issue #61 · wangshub/wechat_jump_game](https://github.com/wangshub/wechat_jump_game/issues/61)

**Comment by Donng** [comment]
@binderclip  我现在时间系数调到1.35（坚果pro2），正在测试，感觉还算精确。之前的问题可能是脚本执行先于游戏打开的问题。还是谢谢不吝赐教 ！

**Comment by liuchonggao** [comment]
@Donng 坚果 pro2 配置应该怎么样？

**Comment by zhv9** [comment]
自动识别的参数不太好，得专门调
