### ISSUE TITLE
Windows下，模拟器测试成功

### ISSUE THREAD

**Issue by Hackxiaoya** [wangshub/wechat_jump_game#192]
自己只有苹果手机，可是又想逆天高分，苹果的那个框架我看到大神都是mac，我是windows，没有详细教程，完全没希望自己能弄进去。**求大神来一份windows+苹果手机的教程**。

不瞎哔哔了，直接开始。
我使用的是夜神模拟器，官方去下载，然后新建一个模拟器安卓5.1版本的，因为默认的那个运行小程序会未响应什么的，所以要新建一个模拟器。。。。选择安卓5.1版本。。。。
别的模拟器运行小程序会假死，我不知道为什么，可能是我电脑问题吧。。。

我用夜神模拟器做的例子，夜神模拟器的adb路径是D:\Program Files (x86)\Nox\bin 我装在D盘 所以是这个。大家根据自己的修改路径。
然后把这个路径加入到系统环境中去。右键我的电脑-属性-高级系统设置-高级-环境变量-系统变量-path-编辑   win7是加到最后，win10是直接新建。填入adb的那个路径就可以了。。
然后你打开CMD 输入 adb不报错就是路径正常了。。如果CMD在加入系统路径之前打开的，请从新打开一个。。。不然输入adb会报错。

然后安装python3。。怎么安装自己百度吧。这个是python脚本。
然后打开模拟器，模拟器运行好了之后，CMD输入adb devices正常会出现 就是有端口监听到了。然后端口什么的。可能我们不一样。反正就大概是酱紫。
`List of devices attached
127.0.0.1:62025 device`

然后模拟器安装微信啊。就这样啊。。
然后下载电脑下载脚本啊。
然后打开模拟器的小游戏界面啊。
然后直接在CMD 输入  python wechat_jump_auto.py
然后你就看到自动在跑了。。。

============================================
如果你运行的wechat_jump_auto_1280_720.py
模拟器下有个文件管理，找到DCIM目录，里面新建一个play文件夹。不然会报错。
还有模拟器顶部有个设置可以设置分辨率什么的。自己看吧。

==========================
大概就是酱紫了。如果还有问题。可以在某个人建的群里找我。群号是 319974799
我Q名叫  这个地方叫Dora朵拉

**Comment by Hackxiaoya** [comment]
对了。还要装依赖包。忘记了。。。
就是python3安装好了之后。
CMD进入到脚本目录。然后运行pip install -r requirements.txt  安装依赖包。。。

**Comment by Hackxiaoya** [comment]
如果直接在CMD 输入 python wechat_jump_auto.py。。请把config文件夹里面对应的config.json 替换掉根目录的config.json  不然分辨率不对应也会0分的。

**Comment by 0312birdzhang** [comment]
貌似模拟器用微信容易被封

**Comment by daylightmazekun** [comment]
夜神模拟器打开游戏直接黑了。。。。。

**Comment by zy857703023** [comment]
Traceback (most recent call last):
  File "wechat_jump.py", line 1, in <module>
    import numpy as np
ImportError: No module named 'numpy'

求教这个错误是怎么回事,本人新手小白一个,我拿手机运行那个wechat_jump_auto.py就没问题,可能是因为那个里没有'numpy'这个参数吧

**Comment by Egoole** [comment]
现在使用blueStacks 更新最新微信进入小程序，显示“当前设备系统暂不支持小游戏”。是被屏蔽了吗？

**Comment by pobingwanghai** [comment]
@Egoole 是的

**Comment by WhitLor** [comment]
我这里打开模拟器但是adb devices里没有，已经关了adb.exe，环境变量也加上去了~

**Comment by TonyLiuYan** [comment]
多谢，已经测试成功了。中间遇见了分辨率的问题  我的电脑是1080P的分辨率 ，把模拟器设置成1080P的就好了

**Comment by daylightmazekun** [comment]
@TonyLiuYan 请问你用的什么模拟器成功的
