### ISSUE TITLE
定点有待改进

### ISSUE THREAD

**Issue by reechang** [wangshub/wechat_jump_game#198]
如图，这种情况好几次了
![1514680639_d.png](https://i.loli.net/2017/12/31/5a4839ffc76e7.png)
另外，目前对于白色方框的识别很不准确。连续两个白色方框的话，误差就很大了

手机使用的是Oneplus 3T

**Comment by hiyzx** [comment]
是不是同种手机设置的参数都一样？？我也是一加3t，第一格就挂了

**Comment by gunten** [comment]
你的睡眠时间太短了吧  截图把光晕效果截进去了
