### ISSUE TITLE
windows下,老是报错:'cp' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by qiushicai** [wangshub/wechat_jump_game#20]
:'cp' 不是内部或外部命令，也不是可运行的程序

求指导

**Comment by binderclip** [comment]
@qiushicai 你的是 Windows 机器吗？
大概是 Windows 下没有 cp 命令吧。。

**Comment by qiushicai** [comment]
@binderclip  windows 是啥！！

**Comment by qiushicai** [comment]
@binderclip 
 我的电脑是win10

**Comment by binderclip** [comment]
@qiushicai 你可以先把那行注释了，是可选的操作

**Comment by qiushicai** [comment]
@binderclip   我现在注释掉了。 然后把参数press_time = distance * 1.45    hahahah.但是有点慢

**Comment by qiushicai** [comment]
@binderclip   我现在注释掉了。 然后把参数press_time = distance * 1.45    hahahah.但是有点慢

**Comment by mg459046365** [comment]
@qiushicai 改成1.45，还是会掉

**Comment by qiushicai** [comment]
@binderclip 对呀！！等大神们 再改改  我到了181~~~

**Comment by 201419** [comment]
@binderclip 我的到495了，后边就没往上刷了

**Comment by zwzzwzzwz** [comment]
同win10，注释掉那行就好了，不注释放着报错也不影响刷分

**Comment by lt846786463** [comment]
楼上全是在鬼扯。。。。cp是复制的意思 linux 的命令行  在windows 里用copy替换cp

**Comment by Zhao19980117** [comment]
cp是linux系统的命令 copy是windows系统的命令 我是windows系统 运行打包命令时有cp 报错 怎么解决

**Comment by xiao-shu-sheng** [comment]
加个包cpx， 用cpx代替cp或者copy

**Comment by mingyue6952** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Easyboy0405** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
