### ISSUE TITLE
定位在连续转弯时出现错误

### ISSUE THREAD

**Issue by lly2016** [wangshub/wechat_jump_game#202]
小米5最新开发版
1920x1080
win10 1709
遇到几个识别不准的情况
![1514684879_d](https://user-images.githubusercontent.com/26106190/34458557-ca181a1a-ee11-11e7-918d-98da90db5c8d.png)
![1514685284_d](https://user-images.githubusercontent.com/26106190/34458563-f9bd797c-ee11-11e7-85ab-50262e764fd9.png)
![1514685047_d](https://user-images.githubusercontent.com/26106190/34458565-fe3ae836-ee11-11e7-864d-cbd865ad849e.png)
![1514684879_d](https://user-images.githubusercontent.com/26106190/34458568-040a45fe-ee12-11e7-99b0-447fb800ccc9.png)
类似的还有很多，参数只调了时间变量为1.55，识别正确的时候1.55可以跳到正中心。

**Comment by likantour** [comment]
我是小米5s，出现这种连续变向的场景，基本必死

**Comment by lly2016** [comment]
有道理啊！之前还以为是因为颜色问题，再运行发现就是连续转向的时候判定会出现错误

**Comment by lly2016** [comment]
![1514688867_d](https://user-images.githubusercontent.com/26106190/34458762-07823a82-ee19-11e7-99e6-c915f5e3e5ad.png)
![1514688133_d](https://user-images.githubusercontent.com/26106190/34458765-1080165e-ee19-11e7-97b4-a40208ec82c2.png)
![1514686257_d](https://user-images.githubusercontent.com/26106190/34458766-1bd7d21c-ee19-11e7-8585-8b727241d479.png)

**Comment by baolw** [comment]
之所以连续转向容易死是因为代码写死了起点位置和下一个图形的中心是30°，而实际上如果做不到每次都跳到中心，这个角度不是30°，所以距离计算出错，导致跳的位置距离有偏差
