### ISSUE TITLE
iOS的玩家这么少？真机跑成功的兄弟能不能出来秀秀环境配置？

### ISSUE THREAD

**Issue by LLwanran** [wangshub/wechat_jump_game#207]
在wda的inspector界面，一片空白，再也走不动了。（模拟器正常）

**Comment by skerwin** [comment]
好像并不需要什么环境配置，wda装好，python脚本运行起来就ok的

**Comment by kaizhetutuquliaomei** [comment]
@skerwin  照着readme流程走下来都正常，一切安装均无问题，但是inspector界面空白，导致python脚本运行报错：`Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 29, in <module>
    pull_screenshot()
  File "wechat_jump_iOS_py3.py", line 18, in pull_screenshot
    c.screenshot('1.png')`
然后就没有然后了。
我的是XCode9.2，iOS9.3.5，Python 3.6.4

**Comment by skerwin** [comment]
![image](https://user-images.githubusercontent.com/16834466/34458713-355ac4c2-ee20-11e7-9892-a9425e9b5aaa.png)那里空白不空白也关系不大，只是查看ui图层而已，json字符串收到了么，然后让控制台处于上图状态，在运行

**Comment by kaizhetutuquliaomei** [comment]
@skerwin wda正常跑起来了，输出均无问题，就是python执行到截屏那里报错，搜索查不到这类问题解决方案

**Comment by drawwon** [comment]
python脚本运行后直接退出，也不报错怎么回事呢

**Comment by cultivater** [comment]
@kaizhetutuquliaomei  我跟你一样的情况 9.3的系统   inspector界面死活不出截屏

**Comment by kaizhetutuquliaomei** [comment]
@cultivater 安装Python库（目前这个版本的库支持py2.7~3.5之间的版本）
pip install --pre facebook-wda
会不会是py版本问题？我装的3.6.4

**Comment by cultivater** [comment]
@kaizhetutuquliaomei  我也是python3.6...

**Comment by cultivater** [comment]
@kaizhetutuquliaomei   可是import wda也没报错啊  说明wda应该支持3.6吧

**Comment by kaizhetutuquliaomei** [comment]
@cultivater 我已经试过了，就是这个引起的。你可以切换模拟器，inspector肯定是有截屏的，然后你运行`import wda
c = wda.Client('http://localhost:8100')
c = wda.Client()
c.screenshot('1.png')`切换屏幕并没有问题，都可以正常截图，所以就是这一步走不通，py没法正常运行。

**Comment by cultivater** [comment]
@kaizhetutuquliaomei  试过python3.5了 依然不行  不折腾了

**Comment by kaizhetutuquliaomei** [comment]
@cultivater 我已经无解了，issues里面又没人太关注iOS问题，我想尝试升级iOS系统到11，但如果不是这个问题引起的那就太折腾了。现在只感觉就是wda无法调起真机界面的问题导致的，一直卡这里。

**Comment by DisMeo** [comment]
wda同样不行，还好有台小米测试

**Comment by ChaosXu** [comment]
mac用 python3
pip3 install --pre facebook-wda --user

**Comment by kaizhetutuquliaomei** [comment]
@cultivater 妈蛋，真的是iOS版本问题，我已经升级到iOS11.2了，运行正常，真操蛋，iOS9居然不支持，折腾了一天时间

**Comment by cultivater** [comment]
@kaizhetutuquliaomei  不容易啊。。。说是最低要求9.3系统  看来9系统不支持

**Comment by kaizhetutuquliaomei** [comment]
@cultivater 是啊，你升级一下肯定也OK的。

**Comment by cultivater** [comment]
@kaizhetutuquliaomei   不搞了，越升越卡

**Comment by kylesean** [comment]
@skerwin @cultivater 
```
 pip3 install --pre facebook-wda
Requirement already satisfied: facebook-wda in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from facebook-wda)
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.6/site-packages (from facebook-wda)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
```
明明提示已经装好了wda，为啥执行的时候报:
```
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ImportError: No module named 'wda'
```

**Comment by Klunio** [comment]
@kylesean 好像要在模拟环境里装wda

**Comment by liyuankunbix** [comment]
@cultivater 一样，9.3.5，Inspector死活不出截屏

**Comment by singleD** [comment]
@Klunio 请问你说的在模拟环境下安装指的是？
