### ISSUE TITLE
所以IOS的wda的API怎么弄

### ISSUE THREAD

**Issue by guiw629** [wangshub/wechat_jump_game#21]
adb的调用替换成wda的api就好了，哪个api请指教

**Comment by wangshub** [comment]
@guiw629 已经有IOS代码更新了

[https://github.com/wangshub/wechat_jump_game/commit/b9e13c2827920d591ad81919c10dbd6fbc78dfd0](https://github.com/wangshub/wechat_jump_game/commit/b9e13c2827920d591ad81919c10dbd6fbc78dfd0)
