### ISSUE TITLE
三星S8+怎么配置参数选择跳一下就死

### ISSUE THREAD

**Issue by qq44407978** [wangshub/wechat_jump_game#210]
三星S8+现在跳一下就死

**Comment by michelle6147** [comment]
同求

**Comment by lly2016** [comment]
看看截图里面_d.png结尾的图片中对于棋子位置和下一个方块位置判定准不准，准的话慢慢调时间参数就行了

**Comment by liaobei** [comment]
我改了参数后前面跳没问题，左边跳不过

**Comment by qq44407978** [comment]
懂的加Q群373873 教我下 谢谢

**Comment by charles2hang** [comment]
关闭曲面侧屏、悬浮球一类的功能
按以下的参数在WQHD+ 2960x1440下测过十几次
{
"under_game_score_y": 460,
"press_coefficient": 1.05,
"piece_base_height_1_2": 96,
"piece_body_width": 100
}
上千比较轻松 连续跳出十多次+32 分数基本分布在1000~1500

**Comment by OvenGuo0224** [comment]
@charles2hang 老哥 你这个用s8+试了试 只能跑个200+

**Comment by charles2hang** [comment]
@OvenGuo0224 不应该吧 我又测了两次 有可能是我用adb隐藏了底部导航栏的原因 你确定你的分辨率是2960x1440？

**Comment by demidroid** [comment]
我的跑了100多，那也比我自己玩的好哈

**Comment by lupengwei** [comment]
今天怎么不能用了
