### ISSUE TITLE
请问刷到多少分会被清0，小米5，目前正在刷到1369....

### ISSUE THREAD

**Issue by Superbsco** [wangshub/wechat_jump_game#212]
请问刷到多少分会被清0，小米5，目前正在刷到1369....

统一回复一下参数。只适合小米5：
config.json

`

{
    "under_game_score_y": 300, 
    "press_coefficient": 1.6,
    "press_base_time": 600,
    "press_coefficient_fix": 4000,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70
}

`
pyauto那个代码链接上不了，直接看pr里面的二次修正那位大神改了一点的那个

**Comment by JackZs** [comment]
你分辨率多少，我也是红米5,1280*720

**Comment by Superbsco** [comment]
小米5，1920*1080，我改了一点点代码

**Comment by JackZs** [comment]
我的不行，每次都是0

**Comment by Superbsco** [comment]
@JackZs 可能你没调好

**Comment by JackZs** [comment]
怎么调

**Comment by Superbsco** [comment]
@JackZs adb先连成功手机，小米要在开发者模式那里选上，USB调试和USB调试（安全模式）。连成功直接跑这个程序就好了。然后再改参数啊

**Comment by JackZs** [comment]
参数怎么改，我每次跑都是0

**Comment by superwzlx** [comment]
请问5s还是5x呢，我5x一直找不到参数，5x 1920*1080的

**Comment by AmosLee94** [comment]
# **我还在跑，根本停不下来！**
![image](https://user-images.githubusercontent.com/33691772/34458800-2496664c-ee1a-11e7-9a17-6ae5e88d997c.png)

**Comment by Superbsco** [comment]
@superwzlx 我是小米5啊，后面没有s，没有x

**Comment by Superbsco** [comment]
@AmosLee94 我跑到1520都清0了，你这个危险啊

**Comment by guoqing-tang** [comment]
参数多少？

**Comment by AmosLee94** [comment]
@Superbsco 无所谓啊，我就看看怎么样可以调到按压得最精准 XD

![image](https://user-images.githubusercontent.com/33691772/34458819-fb11e41c-ee1a-11e7-9c3e-6317fd8d1cf5.png)

**Comment by zack624** [comment]
我用的红米5a，刷到1000，结果只有本机有记录，别人的机子看不到这个记录。

**Comment by Superbsco** [comment]
@zack624 所以说，上了1000会被清0

**Comment by AmosLee94** [comment]
# **5000+分，没被清，且，好友列表里，还是5000+**

过段时间再看吧 XD

![image](https://user-images.githubusercontent.com/33691772/34458867-d4bf6b66-ee1c-11e7-9411-087e74f78ed0.png)

**Comment by Neptunesy** [comment]
我的也是小米5 每次只能到三十几分为什么

**Comment by Superbsco** [comment]
@Neptunesy 更新最新代码，按照我上面说的改，就可以了，目前亲测972分正常。不会被删

**Comment by zack624** [comment]
@Neptunesy 你自己截图，再量下那个瓶子的高宽，改下config.json文件里的数据，测试下时间系数。我的这样搞的，小米和魅族都调得好。如果你的1280*720的，我可以把我的数据发给你。

**Comment by JackZs** [comment]
zack624，我的是小米，1280*720的数据发我一下

**Comment by JackZs** [comment]
@zack624

**Comment by JackZs** [comment]
@zack624

**Comment by Neptunesy** [comment]
"press_base_time": 600,
"press_coefficient_fix": 4000,

这两个参数没有载入啊，在auto.py中

@Superbsco

**Comment by ysy950803** [comment]
我试过了，到5000多故意失败，然后没更新分数。后来缓缓地来，一次比上次多个两三百，就会更新，貌似跨度太大就不会更新。

**Comment by peanutA** [comment]
@zack624  魅族的手机在打开USB调试之后，还需要打开什么设置吗？

**Comment by zack624** [comment]
@peanutA 魅族如果打开了，还找不到设备，可能需要参考这个。http://blog.csdn.net/lmouse_/article/details/54238068

**Comment by DisMeo** [comment]
auto用的什么版本的代码？最新的么？

**Comment by Superbsco** [comment]
@DisMeo 看pr那里，提交的那个二次修正

**Comment by BeWithU** [comment]
@AmosLee94 你那个按压系数是多少，也是1.6？

**Comment by msc1122** [comment]
@Superbsco 这个怎么用啊 我替换到config.json 跳的特别远。怎么调二次修正 这个代码替换到哪里啊？

**Comment by learn2Pro** [comment]
代码看下啊

**Comment by qiushicai** [comment]
@AmosLee94  小米五吗？ 大兄弟，  你修改了什么?参数是啥。分享一下~

**Comment by gongzelong0718** [comment]
如何调试跳得更精准呢，有人有什么调试的方法吗？结果不太重要，求过程。
