### ISSUE TITLE
功能建议，请大家反馈到这里

### ISSUE THREAD

**Issue by wangshub** [wangshub/wechat_jump_game#218]

**Comment by aiyolo** [comment]
相邻的方块识别准确率不高

![image](https://user-images.githubusercontent.com/12464091/34458827-414f1f12-ee1b-11e7-9629-2d8caa15a7a8.png)

**Comment by baolw** [comment]
试了个通宵，一直在想办法没想出来。代码中提到夹角假设为30°，很多手机无法成功就是因为这个原因。因为如果不知道官方的计算按压时间与距离的关系，总是会存在误差，最终导致跳到下一个图形时点不在中心，而这个夹角此时就不能直接用30°来计算了，还是得获取一个真正图形中心的方法啊

**Comment by wangshub** [comment]
是的，那个参数是测试出来的

**Comment by wangshub** [comment]
手机有悬浮球的需要关闭一下
https://github.com/wangshub/wechat_jump_game/issues/226

**Comment by baolw** [comment]
作者，我想问一下你们能筛选掉阴影的颜色么

**Comment by Vg1ee** [comment]
由于微信算法问题，即使上一跳跳歪了，拐弯后会自动回正，这种情况下跳跃距离不应该以两点实际距离计算。

![github](https://user-images.githubusercontent.com/19946467/34462091-a1524dde-ee76-11e7-9b32-90fc38c63aca.jpg)
假设小人在O点上，A点为目标点，实际跳跃距离应为OB，而非AO。
红色参考线与实际跳跃方向平行。蓝色参考线为直角坐标系。
由于红色参考线与X轴夹角恒定为∠BOX，可算出三角形AOB各内角。又已知AO边长，根据正弦定理可算出OB为实际跳跃距离。

如有错误欢迎指正，由于不会py只能帮到这里了。
