### ISSUE TITLE
提交手机参数，上传配置，看这里

### ISSUE THREAD

**Issue by wangshub** [wangshub/wechat_jump_game#219]

**Comment by TjXuhunfa** [comment]
求三星S7 edge高分参数，  屏幕分辨率1920*1080

**Comment by liaobei** [comment]
求三星S8+参数

**Comment by wangshub** [comment]
三星S8的我找下有没有，等有人贡献出来加进去 @liaobei

**Comment by TjXuhunfa** [comment]
老兄，有S7 edge吗，给的参数在我的手机里跳一下就死

**Comment by middlexu** [comment]
求小米5S参数，目前最高300多一点

**Comment by ccldvv** [comment]
同求S8

**Comment by loveJuly** [comment]
有没有iPhone5s的参数，求大佬分享

**Comment by xu42** [comment]
小米5X #278

**Comment by 1038200595** [comment]
求华为p10 plus    1440x2560系数

**Comment by Moosphan** [comment]
求vivox20，2160x1080

**Comment by PTChenrr** [comment]
@wangshub 求小米4参数 1920*1080 最多跳35步

**Comment by RadiumCao** [comment]
三星 s8+ 2960x1440 在设置里面 关闭曲面侧屏
{
"under_game_score_y": 390,
"press_coefficient": 1.038,
"piece_base_height_1_2": 28,
"piece_body_width": 110,
"swipe" : {
"x1": 320,
"y1": 410,
"x2": 320,
"y2": 410
}
}

**Comment by yeming1001** [comment]
小米4    下面的配置 560多
不知有没有更高的配置
{
    "under_game_score_y": 300,
	"press_coefficient": 1.475, 
    "piece_base_height_1_2": 20,
    "piece_body_width": 73,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1602
    }
}

**Comment by BOOMBowen** [comment]
三星 s7 edge 亲测 成功
参数press_coefficient 调整为1.40左右。其他不变。
分辨率2560x1440
还没跳完

**Comment by wuhfen** [comment]
魅族MX4 
分辨率 1920 x 1152
调整参数：
"press_coefficient": 1.30, 
亲测，现在跳到2000+

**Comment by ngc7292** [comment]
小米4s

**Comment by MaxQin** [comment]
小米4S

**Comment by PhillipHuang2017** [comment]
小米5s plus参数，能稳定跳到800+，被我手动结束了
{
    "under_game_score_y": 300,
    "press_coefficient": 1.45,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}

**Comment by luxueyan** [comment]
@PhillipHuang2017 貌似不是很准确 我的有点歪啊

**Comment by kevinofsias** [comment]
分享2个，米5s plus
{
    "under_game_score_y": 300,
    "press_coefficient": 1.3,
    "piece_base_height_1_2": 25,
    "piece_body_width": 80,
    "swipe": {
        "x1": 540,
        "y1": 1514,
        "x2": 540,
        "y2": 1514
    }
}


米5s
{
    "under_game_score_y": 300,
    "press_coefficient": 1.392,
    "piece_base_height_1_2": 25,
    "piece_body_width": 80,
    "swipe": {
        "x1": 540,
        "y1": 1514,
        "x2": 540,
        "y2": 1514
    }
}
wechat_jump_auto.py文件改个地方，2个型号手机都改这里
def jump(distance):
    """
    跳跃一定的距离
    """
    if distance < 400:
        distance = 0.9 * distance + 60
    else:
        distance = 0.9 * distance + 80
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
        duration=press_time
    )
    print(cmd)
    os.system(cmd)
    return press_time
