### ISSUE TITLE
闲聊，晒战绩，心得交流～

### ISSUE THREAD

**Issue by wangshub** [wangshub/wechat_jump_game#220]

**Comment by VitalyAnkh** [comment]
为什么不吭一声就关了我的pr啊

**Comment by AmosLee94** [comment]
还活着...
不过不继续刷了
![image](https://user-images.githubusercontent.com/33691772/34458879-37ff7bc6-ee1d-11e7-9e3b-099907b8adf1.png)

**Comment by wangshub** [comment]
分数容易异常，我是最早刷的，后来分数消失了一段时间 @VitalyAnkh

**Comment by wangshub** [comment]
实在是抱歉，可能是我忘记回复您了 @VitalyAnkh ,今天代码出现了很大的冲突，有参数出错，不得已回滚了

**Comment by wangshub** [comment]
是我的原因 @VitalyAnkh ，可以重新更新最新代码吗

**Comment by VitalyAnkh** [comment]
@wangshub 好的，我再提一次，参数我帮您调，您试试。感觉使用非线性的来拟合比线性的好多了

**Comment by wangshub** [comment]
有个二次拟合的的，今天试了效果不太好 @VitalyAnkh

**Comment by hceasy** [comment]
我说怎么刚提交通过就没了代码呢

**Comment by tarvos21** [comment]
![20186666-good](https://user-images.githubusercontent.com/18745870/34459306-b0de4e3c-ee27-11e7-8760-beb8db5ef7b2.png)
![wechatimg17 copy](https://user-images.githubusercontent.com/18745870/34459309-bf36d2e2-ee27-11e7-83df-f71e36cc8ac8.jpeg)
6000多是立地成佛，请问还有比这更高的级别吗？有大佬玩到的吗？

**Comment by GordonKing** [comment]
![image](https://user-images.githubusercontent.com/1321699/34460325-c08c11ac-ee45-11e7-99c2-4e363481bf3f.png)

貌似夹角太小容易翻车。。。

**Comment by Sowevo** [comment]
新的计算方式...  一万八死掉了   
![1514774865_d](https://github.com/Sowevo/tutu/raw/master/1514774865_d.png)

**Comment by wangshub** [comment]
@Sowevo 你的邮箱有吗

**Comment by Sowevo** [comment]
@wangshub 进到群1里了   你在里面吗

**Comment by wangshub** [comment]
群主是我 @Sowevo
