### ISSUE TITLE
小白昨天在这里把程序启动了，原理了解了，但是代码是怎样实现的看不懂

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#222]
第一次接触python，如果自己动手写需要那些知识点啊？还有就是怎么通过adb.exe和python的代码就可以操作手机啊？哪位大神说下啊

**Comment by hiyoi** [comment]
实际上python 只是执行adb shell 的命令来对设备进行操作
```
    os.system('adb shell screencap -p /sdcard/1.png')
    os.system('adb pull /sdcard/1.png .')
```
```
   'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time)
    os.system(cmd)
```


并非python可以，实际上只要能执行shell命令的语言，都可以实现
当然，还需要有图像处理库

**Comment by wangshub** [comment]
可以反馈到哦，原谅我先关闭了哈 @mjzcyhp 
https://github.com/wangshub/wechat_jump_game/issues/217
