### ISSUE TITLE
File "wechat_jump_auto.py", line 66, in <module>     is_debug = config['debug'] KeyError: 'debug'

### ISSUE THREAD

**Issue by zhengcx** [wangshub/wechat_jump_game#223]
File "wechat_jump_auto.py", line 66, in <module>
    is_debug = config['debug']
KeyError: 'debug'

**Comment by doubiermie** [comment]
C:\Users\Yangzichen\Desktop\123\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from ./config/1920x1080/config.json
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 62, in <module>
    is_debug = config['debug']
KeyError: 'debug'

**Comment by wangshub** [comment]
请pull更新一下最新代码 @zhengcx
