### ISSUE TITLE
运行wechat_jump_auto.py出现No such file or directory: 'config.json'，求解

### ISSUE THREAD

**Issue by tiramisu233** [wangshub/wechat_jump_game#228]
C:\Users\Administrator.USER-20141014GI>C:\Users\Administrator.USER-20141014GI\De
sktop\wechat_jump_game-master\wechat_jump_auto.py
Traceback (most recent call last):
  File "C:\Users\Administrator.USER-20141014GI\Desktop\wechat_jump_game-master\w
echat_jump_auto.py", line 29, in <module>
    with open('config.json','r') as f:
IOError: [Errno 2] No such file or directory: 'config.json'

**Comment by yingang** [comment]
路径下有那个文件吗？启动/工作路径对吗？

**Comment by WeidongHe** [comment]
cd 到 'config.json' 当前目录

**Comment by XicnZky** [comment]
我也是这个问题

**Comment by Jessefrom1997** [comment]
你要先把config文件夹里对应的json文件复制到和你要用的脚本同一个目录，然后用命令行 cd 到你这个脚本的目录，然后再运行脚本，就是说你运行这个脚本要在脚本所在的文件夹内运行，不能直接运行脚本。

**Comment by LingyvKong** [comment]
我也是这个问题。我是用Spyder打开wechat_jump_auto.py运行的
