### ISSUE TITLE
期待进一步改进

### ISSUE THREAD

**Issue by VitalyAnkh** [wangshub/wechat_jump_game#23]
我的手机也是1920×1080，但是可能截图size不同使用效果不太好。经常第一个就跳不过去。

**Comment by VitalyAnkh** [comment]
使用的是wechat_jump_auto.py

**Comment by wangshub** [comment]
安卓的适配比较多，给我一些时间整理一下 @VitalyAnkh

**Comment by crazyxhz** [comment]
贡献几个参数，小米6 1920*1080，
```python

press_time = distance * 1.445

piece_y = piece_y_max - 19  # 17-19都可以，超过20，在小米6上误差较大

```

另外，期待作者解释下
board_y = piece_y + abs(board_x - piece_x) * abs(1122 - 831) / abs(813 - 310)   
的具体意义？ 是算夹角么？@wangshub

**Comment by crazyxhz** [comment]
@wangshub  另外，能否利用一下出现连续combo的时候目标上出现的白点？
