### ISSUE TITLE
为啥我的跳了几部就挂了。需要改啥参数吗？

### ISSUE THREAD

**Issue by zkjmyy** [wangshub/wechat_jump_game#230]

**Comment by wangshub** [comment]
说下手机型号呢 @zkjmyy

**Comment by zkjmyy** [comment]
小米4c 我运行的是 wechat_jump_auto.py .分辨率应该是1920 *

**Comment by xiaobing88** [comment]
press_coefficient 需要自己 试试

**Comment by i-MaTh** [comment]
小米note也是跑到100多分就挂了

**Comment by zkjmyy** [comment]
@i-MaTh 你的屏幕分辨率是1920 * 1080？

**Comment by zkjmyy** [comment]
@wangshub =====           
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Mi-4c
=====

**Comment by zhaoy875** [comment]
同楼上是小米4c几步就挂==
 5寸屏  1080 1920分辨率  像素密度441ppi 
求参数

**Comment by zkjmyy** [comment]
@zhaoy875 你找到合适的参数了吗？

**Comment by 286471320** [comment]
同为4c 根本跳不到中心。。。。
