### ISSUE TITLE
图中蓝线和灰线是什么意思

### ISSUE THREAD

**Issue by Gczw** [wangshub/wechat_jump_game#231]
![image](https://user-images.githubusercontent.com/13687632/34459118-eba911de-ee20-11e7-88fe-8293ecbbb14e.png)

**Comment by xiaobing88** [comment]
红线是棋子的点 
蓝线是棋盘中心

**Comment by Sowevo** [comment]
你这右边上的一条是什么东西,这个影响到计算的~ @Gczw
