### ISSUE TITLE
红米4A 执行1280*720.py报错IOError: [Errno 2] No such file or directory: 'original_screen_shots/screen1.png'

### ISSUE THREAD

**Issue by ObjLin** [wangshub/wechat_jump_game#232]
报错： IOError: [Errno 2] No such file or directory: 'original_screen_shots/screen1.png'；是要把文件放在指定目录下执行吗

**Comment by xiaobing88** [comment]
有 sd卡会更好，sdcard

**Comment by yingang** [comment]
先确认下adb相关装好了吧？我刚才是这个问题，不行就用新手目录下的，下载的adb工具放到代码目录下，下载的驱动直接安装，然后adb devices能看到你的手机，应该就没问题了。

**Comment by ObjLin** [comment]
adb能看到手机，但是仍然报这个错

**Comment by zgmd** [comment]
我的S8也是相同的问题，我通过自己手动创建了一个play文件夹，解决了

**Comment by ObjLin** [comment]
在哪创建play文件夹

**Comment by ObjLin** [comment]
DCIM 我试试

**Comment by ObjLin** [comment]
新建play文件夹依然不行。。

**Comment by frank065** [comment]
小米2s 新建play文件夹有效。play文件夹不是新建在wechat_jump_game-master文件夹下，而是手机sdcard/DCIM目录下

**Comment by alanforgithub** [comment]
我的小米2页是这个错误

**Comment by F-loat** [comment]
新版本应该没这个问题了 #288
