### ISSUE TITLE
小米note  两步就挂，求配置参数！

### ISSUE THREAD

**Issue by x55admin** [wangshub/wechat_jump_game#233]
如题！

**Comment by aiyolo** [comment]
config.json
{
    "under_game_score_y": 300, 
    **"press_coefficient": 3.105,** 
    "piece_base_height_1_2": 28, 
    "piece_body_width": 110
}

wechat_jump_auto.py
def jump(distance):
    **press_time = math.pow(distance,0.85) * press_coefficient**
    press_time = max(press_time, 200)   # 设置 200 ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time)
    print(cmd)
    os.system(cmd)

**Comment by zkjmyy** [comment]
@aiyolo 我在小米4c 上。你这个代码也不行

**Comment by x55admin** [comment]
@aiyolo  试了你的代码，不行啊，六步，确定是小米note的参数，请问参数怎么确定，方法是什么？求指教！

**Comment by Donglong** [comment]
我的note4x 把press_coefficient改成1.45

**Comment by aiyolo** [comment]
@x55admin 我的设备是Xiaomi Note顶配版，还有一个是标准版，两者分辨率不一样，你试着挑一下参数press_coefficient
![image](https://user-images.githubusercontent.com/12464091/34459274-a51316a6-ee26-11e7-86f5-51c695748c51.png)

**Comment by x55admin** [comment]
@aiyolo  哦哦 我的是标准版，所以你的参数不适合我，请问怎么得到的参数？

**Comment by zkjmyy** [comment]
@aiyolo 这个参数改成多少，有规则吧。

**Comment by zkjmyy** [comment]
@x55admin 你找到好的配置参数了吗？

**Comment by x55admin** [comment]
@zkjmyy  没有 我最多6步

**Comment by fetdog** [comment]
@aiyolo 最新的note顶配配置可以发个出来么，我按你的改还是几步就挂了

**Comment by huhuno1** [comment]
小米note顶配同求啊 config求大腿

**Comment by huhuno1** [comment]
@aiyolo 兄弟你的联系方式来一个号码 ，想详细咨询你，可以吗 大腿

**Comment by huhuno1** [comment]
@aiyolo 我的也是顶配，兄弟

**Comment by huhuno1** [comment]
@aiyolo 140挂了
