### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by Mason-Xu** [wangshub/wechat_jump_game#235]
![](http://oz2u8kxpt.bkt.clouddn.com/17-12-31/33246578.jpg)  这是怎么回事呀

**Comment by TjXuhunfa** [comment]
没有安装pil

**Comment by TjXuhunfa** [comment]
可以安装一个pillow

**Comment by Mason-Xu** [comment]
![](http://oz2u8kxpt.bkt.clouddn.com/17-12-31/70947167.jpg)

**Comment by wuhonglei** [comment]
我使用的是 Mac 系统，在运行`python wechat_jump_auto.py`出现了和你同样的问题。
解决办法 **`pip install Pillow`** ， 安装完成后就不会提示这个错误了。如果你的问题得到解决，请请关闭该问题。
