### ISSUE TITLE
找不到config.json 

### ISSUE THREAD

**Issue by zgmd** [wangshub/wechat_jump_game#236]
![image](https://user-images.githubusercontent.com/13150538/34459197-bb43dbde-ee23-11e7-87b7-b7bf555324e6.png)
![image](https://user-images.githubusercontent.com/13150538/34459201-dc0bd740-ee23-11e7-9cb6-f9bb2722ac32.png)

**Comment by WeidongHe** [comment]
cd 到 当前目录
