### ISSUE TITLE
运行出错，弄了好几个小时了。路过的大佬进来看一下，在线等，急！急！急！！！

### ISSUE THREAD

**Issue by whoknowne** [wangshub/wechat_jump_game#238]
Traceback (most recent call last):
  File "F:\Python\wechat_jump_auto.py", line 30, in <module>
    config = json.load(f)
  File "F:\Python\lib\json\__init__.py", line 291, in load
    **kw)
  File "F:\Python\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "F:\Python\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Python\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
这是怎么个情况，我的前期工作应该没问题，下载安装调试折腾了好几个小时了，路过的大佬帮我解答一下，不胜感激！

**Comment by maxlv7** [comment]
看最后一行，应该是没有载入json文件

**Comment by whoknowne** [comment]
我想请问一下，具体要怎么做？

**Comment by whoknowne** [comment]
还有就是这个文件wechat_jump_auto.py里面的config.json要进行修改是什么意思？新人小白，一点不懂。
是要把下面的代码改成什么吗？
with open('config.json','r') as f:
    config = json.load(f)

**Comment by mjzcyhp** [comment]
直接把config.json文件放到wechat_jump_auto.py同一个目录里面就好了

**Comment by whoknowne** [comment]
之前就放在同一个目录下面了，然后显示上面的话，所以说很费解啊！

**Comment by F-loat** [comment]
你是在项目目录里执行的脚本吗

**Comment by whoknowne** [comment]
我的Python安装目录是F:\Python，我把wechat_jump_auto.py和config.json都放在这里面面了，然后运行的wechat_jump_auto.py。

**Comment by lhy1993** [comment]
print 一下f，看看f是个什么东西再说。

**Comment by wangshub** [comment]
release已经发布

**Comment by whoknowne** [comment]
我后来试了好久，终于发现了个问题，网站里给的config.json中参数，具体是四个数字没有加双引号，我用记事本重写了一份，改了文件名后缀，就可以了。在此感谢所有解答问题的大佬，感谢感谢！！！
