### ISSUE TITLE
突然从排行榜消失了，大家有没有遇到过

### ISSUE THREAD

**Issue by zhaoweihaoChina** [wangshub/wechat_jump_game#240]
我前天晚上玩到2000+，我朋友也看到了，但是昨天早上突然从排行榜消失了，我朋友的排行榜也看不到我，很奇怪，不知道大家有没有遇到过
![tim 20171230114100](https://user-images.githubusercontent.com/25500786/34459286-10e7e2da-ee27-11e7-801a-d5a1877c8a6c.png)
我发到群排行，发现自己变0了:flushed:
这是小游戏的bug吗
![screenshot_20171231-122921](https://user-images.githubusercontent.com/25500786/34459288-12dea7ae-ee27-11e7-9fd9-ba125d5269fe.png)

**Comment by doubiermie** [comment]
你已经被ban了。。。

**Comment by zhaoweihaoChina** [comment]
@doubiermie 就我一个吗

**Comment by cisiqo** [comment]
刚刷了400多，没有问题

**Comment by wangshub** [comment]
大兄弟，注意节制，哈哈开心就好 @zhaoweihaoChina
