### ISSUE TITLE
 No module named 'PIL'

### ISSUE THREAD

**Issue by xinpengfei520** [wangshub/wechat_jump_game#241]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wechat_jump_game-master\wechat_jump_auto.py", line 6, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'

**Comment by whoknowne** [comment]
你应该是没有安装PIL吧

**Comment by KitYeungDev** [comment]
https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

**Comment by xinpengfei520** [comment]
Thanks.

**Comment by wuhonglei** [comment]
我使用的是 Mac 系统，在运行`python wechat_jump_auto.py`出现了和你同样的问题。
解决办法 **`pip install Pillow`** ， 安装完成后就不会提示这个错误了。如果你的问题得到解决，请请关闭该问题。
