### ISSUE TITLE
我的1280*720手机这样手动玩的  玩了4个觉得太麻烦， 有没有大佬会Python自动化一下啊

### ISSUE THREAD

**Issue by ObjLin** [wangshub/wechat_jump_game#242]
1 截图 adb shell screencap -p /sdcard/1.png
    adb pull /sdcard/1.png .
2 打开windows画图，获取起始点和终点的坐标，用程序算出两点的距离，根据压力指数大概0.513，计算出时间=距离/0.513
3 adb shell input swipe x y x y time 进行跳动

**Comment by wangshub** [comment]
https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py
@ObjLin
