### ISSUE TITLE
Python小白，求手把手操作，微信50红包

### ISSUE THREAD

**Issue by ningshaoV587** [wangshub/wechat_jump_game#244]
华为P9手机，用了同学的Lenovo win10试了一早上，不是adb不是内部指令，就是代码内找不到指定名称

本来以为就是像楼主说的那样，安卓下载Python，下载adb，连接手机调试开发者模式和，运行代码（auto_py）那么简单，可是操作写来，每次都提示adb安装成功，但是也不知道到底文件在哪，成功与否。

![11111](https://user-images.githubusercontent.com/18507919/34459457-4de951b0-ee2b-11e7-86b8-bc99d001d99b.png)

**Comment by hzzzero** [comment]
WeChat zero-hzz

**Comment by Lemniscate317** [comment]
qq jiu si jiu wu jiu ba qi liu san

**Comment by ningshaoV587** [comment]
微信ningshaoV587

**Comment by ningshaoV587** [comment]
不可以删除自己的问题吗？
