### ISSUE TITLE
请问adb应该如何配置

### ISSUE THREAD

**Issue by lyrical1991** [wangshub/wechat_jump_game#247]
提示这个 ：
error: device not found
error: device not found

**Comment by F-loat** [comment]
手机开启usb调试，检查驱动是否安装

**Comment by lyrical1991** [comment]
弄好了，多谢。

**Comment by xiahuyu** [comment]
怎么弄的，我也是这个问题

**Comment by heachou** [comment]
我是先   adb kill-server
再 adb start-server
然后解决了找不到设备问题

**Comment by wangshub** [comment]
相似问题 可以参考这个文章
[https://zhuanlan.zhihu.com/p/32497067](https://zhuanlan.zhihu.com/p/32497067)

**Comment by mrfuckk** [comment]
你把手机模式不要调成充电模式试试

**Comment by wangshub** [comment]
小米需要额外开启 【USB调试（安全设置）】   这个开关
