### ISSUE TITLE
有个大胆的想法。关于第二个图形中点坐标的获取！

### ISSUE THREAD

**Issue by baolw** [wangshub/wechat_jump_game#248]
因为阴影的颜色是一致的，所以如果这边能把阴影的颜色排除掉，还是可以获取到中点的，除了有一种长耳朵块的特殊情况

**Comment by baolw** [comment]
中点获取，首先还是原来的算法算出第二个图形顶点的位置，得到顶点的x，y坐标，然后棋子底座的坐标我们也可以计算

**Comment by zkjmyy** [comment]
那你赶紧搞一个啊

**Comment by wangshub** [comment]
注意背景颜色有时候是渐变的哦 @baolw

**Comment by baolw** [comment]
然后根据2个横坐标的相减，可以得到棋子是往哪边跳的。可能挨得很紧的话会有特殊情况。比如如果是往右边跳的，那么就从屏幕右往左到第二个图形的x坐标遍历，从第二个块的顶点y坐标往下遍历，排除阴影，得到的第一个非背景点就是第二个块平面的中点纵坐标了，横坐标就是顶点的横坐标

**Comment by baolw** [comment]
那你顶点的那个是怎么获取的，我对取色那块不是很了解

**Comment by baolw** [comment]
我在外面，用手机打字的，不知道怎么@

**Comment by zengke123** [comment]
@baolw 获取顶点的x坐标，是从分数线以下逐行扫描每个像素点，比较像素点的RGB值偏差范围，超过一定范围就可以判定扫描到顶点了，@wangshub 是这样的吧

**Comment by baolw** [comment]
我理解的也是这样，但是具体什么范围就不好说了，主要是看能不能把阴影排除掉

**Comment by llxisdsh** [comment]
仔细观察了下,  基本上可以使用两边的凸点来判断Y,   这个凸点基本在阴影之上,  且阴影的斜率是明显不同的
