### ISSUE TITLE
偶尔会跳不动

### ISSUE THREAD

**Issue by evanhvy** [wangshub/wechat_jump_game#25]
![1](https://user-images.githubusercontent.com/30188008/34450090-3d1ab206-ed3c-11e7-8e31-7375d0b6d0d3.png)
@wangshub

**Comment by wangshub** [comment]
@evanhvy 应该是识别出来的圆形不对，稍后改进这块

**Comment by wangshub** [comment]
是出现这种小圆盘会跳不动吗

**Comment by evanhvy** [comment]
@wangshub 对的,有时候矩形也跳不到,应该是没有测量到,直接用了200

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
