### ISSUE TITLE
小白教程

### ISSUE THREAD

**Issue by windbeijing** [wangshub/wechat_jump_game#250]
始终搞不明白整个操作流程，也不知道要装的这些乱七八糟工具都是干嘛的，可以看这里，说的比较清楚：

![qscode](https://user-images.githubusercontent.com/34977008/34459726-94c93908-ee33-11e7-9aab-e7fd062d820d.jpeg)

**Comment by wangshub** [comment]
别做推广啦，抱歉 @windbeijing
