### ISSUE TITLE
是不是还可以加个跳到多少分的功能呀

### ISSUE THREAD

**Issue by zack624** [wangshub/wechat_jump_game#253]
比如520，1314之类的就停住，嘿嘿，突发其想。

**Comment by Ccptsoap** [comment]
这个会麻烦很多的 要么你读取内存数值 要么图像识别 两个方法都会工程量大增

**Comment by DisMeo** [comment]
要是再加一个图像识别的话，代码就会很慢了吧

**Comment by wangjianssd** [comment]
这个 很好实现，  做一个区域截图，外加简单的OCR 算法
