### ISSUE TITLE
小白求问  import numpy as np   ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by lancer1126** [wangshub/wechat_jump_game#257]
小白一枚  这是什么原因啊
Traceback (most recent call last):
  File "D:/MyCode/PythonLearn/githubDownload/wechat_jump_game-master/wechat_jump_py3.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by kryhuai** [comment]
pip install numpy

**Comment by wjllance** [comment]
pip install -r requirements.txt

**Comment by silian1988** [comment]
pip3 install -r requirements.txt

**Comment by markwang126** [comment]
缺少numpy库
进命令行 pip install numpy

**Comment by wangshub** [comment]
如上哦 @lancer1126
