### ISSUE TITLE
Bluestacks模拟疑似被腾讯封了

### ISSUE THREAD

**Issue by podcctv** [wangshub/wechat_jump_game#259]
提示该设备无法运行小游戏。

**Comment by yefuchao** [comment]
同 应该是封了

**Comment by Lucahan** [comment]
去微信官网下载apk重新安装，不要用blue自带的安装就可以解决了。

**Comment by yangxuanx** [comment]
现在官网下载的也不行，刚试了一下，提示环境加载失败

**Comment by AllenMRbai** [comment]
微信更新到6.6.1即可

**Comment by morganlaowang** [comment]
需要更新+1

**Comment by yefuchao** [comment]
当前设备系统不支持小游戏，官网下的也这样。

**Comment by morganlaowang** [comment]
要在程序里面设置里选择更新

**Comment by yangxuanx** [comment]
更新后可以点击跳一跳，但是最后卡在初始化游戏界面，微信直接卡死

**Comment by zwjsylar** [comment]
显示已封禁，然后手机端也登陆不起了

**Comment by zzhaowf** [comment]
目前我这边还是可以用的。入口在更新完第一次登陆的时候启动页面的开始游戏。在微信中进去会提示设备不支持。2018_1_1_10_42
