### ISSUE TITLE
小米MIX读IMG路径问题

### ISSUE THREAD

**Issue by DragonQin** [wangshub/wechat_jump_game#260]
小米MIX读截屏的路径应该怎么写？有人知道吗？谢谢！

**Comment by jchen357** [comment]
46-48行改成这个
def pull_screenshot():
    os.system('adb shell screencap -p /mnt/sdcard/1.png')
    os.system('adb pull /mnt/sdcard/1.png .')

**Comment by F-loat** [comment]
新版本应该没问题了
