### ISSUE TITLE
求问如何获取游戏内部状态？

### ISSUE THREAD

**Issue by xjwxjw** [wangshub/wechat_jump_game#262]
求问能否通过微信的API或者其他方式获取这个游戏的基本内部状态？比如当前得分，是否死亡之类的？

**Comment by wjllance** [comment]
想多了兄弟

**Comment by wjllance** [comment]
不要老想着捡便宜haha还是自己动手吧，获取了得分和死亡就可以套DQN了，加油老哥

**Comment by chloechj** [comment]
没有combo就加0.1分，有combo加1分，死亡-1分，游戏得分一直在左上角应该能做出来了吧
