### ISSUE TITLE
跑了3次 都在500~1000之间 需要继续修正

### ISSUE THREAD

**Issue by HuRuWo** [wangshub/wechat_jump_game#267]

**Comment by HuRuWo** [comment]
而且并不能保证每次跳到中间，所以分数加的很慢

**Comment by haohaitao** [comment]
兄弟，你参数多少，我没跳到100过...

**Comment by chenyy93** [comment]
https://github.com/wangshub/wechat_jump_game/issues/182，你看一下这个方法，分数可以高一点，但基本也过不了千 @haohaitao
