### ISSUE TITLE
希望用小米5的同学进来讨论参数设置

### ISSUE THREAD

**Issue by jchen357** [wangshub/wechat_jump_game#269]

**Comment by MoonChasing** [comment]
{
    "under_game_score_y": 300, 
    "press_coefficient": 1.475, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70
}
最高686分

**Comment by bakaleos** [comment]
同米5，上面这个参数挺稳的

**Comment by jchen357** [comment]
@MoonChasing 厉害，press_coefficient调高了？这个参数是干嘛用地？

**Comment by MoonChasing** [comment]
@jchen357 按压时间参数，相当于这个数越大对压按压时间越长。

**Comment by MoonChasing** [comment]
#270  大家可以往这里边上传些失败情况下截图。QAQ

**Comment by DisMeo** [comment]
1.4665 基本都在200左右。
用1.475的话，100都不到。
不知道会不会是mac的问题或者是rom的问题

**Comment by xu42** [comment]
[https://github.com/wangshub/wechat_jump_game/pull/278](MI5X可以看看这个PR)已经2300+了还在增高

**Comment by Superbsco** [comment]
#212
小米5看这里

**Comment by moxiaotu** [comment]
1.475在200左右

**Comment by AzuraZh** [comment]
同米5 我用这个参数就跳了3分 求助

**Comment by BeWithU** [comment]
这个要看出现方块左右的随机性吧，我用1.45最多919。我观察了一下，有时候这次跳的距离近，下一次就修正回来了，修正不回来，连续几次短了就挂了。

**Comment by manmanmango** [comment]
我也小米5 每次自动用的就是1920*1080的那个配置 ，不是还有一个mi5的配置么，用哪个？

Load config file from D:\Users\yunlong\Downloads\wechat_jump_game-master/config/1920x1080/config.json

**Comment by qiushicai** [comment]
{
	"under_game_score_y": 300,
	"press_coefficient": 1.475,
	"press_base_time": 600,
	"press_coefficient_fix": 4000,
	"piece_base_height_1_2": 20,
	"piece_body_width": 73,
	"swipe" : {
		"x1": 500,
		"y1": 1600,
		"x2": 500,
		"y2": 1602
	}
}
小米五这个配置 666分！哈哈哈。

**Comment by jchen357** [comment]
![1514890999_d](https://user-images.githubusercontent.com/15809493/34481972-1264e7b4-eff0-11e7-9a26-7a76ad40a650.png)
![1514890997_d](https://user-images.githubusercontent.com/15809493/34481975-140d7bf8-eff0-11e7-85aa-995cb2d3027c.png)

**Comment by jchen357** [comment]
![1514891613_d](https://user-images.githubusercontent.com/15809493/34482264-cc15cc40-eff1-11e7-8bb5-23470d46fe90.png)

**Comment by jchen357** [comment]
![1514891875_d](https://user-images.githubusercontent.com/15809493/34482279-e5112b68-eff1-11e7-861b-a83b3e2eb905.png)

**Comment by jchen357** [comment]
![1514892050_d](https://user-images.githubusercontent.com/15809493/34482320-283f5892-eff2-11e7-92a4-b57dcd04a369.png)

**Comment by jchen357** [comment]
![1514892597_d](https://user-images.githubusercontent.com/15809493/34482531-853edef4-eff3-11e7-898b-c6bbb11bdccb.png)

**Comment by gongzelong0718** [comment]
你们的截图是怎么获取的呢?求问
