### ISSUE TITLE
失败情况的截图，大家一起上传些

### ISSUE THREAD

**Issue by MoonChasing** [wangshub/wechat_jump_game#270]
![1514703420_d](https://user-images.githubusercontent.com/27677938/34460187-da92394e-ee42-11e7-844a-c77d432d3196.png)
![1514703526_d](https://user-images.githubusercontent.com/27677938/34460188-db4e4c38-ee42-11e7-98fc-e2454ec11cd4.png)
![1514704227_d](https://user-images.githubusercontent.com/27677938/34460189-db86e688-ee42-11e7-84a4-94f48aeb0930.png)
![1514704557_d](https://user-images.githubusercontent.com/27677938/34460190-dbb99024-ee42-11e7-80b0-3a432a99e499.png)
![1514704883_d](https://user-images.githubusercontent.com/27677938/34460191-dbed00f8-ee42-11e7-8b96-f6698f2ff848.png)
![1514705835_d](https://user-images.githubusercontent.com/27677938/34460192-dc262e50-ee42-11e7-86b5-23f3195bd698.png)
![1514705839_d](https://user-images.githubusercontent.com/27677938/34460193-dc6dbcca-ee42-11e7-97e8-085d5a20f1af.png)

**Comment by haohaitao** [comment]
{
    "under_game_score_y": 300,
    "press_coefficient": 1.48,
    "piece_base_height_1_2": 20,
    "piece_body_width": 73
}

300+就上不去了  米5

**Comment by qiushicai** [comment]
![1514809767_d](https://user-images.githubusercontent.com/20509980/34467653-c2f83e78-ef32-11e7-98b2-a0322b621478.png)

**Comment by qiushicai** [comment]
{
	"under_game_score_y": 300,
	"press_coefficient": 1.475,
	"press_base_time": 600,
	"press_coefficient_fix": 4000,
	"piece_base_height_1_2": 20,
	"piece_body_width": 73,
	"swipe" : {
		"x1": 500,
		"y1": 1600,
		"x2": 500,
		"y2": 1602
	}
}

小米五这个配置，666分  哈哈哈！

**Comment by qiushicai** [comment]
![1514810190_d](https://user-images.githubusercontent.com/20509980/34467720-6ca3ef0c-ef34-11e7-8604-d59f2910ef51.png)
