### ISSUE TITLE
能否加个屏幕截图自动删除功能

### ISSUE THREAD

**Issue by KMKNKK** [wangshub/wechat_jump_game#274]
从adb连真机，pull上来的图片会存放在一个缓存文件夹，如果是小白的话可能会造成占用内存过大的问题。

**Comment by markwang126** [comment]
可以吧，那就每走一步删除上次的图片

**Comment by shaoguoji** [comment]
有么。。。pull上来的图片在 repo 目录下的 1.png，每次都会覆盖旧图……

**Comment by DisMeo** [comment]
@KMKNKK 可以在 save_debug_creenshot 下面加一个判断文件夹大小

**Comment by KMKNKK** [comment]
@shaoguoji 不是那个，你仔细看看有个缓存文件夹。主要是怕小白不知道。

**Comment by shaoguoji** [comment]
@KMKNKK 是 screenshot_backups 看到了，可以增加调试开关，需要时再保存……

**Comment by KMKNKK** [comment]
@shaoguoji 嗷嗷看到了，刚开始没仔细看源码，我的锅
