### ISSUE TITLE
优化方案

### ISSUE THREAD

**Issue by axfv** [wangshub/wechat_jump_game#276]
取色或者检测出棋子位置
棋子x坐标<图像宽度/2 目标位置则在以棋子中心为原点参考的第一象限，目标与棋子夹角为30度
棋子x坐标>图像宽度/2 目标位置则在以棋子中心为原点参考的第二象限，目标与棋子夹角为60度
目标所在象限边缘检测第一个点即为目标顶点
![20171231155941](https://user-images.githubusercontent.com/20575027/34460347-6bcdb804-ee46-11e7-9e3e-f1d0951ff383.png)
![20171231155858](https://user-images.githubusercontent.com/20575027/34460348-6ff34dfe-ee46-11e7-9afb-427d0632aad8.png)

**Comment by coofly** [comment]
是个好办法！
