### ISSUE TITLE
白色图像中心识别错误率高

### ISSUE THREAD

**Issue by ChenLiaoyuan** [wangshub/wechat_jump_game#280]
机型：小米6 windows10
分辨率：1920x1080
错误信息：在我的机型上调节了这个配置后，
{
    "under_game_score_y": 300, 
    "press_coefficient": 1.38, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70
}
几乎可以跳到每个图案的中心，但一遇到白色的图案，
（站在白色的图案上，或者要跳到白色的图案上），
中心的错误识别率几乎达到90%以上。
下面是识别截图：
![1514709980_d](https://user-images.githubusercontent.com/21029600/34460512-c5b7a172-ee4b-11e7-826b-f15c547f48a2.png)
![1514710051_d](https://user-images.githubusercontent.com/21029600/34460513-c5efd060-ee4b-11e7-8162-2e0ba0836733.png)
![1514710088_d](https://user-images.githubusercontent.com/21029600/34460514-c6294c46-ee4b-11e7-9ea0-b1d818fd25e7.png)
![1514710212_d](https://user-images.githubusercontent.com/21029600/34460515-c660bd20-ee4b-11e7-96f3-bc48c0c780d6.png)

**Comment by douzi-shenqi** [comment]
小米5s  所有的圆形失败失败
