### ISSUE TITLE
手机端不动

### ISSUE THREAD

**Issue by MrLiukang** [wangshub/wechat_jump_game#282]
我的电脑显示在运行着，但是我的手机却不动，

**Comment by DisMeo** [comment]
安卓的话需要开发者模式usb调试，小米还需要开启模拟点击

**Comment by MrLiukang** [comment]
我点击了，现在z在电脑上是这的，一直在输出，但是手机端一直不动
![image](https://user-images.githubusercontent.com/20420044/34460546-784fb946-ee4c-11e7-825e-f291eb8f819c.png)

**Comment by DisMeo** [comment]
@MrLiukang 看下adb有没有识别手机的id吧

**Comment by MrLiukang** [comment]
如果没有识别的话，图片肯定也上传不了啊。应该不是这个问题吧

**Comment by HuangPZ** [comment]
+1，小米6，遇到同样问题。请问所谓的小米手机开启模拟点击是什么意思？

**Comment by hithzf** [comment]
+1，请问解决了么

**Comment by MrLiukang** [comment]
还没。。。感觉应该和手机又关系，手机可能控制的太严了

**Comment by MrLevo520** [comment]
同样，安卓机，运行没问题，但是一直在蓄力阶段，就是不松开。。。。

**Comment by MrLevo520** [comment]
已解决，见https://github.com/wangshub/wechat_jump_game/issues/301
