### ISSUE TITLE
楼主汇报一些实验结果

### ISSUE THREAD

**Issue by llxisdsh** [wangshub/wechat_jump_game#283]
我是mi6, 在你的程序基础上修改了一些, 现在轻松上千了
1. 你提到的只用X轴进行计算, 我也是这么简化的, 效果还是很显著的, 因为两个块X计算还是准确的
    =abs(X1-X2)*2/sqrt(3)

2. 关于棋子的X值, 在Mi6上, 应该向左偏移两个像素,  这个应该和颜色阴影有关, 所以重心普遍像右偏移了.

3. 关于棋子Y的计算可以做一些修改, 当然用了上面这个就没意义了
piece_y = piece_y_max - (math.sqrt(piece_x_c) / 1.5)  #我是用piece_x_c这个计算底盘尺寸的,1.5这个系数可固定, 应该和设备无关

4. 屏幕的中心试验后发现,  和两块中心, 不是一条直线, 有一定参照意义但不大

5. 还有个思路应该更准确,  计算目标块的中心,  现在只差Y,  其实可以类似你计算X那样计算,  当遇到两边凸顶时确认Y值,  虽然复杂, 但只要做好容错, 比现在固定30度的算法会准确很多.

**Comment by chenweiguang82** [comment]
兄弟，我的也是mi6，一直到不了500，那个时间我增大了些，求更好的参数，谢谢

**Comment by llxisdsh** [comment]
wechat_jump_auto.py:

函数def main():
    #jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
    jump(abs(board_x - piece_x)*2.0/math.sqrt(3.0))

函数def find_piece_and_board(im):
    #piece_x = (piece_x_sum / piece_x_c)
    piece_x = (piece_x_sum / piece_x_c) - 2

config.json:
    "press_coefficient": 1.46,

**Comment by llxisdsh** [comment]
现在作者这个算法很巧妙, 但最终还是要计算目标块的中心, 这个攻克了, 几千没问题了

**Comment by chenweiguang82** [comment]
多谢，我先前想着用opencv进行图像识别，作者的方法确实挺巧妙的，先用这个刷刷分：D

**Comment by chenweiguang82** [comment]
貌似还是有问题，目前最高是600多分，还是有偏移，不知道程序本身对这个距离有什么算法。

**Comment by llxisdsh** [comment]
嗯, 基本算法没改变, 只是优化了下,  只要改算法才能更准
