### ISSUE TITLE
你们还能提交数据吗？

### ISSUE THREAD

**Issue by liangkun16** [wangshub/wechat_jump_game#286]
我跳到400多失败，然后看下排行还是我手打的100分。是不是被腾讯封了

**Comment by wjzhangcsu** [comment]
你试了几次？

**Comment by GitHubZhuMin** [comment]
我刚才程序跑的分退出微信还是以前的分， 刷的现在数据同步不上去了

**Comment by liangkun16** [comment]
后来排行榜又更新了我422分，然后我又跳了200多分，微信又把我的排行榜记录到200多分，哈哈 什么鬼

**Comment by yuchunyu97** [comment]
别高出你朋友圈排行榜太多就可以被记录

**Comment by yefuchao** [comment]
有时候不会马上更新，前天拿别人手机手动跳了100多也这样，自己跳200多反倒马上更新了，今天刷的1000多过了半个小时左右才更新出来。
