### ISSUE TITLE
自动跳转脚本，无效，第一次跳的很短距离

### ISSUE THREAD

**Issue by malatachehongbin** [wangshub/wechat_jump_game#29]
`
  board_y = piece_y + abs(board_x - piece_x) * abs(1122 - 831) / abs(813 - 310)   # 按实际的角度来算，找到接近下一个 board 中心的坐标`

这里面的数值是怎么来的？

**Comment by 0x9c** [comment]
我也是这个情况，后来用手动了

**Comment by MrHwq** [comment]
修改下auto.py，给他拉远一点
        board_y += 30
        if piece_x > board_x:
            board_x -= 30
        else:
            board_x += 30
        jump(math.sqrt(abs(board_x - piece_x) ** 2 + abs(board_y - piece_y) ** 2))

**Comment by cuiyubao** [comment]
我是多试了几次可以的

**Comment by Donng** [comment]
先打开游戏，再执行脚本，我出现这个问题就是因为先开了脚本再打开的游戏。
