### ISSUE TITLE
小米手机记得要把悬浮球关掉！否则只能跳个位数

### ISSUE THREAD

**Issue by teaGod-s** [wangshub/wechat_jump_game#297]
手机型号红米note3双网通，分辨率1920*1080，参数
`{
    "under_game_score_y": 300,
    "press_coefficient": 1.392,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}`
最终结果1124分

**Comment by troubadour-hell** [comment]
把球移到屏幕下方三分之一的区域就好了

**Comment by NJUDavidWu** [comment]
谢谢，终于解决。把悬浮球关掉就可以了。
