### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by INtEReSTiNg1234** [wangshub/wechat_jump_game#30]
Traceback (most recent call last):
  File "D:/py/untitled/wechat_jump_py3.py", line 28, in <module>
    img = np.array(Image.open('1.png'))
  File "C:\Users\WKN\Anaconda3\lib\site-packages\PIL\Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '1.png'

**Comment by wangshub** [comment]
没有 ‘1.png’ 图片，请看一下Adb能否拉上来图片

**Comment by wangshub** [comment]
@INtEReSTiNg1234

**Comment by shizhidi** [comment]
我也是这个问题，啥意思？ @ @wangshub

**Comment by wangshub** [comment]
请终端执行一下 `adb devices`，看下有没有设备，如果没有的话请开启USB调试
@shizhidi

**Comment by shizhidi** [comment]
解决了，
![image](https://user-images.githubusercontent.com/7605007/34450695-9e42ccd0-ed4b-11e7-847b-5ab77ae23b03.png)
放到这个目录下就可以截图了,电脑上的图片怎么点，是点目标地点是吧？
![image](https://user-images.githubusercontent.com/7605007/34450703-c438aca2-ed4b-11e7-80aa-ef2b9d198039.png)

**Comment by wangshub** [comment]
@shizhidi 最新 `wechat_jump_auto.py` 可以实现自动跳了 @shizhidi

**Comment by coder30** [comment]
@shizhidi 我放在这个目录下面也还是和之前一样的情况

**Comment by wangshub** [comment]
这个是点小人底座，再点目标位置 @shizhidi

**Comment by wangshub** [comment]
[https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py](https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py)

**Comment by coder30** [comment]
@wangshub 
![image](https://user-images.githubusercontent.com/22569249/34450789-44514906-ed4e-11e7-97d7-1410007050e0.png)这该怎么解决

**Comment by wangshub** [comment]
应该是你的adb没有连上，麻烦终端执行`adb devices`看下设备列表 @coder30

**Comment by coder30** [comment]
@wangshub 终端运行提示不存在这个命令

**Comment by INtEReSTiNg1234** [comment]
把ADB路径加到PATH里就可以了

**Comment by Tao-Chan** [comment]
@wangshub USB调试打开，abd也提示连上了还是这个错误
![image](https://user-images.githubusercontent.com/17512689/34451502-cb3d1cce-ed62-11e7-9958-9d3a91765926.png)

**Comment by xiaooooooowu** [comment]
我用了adb devices可以看到设备列表
但是还是出现上图的错误 问什么呀@wangshub
