### ISSUE TITLE
macOS和Linux截图问题

### ISSUE THREAD

**Issue by yiranshaxiao** [wangshub/wechat_jump_game#300]
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: SM-G9200
=====
List of devices attached
0123456789ABCDE	device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 231, in <module>
    main()
  File "wechat_jump_auto.py", line 218, in main
    im = Image.open('./autojump.png')
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

```
 去掉pull_screenshot函数里面的 .replace(b'\r\n', b'\n') 就可以了。
```

**Comment by F-loat** [comment]
你是用linux的吗

**Comment by yiranshaxiao** [comment]
@F-loat  mac

**Comment by F-loat** [comment]
做了兼容处理 3062e1bede40432355ad98b090c5a7df1e7c9355

**Comment by Pesdestrian** [comment]
去掉一样，还是报错。

**Comment by F-loat** [comment]
输出screenshot变量看下

**Comment by wangzihan424** [comment]
输出是一堆乱码

**Comment by F-loat** [comment]
帮忙测试下直接执行 `adb shell screencap -p | sed s/\r$// > autojump.png  ` 能否获取到截图，能的话mac和linux可以换成这个命令

**Comment by F-loat** [comment]
@wangzihan424 截取最开始的一部分发一下

**Comment by wangzihan424** [comment]
我是win10系统

**Comment by F-loat** [comment]
@wangzihan424 python版本呢

**Comment by wangzihan424** [comment]
anaconda 2.7

**Comment by yiranshaxiao** [comment]
@wangzihan424 去掉 ```pull_screenshot``` 函数里面的 ```sys.platform == 'win32':``` 试试？

**Comment by wangzihan424** [comment]
@F-loat 输出的是这个乱码
�PNG

��ӆ7��A�	�6�n�T�<tW�)3���Ž��"2�č߯�r���E�ʗ���s�o��k%ֽ֔�/���������u6��e#��^�M\c�\�O����w�܉�����ȵ��֭[�?�[y��ݿ����6�m#sl�ߝ�~��X������Kl�E��k;��k���F�>����{\��Q���k3^i�+T�|j�wg�d��:u<�Z~��S��]���U��]�s����\�wO���\�C�P����F��-'''��/���,���/��am_���?  �� �Џ���z�+�ַ�u���   7I�[��JDď�ȏl�Z����}�#�)�O�P  �
�������]�q%���jܽ{w���>9,B  vA�[��ʏ�؏m�Z��}m�#�)�O  `��] �h���t���'�ٻ��o�ox&�+_�����k� ���0Q�'  �9�	:���+_��]�  ��    \@�01��>Y�B `[( �5!
  � @��Cj�  �6	P �{Z(  �4
�Dh�  ��� L��D ��%@`2�(  �
���> ��'@`R�P  �	�=�}  �!@�S��B `�(    � �!퓋i�  �I &K� ��P ���	  l� �I�B `( {D�  vC��'�'ק� ��(    � ���i�  �
 C� �u	P *�}  �'@�h�  p��i�  @( ���-  �J�   p

**Comment by wangzihan424** [comment]
@yiranshaxiao 这句话不是判断到底是window系统还是linux系统的吗。。删这个没啥用啊

**Comment by F-loat** [comment]
嗯，我是用python3测试的，这个应该不支持2.7，因为用到了 `bytes`

**Comment by F-loat** [comment]
输出这个才对
```
xb3k\xfd|zz:\xbe\xfc\xf2Kq\xf9\xf5\xd7_\xd7\xb8ouUQQ\x81\xf8\xf8x\\\xb9r\x05\xb7o\xdfFQQ\x11***`gg\x07www\xf8\xf8\xf8   \x00\x0e\x0e\x0e\xb5\xaeG\x9a\xc0\xc9\xd5\xd5\x15_~\xf9%JJJp\xe4\xc8\x11$$$ ;;\x1b\xe5\xe5\xe5\x983g\x0e\x02\x03\x03\xb5\x96%..\x0e\t\t\t\xb8s\xe7\x0eJJJ`kk\x0b\'\'\'\xf4\xec\xd9\x13~~~\x06\x992\xf4\xd2\xa5K\xb2\x04S\x8b\x17/\x86\x93\x93\x13\xa2\xa3\xa3\x11\x1b\x1b\x8b\xac\xac,\x94\x94\x94
```

**Comment by wangzihan424** [comment]
那gg了

**Comment by yiranshaxiao** [comment]
@wangzihan424 
sys.platform

System | platform value
-- | --
Linux (2.x and 3.x) | 'linux2'
Windows | 'win32'
Windows/Cygwin | 'cygwin'
Mac OS X | 'darwin'
OS/2 | 'os2'
OS/2 EMX | 'os2emx'
RiscOS | 'riscos'
AtheOS | 'atheos'

**Comment by zealot00** [comment]
linux可以把pull_screenshout函数替换，更改成：
 78 def pull_screenshot():
 79      os.system('adb shell screencap -p /sdcard/autojump.png')
 80      os.system('adb pull /sdcard/autojump.png ./')
 81 #    process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
 82 #    screenshot = process.stdout.read()
 83 #    if sys.platform == 'win32':
 84 #        screenshot = screenshot.replace(b'\r\n', b'\n')
 85 #    f = open('./autojump.png', 'wb')
 86 #    f.write(screenshot)
 87 #    f.close()
这个办法虽然笨，但是保证Linux可以使用，

**Comment by F-loat** [comment]
@zealot00 嗯，在做这方面的处理了，可以关注下 #325
