### ISSUE TITLE
解决一直处于蓄力不弹跳的问题

### ISSUE THREAD

**Issue by MrLevo520** [wangshub/wechat_jump_game#301]
主要原因在于adb shell input swipe 320 410 320 410 问题，这里使用了swipe的方式，进行滑动时长操作，那么对于18：9的屏幕，可能你的屏幕像素位置它永远无法捕捉到！！！这就导致手机一直在蓄力！希望更新到readme.md中！举个例子

这里我设置adb shell input swipe 320 1210 720 910即完成修复！！！！！
对应自己的手机具体截屏后的matplotlib展示图进行对应修复，测试的时候用wechat_jump_py3.py文件即可，自动跳的同样道理！！
![img_6089](https://user-images.githubusercontent.com/20299815/34461176-cf1af3d2-ee5e-11e7-97a5-17a6e85c03bc.JPG)

**Comment by MrLiukang** [comment]
我的是华为手机，不管怎么设置，也是不行。没有任何反应。就和没有运行程序一样

**Comment by MrLevo520** [comment]
@MrLiukang 确定adb能连接到你的设备，看看adb devices。。如果用哪个手动的文件，能弹出matplotlib的图么？

**Comment by MrLiukang** [comment]
我确定可以链接，因为我用adb截过图，并且拿到了我的电脑上，但是。。。。手机上就是一动不动，而电脑上的程序在呼呼的跑。

**Comment by MrLiukang** [comment]
程序的输出是一样的，
![image](https://user-images.githubusercontent.com/20420044/34461529-c2bd1fd0-ee67-11e7-993e-df61623d6854.png)

**Comment by vipmike007** [comment]
我的小米6也是，程序输出但是手机不动

**Comment by MrLevo520** [comment]
@vipmike007 @MrLiukang 你们用wechat_jump_py3.py进行测试，如果是存在是一直蓄力过程，则修改哪个swape，如果连蓄力过程都没有，建议先试用adb shell input tap 320 1210模拟下点击的操作

**Comment by holdjohnh** [comment]
不知道有没有同学和我一样是用锤子 坚果pro2 的 一直在蓄力跳不出去的 
告诉你们 可能是因为触发大爆炸了。。。。在设置里关了就可以跳了

**Comment by MrLevo520** [comment]
@holdjohnh 哈哈。我也是坚果pro2！刚开始由于大爆炸和ORC识别然后被误操作，然后关了之后还是不行，之后修改了下代码的swape距离起始点，然后改了下就ok啦

**Comment by HirayClay** [comment]
是的，我是锤子ML，在设置里面关了大爆炸就好了；一开始我也觉得锤子的话就一个大爆炸和其他手机有些不同可能对按压有影响但是以为这个命令应该没有模拟那么大的接触面积就没关，一直跳不出去，关了就ok了。

**Comment by zhangsanfeng01** [comment]
@holdjohnh 哈哈 非常感谢 我的就是锤子 弄了一天了@ 看了你的回答才解决

**Comment by Eddie-he** [comment]
@holdjohnh 确实是大爆炸的问题，关闭就好了！

**Comment by rainbowjlinux** [comment]
@MrLevo520 距离起始点是如何修改的？
