### ISSUE TITLE
一加5  可以上传截图，但是第一步都不跳

### ISSUE THREAD

**Issue by guangfa** [wangshub/wechat_jump_game#302]
一加5  可以上传截图，但是第一步都不跳，系统安卓8.0，电脑win10。

**Comment by taotao7** [comment]
同问

**Comment by taotao7** [comment]
不过我成公过一次
300分

**Comment by guangfa** [comment]
如何成功的？

**Comment by wangshub** [comment]
我也是一加五，应该没啥问题呀，开启权限了吗，会有弹窗

**Comment by taotao7** [comment]
我成功了

**Comment by guangfa** [comment]
调试权限开了，ADB版本1.0.32.
用的官方氢8.0第二版

**Comment by MrLevo520** [comment]
见https://github.com/wangshub/wechat_jump_game/issues/301

**Comment by taotao7** [comment]
脚本成功执行只是不跳动对吗

**Comment by taotao7** [comment]
把你其他软件全关闭，我把保护眼睛的软件关闭了就可以了

**Comment by guangfa** [comment]
可以执行，不跳动，弹出截屏了。
不是18：9的屏，是1080P.config已经改了

**Comment by guangfa** [comment]
夜间模式？？我试试

**Comment by taotao7** [comment]
1980*1080分辨率，查看脚本执行时config的路径

**Comment by taotao7** [comment]
可以了说一声，我就是关闭了就正常了

**Comment by guangfa** [comment]
嗯，刚刚把python重装了一下，正在安装依赖库

**Comment by taotao7** [comment]
如果不行就是调用config错误了，你看看他调用是文件夹里面的1980*1080还是其他的是其他的就时错误的

**Comment by taotao7** [comment]
现在一次刷太高已经不会被上传了

**Comment by guangfa** [comment]
对，一加5关闭夜间模式、阅读模式，可以正常运行

**Comment by taotao7** [comment]
nice++
