### ISSUE TITLE
模拟器端无法运行wechat_jump_auto

### ISSUE THREAD

**Issue by morganlaowang** [wangshub/wechat_jump_game#307]
Load default config
如果你的脚本无法工作，上报issue时请copy如下信息:
=====
Screen: Physical size: 1920x1080
Density: Physical density: 240
DeviceType: SAMSUNG-SM-N900A
=====
List of devices attached
127.0.0.1:5555  device

Traceback (most recent call last):
  File "123.py", line 234, in <module>
    main()
  File "123.py", line 221, in main
    im = Image.open('./autojump.png')
  File "D:\Python\lib\site-packages\PIL\Image.py", line 2519, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by yiranshaxiao** [comment]
#300   试试这个？

**Comment by morganlaowang** [comment]
明天试试看
