### ISSUE TITLE
安卓手机到底是怎么个操作流程啊？

### ISSUE THREAD

**Issue by suyie001** [wangshub/wechat_jump_game#31]
安卓手机到底是怎么个操作流程啊？哪位大神说一下完整流程？我才刚刚开始学Python ，安卓编程也不太懂，adb就用过一次，用RN开发过一些简单的app

**Comment by qiushicai** [comment]
@suyie001  啥手机，我小米5.开启开发者选项，电脑安装adb .

**Comment by 201419** [comment]
@qiushicai 我小米5s，电脑上跑的程序手机没反应是什么情况

**Comment by MovvoM** [comment]
打开开发者选项，打开USB调试，打开USB调试模拟点击，第一次用时，需要在手机上允许此电脑进行USB调试

**Comment by qiushicai** [comment]
@201419  将手机点击到《跳一跳》小程序界面，cmd运行python wechat_jump_auto.py

**Comment by 201419** [comment]
@MovvoM @qiushicai 谢谢，原来是开启了USB调试模式，但是没有把安全设置打开

**Comment by qiushicai** [comment]
@201419 连接后，运行adb devices看看设备

**Comment by wangshub** [comment]
@suyie001 [readme](https://github.com/wangshub/wechat_jump_game)

**Comment by abcd106** [comment]
在命令行显示adb不是内部命令，好无奈啊

**Comment by 201419** [comment]
@abcd106 没有配置环境变量的话，1、去配置环境变量，2、去具体的文件夹运行命令
