### ISSUE TITLE
锤子坚果Pro2 出现一下错误 cannot identify image file './autojump.png'

### ISSUE THREAD

**Issue by c81113418** [wangshub/wechat_jump_game#313]
=====
Screen: Physical size: 1080x2160
Density: Physical density: 400
DeviceType: OS105
=====
List of devices attached
fe92c819        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 234, in <module>
    main()
  File "wechat_jump_auto.py", line 221, in main
    im = Image.open('./autojump.png')
  File "C:\Python\Python36\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by Pesdestrian** [comment]
同样的问题

**Comment by fgq1021** [comment]
同样的问题

**Comment by c81113418** [comment]
@fgq1021 @Pesdestrian   
将pull_screenshot改为下面这样。
os.system('adb shell screencap -p /sdcard/autojump.png')
os.system('adb pull /sdcard/autojump.png .')


我的是这样改的 现在好了
