### ISSUE TITLE
小米6 程序一直运行，但是不蓄力也不跳动

### ISSUE THREAD

**Issue by vipmike007** [wangshub/wechat_jump_game#315]
我的小米6，程序一直在跑，但是程序上的人人一直不动，不蓄力也不跳动

**Comment by vipmike007** [comment]
![image](https://user-images.githubusercontent.com/869898/34461656-d428acf0-ee6a-11e7-981c-03021a2fc379.png)

**Comment by vipmike007** [comment]
连接是成功的，跑wecahat_jump_py3.py 可以得到截图
![image](https://user-images.githubusercontent.com/869898/34461660-fe802d3e-ee6a-11e7-8adf-c9e944714fba.png)

**Comment by wjzhangcsu** [comment]
这个命令在小米手机上是需要root权限的，如果是早期的安卓的话可能就可以

**Comment by yulindyy** [comment]
开发者选项里面,,模拟触摸要开启

**Comment by seclion** [comment]
需要登陆小米账号，然后开启USB调试（安全设置）

**Comment by vipmike007** [comment]
开启了USB调试， 没有root ,我觉得调试又不是用其他程序改别的程序应该不需要root 吧。 @yulindyy 说的模拟触摸我在开发者选项里没看到。

**Comment by skylinebin** [comment]
开启USB调试（安全设置）,需要使用流量，wifi好像不行

**Comment by vipmike007** [comment]
@yulindyy 谢谢，你是对的，打开允许调试（模拟触摸）可以

**Comment by vipmike007** [comment]
可以跳了，但是也就只能跑20多步骤

**Comment by yulindyy** [comment]
需要再改几行代码
wechat_jump_auto.py:

函数def main():
#jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
jump(abs(board_x - piece_x)*2.0/math.sqrt(3.0))

函数def find_piece_and_board(im):
#piece_x = (piece_x_sum / piece_x_c)
piece_x = (piece_x_sum / piece_x_c) - 2

config.json:
"press_coefficient": 1.46,
不懂再问

**Comment by wayss000** [comment]
同问题，打开允许调试（模拟触摸）可以了，多谢。

**Comment by Dielizhijie** [comment]
我打开了允许调试（模拟触摸），还是不可以
