### ISSUE TITLE
是一定要用anaconda吗？能不能用原生的python解释器

### ISSUE THREAD

**Issue by Weilet** [wangshub/wechat_jump_game#317]

**Comment by gaieepo** [comment]
没有必须要用anaconda 请详细描述你遇到的问题

**Comment by Weilet** [comment]
我在命令行输入：python python wechat_jump_auto.py
返回： File "wechat_jump_auto.py", line 8, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'
#大大我是python萌新，真的不太懂嘤嘤嘤

**Comment by skylinebin** [comment]
@Weilet 需要安装 PIL库 （用pip 可以直接装 pip install PIL）

**Comment by Weilet** [comment]
@skylinebin thx

**Comment by mozjiang** [comment]
好像这个 issue 可以关闭了？@Weilet
