### ISSUE TITLE
win10 cmd中运行pip install -r requirements.txt报错Traceback (most recent call last):。哪位遇到过我这样的问题吗

### ISSUE THREAD

**Issue by Ljhhhhhh** [wangshub/wechat_jump_game#318]
## win10 cmd中运行pip install -r requirements.txt报错Traceback (most recent call last):，具体如图
![tim 20171231210055](https://user-images.githubusercontent.com/30891695/34461734-b52613ee-ee6d-11e7-811b-985ee99e6e87.png)
## requirements.txt文件内容是这样的，已经改成utf-8编码
![tim 20171231210129](https://user-images.githubusercontent.com/30891695/34461738-c9f42900-ee6d-11e7-855c-afbd1c91554d.png)
求解答，谢谢

**Comment by aloneZERO** [comment]
能把错误信息截全一下吗？

**Comment by Trency** [comment]
@Ljhhhhhh
我和你报同样的错，我用Atom打开requirements.txt后，发现文件有很多空的小方块，删去后，重新执行，就可以了。

**Comment by gaieepo** [comment]
请把错误信息全部放出来

**Comment by Mersone** [comment]
同样的问题啊，你现在解决了吗？

**Comment by Mersone** [comment]
![tim 20180102205221](https://user-images.githubusercontent.com/24414111/34484303-d7c7fede-effe-11e7-9097-65e164c8c8f4.jpg)

**Comment by Ljhhhhhh** [comment]
报错的完整截图
![tim 20180103190519](https://user-images.githubusercontent.com/30891695/34518168-2a8d85b6-f0b9-11e7-994a-ea1129365abf.png)
我的文件夹内容
![tim 20180103190542](https://user-images.githubusercontent.com/30891695/34518169-2afc27d2-f0b9-11e7-827f-962146b5782c.png)

**Comment by gaieepo** [comment]
@F-loat 看一下这个问题 你有遇到过么 我没有win的机器

**Comment by F-loat** [comment]
看起来还是编码的问题，cmd 和 powershell 都会报这个错吗

**Comment by aloneZERO** [comment]
@Mersone 你的是权限问题啊，文件夹拒绝访问。试试用管理员身份登录，或者右键`->`**以管理员权限**运行cmd`->`执行pip命令安装依赖库
