### ISSUE TITLE
三星Note8的启动配置。

### ISSUE THREAD

**Issue by xuyanatsyxl** [wangshub/wechat_jump_game#319]
=====
Screen: Physical size: 1440x2960
Density: Physical density: 560
Override density: 640
DeviceType: SM-N9500
=====
List of devices attached

**Comment by rocskyfly** [comment]
you can try:
"under_game_score_y": 460,
"press_coefficient": 1.0935,
"piece_base_height_1_2": 70,
"piece_body_width": 75
}

make sure setting screen resolution is the largest.

**Comment by sailing0505** [comment]
@rocskyfly  provided configure is not working for my note8

**Comment by rocskyfly** [comment]
What’s your phenomenon?

BTW, you should close your Note 8 side panel in settings.

Best Regards
Rocky
