### ISSUE TITLE
两个块之间的距离较近时，误差比较大，如果连续几个块都很近就会挂掉了。

### ISSUE THREAD

**Issue by qiushicai** [wangshub/wechat_jump_game#32]
颜色很类似的时候好像也会有这样的问题？距离远的时候就超完美的！ 小米5：press_time = distance * 1.45

**Comment by binderclip** [comment]
@qiushicai 方便上传一下失败的截图吗

**Comment by qiushicai** [comment]
@binderclip  具体表现就是：块之间距离很近的时候会跳偏，会跳到下一个块的边缘。

**Comment by wangshub** [comment]
@binderclip 我把你加进Collaborators啦，希望多多支持维护 ～

**Comment by MrHwq** [comment]
自动运行，还有手动运行都是有偏差的，看规律总是更近，我把auto.py增加了下距离
        board_y += 30
        if piece_x > board_x:
            board_x -= 30
        else:
            board_x += 30
        jump(math.sqrt(abs(board_x - piece_x) ** 2 + abs(board_y - piece_y) ** 2))
现在运行基本是在中间，可以自己一直跳

**Comment by binderclip** [comment]
准备去把计算出来的结果在图上画下来，好看实际效果

**Comment by binderclip** [comment]
@MrHwq 之前坐标取的似乎有点 bug，改了之后现在好一些了，就不用做修正了。另外现在也把测量的坐标在图上画线保存了，可以帮助 debug。
