### ISSUE TITLE
我的华为平板不能运行，报找不到图片

### ISSUE THREAD

**Issue by lusongcai** [wangshub/wechat_jump_game#320]
Screen: Physical size: 1200x1920
Density: Physical density: 240
DeviceType: HUAWEI M2-A01W
# 下面是报错信息
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 234, in <module>
    main()
  File "wechat_jump_auto.py", line 221, in main
    im = Image.open('./autojump.png')
  File "/home/lsc/.local/lib/python3.5/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by lee6256** [comment]
def pull_screenshot():
    # process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
    # screenshot = process.stdout.read()
    # if sys.platform == 'win32':
    #     screenshot = screenshot.replace(b'\r\n', b'\n')
    # f = open('autojump.png', 'wb')
    # f.write(screenshot)
    # f.close()
    #使用了下面两行代码
    os.system('adb shell screencap -p /sdcard/1.png')
    os.system('adb pull /sdcard/1.png autojump.png')

**Comment by lee6256** [comment]
def pull_screenshot():
    # process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
    # screenshot = process.stdout.read()
    # if sys.platform == 'win32':
    #     screenshot = screenshot.replace(b'\r\n', b'\n')
    # f = open('autojump.png', 'wb')
    # f.write(screenshot)
    # f.close()
    #使用下面的两行代码截图和拉取图片
    os.system('adb shell screencap -p /sdcard/temp.png')
    os.system('adb pull /sdcard/temp.png autojump.png')
