### ISSUE TITLE
autojump图片无法打开，，怎么回事Ubuntu

### ISSUE THREAD

**Issue by xinca-liu** [wangshub/wechat_jump_game#324]
=====           
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: NX529J
=====
List of devices attached 
37fd833	device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 234, in <module>
    main()
  File "wechat_jump_auto.py", line 221, in main
    im = Image.open('autojump.png')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'autojump.png'

**Comment by wangzihan424** [comment]
将pull_screenshot改为下面这样。
os.system('adb shell screencap -p /sdcard/autojump.png')
os.system('adb pull /sdcard/autojump.png .')

**Comment by gaieepo** [comment]
@xinca-liu 哈哈正巧需要linux测试 试试取消pull screenshot里面的if条件 也就是说需要一下\r\n到\n的转换 应该就可以了

**Comment by F-loat** [comment]
python3的话试下参考 [这个](https://github.com/wangshub/wechat_jump_game/pull/325/files) 修改

**Comment by shekang** [comment]
同问。。 改了之后执行`python wechat_jump_auto.py` 还是报错 autojump.png 也损坏

**Comment by F-loat** [comment]
@shekang 你是什么系统，python版本是什么

**Comment by hauyi** [comment]
Load config file from E:\python\wechat_jump_game-master/config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
=====
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: m1 metal
=====
List of devices attached
A10ABNM92DAE    device

Traceback (most recent call last):
  File "E:\python\wechat_jump_game-master\wechat_jump_auto.py", line 236, in <module>
    main()
  File "E:\python\wechat_jump_game-master\wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "E:\python\articalSpider\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'
============================================================
win10 系统 python 3.6   楼上改动pull_screenshot的方法都试了没有用？求解

**Comment by F-loat** [comment]
@hauyi autojump.png 这个文件是否存在，大小是否为0

**Comment by gaieepo** [comment]
@hauyi 两种方法都没有用？那应该是你哪个步骤有问题的 请试着手动打开图片

**Comment by hauyi** [comment]
@F-loat 文件存在且大小为14kb 无法手动打开图片

**Comment by hauyi** [comment]
@F-loat @gaieepo 我换了个华为的手机，可以跑起来了，用的是
os.system('adb shell screencap -p /sdcard/autojump.png')
os.system('adb pull /sdcard/autojump.png .')
其余没测试
原魅族手机，都不行。

**Comment by F-loat** [comment]
@hauyi 嗯，这个兼容处理我们测试后完善一下
