### ISSUE TITLE
跳一步就死了。。。

### ISSUE THREAD

**Issue by wangzihan424** [wangshub/wechat_jump_game#327]
2024 KB/s (135932 bytes in 0.065s)
('scan_start_y: ', 157)
(1514727842, 0, 0, 0, 0)
adb shell input swipe 552 496.61171875 552 496.61171875 200
2059 KB/s (135932 bytes in 0.064s)
('scan_start_y: ', 157)
(1514727845, 0, 0, 0, 0)
adb shell input swipe 552 496.61171875 552 496.61171875 200
1881 KB/s (135932 bytes in 0.070s)
('scan_start_y: ', 157)
(1514727847, 0, 0, 0, 0)
adb shell input swipe 552 496.61171875 552 496.61171875 200
永远不会变这是咋回事啊？

**Comment by chenjiandongx** [comment]
请使用最新版本的代码
