### ISSUE TITLE
求分数的字体文件或者0~9的mask图

### ISSUE THREAD

**Issue by QuantumLiu** [wangshub/wechat_jump_game#328]
我要训练一个CNN来识别分数，实现指定分数停止

**Comment by F-loat** [comment]
![7](https://user-images.githubusercontent.com/16759376/34461992-952b6394-ee74-11e7-95f6-bd9c875c656e.png)
![8](https://user-images.githubusercontent.com/16759376/34461993-9746aef4-ee74-11e7-9ae2-257f19f69b45.png)
![9](https://user-images.githubusercontent.com/16759376/34461994-97c5fcd6-ee74-11e7-90b7-b3e905455a90.png)
![0](https://user-images.githubusercontent.com/16759376/34461995-9842cf7c-ee74-11e7-848e-b46a4144b6b6.png)
![1](https://user-images.githubusercontent.com/16759376/34461996-98c33126-ee74-11e7-8c6a-b250b2fa608f.png)
![2](https://user-images.githubusercontent.com/16759376/34461997-9986f372-ee74-11e7-9057-2785df0d04e7.png)
![3](https://user-images.githubusercontent.com/16759376/34461998-9a8a8fae-ee74-11e7-85a9-540603c32af8.png)
![4](https://user-images.githubusercontent.com/16759376/34461999-9b00a072-ee74-11e7-8eb7-93da01939b93.png)
![5](https://user-images.githubusercontent.com/16759376/34462000-9b734406-ee74-11e7-9ae9-2de953e148ed.png)
![6](https://user-images.githubusercontent.com/16759376/34462001-9c36bdb4-ee74-11e7-87a9-c1d65fd46af7.png)

**Comment by QuantumLiu** [comment]
@F-loat 老哥你这不是他的字体，我怕不行

**Comment by F-loat** [comment]
[num.zip](https://github.com/wangshub/wechat_jump_game/files/1595205/num.zip)

**Comment by F-loat** [comment]
可以直接发压缩包的吗。。

**Comment by gaieepo** [comment]
@QuantumLiu 字体应该是固定的而且是固定位置的吧 占据特定的格子 这个简单问题 应该不需要训练神经网络

**Comment by QuantumLiu** [comment]
@F-loat 谢谢！

**Comment by F-loat** [comment]
没事 ：）
