### ISSUE TITLE
【需求】自动识别井盖、播放器、便利店图标并停留3秒

### ISSUE THREAD

**Issue by ZedeX** [wangshub/wechat_jump_game#331]
加分项，做个新feature。

另外，药瓶盖等小的面积还是容易miss。

**Comment by VitalyAnkh** [comment]
这个不需要。使用时停一秒就自动加分了，不需要改程序。你用程序跳过吗

**Comment by gaieepo** [comment]
一秒已经可以自动加分

**Comment by ZedeX** [comment]
试过的，有miss，可能是1秒的误差，调整到1.2-1.3就好了

**Comment by gaieepo** [comment]
@ZedeX 大概miss概率是多少可以测试一下吗？我自己的这边是没有看到miss的 可能是执行效率问题
@F-loat @wangshub 这个可以标一下测试相关的tag

**Comment by ZedeX** [comment]
@gaieepo 重新拉了一下代码，看到time.sleep(random.uniform(1.2, 1.4))这次没有miss了，之前(1.0, 1.1)的时候会抽风。

**Comment by Sowevo** [comment]
延时太小还会导致动画没有播放完影响下一步的识别

**Comment by gaieepo** [comment]
这个项目想覆盖的面太大 开发的几个人也管不过来所有情况 很多外在问题都会影响程序的运行 大家理解一下

**Comment by ZedeX** [comment]
理解，close没问题。而且已经fix了。
