### ISSUE TITLE
“或许正确”的算法改进

### ISSUE THREAD

**Issue by Vg1ee** [wangshub/wechat_jump_game#334]
由于微信算法问题，即使上一跳跳歪了，拐弯后会自动回正，这种情况下跳跃距离不应该以两点实际距离计算。

![github](https://user-images.githubusercontent.com/19946467/34462117-2bfebd32-ee77-11e7-950b-c507c5b772bd.jpg)
假设小人在O点上，A点为目标点，实际跳跃距离应为OB，而非AO。
红色参考线与实际跳跃方向平行。蓝色参考线为直角坐标系。
由于红色参考线与X轴夹角恒定为∠BOX，可算出三角形AOB各内角。又已知AO边长，根据正弦定理可算出OB为实际跳跃距离。

如有错误欢迎指正，由于不会py只能帮到这里了。

**Comment by AlPha5130** [comment]
我每次挂掉都是这种情况，附图
![1514729567_d](https://user-images.githubusercontent.com/34984380/34462335-c3027f0c-ee7c-11e7-977f-2cb7a4973af2.png)
以及类似情形
![1514729443_d](https://user-images.githubusercontent.com/34984380/34462393-d2732f12-ee7d-11e7-96c8-04e9914fa26f.png)
![1514729531_d](https://user-images.githubusercontent.com/34984380/34462399-f9cf500e-ee7d-11e7-9f0c-2d6713a87816.png)
