### ISSUE TITLE
关于三星s8

### ISSUE THREAD

**Issue by fullstackoverflow** [wangshub/wechat_jump_game#335]
参数怎么都调不对一看定位错误都是在右侧边缘，在设置里关闭曲面侧屏就行了，我的配置
    {
        "under_game_score_y": 460, 
        "press_coefficient": 1.365, 
        "piece_base_height_1_2": 70, 
        "piece_body_width": 75
    }

**Comment by NoBey** [comment]
@fullstackoverflow  这个是正解 关闭曲面侧屏

**Comment by chxpu** [comment]
请问swipe参数如何设置，我的曲面侧屏已经关闭，配置：
{
"under_game_score_y": 460,
"press_coefficient": 1.365,
"piece_base_height_1_2": 70,
"piece_body_width": 75
}
目前最高100跳

**Comment by fullstackoverflow** [comment]
@chxpu swipe参数应该是再来一局按钮的位置，我用的是默认的没什么问题，具体你可以截个图看看位置对不对，press_coefficient参数我调到1.37可以跳到1600

**Comment by chxpu** [comment]
@fullstackoverflow 好的 谢谢，我现在用这个配置跳了800
config = {
    "under_game_score_y": 460,
    "press_coefficient": 1.4333,
    "piece_base_height_1_2": 70,
    "piece_body_width": 75,
    # "swipe": {"x1": 320,"y1": 410,"x2": 320,"y2": 410}
}
