### ISSUE TITLE
pip install失败 提示编码错误

### ISSUE THREAD

**Issue by zhouziliang** [wangshub/wechat_jump_game#339]
pip install pillow显示UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
在Python27\Lib\site-packages下创建了sitecustomize.py也不行
显示'import sitecustomize' failed; use -v for traceback
重装python2.7也不行

**Comment by 7449** [comment]
将编码改为 UTF-8

**Comment by zhouziliang** [comment]
已经将import sys
sys.setdefaultencoding(‘utf8’)写入sitecustomize.py
但显示import failed
