### ISSUE TITLE
下载的最新代码，不能找到autojump.png

### ISSUE THREAD

**Issue by wangtingit** [wangshub/wechat_jump_game#347]
Screen:
Density:
DeviceType:
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
=====
List of devices attached
84dcc388        device

error: unknown host service
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "C:\Users\wt\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by westinyang** [comment]
![default](https://user-images.githubusercontent.com/4905028/34462453-926a3990-ee7f-11e7-9df0-50336444a418.png)

**Comment by wangtingit** [comment]
搞定了 360把5037端口占了导致adb shell error: unknown host service 看看5037端口被谁占了杀死 就行了

**Comment by yuanhuikai** [comment]
我也遇见了这个问题，运行wechat_jump_auto的时候，报错，win环境，360我也关闭了。请问该怎么办啊

**Comment by yuanhuikai** [comment]
![default](https://user-images.githubusercontent.com/7391649/34462685-67eb4498-ee84-11e7-8967-5578b101c920.PNG)

**Comment by ant1s** [comment]
我也遇到了，我的环境是win10 64位，应该是保存png格式的原因，我把
if sys.platform == 'win32':
    #   screenshot = screenshot.replace(b'\r\n', b'\n')
这两行注释了也不对，最后把整个函数替换成
os.system('adb shell /system/bin/screencap -p /sdcard/screenshot.png')
os.system('adb pull /sdcard/screenshot.png ./autojump.png')
解决问题
没有在其他手机上测试，有可能会提示/sdcard/这个路径找不到，可以根据自己的情况修改

**Comment by yuanhuikai** [comment]
@ant1s 可以了。

**Comment by ccinside** [comment]
@ant1s 替换整个函数，请问大佬是怎么操作呀？

**Comment by ant1s** [comment]
@ccinside 就是把pull_screenshot的函数定义改成那两行

**Comment by xdbaqiao** [comment]
改一下 这句试试 screenshot = screenshot.replace(b'\r\r\n', b'\n')，我这改完之后运行正常了，我提交了一个 PR

**Comment by PTChenrr** [comment]
@ant1s 刚试了可以 谢谢

**Comment by findfz** [comment]
win 7 x64,Samsung a5,截图失败了么？
Load default config
226.15384615384608 0.06074766355140192 0.8392156862745098
140 142 149
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen: 
Density: 
DeviceType: 
OS: win32
Python: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
**********
Traceback (most recent call last):
  File "C:/Users/win/Desktop/wechat_jump_game-master/wechat_jump_auto.py", line 360, in <module>
    main()
  File "C:/Users/win/Desktop/wechat_jump_game-master/wechat_jump_auto.py", line 347, in main
    im = Image.open('./autojump.png')
  File "C:\Users\win\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by ccinside** [comment]
tks！
