### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by daiqiang838** [wangshub/wechat_jump_game#357]
![image](https://user-images.githubusercontent.com/16677236/34462759-c8ec8bac-ee85-11e7-929d-9b7e860edba7.png)

**Comment by yuanhuikai** [comment]
我也有这个问题。

**Comment by Tonysmark** [comment]
同上

**Comment by yuanhuikai** [comment]
@Tonysmark   @daiqiang838  用管理员权限， 参看#347解决方案

**Comment by chilyoniki** [comment]
我也是同样问题macbook pro+魅族mx5

**Comment by herojijiangfan** [comment]
截图方法有误

**Comment by wangshub** [comment]
已修正
