### ISSUE TITLE
红米Note3 可以，已经800，还在继续

### ISSUE THREAD

**Issue by lusongcai** [wangshub/wechat_jump_game#365]
config配置
{
"under_game_score_y": 200,
"press_coefficient": 2.329,
"piece_base_height_1_2": 13,
"piece_body_width": 47
}

再在190行后面插入
if (board_y > 580):
board_y = 566
以上600分还在继续

**Comment by forilux** [comment]
请问
再在190行后面插入
if (board_y > 580):
board_y = 566
是加哪的？加到AUTO文件里运行闪过，不对。
