### ISSUE TITLE
jump_auto代码正常运行，但是不跳

### ISSUE THREAD

**Issue by CodeDogandCat** [wangshub/wechat_jump_game#366]
如果你的脚本无法工作，上报issue时请copy如下信息:
=====           
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 4LTE
=====
List of devices attached 
26xxxxxx	device

scan_start_y:  690
1514737978 424.1214374225527 1060 788.5 849.6259388089819
E:\adb\adb shell input swipe 320 410 320 410 585

**Comment by liuleileis** [comment]
我的开始也不跳，后来发现开发者选项里的“USB调试（安全选项）”没开。手机不允许模拟点击。开启后就可以了。
