### ISSUE TITLE
保存到电脑的图片变成横向的。。。

### ISSUE THREAD

**Issue by Evan-Huang** [wangshub/wechat_jump_game#368]
图片变成横向展示，导致坐标计算出错。
![image](https://user-images.githubusercontent.com/15259409/34463075-c5d06216-ee8c-11e7-90b5-a8573f4cd5ca.png)

**Comment by daiqiang838** [comment]
+1

**Comment by kennypku** [comment]
在程序里手动将图片旋转90度可处理 im.transpose(Image.ROTATE_90)
