### ISSUE TITLE
提供三星s7e参数供参考

### ISSUE THREAD

**Issue by Jun0413** [wangshub/wechat_jump_game#376]
- 设备信息：
Screen: Physical size: 1440x2560
Override size: 1080x1920
Density: Physical density: 640
Override density: 480
DeviceType: SM-G9350

- 文件所在路径：./config/2560x1440/config.json

- 文件内容：

{
    "under_game_score_y": 384,
    "press_coefficient": 1.36,
    "piece_base_height_1_2": 95,
    "piece_body_width": 102,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}

- 另外，我关闭了侧屏不知道这个有没有帮助。刷到了快600分但是数据线不是原配，所以不稳定掉线了。

**Comment by 4396NeverBeSlaves** [comment]
我开的1080p分辨率直接把1920*1080的复制过去用了，注意要把曲面工具关掉，之前不知道是不是没有关一直跳得不对
{
    "under_game_score_y": 300,
    "press_coefficient": 1.392,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1602
    }
}
