### ISSUE TITLE
老哥能教教我怎么使用么？

### ISSUE THREAD

**Issue by DevXue** [wangshub/wechat_jump_game#38]
老哥啊！！  我是安卓开发者，  不会Python，  能不能教教我第一步该咋，第二部该咋？  我现在把Python安装到Windows上了，环境变量也配置了， 接下来该咋搞？  完全没有头绪啊！！   谢老哥。

**Comment by wangshub** [comment]
你需要先装下库 `pip install -r requirements.txt` @897902334

**Comment by 897902334** [comment]
@wangshub    老哥啊！！pip install -r requirements.txt这个命令直接在cmd中执行么？  报错命令找不到！

**Comment by cjy825** [comment]
windows问题一大推 各种库装不上  我还是跑到ubuntu用的  自带python27  安装库也很快几条pip install 就好了

**Comment by 897902334** [comment]
@cjy825 老哥，如果用Windows的话，就像作者说的 pip install -r requirements.txt  这个是在cmd中执行么？

**Comment by wangshub** [comment]
是啊 python在 mac和ubuntu还是比较容易装环境的

**Comment by 897902334** [comment]
谢谢！！   我去研究研究ubuntu去！

**Comment by wangshub** [comment]
祝你折腾的过程中能够玩的开心～ @897902334

**Comment by cjy825** [comment]
建议把def backup_screenshot(ts):注释掉  这个是作者调试用的 咱们不需要 还有倒数第四行的backup_screenshot(ts)

**Comment by se4** [comment]
老哥，安卓开发者完全可以考虑在 Xposed框架下实现啊 💯  @897902334

**Comment by 897902334** [comment]
@se4   老哥， 你用这个Xposed搞出来了？？？   能教教我么？？

**Comment by se4** [comment]
😄没没没~我不懂安卓开发，只会一点点python。小游戏出来的第一时间，我就考虑抓包看看有没有游戏相关的数据比如距离信息在封包里，结果什么都没看到。其他的办法，我能想到的有 (1)截图，图像处理计算后模拟按压 (2) Xposed

**Comment by 897902334** [comment]
@se4   谢啦老哥，  我还是继续研究Python吧！

**Comment by F-loat** [comment]
@se4 知乎上有篇文章《微信跳一跳万分攻(作)略(弊)》就是抓包实现的

**Comment by se4** [comment]
@F-loat  谢谢老哥，原来是这样的！

> 后来抓包观察到破纪录以后发完settlement包紧接着的getFriendScore返回的个人信息已经是更新的。这个settlement包数据加密了，我只好去找小程序的源码。通过搜索引擎找到有关微信小程序包wxapkg的解包方法，找到了游戏的js文件。然后就在混淆的代码里面找到发请求的地方……
