### ISSUE TITLE
【bug】坚果pro会一直蓄力，不会起跳

### ISSUE THREAD

**Issue by wsmwzms123** [wangshub/wechat_jump_game#380]
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
scan_start_y:  690

**Comment by MrLevo520** [comment]
看issue 301，也是坚果，已解决

**Comment by sbwzy** [comment]
参数没改，关闭了大爆炸功能后就可以正常使用

**Comment by wsmwzms123** [comment]
确实，关闭了大爆炸功能就可以了。
