### ISSUE TITLE
求 红米NOTE4X 设置

### ISSUE THREAD

**Issue by forilux** [wangshub/wechat_jump_game#383]
NOTE3
config配置
{
"under_game_score_y": 200,
"press_coefficient": 2.329,
"piece_base_height_1_2": 13,
"piece_body_width": 47
}

再在190行后面插入
if (board_y > 580):
board_y = 566
以上600分还在继续

不明白190行后面是放哪？我放在AUTO文件里，不对。

**Comment by bwdrea** [comment]
同红米note4x，我用的是第一天的那个代码改的，和现在的不太一样，能到1000
under_game_score_y = 300
press_coefficient = 1.393
piece_base_height_1_2 = 25
piece_body_width = 80
pull_screenshot函数改为下面的样子
def pull_screenshot():
    os.system('adb shell screencap -p /sdcard/1.png')
    os.system('adb shell screencap -p /sdcard/1.png')
    os.system('adb pull /sdcard/1.png .')
