### ISSUE TITLE
求个小米5S的能上2000的配置

### ISSUE THREAD

**Issue by zhoudanwei** [wangshub/wechat_jump_game#385]
目前在用小米5的配置,虽然说米5和5s本质上没啥区别,但是跳不到高分呀,求大神给个能上2000的配置,1000也行,先谢谢啦...

**Comment by Ryan-Miao** [comment]
https://github.com/Ryan-Miao/wechat_jump_game/commit/0e27d4f29b0ee8a64b33e312f37c17b701849801

**Comment by zhoudanwei** [comment]
谢谢大大呢,辛苦了

**Comment by Jarvis03** [comment]
可以使用 ，谢谢啦

**Comment by bin520ss** [comment]
2000不行啊。。

**Comment by zhoudanwei** [comment]
我跑了4000,你去他那里下专版
