### ISSUE TITLE
图片找不到 OSError

### ISSUE THREAD

**Issue by xuess** [wangshub/wechat_jump_game#386]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: HTC Butterfly
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
**********
List of devices attached
HC3ANPN00309    device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "C:\Python3\lib\site-packages\pillow-4.3.0-py3.6-win32.egg\PIL\Image.py", line 2572, in open
OSError: cannot identify image file './autojump.png'

**Comment by nanyang24** [comment]
虚拟机模拟也遇到这个问题，求解

**Comment by VincentLieie** [comment]
+1

**Comment by F-loat** [comment]
[这个](https://github.com/wangshub/wechat_jump_game/blob/c2d162e2bc0acb0b6773b50007801c0af3a738cf/wechat_jump_auto.py)应该可以用，后续会在 #325 继续更新

**Comment by nanyang24** [comment]
@F-loat 模拟器可以吗

**Comment by xuess** [comment]
@F-loat 问题解决
