### ISSUE TITLE
小白如何从0到运行代码跑出1000+分，1280*720参数更新，跳至2500分

### ISSUE THREAD

**Issue by zsy2504** [wangshub/wechat_jump_game#389]
首先表示一下对创始人的崇拜，仅两个小时完工，而我就实现花了仅10个小时，不过算是一个好的开始。

言归正传，
step1 装Python，不用详细说了，winxp，装的3.4版本
step2 找出手机的USB 调试模式。华为手机，设置——关于手机——版本号，连击7次，出现：开发人员选项，打开usb调试
step3 下载ADB驱动，这块不太熟，浪费了很多时间，给出的adb在winxp上不支持，然后各种找，找了很多很多版本，也不知道哪个起作用了，装好之后不会用，又浪费很多时间，终于在百度上找到了方法，原来是【环境变量】没有设置，在我的电脑——属性——高级——环境变量——系统变量中找到path增加c：\adb就好了(不一定是c:\adb，而是你的adb文件夹的位置，比如你放在E:\wechat_jump_game\adb下的)，然后运行cmd，输入adb shell验证
step4 下载代码。下载自动和手动代码，根据分辨率下载配置文档，下载requirements.txt文件。
step4 安装依赖。运行cmd，输入python -m pip install -r requirements.txt，安装需要的库
step5 个别情况报错，提示No module named 'PIL' ，参考 #241装一下
完成以上步骤，基本完工了，然后就可以运行代码了，我运行手动版，需要用鼠标点移动前后位置，大伙儿给出的参数很准，每次都能调到最中心，加分很多，100分跳8次就可以达到，很好玩。自动版现在还有个问题没解决，解决好了再跟大家说。

2018啦，实现python的第一个项目，尽管用了很长时间，但是很开心，愿大家新的一年梦想都能实现！

1.1 更新参数 piece_base_height_1_2为20，由700多跳到1500多
1.2 更新参数 press_coefficient为2.0988，跳到2500多

**Comment by Vg1ee** [comment]
感觉Issues被一群平时不敲代码的小白攻占了

**Comment by hakrtt** [comment]
我觉得这个比较容易
https://github.com/hakrtt/wechatgame

**Comment by zsy2504** [comment]
@Vg1ee 哈哈，确实是个好项目

**Comment by zsy2504** [comment]
@hakrtt 确实很全，早点看到就好了，谢谢！

**Comment by hyzaoia** [comment]
环境变量里的path添加的值不一定是c:\adb，而是你的adb文件夹的位置
比如我是放在E:\wechat_jump_game\adb下的
