### ISSUE TITLE
老哥，依赖脚本模块缺少opencv的

### ISSUE THREAD

**Issue by Zane96** [wangshub/wechat_jump_game#39]
如果你遇到这个问题：no named module cv2
使用：pip install opencv-python

**Comment by wangshub** [comment]
装上了吗？ @Zane96

**Comment by Zane96** [comment]
装上了！～帮助一下其他人，依赖包里面可以把opencv的加上

**Comment by Zane96** [comment]
@wangshub

**Comment by wangshub** [comment]
OK @Zane96

**Comment by Zane96** [comment]
@wangshub 
Successfully installed opencv-python-3.4.0.12
 Zane@Hello-World  ~/programming/AndroidProject2/wechat_jump_game   master ●  python3 wechat_jump.py
Traceback (most recent call last):
  File "wechat_jump.py", line 7, in <module>
    import cv2
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cv2/cv2.cpython-35m-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cv2/cv2.cpython-35m-darwin.so: mach-o, but wrong architecture
	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cv2/cv2.cpython-35m-darwin.so: mach-o, but wrong architecture

老哥，装好了之后，运行是这个情况。。咋回事

**Comment by Zane96** [comment]
@wangshub 只能运行在2.7吗

**Comment by Zane96** [comment]
抱歉没看到py3的脚本。运行了，但是distance一直是0.。。。

**Comment by 897902334** [comment]
老哥 能教教我么？   我是Phtyon小白啊！   我把Phthon装上了，环境变量配置了，在cmd执行 pip install -r requirements.txt 这个报错命令找不到！  咋搞呢？ 装的是2.7

**Comment by Zane96** [comment]
错误什么。。你贴出来啊

**Comment by 897902334** [comment]
@Zane96 


日了狗了，为什么不能上传tu图片  上传总是失败！！！

**Comment by Zane96** [comment]
copy文字

**Comment by 897902334** [comment]
Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pip install -r requirements.txt
'pip' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator> python
Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install -r requirements.txt
  File "<stdin>", line 1
    pip install -r requirements.txt
              ^
SyntaxError: invalid syntax
>>>

**Comment by Zane96** [comment]
@wangshub 不知道为啥。计算出来的distance一直是0.我连系数都不用修正了，反正都是0.
小米6，MIUI9

**Comment by Zane96** [comment]
@897902334 pip是一个单独的包管理工具，你需要去下载

**Comment by 897902334** [comment]
非常感谢你，我去下载去！！

**Comment by Zane96** [comment]
@wangshub 就一直原地跳。。

**Comment by 897902334** [comment]
Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>python get-pip.py
python: can't open file 'get-pip.py': [Errno 2] No such file or directory

C:\Users\Administrator>
@Zane96    我在命令中下载么？他提示这个

**Comment by Zane96** [comment]
@wangshub 老哥。猛的发现我玩法弄错了。。我点了两次都是在对面格子点的。。

**Comment by Zane96** [comment]
@897902334 http://blog.csdn.net/liuchunming033/article/details/39578019

**Comment by 897902334** [comment]
@Zane96 Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>python -m pip install -U pip
D:\Python27\python.exe: No module named pip

C:\Users\Administrator>  按照帖子搞得  提示这个了。

**Comment by F-loat** [comment]
[Installation](https://pip.pypa.io/en/stable/installing/)，下载 `get-pip.py` 这个文件，然后执行就行

**Comment by 897902334** [comment]
@F-loat   老哥，当我点击 get-pip.py的时候  出现了这个页面
#!/usr/bin/env python
#
# Hi There!
# You may be wondering what this giant blob of binary data here is, you might
# even be worried that we're up to something nefarious (good for you for being
# paranoid!). This is a base85 encoding of a zip file, this zip file contains
# an entire copy of pip.
#
# Pip is a thing that installs packages, pip itself is a package that someone
# might want to install, especially if they're looking to run this get-pip.py
# script. Pip has a lot of code to deal with the security of installing
# packages, various edge cases on various platforms, and other such sort of
# "tribal knowledge" that has been encoded in its code base. Because of this
# we basically include an entire copy of pip inside this blob. We do this
# because the alternatives are attempt to implement a "minipip" that probably
# doesn't do things correctly and has weird edge cases, or compress pip itself
# down into a single file.
#
# If you're wondering how this is created, it is using an invoke task located
# in tasks/generate.py called "installer". It can be invoked by using
# ``invoke generate.installer``.

import os.path
import pkgutil
import shutil
import sys
import struct
import tempfile

# Useful for very coarse version differentiation.
PY2 = sys.version_info[0] == 2
PY3 = sys.version_info[0] == 3

if PY3:
    iterbytes = iter
else:
    def iterbytes(buf):
        return (ord(byte) for byte in buf)

try:
    from base64 import b85decode
except ImportError:
    _b85alphabet = (b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                    b"abcdefghijklmnopqrstuvwxyz!#$%&()*+-;<=>?@^_`{|}~")

    def b85decode(b):
        _b85dec = [None] * 256
        for i, c in enumerate(iterbytes(_b85alphabet)):
            _b85dec[c] = i

        padding = (-len(b)) % 5
        b = b + b'~' * padding
        out = []
        packI = struct.Struct('!I').pack
        for i in range(0, len(b), 5):
            chunk = b[i:i + 5]
            acc = 0
            try:
                for c in iterbytes(chunk):
                    acc = acc * 85 + _b85dec[c]

另外 我重新下载了一遍2.7的版本  然后发现Scripts文件夹下有pip.exe文件了

**Comment by F-loat** [comment]
对，新版的自带pip，配置下环境变量就行，[get-pip.py](https://bootstrap.pypa.io/get-pip.py) 这个文件可以直接复制链接下载，用chrome打开会直接显示代码，复制下来粘贴到文件里也行

**Comment by 897902334** [comment]
@F-loat   嗯嗯嗯嗯嗯 老哥， 我把环境变量都配置好了，Python2.7和那个pip也配置到Path中了，  接下来该咋搞呀？？？  求教 谢谢！

**Comment by F-loat** [comment]
@897902334 安装依赖，adb，驱动，打开usb调试，然后执行 `wechat_jump_auto.py` 这个脚本就行，（之前版本 `wechat_jump.py` 是ok的，但是加了opencv后windows好像不兼容

**Comment by 897902334** [comment]
@F-loat ， 嗯嗯  老哥 安装依赖的前提  我要把这个项目下载下来了吧？  比如我下载到了D盘  是不是 pip install -r  D:/ requirements.txt  然后就行了？还有作者说的这个 Python Matplot绘图   这个东西我需要装么？？？

**Comment by F-loat** [comment]
下载下来后，在项目目录里执行 `pip install -r requirements.txt`，Python Matplot 包含在刚刚安装的依赖里了，但是 opencv 目前好像还没（也就是这个issue反馈的问题了

**Comment by 897902334** [comment]
@F-loat   老哥，  我下载下来用啥工具打开啊？？？ 你说的实在项目里面执行？ 咋执行？   用AndroidStudio可以不 ？

**Comment by F-loat** [comment]
@897902334 你下载压缩包的话解压就行，然后在项目文件夹里按 `shift + 鼠标右键`，打开命令行窗口，执行安装依赖和运行的命令就行
``` bash
pip install -r requirements.txt # 安装依赖
python wechat_jump_auto.py # 执行自动识别脚本
```
上面那个没问题的话就ok了，识别不准确的话得自己调下参数，或者用下面的手动脚本
``` bash
pip install opencv-python # 安装opencv
python wechat_jump.py # 执行手动识别脚本
```

**Comment by 897902334** [comment]
@F-loat ，感谢老哥的回答啊，  我正在下载这个openvc的库了，  上一个执行失败了 报错  说是
C:\wechat_jump_game-master>python wechat_jump_auto.py
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 126, in <module>
    main()
  File "wechat_jump_auto.py", line 115, in main
    im = Image.open("./1.png")
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'
我试试你说的另一种方法！

**Comment by F-loat** [comment]
@897902334 adb配置下环境变量吧

**Comment by 897902334** [comment]
@F-loat   我刚刚配置了  还是提醒 adb不是内部命令  下面是我配置后的  在cmd中执行的

(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>adb devices
List of devices attached
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
6494f2e8        device


C:\Users\Administrator>

**Comment by F-loat** [comment]
@897902334 终端关了重开下试试

**Comment by 897902334** [comment]
@F-loat   重开了窗口之后  提示这个 

C:\wechat_jump_game-master>python wechat_jump_auto.py
/sdcard/1.png: 1 file pulled. 1.3 MB/s (58561 bytes in 0.044s)
(1514615358, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
/sdcard/1.png: 1 file pulled. 2.0 MB/s (51498 bytes in 0.025s)
(1514615370, 565, 1138, 788, 1274)
adb shell input swipe 320 410 320 410 363
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
/sdcard/1.png: 1 file pulled. 3.6 MB/s (58728 bytes in 0.016s)
(1514615381, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by F-loat** [comment]
@897902334 这个问题issue里问过好几次了，善用搜索

**Comment by 897902334** [comment]
@F-loat 老哥  我在issues里头看到说是把cp改成copy  但是我改了
他提示这个
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 2.8 MB/s (58728 bytes in 0.020s)
(1514615855, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 2.5 MB/s (58728 bytes in 0.022s)
(1514615866, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 2.4 MB/s (58728 bytes in 0.024s)
(1514615877, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 2.5 MB/s (58728 bytes in 0.023s)
(1514615888, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 2.8 MB/s (58728 bytes in 0.020s)
(1514615899, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 3.5 MB/s (58728 bytes in 0.016s)
(1514615911, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
命令语法不正确。
/sdcard/1.png: 1 file pulled. 1.8 MB/s (58728 bytes in 0.032s)


这是我修改之后的代码
def backup_screenshot(ts):
    # 为了方便失败的时候 debug
    dir_path = 'screenshot_backups/'
    if not os.path.isdir(dir_path):
        os.mkdir(dir_path)
    os.system('copy 1.png {}{}.png'.format(dir_path, ts))

**Comment by F-loat** [comment]
@897902334 cp那行你先注释了吧，不影响的

**Comment by 897902334** [comment]
@F-loat   老哥，这次没有提示任何错误

C:\>cd wechat_jump_game-master

C:\wechat_jump_game-master>wechat_jump_auto.py
/sdcard/1.png: 1 file pulled. 2.6 MB/s (58356 bytes in 0.021s)
(1514616276, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
/sdcard/1.png: 1 file pulled. 2.6 MB/s (58356 bytes in 0.022s)
(1514616287, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
/sdcard/1.png: 1 file pulled. 2.9 MB/s (62975 bytes in 0.021s)
(1514616299, 503, 1003, 433, 1046)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 2.5 MB/s (58740 bytes in 0.022s)


请问接下来咋搞了？？？  开始玩游戏？？？

**Comment by F-loat** [comment]
@897902334 对啊，先开始游戏，再执行脚本

**Comment by 897902334** [comment]
@F-loat   老哥 ，  游戏我先打开的，然后执行的脚本，然后呢？  他自动玩呢？ 还是我自己玩了？  啥反应也没啊? 命令行执行提示这个   一点其他动静也没··
/sdcard/1.png: 1 file pulled. 4.0 MB/s (59073 bytes in 0.014s)
(1514616551, 338, 1109, 788, 1385)
adb shell input swipe 320 410 320 410 735
/sdcard/1.png: 1 file pulled. 2.9 MB/s (58475 bytes in 0.019s)
(1514616562, 338, 1069, 788, 1345)
adb shell input swipe 320 410 320 410 735
/sdcard/1.png: 1 file pulled. 4.2 MB/s (104833 bytes in 0.024s)
(1514616573, 636, 669, 566, 712)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 2.1 MB/s (211926 bytes in 0.098s)
(1514616583, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 2.9 MB/s (211926 bytes in 0.070s)
(1514616594, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 3.0 MB/s (211926 bytes in 0.067s)
(1514616603, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 3.0 MB/s (211926 bytes in 0.067s)
(1514616614, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 3.0 MB/s (211926 bytes in 0.067s)
(1514616625, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200
/sdcard/1.png: 1 file pulled. 5.5 MB/s (211926 bytes in 0.037s)
(1514616636, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200

**Comment by 897902334** [comment]
@F-loat  哈哈哈  老哥   我的安全模式没有打开，他开始跳了  但是控制台提示这个
C:\wechat_jump_game-master>wechat_jump_auto.py
adb: error: remote object '/sdcard/1.png' does not exist
(1514616921, 268, 782, 374, 847)
adb shell input swipe 320 410 320 410 200
adb: error: remote object '/sdcard/1.png' does not exist
(1514616933, 268, 782, 374, 847)
adb shell input swipe 320 410 320 410 200
而且跳的很慢！

**Comment by F-loat** [comment]
@wangshub 你先看看其他issue，可能要开adb的模拟输入什么的
@Zane96 opencv的依赖添加了，这个issue可以关闭了😅

**Comment by 897902334** [comment]
@F-loat 先等等老哥，···     为啥他就跳了一步？  而且很慢！！！

**Comment by F-loat** [comment]
@897902334 储存路径不对吧，你看下手机上截图保存在哪儿了，改下参数

**Comment by 897902334** [comment]
都在SD卡根目录下了，而且我发现项目的部分源码莫名其妙的不见了，我重新下载下来再试试吧！  太感谢你大神！真的非常感谢！

**Comment by 897902334** [comment]
@F-loat   在GitHub上重新下载了一遍项目  报这个错  而且我在项目里头也没有找到这个1.png啊！  手机里头也没有

C:\wechat_jump_game-master>wechat_jump_auto.py
adb: error: remote object '/sdcard/1.png' does not exist
Traceback (most recent call last):
  File "C:\wechat_jump_game-master\wechat_jump_auto.py", line 139, in <module>
    main()
  File "C:\wechat_jump_game-master\wechat_jump_auto.py", line 127, in main
    im = Image.open("./1.png")
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

C:\wechat_jump_game-master>

**Comment by F-loat** [comment]
@897902334 我试试看能不能不把截图保存到手机，直接传到电脑上，这样就没这个问题了

**Comment by 897902334** [comment]
@F-loat  老哥 问题解决了， 把代码里的1.png 全部修改成 test.png就行了！！  谢谢你啦

**Comment by F-loat** [comment]
@897902334 没事，直接保存在linux下没问题，但是windows好像没法直接实现，不弄了先

**Comment by Zane96** [comment]
close吧
