### ISSUE TITLE
如何才能安装依赖程序pip install -r requirements.txt

### ISSUE THREAD

**Issue by TeaApricot** [wangshub/wechat_jump_game#390]
Last login: Mon Jan  1 03:24:31 on ttys000
Cdq-Pro:~ cdq$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Cdq-Pro:~ cdq$

**Comment by soysaucemo** [comment]
运行pip需要在requirements.txt的路径下，否则找不到

**Comment by hakrtt** [comment]
推荐小白用这个https://github.com/hakrtt/wechatgame

**Comment by TeaApricot** [comment]
Last login: Mon Jan  1 08:25:12 on console
Cdq-Pro:~ cdq$ pip install -r requirements.txt
Requirement already satisfied: backports.functools-lru-cache==1.4 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: cycler==0.10.0 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: matplotlib==2.1.1 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: numpy==1.13.3 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: olefile==0.44 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: opencv-python==3.4.0.12 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: Pillow==4.3.0 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pyparsing==2.2.0 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: python-dateutil==2.6.1 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: pytz==2017.3 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: six==1.11.0 in ./anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Cdq-Pro:~ cdq$ 

谢谢,目前是这个情况,是正确还是错误?

**Comment by HJH12315** [comment]
@soysaucemo requirements.txt的路径在哪里？这个text在哪里能下载呢？

**Comment by 918Wu** [comment]
作者的文件不是UTF-8编码，改为UTF-8

**Comment by leegang** [comment]
先cd到你下载的文件路径下

**Comment by wxlzmt** [comment]
如果是网络不好的,建议用国内的源,亲测好使,命令行如下:
```
pip install --index https://mirrors.ustc.edu.cn/pypi/web/simple/ -r requirements.txt
```
