### ISSUE TITLE
首先问题是image读取.png文件出现oserror错误，改了源代码之后方向判断错误

### ISSUE THREAD

**Issue by gjwang-ICME** [wangshub/wechat_jump_game#392]
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: A51
OS: win32
Python: 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
**********
![1514752000_d](https://user-images.githubusercontent.com/31840432/34464139-61d920fa-eeae-11e7-9763-4717234ab1d6.png)
[
![qq 20180101044321](https://user-images.githubusercontent.com/31840432/34464137-53f9a004-eeae-11e7-9b42-dee4dedb594d.png)
](url)

**Comment by soysaucemo** [comment]
把悬浮窗，悬浮球啥的辅助都关掉，再试试

**Comment by ant1s** [comment]
#347 试试这个
