### ISSUE TITLE
自动获取截图出错(含自行测试结果)

### ISSUE THREAD

**Issue by MindsculptorX** [wangshub/wechat_jump_game#394]
**********        
Screen: 
Density: 
DeviceType: 
OS: darwin
Python: 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
**********
报错:
OSError: cannot identify image file

测试:
每次可以截图 但是截下来的图无法打开 会显示:
未能打开文件“autojump.png”，因为它是空的。

我试了一下 如果跳过截图 直接用train_data的当截图的话 是可以跑的 但是也不会有任何反应
不知道可能是哪里的问题?

**Comment by soysaucemo** [comment]
adb devices能不能显示手机？这情况和adb驱动没装一样。

**Comment by MindsculptorX** [comment]
⟹   adb devices
List of devices attached
2cf7c60e	device

查了 能显示的

**Comment by ant1s** [comment]
#347 试试这个
