### ISSUE TITLE
imshow正常，auto截图出错

### ISSUE THREAD

**Issue by ouxiaogu** [wangshub/wechat_jump_game#396]
**********        
Screen: Physical size: 1600x900
Density: Physical density: 240
DeviceType: SAMSUNG-SM-N900A
OS: win32
Python: 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]3, 
**********        
adb 路径已经加到环境变量.

我用wechat_jump.py跑 imshow 正常，这里的路径是  /sdcard/autojump.png
但是在wechat_jump_auto.py跑 的时候 会出现 “OSError: cannot identify image file”
Windows 命令行是能看到devices，但是不能再adb下截图，何解? Thanks!
```shell
C:\Users\ouxiaogu> adb devices
List of devices attached
emulator-5554   device
C:\Users\ouxiaogu> adb -s emulator-5554 shell
shell@hlteatt:/ $ adb shell screencap -p ./autojump.png
adb shell screencap -p ./autojump.png
* daemon not running. starting it now on port 5038 *
* daemon started successfully *
Error opening file: ./autojump.png (Read-only file system)
```

**Comment by ObjLin** [comment]
把电脑用户文件夹也就是 . 管理员获取所有权限，试试
