### ISSUE TITLE
附上python3 mac测试成功代码

### ISSUE THREAD

**Issue by barrer** [wangshub/wechat_jump_game#4]
python2的库mac安装有问题
python3一切完美

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from PIL import Image
import math
import time
import os

def pull_screenshot():
    os.system('adb shell screencap -p /sdcard/1.png')
    os.system('adb pull /sdcard/1.png .')

def jump(distance):
    press_time = distance * 1.35
    press_time = int(press_time)
    cmd = 'adb shell input swipe 320 410 320 410 ' + str(press_time)
    print(cmd)
    os.system(cmd)

fig = plt.figure()
index = 0
cor = [0, 0]

pull_screenshot()
img = np.array(Image.open('1.png'))

update = True 
click_count = 0
cor = []

def update_data():
    return np.array(Image.open('1.png'))

im = plt.imshow(img, animated=True)


def updatefig(*args):
    global update
    if update:
        time.sleep(1.5)
        pull_screenshot()
        im.set_array(update_data())
        update = False
    return im,

def onClick(event):      
    global update    
    global ix, iy
    global click_count
    global cor

    # next screenshot
    
    ix, iy = event.xdata, event.ydata
    coords = []
    coords.append((ix, iy))
    print('now = ', coords)
    cor.append(coords)
    

    click_count += 1
    if click_count > 1:
        click_count = 0
        
        cor1 = cor.pop()
        cor2 = cor.pop()

        distance = (cor1[0][0] - cor2[0][0])**2 + (cor1[0][1] - cor2[0][1])**2 
        distance = distance ** 0.5
        print('distance = ', distance)
        jump(distance)
        update = True
        


fig.canvas.mpl_connect('button_press_event', onClick)
ani = animation.FuncAnimation(fig, updatefig, interval=50, blit=True)
plt.show()
```

**Comment by barrer** [comment]
安装python3  
安装引用库  
`pip3 install matplotlib`  
`pip3 install Pillow`  
然后开始游戏  
然后运行`python3 wechat_jump.py`
点击`目标`点击`黑感叹号`, done！

**Comment by zhuweiyou** [comment]
我的 2.x 各种报错。按照你说的装 3 试一下看看

**Comment by SSSSHIELD** [comment]
分辨率适配有点问题

**Comment by vuuihc** [comment]
input swipe 命令没有反应，搜了一通也没结论，是我手机问题么

**Comment by zhuweiyou** [comment]
成功了，根据我自己的手机调整了一下系数，现在刷到好友第一了。

**Comment by Fennay** [comment]
@zhuweiyou  请问下，如何调整呢

**Comment by zhuweiyou** [comment]
@Fennay  distance * 1.5 我改的 1.5 刚好符合我的手机。。你调整这个值，测试下就行了

**Comment by Fennay** [comment]
@zhuweiyou 
adb shell input swipe 320 410 320 410 509
3035 KB/s (31102 bytes in 0.010s)
卡这里了，已经修改为1.5 
手机是红米3s，分辨率是1280*720
还会有别的影响吗...

**Comment by vuuihc** [comment]
@Fennay MIUI8需要打开USB调试（安全调试）

**Comment by Zijianlalala** [comment]
cor 声明了两次呀

**Comment by wangshub** [comment]
赞

**Comment by qianbiTH** [comment]
可以的

**Comment by jkzing** [comment]
MIX2参数设成1.4最佳😎

**Comment by Fly-Bird** [comment]
小米5s经过调试完美运行

**Comment by iMLe0n** [comment]
所以这个到底怎么玩啊，求详细教程

**Comment by Akihi777** [comment]
有没有 纯小白教程？

**Comment by sqrtqiezi** [comment]
坚果手机，把参数调整为：
```
adb shell input swipe 320 410 320 930
```
即可

**Comment by Fennay** [comment]
@vuuihc 感谢，开启调试后，完美运行

**Comment by ingShen** [comment]
@vuuihc 多谢老哥 红米手机已ok。

**Comment by keytodoor** [comment]
mac 上python3.6   onClick(event)函数没有被调用啊 大神  刚接触python

**Comment by 0x9c** [comment]
三星s7 edge系数调到1.05正好

**Comment by 1soYang** [comment]
有没有老哥告诉一声s8改成什么参数效果最佳

**Comment by 0312birdzhang** [comment]
酷派大神F2 系数调为 `1.98`能到100多 😂 
swipe值调为`323 1057 323 1059`可以无限重玩

**Comment by AndrWang** [comment]
没发现底部的黑色感叹号啊

**Comment by AndrWang** [comment]
@sqrtqiezi 我是坚果 Pro，调成这个参数发现也没用啊

**Comment by whiyc** [comment]
多谢老哥,有一点点误差,2个小瓶子之间操作不好容易翻车

**Comment by jing36** [comment]
运行之后有两个错误
img =np.array(Image.open('1.png'))
还有FileNotFoundError: [Errno 2] No such file or directory: '1.png'

**Comment by a905139429** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'plt' is not defined

**Comment by a905139429** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'plt' is not defined   怎么板

**Comment by hopesala** [comment]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1163f40f0>: Failed to establish a new connection: [Errno 61] Connection refused',))

mac os下 python3.6

**Comment by loveJuly** [comment]
iPhone 7 plus跳一步之后界面刷新不完整，有大佬遇到过么，求解决方法。

**Comment by ValentinZhao** [comment]
赞赞赞~！

**Comment by kuiblog** [comment]
我的设备是 Mac，目前Mac+iPhone和Mac+Android 都成功了，大家可以参考下这篇文章：http://kuiblog.com/archives/402/

**Comment by chengkunlun** [comment]
安装web的时候,运行会报缺少依赖库的问题,有遇见过得吗?

**Comment by MrLevo520** [comment]
0. 请使用最新版代码
1. 使用adb免配置版本
2. 使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
下次请规范提交issue，谢谢
