### ISSUE TITLE
pip install -r requirements.txt 时报错

### ISSUE THREAD

**Issue by RyomaFYx** [wangshub/wechat_jump_game#40]
mac 使用 pip install -r requirements.txt 报错内容
  "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"
  已经安装了pip 
![image](https://user-images.githubusercontent.com/20924164/34451028-c08065c4-ed54-11e7-9149-19b1231c3d44.png)
本人android开发～不懂python..

**Comment by zhangkangbin** [comment]
requirements.txt有下载，在当前目录？

**Comment by wangshub** [comment]
先clone下来，cd 到工程目录下面哦，需要找到文件 @RyomaFYx
