### ISSUE TITLE
优化按压时间计算的新方法

### ISSUE THREAD

**Issue by zhuweiyou** [wangshub/wechat_jump_game#407]
看到已经有人把《跳一跳》源码解包出来了，可以直接改分数发包了（但是貌似被封了）。

不过可以分析源码，来优化脚本的按压时间计算

https://github.com/zhuweiyou/wxgameHacker/tree/master/wx7c8d593b2c3a7703_3.wxapkg.unpack

https://github.com/zhuweiyou/wxgameHacker/blob/master/wx7c8d593b2c3a7703_3.wxapkg.unpack/game.js#L21072-L21170

搜索 `canvas.addEventListener("touchend"`、`touchend` 之类的词，定位手指松开的相关代码

@wangshub 

源码可以直接用微信开发者工具跑起来

![image](https://user-images.githubusercontent.com/8413791/34465245-a6d5cb2c-eee0-11e7-8b8e-551e2b11292a.png)

**Comment by Sowevo** [comment]
这个,你研究下....

**Comment by wangshub** [comment]
@Sowevo https://github.com/wangshub/wechat_jump_game/invitations 不知道是否愿意一起维护

**Comment by Sowevo** [comment]
我不太会玩github...   现学的奥

**Comment by wangshub** [comment]
欢迎加入多讨论交流 @Sowevo , 现在合并的时候一定要慎重一些，要不然会出现更多的问题。也可以参与到讨论中来～大家一起想办法

**Comment by Sowevo** [comment]
不行我要加群   还有没有了 @wangshub
