### ISSUE TITLE
程序都跑不出来啊

### ISSUE THREAD

**Issue by wowtrxqn** [wangshub/wechat_jump_game#411]
![qq 20180101110102](https://user-images.githubusercontent.com/24369118/34465347-1867241e-eee3-11e7-9c9a-8f78e76f074a.png)

**Comment by wowtrxqn** [comment]
![auto](https://user-images.githubusercontent.com/24369118/34465359-98bb69fe-eee3-11e7-8243-87992d80fe7a.png)

**Comment by stevenling** [comment]
你看一下电脑上有微信的截图吗

**Comment by wowtrxqn** [comment]
我用的安卓手机

**Comment by wowtrxqn** [comment]
装模拟机的时候打开威信里面跳一跳运行加载失败，现在用安卓真机就出现上面的报错图片了

**Comment by jack0707** [comment]
我的也是

**Comment by jack0707** [comment]
解析josn文件出错

**Comment by yuanhuikai** [comment]
@wowtrxqn 试试#347 解决方法

**Comment by wowtrxqn** [comment]
程序跑出来了，但是第一步跳就死了，参数不对，我的是OPPO R9Sk

**Comment by wowtrxqn** [comment]
现在每部都跳一样的距离啊
![qq 20180101121200](https://user-images.githubusercontent.com/24369118/34465577-08b19914-eeed-11e7-9bb7-17bbaf0ddc1a.png)
