### ISSUE TITLE
MIX2 适配

### ISSUE THREAD

**Issue by Gongcong** [wangshub/wechat_jump_game#412]
Screen: Physical size: 1080x2160
Density: Physical density: 440
DeviceType: MIX 2
OS: darwin
Python: 2.7.11 (default, Jul 16 2016, 14:44:36)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]

**Comment by Moosphan** [comment]
设置模拟按压各项参数，经过多台手机测试，其中2160x1080建议调整参数为320，1210，720，910
config中的press指数尝试设置为1.372，再次运行

**Comment by HJH12315** [comment]
@Moosphan 1136 x 640参数大概是多少呢  多谢

**Comment by Moosphan** [comment]
不好意思，没有测试iphone的机型，Android党😓
