### ISSUE TITLE
小米6的配置貌似有问题

### ISSUE THREAD

**Issue by guanhonly** [wangshub/wechat_jump_game#416]
目前给出的小米6配置如下：
{
    "under_game_score_y": 300,
    "press_coefficient": 1.42,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,

    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}

然而截止目前玩到的最高分为293

希望有大神给出更好的配置

**Comment by guanhonly** [comment]
亲测，小米6还是用1920x1080分辨率的配置比较好

**Comment by blueberryCoder** [comment]
{
    "under_game_score_y": 300, 
    "press_coefficient": 1.452, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70
}
最高888分

**Comment by siyuanseever** [comment]
我给出了参数，已提交 #457 ,可以然而依然会死，因为拟合函数的问题；
更优的方法可见 #229 ，使用原始参数就行。

**Comment by fantasy525** [comment]
小米6需要改哪个配置文件啊？改mi6文件夹的貌似没用啊
