### ISSUE TITLE
关于偏位具体位置

### ISSUE THREAD

**Issue by zhaoweihaoChina** [wangshub/wechat_jump_game#42]
![screenshot_20171230_113833](https://user-images.githubusercontent.com/25500786/34451097-9c887948-ed56-11e7-8ceb-a26f77e1b55f.png)
![screenshot_20171230_113905](https://user-images.githubusercontent.com/25500786/34451098-9cb98470-ed56-11e7-8b13-d942e1f115e4.png)
![tim 20171230114100](https://user-images.githubusercontent.com/25500786/34451099-9ce5bbb2-ed56-11e7-9545-10661a3f24d4.png)

修复：
大概位置在鼠标左下角，鼠标左下角点中跳棋下部，然后在点中心点

原来最高能+32分:smile:

**Comment by TimmyGzw** [comment]
老哥. 新手可以问一下 如何打开图片么  截图成功了 也导出来了

**Comment by zhaoweihaoChina** [comment]
@TimmyGzw 我python也是新手，我只是下载了python2.7环境，然后安装依赖(建议使用国内镜像https://www.cnblogs.com/microman/p/6107879.html)，刚好我有androidstudio就没有安装adb，就直接在pycharm运行wechat_jump.py就可以了

**Comment by zhaoweihaoChina** [comment]
补充一下，这是1080p手机的偏位调整
