### ISSUE TITLE
程序已运行起来，但是距离不变

### ISSUE THREAD

**Issue by wowtrxqn** [wangshub/wechat_jump_game#421]
![qq 20180101121200](https://user-images.githubusercontent.com/24369118/34465592-3930d7d4-eeee-11e7-9b14-b5e72d2e9ca4.png)

**Comment by wowtrxqn** [comment]
我把
process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
    screenshot = process.stdout.read()
    if sys.platform == 'win32':
        screenshot = screenshot.replace(b'\r\n', b'\n')
    f = open('autojump.png', 'wb')
    f.write(screenshot)
    f.close()

换成    os.system('adb shell /system/bin/screencap -p /sdcard/screenshot.png')
os.system('adb pull /sdcard/screenshot.png ./autojump.png')
才运行起来的，但是现在每部自动跳的距离一样，是我改的问题？

**Comment by sunqing94** [comment]
@wowtrxqn 截图和pull加上延时，大概1s左右，因为手机截图和图片传输需要时间
