### ISSUE TITLE
距离 和 按压时间呈线性关系是否合理？

### ISSUE THREAD

**Issue by LibraSkywalker** [wangshub/wechat_jump_game#423]
如果微信采用的是真实物理引擎模拟的话，对于斜抛运动应该距离和按压时间呈平方关系 S=V0^2sin2(theta)/g。

**Comment by zh-h** [comment]
我用机械臂加手动测量的数据对比，排除测量误差，拟合的曲线是基本是线性的，偏移量是触屏和机械臂的延迟。

![default](https://user-images.githubusercontent.com/13273151/34465766-a93c1408-eef8-11e7-8cdf-7c94b195b995.png)

底部距离（毫米） | 按压时间(10毫秒)
-- | --
12 | 38
13 | 40
14 | 40
15 | 43
16 | 40
18 | 48
19 | 50
20 | 54
21 | 56
22 | 60
24 | 65
25 | 65
26 | 70
27 | 73
28 | 72
29 | 75
31 | 78
32 | 84
33 | 88
35 | 93
36 | 93
38 | 96
41 | 96

应该是为了简单，所以游戏是使用线性处理，厉害就上机器学习啊，每次跳跃都能修正轨迹。

**Comment by BeiTown** [comment]
<img width="564" alt="wx20180102-215244 2x" src="https://user-images.githubusercontent.com/34995486/34485825-7443b21e-f007-11e7-8587-6e7d087f0135.png">
程序500次结果拟合的离散点趋势线
