### ISSUE TITLE
 求iphone se 的参数

### ISSUE THREAD

**Issue by HJH12315** [wangshub/wechat_jump_game#425]
高度 | 123.8 毫米（4.87 英寸）
宽度 | 58.6 毫米（2.31 英寸）
厚度 | 7.6 毫米 （0.30 英寸）
4 英寸LED背光宽显示屏
1136 x 640 像素分辨率，326 ppi
 多谢大佬

**Comment by xinyulab** [comment]
我也想要

**Comment by LibraSkywalker** [comment]
。。。写个二分调参有那么难么

**Comment by xinyulab** [comment]
毕竟懒hhhh

**Comment by HJH12315** [comment]
@LibraSkywalker  不太懂这个参数的原理 应该是根据分辨率和屏幕大小吧？

**Comment by LibraSkywalker** [comment]
简单来说就是跳远了。。。把参数减小点。。。跳近了。。。把参数调大点

**Comment by HJH12315** [comment]
"piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410

那这个呢？

**Comment by FaiChou** [comment]
```
if config.get('swipe'):
    swipe = config['swipe']
else:
    swipe = {
        "x1": 320,
        "y1": 410,
        "x2": 320,
        "y2": 410
    }
```

默认就是你这个
@HJH12315

**Comment by HJH12315** [comment]
@FaiChou 我知道 但这个数据不对呀 所以求参数 heigjt wedith

**Comment by pansy-cx** [comment]
```
{
    "under_game_score_y": 180,
    "press_coefficient": 2.3,
    "piece_base_height_1_2": 13,
    "piece_body_width": 49,

    "swipe" : {
        "x1": 375,
        "y1": 1055,
        "x2": 375,
        "y2": 1055
    }
}

```
调了个不算完美但能用的参数，你可以试试

**Comment by FaiChou** [comment]
@HJH12315 

在`wechat_jump_auto_iOS.py` 下 swipe 是没用的. 不用关心这个参数.

**Comment by Kryssss** [comment]
同求
