### ISSUE TITLE
求三星S8的config.json参数

### ISSUE THREAD

**Issue by MaxPPain** [wangshub/wechat_jump_game#426]
Screen: Physical size: 1440x2960
Density: Physical density: 640
DeviceType: SM-G9500
OS: darwin
Python: 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by MaxPPain** [comment]
{
    "under_game_score_y": 390,
    "press_coefficient": 1.075,
    "piece_base_height_1_2": 28,
    "piece_body_width": 110,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}

**Comment by MaxPPain** [comment]
{
    "under_game_score_y": 390,
    "press_coefficient": 1.045,
    "piece_base_height_1_2": 28,
    "piece_body_width": 110,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}
1000+

**Comment by demidroid** [comment]
这些参数怎么设置的

**Comment by MaxPPain** [comment]
目前这个S8参数分数上5000+没问题。
