### ISSUE TITLE
改变方向之后定位出错

### ISSUE THREAD

**Issue by AlienMarkWong** [wangshub/wechat_jump_game#428]
![1514780749_d](https://user-images.githubusercontent.com/31840432/34465679-8ea9ffde-eef2-11e7-87b5-67ac4f9368ba.png)
刚开始还可以，定位也没有问题，但是改变方向之后定位出错
![1514780764_d](https://user-images.githubusercontent.com/31840432/34465682-a24890b4-eef2-11e7-98ab-cce164ce2f3f.png)

**Comment by daiqiang838** [comment]
你说的是改变 图片横向变为纵向？？

**Comment by gjwang-ICME** [comment]
不是滴，是坐标的定位错了，蓝点并不在下一个图形中心位置

**Comment by baolw** [comment]
你这个还不算是改变方向的原因。你这个是源代码对白色块的识别有问题导致的
