### ISSUE TITLE
脚本运行报错：IOError: cannot identify image file './autojump.png'

### ISSUE THREAD

**Issue by cchungry** [wangshub/wechat_jump_game#429]
**********        
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 3W
OS: win32
Python: 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
**********
List of devices attached
cb9aad77	device

**Comment by F-loat** [comment]
#325
