### ISSUE TITLE
棋子识别步骤感觉比较冗余

### ISSUE THREAD

**Issue by LibraSkywalker** [wangshub/wechat_jump_game#430]
我觉得既然棋子的头部是个圆形的，可以直接用cv2的HoughCircle识别，把参数里面最大和最小半径定在头部大小+-2像素内可以完美识别棋子。

**Comment by wenxingxing** [comment]
圆形的跳台怎么办

**Comment by LibraSkywalker** [comment]
圆形跳台半径比头部大很多，所以可以通过minRadius和maxRadius这两个参数filter掉
