### ISSUE TITLE
求红米NOTE4的参数，感谢

### ISSUE THREAD

**Issue by CHHack0l** [wangshub/wechat_jump_game#435]
求红米NOTE4的参数，感谢

**Comment by dmego** [comment]
参考红米note4X[#383](https://github.com/wangshub/wechat_jump_game/issues/383)
以及注意点[#297](https://github.com/wangshub/wechat_jump_game/issues/297)

**Comment by dmego** [comment]
可以看看这个[使用0.85次方函数来拟合](https://github.com/wangshub/wechat_jump_game/pull/229)
之前最高230，看了这个改了几行代码，现在1800 还在继续
