### ISSUE TITLE
iphone6 自动跳 调了1.95为什么别人可以连续跳 我一步就游戏结束了

### ISSUE THREAD

**Issue by SIXSIXSIXX** [wangshub/wechat_jump_game#436]
求大佬解答

**Comment by zzlphp** [comment]
我的一步也就结束了 请问你搞定了没?

**Comment by one-smiling** [comment]
time.sleep(random.uniform(1, 1.1))   # 为了保证截图的时候应落稳了，多延迟一会儿

将上面的改为 time.sleep(random.uniform(2, 2.1)) 会更为稳定一些
我测试的时候，发现如果经过距离较长的一次跳跃之后，下一次跳跃就很容易失败，我猜测是因为sleep时间过短，导致sleep完之后，跳跃动画并没有完成，而过长的跳跃距离和过快的跳跃动画，就会将此问题放大。

**Comment by lstk520** [comment]
iPhone6 `"press_coefficient": 1.995` 比较合适

**Comment by TiltCitySong** [comment]
解决了吗  哥
