### ISSUE TITLE
IOError: cannot identify image file './autojump.png'

### ISSUE THREAD

**Issue by singee77** [wangshub/wechat_jump_game#438]
D:\test\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from D:\test\wechat_jump_game-master/config/1920x1080/config.json
(226.15384615384608, 0.06074766355140192, 0.8392156862745098)
(140, 142, 149)
濡傛灉浣犵殑鑴氭湰鏃犳硶宸ヤ綔锛屼笂鎶ssue鏃惰copy濡備笅淇℃伅:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OD103
OS: win32
Python: 2.7.14 |Anaconda, Inc.| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)]
**********
List of devices attached
d316d615        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "C:\ProgramData\Anaconda2\lib\site-packages\PIL\Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

**Comment by lohcve** [comment]
我的也是这样

**Comment by pandaGames** [comment]
一样是这个情况啊~

**Comment by singee77** [comment]
我已经解决了哦，重新下载这个ADB这个地址https://dl.google.com/android/repository/platform-tools-latest-windows.zip，配置一下环境变量就可以了。

**Comment by pandaGames** [comment]
我是把auto那个脚本中的pull_screenshot的一行改了，原来的是这样的
`screenshot = screenshot.replace(b'\r\n', b'\n')`
改成如下
`screenshot = screenshot.replace(b'\r\r\n', b'\n')`
这样生成的screenshot截图就是好的了。

**Comment by HaoShuaia** [comment]
楼上方法可行

**Comment by antallx** [comment]
我生成的截图是这样的，是哪里没有配置对么？
![image](https://user-images.githubusercontent.com/30544100/34466196-bbbe4f52-ef06-11e7-9434-79243e328981.png)
