### ISSUE TITLE
为训练库贡献俩训练素材

### ISSUE THREAD

**Issue by jx3fans** [wangshub/wechat_jump_game#439]
如下，识别成功，但是起跳失败的俩截图。

![1514785559_d](https://user-images.githubusercontent.com/870076/34465864-384161dc-eefc-11e7-89c0-324110a9c3ba.png)
![1514785559](https://user-images.githubusercontent.com/870076/34465865-3873bf74-eefc-11e7-8d33-f43fd3dc6a43.png)
![1514785563_d](https://user-images.githubusercontent.com/870076/34465866-389ffb98-eefc-11e7-9850-6e93e06775ce.png)
![1514785771_d](https://user-images.githubusercontent.com/870076/34465867-38cd4dfa-eefc-11e7-981c-3bafaa7936a0.png)
![1514785771](https://user-images.githubusercontent.com/870076/34465868-38f91cdc-eefc-11e7-9ee1-3f856cc8a3f6.png)
![1514785774_d](https://user-images.githubusercontent.com/870076/34465869-39256e5e-eefc-11e7-908d-2226a840f759.png)

**Comment by jx3fans** [comment]
感觉可以固定划线的角度，似乎不管初始落点在啥地方，起跳点都是在当前方块的中央。

**Comment by zyxbcde** [comment]
是的，歪了就容易连错，然后错误累计就凉了，好像低分辨率不准，同学高分屏基本一直+32上分巨快。
之前是把跳那里加了个手输距离，看着形势不妙就切成手动纠偏一下。
不过今天更新了一下基本自动也死不了了，致敬dalao
