### ISSUE TITLE
运行python wechat_jump_auto.py成功，但是不能自动跳跃，只输出信息

### ISSUE THREAD

**Issue by taoyou123** [wangshub/wechat_jump_game#44]
PS D:\Python\wechat_jump_game> python wechat_jump_auto.py
3248 KB/s (59920 bytes in 0.018s)
1514605731 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2088 KB/s (59920 bytes in 0.028s)
1514605741 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2016 KB/s (59920 bytes in 0.029s)
1514605750 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2165 KB/s (59920 bytes in 0.027s)
1514605760 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2249 KB/s (59920 bytes in 0.026s)
1514605770 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2016 KB/s (59920 bytes in 0.029s)
1514605781 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
1670 KB/s (59920 bytes in 0.035s)
1514605790 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2436 KB/s (59920 bytes in 0.024s)
1514605801 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2338 KB/s (59920 bytes in 0.025s)
1514605810 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
1949 KB/s (59920 bytes in 0.030s)
1514605820 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
1949 KB/s (59920 bytes in 0.030s)
1514605831 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2088 KB/s (59920 bytes in 0.028s)
1514605840 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2088 KB/s (59920 bytes in 0.028s)
1514605850 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2339 KB/s (59920 bytes in 0.025s)
1514605860 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
2339 KB/s (59920 bytes in 0.025s)
1514605870 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
1949 KB/s (59920 bytes in 0.030s)
1514605880 338.54135338345867 1109 788.5 1385.4159479214936
adb shell input swipe 320 410 320 410 735
3479 KB/s (602572 bytes in 0.169s)
1514605889 0 0 0 0
adb shell input swipe 320 410 320 410 200
2284 KB/s (524254 bytes in 0.224s)
1514605898 0 0 0 0
adb shell input swipe 320 410 320 410 200
2382 KB/s (524873 bytes in 0.215s)
...

**Comment by a772856947** [comment]
同样是这种情况，只输出，屏幕上没跳跃

**Comment by Javen205** [comment]
需要开启模拟点击  小米是USB调试（安全设置）

**Comment by taoyou123** [comment]
![663758723959008889](https://user-images.githubusercontent.com/24927517/34451256-e814e626-ed5b-11e7-95d5-af267b446b82.jpg)
开了啊

**Comment by taoyou123** [comment]
弄好了，可他每次只能得到个位数

**Comment by VitalyAnkh** [comment]
你重新开启USB调试和USB调试（安全模式），再试一下呗

**Comment by xxxlfu** [comment]
只截图不跳动，原来是“需要开启模拟点击 小米是USB调试（安全设置）”，感谢楼上的大佬@Javen205
