### ISSUE TITLE
小米5s跳不了

### ISSUE THREAD

**Issue by April-5** [wangshub/wechat_jump_game#440]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5s
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]

**Comment by vipmike007** [comment]
需要打开在开发者模式打开模拟触摸，还有用python2.7

**Comment by Blue-Whale-H** [comment]
已解决，打开USB调试安全设置就好了

**Comment by YxxY** [comment]
更新了最新代码跳不了几步就挂了，大多都是飞出去，昨天还能轻松300+，到底是5s配置变了，还是游戏设置改了

**Comment by NoBey** [comment]
游戏好像更新了
