### ISSUE TITLE
iphone7出现这个异常requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): 

### ISSUE THREAD

**Issue by chenxukunyx** [wangshub/wechat_jump_game#441]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106b3bd68>: Failed to establish a new connection: [Errno 61] Connection refused',)

**Comment by chenxukunyx** [comment]
大佬帮看一下

**Comment by zzlphp** [comment]
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=iOS Simulator,name=iPhone 6S' test
需要启动这个命令之后 才可以

**Comment by chenxukunyx** [comment]
这个是在命令行启动么

**Comment by yunsankai** [comment]
#99

**Comment by gkgy** [comment]
我也是这种情况，怎么办呢？
