### ISSUE TITLE
小米note报错打开autojump.png错误

### ISSUE THREAD

**Issue by bainian** [wangshub/wechat_jump_game#442]
**********        
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI NOTE LTE
OS: darwin
Python: 3.6.4 |Anaconda, Inc.| (default, Dec 21 2017, 15:39:08) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
**********
List of devices attached
4daaf8f0	device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 357, in <module>
    main()
  File "wechat_jump_auto.py", line 344, in main
    im = Image.open('./autojump.png')
  File "/Users/sage/anaconda3/envs/wechat_env3/lib/python3.6/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by F-loat** [comment]
试下最新版的

**Comment by gallonyin** [comment]
把def pull_screenshot():
方法体改成：
os.system('adb shell /system/bin/screencap -p /sdcard/screenshot.png')
os.system('adb pull /sdcard/screenshot.png ./autojump.png')
原来的用#注释掉或删掉
亲测可行
