### ISSUE TITLE
mac ios 怎么自动跳呢?

### ISSUE THREAD

**Issue by zzlphp** [wangshub/wechat_jump_game#443]
mac ios 怎么自动跳呢?环境都配置好了之后,
运行python3 wechat_jump_auto_iOS.py
出现:
size: 750, 1334
scan_start_y:  50
1514787871 0 0 0 0

然后就结束了,没有bug,怎么调试?

**Comment by zsm1703** [comment]
点开始了没

**Comment by zzlphp** [comment]
点击开始了,不知道为什么 1.png不知道哪里来的?老是程序桌面的图
能加个qq指导一下吗 280229278

**Comment by OldDriverWu** [comment]
同样 ：
size: 750, 1334
scan_start_y:  250
1514793941 0 0 0 0

**Comment by kwailamchan** [comment]
修改config.json里的参数

**Comment by zsm1703** [comment]
config.json放到根目录

**Comment by shimminZ** [comment]
怎么设置自动跳啊 ，我的点击才会跳

**Comment by zsm1703** [comment]
@shimminZ 
_wechat_jump_auto_iOS.py_
