### ISSUE TITLE
最新版本 再玩一局按钮 的坐标设置错了

### ISSUE THREAD

**Issue by BeiTown** [wangshub/wechat_jump_game#449]
> 坐标获取不应该只读表，需要根据屏幕尺寸适配

def jump(distance):
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200 ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe['x1'],  ` # 这里应该改为 swipe_x1`
        y1=swipe['y1'],  `# 这里应该改为swipe_y1`
        x2=swipe['x2'],  `# 这里应该改为 swipe_x2`
        y2=swipe['y2'],  `# 这里应该改为 swipe_y2`
        duration=press_time
    )
    print(cmd)
    os.system(cmd)

**Comment by Vg1ee** [comment]
恩你是对的，我pull了一个改过的
