### ISSUE TITLE
截图了，但打不开

### ISSUE THREAD

**Issue by 8311431967** [wangshub/wechat_jump_game#450]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 3
OS: win32
Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
**********
List of devices attached
813ab461        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "D:\APP\pybao\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by Aayes** [comment]
试试新手小白那个行不；
我的也报这个错，我把wechat_jump_auto.py里面的pull_screenshot函数换成新手小白里的就行了。
def pull_screenshot():
    os.system('adb shell screencap -p /sdcard/autojump.png')
    os.system('adb pull /sdcard/autojump.png .')

**Comment by 8311431967** [comment]
谢谢，解决了，但为什么上面的不行呢？
