### ISSUE TITLE
在近距离情况下容易误跳

### ISSUE THREAD

**Issue by EricBrownz** [wangshub/wechat_jump_game#451]
手持米6，在某些方块特别近的情况下容易误跳，要么太近，要么太远

**Comment by siyuanseever** [comment]
我也注意到了这个问题，长按时间和跳跃距离并不是线性相关

**Comment by Vesna0130** [comment]
确实不是线性相关 按压力度越大加速度越大
并且按色差识别棋盘 会在棋盘挨得很近的情况下识别出错 不知道有没有大神能想出解决办法
