### ISSUE TITLE
建一个telegram的群？

### ISSUE THREAD

**Issue by WANG-lp** [wangshub/wechat_jump_game#453]
我们建一个telegram的群吧，感觉qq群里面的小白有点多，消息看不过来。

**Comment by maxlv7** [comment]
可以的

**Comment by maxlv7** [comment]
https://t.me/joinchat/AAAAAFIOmvCInyUfb_Tq4w
这是链接，我创建了一个

**Comment by WANG-lp** [comment]
@maxlv7 老哥，你这个是channel啊，不是group
