### ISSUE TITLE
MI 5 报错说是设备暂不支持 No devices

### ISSUE THREAD

**Issue by xmy351** [wangshub/wechat_jump_game#459]
C:\Users\Administrator>python C:\Users\Administrator\Desktop\wechat_jump_auto.py

error: no devices/emulators found
Load default config
226.15384615384608 0.06074766355140192 0.8392156862745098
140 142 149
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen:
Density:
DeviceType:
OS: win32
Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (I
ntel)]
**********
List of devices attached

error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
暂不支持当前设备

**Comment by atomwangda** [comment]
打开安全设置了吗？

**Comment by xmy351** [comment]
安全模式打开了，好奇怪

**Comment by wjzhangcsu** [comment]
你这个是adb找不到设备，先把adb调通。

**Comment by caogle** [comment]
adb版本太旧
