### ISSUE TITLE
棋子底座高度一半值得是哪里到哪里的距离 。还有宽度

### ISSUE THREAD

**Issue by HJH12315** [wangshub/wechat_jump_game#461]
piece_base_height_1_2 = config['piece_base_height_1_2']   # 二分之一的棋子底座高度，可能要调节
piece_body_width = config['piece_body_width']             # 棋子的宽度，比截图中量到的稍微大一点比较安全，可能要调节

**Comment by telenewbie** [comment]
我也有这个问题,但是不知道是设置多少?
我把二分之一的棋子底座高度设置为0 ,跑的比原来要高一点,原来一百多,调整完变成二百多
