### ISSUE TITLE
小米 max2 脚本正常运行，但是手机上没有开始跳动没有

### ISSUE THREAD

**Issue by ianly** [wangshub/wechat_jump_game#462]
如果你的脚本无法工作，上报issue时请copy如下信息:
=====
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI MAX 2
=====
List of devices attached
3378ac8c	device

**Comment by ianly** [comment]
小米手机不仅要打开 USB 调试，还要打开 USB 调试（安全设置），但是参数好像不对，求小米MAX2参数

**Comment by as6170358** [comment]
还要允许use点击
