### ISSUE TITLE
很多个纯白色圆形识别问题，需调整

### ISSUE THREAD

**Issue by wangyg6** [wangshub/wechat_jump_game#464]
![1514794542_d](https://user-images.githubusercontent.com/15121115/34466470-4e358708-ef0f-11e7-8f2f-3a4e8321f3ab.png)
![1514799146_d](https://user-images.githubusercontent.com/15121115/34466765-5546279a-ef1a-11e7-882c-567a655a2b43.jpg)

**Comment by Vg1ee** [comment]
@Sowevo 你的算法是不是要改进一下？

**Comment by Sowevo** [comment]
@Vg1ee 图2跳的太快了,图1不确定是什么原因,圆顶的识别还有问题
