### ISSUE TITLE
错误，怎么解

### ISSUE THREAD

**Issue by nicemap** [wangshub/wechat_jump_game#468]
G:\openCV\adb\wechat_jump_game-master>python wechat_jump.py
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "wechat_jump.py", line 15, in <module>
    template = cv2.resize(template, (0, 0), fx=scale, fy=scale)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

**Comment by wjzhangcsu** [comment]
不要用wechat_jump.py这个脚本了，试试wechat_jump_auto.py，怎么不先看看readme？
