### ISSUE TITLE
这个按压时间参数，应该还跟机型或者第三方rom不同有关，不仅仅跟分辨率有关。

### ISSUE THREAD

**Issue by mg459046365** [wangshub/wechat_jump_game#47]
我用小米note2，1920*1080，然后参数修改成1.393，分出没有超出过100分。我用1.47，跑出了800+的分数。不过感觉还是不理想，还需要调整。

**Comment by a772856947** [comment]
mix机型，py运行成功，一直有输出，可是屏幕上根本不动

**Comment by Javen205** [comment]
@a772856947 需要开启模拟点击

**Comment by taoyou123** [comment]
弄好了，可他每次只能得到个位数

**Comment by Javen205** [comment]
@taoyou123 这个跟手机的分辨率有关，需要自己修改部分参数。目前程序貌似还没自动处理这些。
