### ISSUE TITLE
iOS random等待时间过短，截图错误

### ISSUE THREAD

**Issue by one-smiling** [wangshub/wechat_jump_game#471]
机型：iPhone 6s 10.3
电脑：Mac
random时间过短，导致棋盘没有完全落下就开始截图，并且棋盘有一个弹跳的时间，甚至如果距离过长会导致棋子未完全落下
![1514802234_d](https://user-images.githubusercontent.com/6986063/34467057-cfe5bd74-ef21-11e7-9632-e7a852ba9e41.png)
<img width="374" alt="2018-01-01 5 26 21" src="https://user-images.githubusercontent.com/6986063/34466713-fb291020-ef18-11e7-8a2c-20a298d87f83.png">

**Comment by one-smiling** [comment]
![1514802234_d](https://user-images.githubusercontent.com/6986063/34467034-4d513f82-ef21-11e7-8a4f-94ba88a12c1e.png)

**Comment by zsm1703** [comment]
自己修改一下time.sleep(random.uniform(1, 1.1))这一行
