### ISSUE TITLE
vivo x20 adb shell swipe 执行这个命令

### ISSUE THREAD

**Issue by azhon** [wangshub/wechat_jump_game#472]
vivo x20 adb shell swipe 执行这个命令 
 
显示 killed 。是什么问题？

**Comment by aComputerGeek** [comment]
小米note3 +1 是权限问题么？

**Comment by robot527** [comment]
也是小米手机，USB调试 下面应该还有一个 “USB调试（安全设置）”，也要打开才行。 @aComputerGeek
