### ISSUE TITLE
openvc error

### ISSUE THREAD

**Issue by nicemap** [wangshub/wechat_jump_game#475]
![qq 20180101175217](https://user-images.githubusercontent.com/17722161/34466850-9a81a5a8-ef1c-11e7-94bc-cf6dabbb6860.png)

**Comment by BruceGui** [comment]
我也碰到了，不知道具体错误在哪里，但是 运行 wechat_jump_py3.py 是可以的

**Comment by XKangs** [comment]
我也是。手动版出错，自动版正常
![qq 20180101201506](https://user-images.githubusercontent.com/17783163/34467564-9acb3506-ef30-11e7-841d-c1f64856b2cd.jpg)
