### ISSUE TITLE
小药瓶每次都跳不上去

### ISSUE THREAD

**Issue by zhangchennjupt** [wangshub/wechat_jump_game#476]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: Mi Note 2
OS: win32
Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
**********

**Comment by BruceGui** [comment]
调节时间系数吧

**Comment by Vg1ee** [comment]
有debug的截图吗？
