### ISSUE TITLE
请求Mi 5s Plus 适配

### ISSUE THREAD

**Issue by Henry3510** [wangshub/wechat_jump_game#477]
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI 5s Plus
OS: win32
Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]

**Comment by Henry3510** [comment]
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI 5s Plus
OS: win32
Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]

**Comment by VitalyAnkh** [comment]
我用的就是小米5s Plus。去我的repository找吧，有现成的

**Comment by Henry3510** [comment]
Thanks!
