### ISSUE TITLE
三星Note3 Lite（N7508V） 分辨率1280×720 ，一直不成功，求教！

### ISSUE THREAD

**Issue by terrybogez** [wangshub/wechat_jump_game#481]
输出信息：
C:\wechat_jump_game-master>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

C:\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from C:\wechat_jump_game-master/config/1280x720/config.json
226.15384615384608 0.06074766355140192 0.8392156862745098
140 142 149
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: SM-N7508V
OS: win32
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (A
MD64)]
**********
List of devices attached
1ad7be70        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "C:\Users\zhangxing\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

脚本地址：
**https://github.com/wangshub/wechat_jump_game**

请教各位是哪里的问题，谢谢！

**Comment by BruceGui** [comment]
这是屏幕截图函数的问题，我也碰到了，解决办法如下：

找到 wechat_jump_auto.py 文件里面的 pull_screenshot() 函数，把里面的内容替换为：

`  os.system('adb shell screencap -p /sdcard/autojump.png')
    os.system('adb pull /sdcard/autojump.png .')
`

就可以了，原始的函数不知道为什么不行

**Comment by terrybogez** [comment]
@BruceGui 谢谢指教，但是我没有成功。
请问是https://github.com/wangshub/wechat_jump_game这个项目地址里的wechat_jump_auto.py 文件吗？我搜索到的pull_screenshot() 函数如下：
85-100行：
def pull_screenshot():
    global screenshot_way
    # 新的方法请根据效率及适用性由高到低排序
    if screenshot_way == 2 or screenshot_way == 1:
        process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
        screenshot = process.stdout.read()
        if screenshot_way == 2:
          binary_screenshot = screenshot.replace(b'\r\n', b'\n')
        else:
          binary_screenshot = screenshot.replace(b'\r\r\n', b'\n')
        f = open('autojump.png', 'wb')
        f.write(binary_screenshot)
        f.close()
    elif screenshot_way == 0:
        os.system('adb shell screencap -p /sdcard/autojump.png')
        os.system('adb pull /sdcard/autojump.png .')
已经包含了你说的替换的内容，你说的替换是全部替换掉吗 ？

多谢！

**Comment by BruceGui** [comment]
嗯 全部替换

**Comment by terrybogez** [comment]
@BruceGui 错误如下。
C:\Users\zhangxing\Desktop\wechat_jump_game-master 1>python wechat_jump_auto.py
Load config file from C:\Users\zhangxing\Desktop\wechat_jump_game-master 1/confi
g/1280x720/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: SM-N7508V
OS: win32
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (A
MD64)]
**********
采用方式1获取截图
scan_start_y:  476
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

所以应该不是截图的问题？
