### ISSUE TITLE
暂不支持当前设备

### ISSUE THREAD

**Issue by chuge26** [wangshub/wechat_jump_game#482]
Screen: 
Density: 
DeviceType: 
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
**********
暂不支持当前设备
>>> 

USB调试已经打开  机型是1+3
听到有USB调试安全模式的说法 可是微臣找不到啊！

**Comment by frinck** [comment]
你这个adb可能和你的手机不匹配，换一个试试

**Comment by frinck** [comment]
你终端先adb devices看可以找到设备没

**Comment by chuge26** [comment]
adb devices可以找到设备 有显示编号

**Comment by chuge26** [comment]
@frinck adb devices可以找到设备 有显示编号

**Comment by 853486395** [comment]
######坚果pro1代手机无法正常运行。第1步都无法跳出去。报错如下######################
(226.15384615384608, 0.06074766355140192, 0.8392156862745098)
(140, 142, 149)
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OD103
OS: darwin
Python: 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
**********
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
采用方式1获取截图
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805594, 338, 1109, 788, 849)
adb shell input swipe 500 1600 500 1602 723
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805598, 340, 1195, 788, 849)
adb shell input swipe 500 1600 500 1602 787
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805602, 340, 1195, 788, 849)
adb shell input swipe 500 1600 500 1602 787
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805606, 340, 1195, 788, 849)
adb shell input swipe 500 1600 500 1602 787

**Comment by wzx011011** [comment]
Screen: Physical size: 1440x2560
Override size: 1080x1920
Density: Physical density: 640
Override density: 480
DeviceType: SM-G9350
OS: win32

**Comment by wzx011011** [comment]
Screen: Physical size: 1440x2560
Override size: 1080x1920
Density: Physical density: 640
Override density: 480
DeviceType: SM-G9350
OS: win32

我的已经识别到了设备，但还是提示“暂不支持该设备”，这是为什么
