### ISSUE TITLE
打开闪退

### ISSUE THREAD

**Issue by qixiangnan1996** [wangshub/wechat_jump_game#484]
C:\Users\39417>python D:\wechat_jump_auto_iOS.py
Traceback (most recent call last):
  File "D:\wechat_jump_auto_iOS.py", line 6, in <module>
    import wda
ModuleNotFoundError: No module named 'wda'
---
![qq 20180101183137](https://user-images.githubusercontent.com/31838572/34467084-60c7e042-ef22-11e7-9a33-614d0f9578c2.png)

**Comment by zsm1703** [comment]
这是iOS的脚本，需要MacOS系统操作的。

**Comment by qixiangnan1996** [comment]
谢谢，我是Windows，安卓手机，应该下载哪个？

**Comment by zsm1703** [comment]
https://github.com/wangshub/wechat_jump_game/blob/master/README.md
仔细看一下
