### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by zzzMaple** [wangshub/wechat_jump_game#485]
Traceback (most recent call last):
  File "X:\python\wechat_jump_auto.py", line 61, in <module>
    config = open_accordant_config()
  File "X:\python\wechat_jump_auto.py", line 46, in open_accordant_config
    return json.load(f)
  File "X:\python\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 2138: illegal multibyte sequence
机型米5

**Comment by BruceGui** [comment]
找到 _open_accordant_config()_ 函数 里面的如下代码：

```python
if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            print("Load config file from {}".format(config_file))
            return json.load(f)
```

然后把 open(config_file, 'r') 改成 open(config_file, 'rb') 试试。

**Comment by zzzMaple** [comment]
还是报一样的错
get出来的是UTF-8...

**Comment by BruceGui** [comment]
那个 else 里面也有一个 open() 函数

```python
else:
        with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:
            print("Load default config")
            return json.load(f)
```

也改成 rb 模式试试

**Comment by zzzMaple** [comment]
提示我 json object 不能是二进制文件

**Comment by zzzMaple** [comment]
我重新下载整个文件就好了0 0不懂到底是什么问题，谢谢楼上的帮忙
