### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by maoliming** [wangshub/wechat_jump_game#486]
Screen: Physical size: 720x1280
Density: Physical density: 300
DeviceType: Redmi 4X
OS: win32
Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]

**Comment by BruceGui** [comment]
你运行的是哪个 py 脚本，有没有 Traceback 信息

**Comment by maoliming** [comment]
解决了，红米开发版不光要打开USB调试模式，还要打开一个USB调试模式（安全设置）
