### ISSUE TITLE
计算方向错误    出现问题的都是这个底座

### ISSUE THREAD

**Issue by Hasiy** [wangshub/wechat_jump_game#487]
![1514802239_d](https://user-images.githubusercontent.com/13153821/34467177-9ac32426-ef24-11e7-9723-7d6cb777c813.png)
计算方向错误    出现问题的都是这个底座

**Comment by Vg1ee** [comment]
我猜是音符bug？ @Sowevo

**Comment by Sowevo** [comment]
是音符的问题,稍后过滤下 @Vg1ee
