### ISSUE TITLE
如果自动运行失败的，请注意一下一些小问题

### ISSUE THREAD

**Issue by kkyflying** [wangshub/wechat_jump_game#49]
1.请关闭你手机上的所有在system的Window的浮窗，例如：魅族的小点点，请关闭，因为是截图到电脑上进行坐标的计算，但是是通过颜值来计算的，有类似的漂窗就会影响到计算，导致一条就会失败
2.请开启开发者模式。允许adb的模拟输入。
本人的测试过华为，魅族都可以
3.刚作者发布的系数请按照设备分辨率来跳。如果不知道可以在
```
def find_piece_and_board(im):
w, h = im.size
print('W = ,H = ',w,h)
```
通过运行一次来查看分辨率

**Comment by kkyflying** [comment]
欢迎大家补充

**Comment by kunphp** [comment]
720X1280的该咋调参数

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
