### ISSUE TITLE
iOS 问题

### ISSUE THREAD

**Issue by Wanguy** [wangshub/wechat_jump_game#490]
请问这个是因为我有哪个framework没有下载吗
![image](https://user-images.githubusercontent.com/21999088/34467297-615f3a86-ef28-11e7-8a8b-98ae92b8b5a1.png)
其他的都正常，就是运行的时候总是提示这个

**Comment by zsm1703** [comment]
brew install python3

**Comment by Wanguy** [comment]
我用的就是py3

**Comment by zsm1703** [comment]
试一下
conda install matplotlib
或者
Step 1: Open terminal
Step 2: Execute conda install python.app to install python.app

**Comment by Wanguy** [comment]
可是我pip list里有这个matplotlib啊，还是说两个不一样

**Comment by zsm1703** [comment]
你可以搜一下 这是我搜到的解决方案

**Comment by Wanguy** [comment]
嗯嗯，我解决了，就是你这个方法，谢谢啦
