### ISSUE TITLE
坚果pro1代手机无法正常运行。第1步都无法跳出去。报错如下

### ISSUE THREAD

**Issue by 853486395** [wangshub/wechat_jump_game#492]
############################
(226.15384615384608, 0.06074766355140192, 0.8392156862745098)
(140, 142, 149)
如果你的脚本无法工作，上报issue时请copy如下信息:

Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OD103
OS: darwin
Python: 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
采用方式1获取截图
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805594, 338, 1109, 788, 849)
adb shell input swipe 500 1600 500 1602 723
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805598, 340, 1195, 788, 849)
adb shell input swipe 500 1600 500 1602 787
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805602, 340, 1195, 788, 849)
adb shell input swipe 500 1600 500 1602 787
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
('scan_start_y: ', 690)
(1514805606, 340, 1195, 788, 849)
adb shell input swipe 500 1600 500 1602 787

**Comment by Hasiy** [comment]
Screen: adb server is out of date.  killing...
* daemon started successfully *
Physical size: 1080x1920
Density: adb server is out of date.  killing...
* daemon started successfully *
Physical density: 480
DeviceType: adb server is out of date.  killing...
* daemon started successfully *
OD103
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
**********
adb server is out of date.  killing...
* daemon started successfully *
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
adb server is out of date.  killing...
* daemon started successfully *
2634 KB/s (210720 bytes in 0.078s)
采用方式0获取截图
adb server is out of date.  killing...
* daemon started successfully *
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
adb server is out of date.  killing...
* daemon started successfully *
2406 KB/s (210720 bytes in 0.085s)
scan_start_y:  690
Traceback (most recent call last):
  File "123.py", line 288, in <module>
    main()
  File "123.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "123.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

通为坚果Pro 1报错

**Comment by AndrWang** [comment]
#501
