### ISSUE TITLE
分数被清0

### ISSUE THREAD

**Issue by dyyshr** [wangshub/wechat_jump_game#493]
机型：一加3 
使用自动跳脚本刷到600多分，刚刚看的时候发现排行榜上自己的分数已经是0分了。
随便跳了几下显示的是最新记录。
这是被微信发现刷分了吗
怎么解决呢？

**Comment by RichardWeiYang** [comment]
啊，现在600就被干掉了啊

**Comment by wjzhangcsu** [comment]
下面是随便瞎扯淡：你可以手动和脚本结合刷分~

**Comment by BruceChen5683** [comment]
我先刷的2000的，还是手动和自动结合，半自动化可以。哈哈

**Comment by Vg1ee** [comment]
刷太高会没朋友的，我17000+没被清零，但是会被很多微信好友问候

**Comment by dyyshr** [comment]
我这次手动和脚本结合刷了500多分 看看会不会被清掉

**Comment by dyyshr** [comment]
好玩了 我刷了500多分 然后之前的被清掉的650分的记录回来了

**Comment by limingyao** [comment]
分数每周一凌晨清零

**Comment by AndrWang** [comment]
分数每周一凌晨清零，哈哈哈哈

**Comment by ondutya** [comment]
每次都跳正中是会被怀疑- -，是不是加个混淆，随机偏一些，但也别跳出去，就能避免被发现？
