### ISSUE TITLE
Mac + 小米Note3 脚本无法工作

### ISSUE THREAD

**Issue by yangfan21** [wangshub/wechat_jump_game#495]
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: Mi Note 3
OS: darwin
Python: 2.7.14 (default, Sep 25 2017, 09:54:19)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

**Comment by yangfan21** [comment]
脚本一直在执行  然而一直没什么用

**Comment by B4i** [comment]
去开发者里面把安全调试打开

**Comment by yangfan21** [comment]
肯定是打开的啊
