### ISSUE TITLE
mi6无法执行

### ISSUE THREAD

**Issue by yhongm** [wangshub/wechat_jump_game#497]
**********        
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: darwin
Python: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

提示语法错误，以下为日志
scan_start_y:  690
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by DEMON3** [comment]
同~

**Comment by AurosG** [comment]
米5同  20分钟前版本还可以的

**Comment by DEMON3** [comment]
改下202行，加个强转就好了
