### ISSUE TITLE
算法改进的建议

### ISSUE THREAD

**Issue by xjy2017y** [wangshub/wechat_jump_game#498]
其实不需要计算y的坐标吧，只用计算出棋子的x坐标以及下一个跳转点的x坐标，abs(x1-x2)其实也是与跳的距离成正比的。我用大牛的代码稍微修改了下，只用棋子的x坐标以及跳转点的x坐标，再把跳转系数除以了个cos30度（大概是成这个角度），运行发现也是可以准确跳到目标位置的。                      --by 一只python小菜鸟

**Comment by Vg1ee** [comment]
这个项目最原始的方案就是这样的，但是这样会带来很多错误，所以才有后续的更改。详细你可以去翻翻之前的issue有人有截图
