### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by Esteban912** [wangshub/wechat_jump_game#499]
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 8, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'

**Comment by xjy2017y** [comment]
目录下敲  pip install -r requirements.txt

**Comment by BruceGui** [comment]
依赖安装了吗

```bash
pip install -r requirements.txt
```

**Comment by zehuichen123** [comment]
PIL现在已经不用了 你安装pillow 二楼的方法里就包含了安装pillow的过程

**Comment by mkby** [comment]
`conda install Pillow`

**Comment by 918Wu** [comment]
pip3 install Pillow
