### ISSUE TITLE
关于测量误差, 其实还有个关键点

### ISSUE THREAD

**Issue by boolean93** [wangshub/wechat_jump_game#5]
实际使用的时候，遇到`有一定几率`测量准确，`也有一定几率`测量出现误差的情况。

仔细观察了一下，有一个原因是：
当你在某一个方块跳歪了的同时转向， 测量的距离就100%会有误差。此时起始点不能是人，而是人投影在方块中线上的那个点。

这种情况在现在简单实现的基础上并不是特别好处理。可以先实现人的识别，以及方块的识别（比如说边缘检测啊这种）。

**Comment by binderclip** [comment]
似乎不是这样的。如果在当前的块上是靠前的，那么下一次跳的距离是正确的，虽然转了向，但依然是靠前的。
所以应该点击调整过的那个位置。
