### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by imliujun** [wangshub/wechat_jump_game#501]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MHA-AL00
OS: darwin
Python: 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
**********
采用方式1获取截图
scan_start_y:  690
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by GeekArtisan** [comment]
同

**Comment by xmdanni** [comment]
同

**Comment by BruceGui** [comment]
试试用 int() 函数转换一下看看行不行

**Comment by xfr3837** [comment]
同

**Comment by imliujun** [comment]
我不会Python，谁能修复测试一下，然后贴一下代码？

**Comment by zehuichen123** [comment]
同

**Comment by BruceGui** [comment]
找到  board_x_start 在的那个 循环 如下：

```python
for j in range(board_x_start, board_x_end):
```

然后修改为如下：

```python
for j in range(int(board_x_start), int(board_x_end)):
```

**Comment by imliujun** [comment]
@BruceGui 按照你的代码修改好了，现在可以运行了，O(∩_∩)O谢谢
