### ISSUE TITLE
auto脚本报错

### ISSUE THREAD

**Issue by blankminder** [wangshub/wechat_jump_game#502]
Screen: Physical size: 1440x2560
Density: Physical density: 560
DeviceType: XT1570
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
**********
采用方式1获取截图
scan_start_y:  1003
1514809868 0 0 0 0
adb shell input swipe 720.0 2112 720.0 2112 200
scan_start_y:  953
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by BruceGui** [comment]
https://github.com/wangshub/wechat_jump_game/issues/501
