### ISSUE TITLE
用大神的算法做了个硬件版，iOS适用

### ISSUE THREAD

**Issue by yangyiLTS** [wangshub/wechat_jump_game#506]
在iOS和Windows上运行，免mac安装WDA
[wechat_jump_game_iOS](https://github.com/yangyiLTS/wechat_jump_game_iOS)

**Comment by shimminZ** [comment]
@yangyiLTS   点击进去404

**Comment by yangyiLTS** [comment]
@shimminZ sorry~链接贴错了 已改
