### ISSUE TITLE
几个计算坐标出错的图片

### ISSUE THREAD

**Issue by zegzhi** [wangshub/wechat_jump_game#507]
![1514810361_d](https://user-images.githubusercontent.com/16538800/34467752-478c7882-ef35-11e7-90e4-69537debf72d.png)
![1514810378_d](https://user-images.githubusercontent.com/16538800/34467756-4cc11f60-ef35-11e7-8680-ef498141efdd.png)
![1514810621_d](https://user-images.githubusercontent.com/16538800/34467757-518b81fc-ef35-11e7-8df8-825c6dd3a656.png)
![1514810638_d](https://user-images.githubusercontent.com/16538800/34467758-54174ea6-ef35-11e7-80fa-f2a63b5bce4b.png)

**Comment by AurosG** [comment]
这个线和点怎么调出来的？

**Comment by Vg1ee** [comment]
收到，谢谢反馈

**Comment by Vg1ee** [comment]
@AurosG 在screenshot_backups文件夹里面
