### ISSUE TITLE
华为P9 plus脚本运行只截了一张图就闪退了

### ISSUE THREAD

**Issue by Imegali** [wangshub/wechat_jump_game#508]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: VIE-AL10
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
![autojump](https://user-images.githubusercontent.com/33613487/34467765-7ccada7a-ef35-11e7-825b-f30a80afa309.png)

**Comment by chenjiandongx** [comment]
请使用最新版本的代码
