### ISSUE TITLE
MX4 

### ISSUE THREAD

**Issue by ShohanPeng** [wangshub/wechat_jump_game#509]
**********
Screen: Physical size: 1152x1920
Density: Physical density: 480
DeviceType: MX4
OS: darwin
Python: 3.6.3 (default, Dec  5 2017, 11:46:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
**********

**Comment by Vg1ee** [comment]
你是出现什么错误了呢？

**Comment by ShohanPeng** [comment]
跑不起来 然后根据报错把这段错误代码粘出来了
1152x1920  480 的设备可以把  press_coefficient 的值设置为 1.3 可以跑到两千多分

**Comment by enfangzhong** [comment]
我的就是MX4  可是跑了20多步就停了
