### ISSUE TITLE
魅族MX5，1080p；不是每一次都是正中心 0.0

### ISSUE THREAD

**Issue by genericyzh** [wangshub/wechat_jump_game#51]
魅族MX5，1080p；不是每一次都是正中心 0.0

**Comment by binderclip** [comment]
现在只能做到一直跳下去，每次正中心是最终的目标

**Comment by genericyzh** [comment]
@binderclip 能设置跳跃速度吗？目前跳得有点慢，哈哈

**Comment by genericyzh** [comment]
第二次跑只跑到了400+分~

**Comment by binderclip** [comment]
[参数不行的发这里 · Issue #62 · wangshub/wechat_jump_game](https://github.com/wangshub/wechat_jump_game/issues/62)

**Comment by ZhaoGuojing** [comment]
魅族MX5求参数

**Comment by genericyzh** [comment]
@ZhaoGuojing 默认代码，没修改过
