### ISSUE TITLE
坚果 Pro1问题

### ISSUE THREAD

**Issue by AndrWang** [wangshub/wechat_jump_game#511]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OD103
OS: darwin
Android Version：7.1.1
Python: 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
刚开始两步正确，后面出现这样了
![](https://ws3.sinaimg.cn/large/006tNc79gy1fn1enezv5fj30u01hc41s.jpg)

**Comment by MrLevo520** [comment]
锤子系列手机请关闭大爆炸功能即可通过

**Comment by AndrWang** [comment]
3q

**Comment by fengbaoshuan** [comment]
确实，开大爆炸截不了图，关闭后6的一笔
