### ISSUE TITLE
方向出错汇总

### ISSUE THREAD

**Issue by cxgreat2014** [wangshub/wechat_jump_game#517]
![image](https://user-images.githubusercontent.com/15062548/34467913-5e64d9f2-ef38-11e7-8409-70b7a6b0af30.png)
![image](https://user-images.githubusercontent.com/15062548/34467914-64b4d64a-ef38-11e7-8dc2-9a0cc3bdfed4.png)
![image](https://user-images.githubusercontent.com/15062548/34467917-7e08a14e-ef38-11e7-93d0-a6f5f8791f49.png)
![image](https://user-images.githubusercontent.com/15062548/34467918-82e697f2-ef38-11e7-9349-d1a069a193ba.png)
![image](https://user-images.githubusercontent.com/15062548/34467921-95ad9f3e-ef38-11e7-9cbf-0f2b899fd258.png)
![image](https://user-images.githubusercontent.com/15062548/34467923-9a59670c-ef38-11e7-82ff-97c76bab1d96.png)

**Comment by cxgreat2014** [comment]
音符的BUG好像还没修完。。？

**Comment by Vg1ee** [comment]
音乐盒的bug是因为图形上面做了玻璃的半透明效果，没有办法取到上下颜色相同的两个点

**Comment by cxgreat2014** [comment]
![image](https://user-images.githubusercontent.com/15062548/34467940-f7d84b78-ef38-11e7-8e8d-b78caa3266b0.png)
![image](https://user-images.githubusercontent.com/15062548/34467943-00eccc34-ef39-11e7-84a9-b1d846d849e0.png)
![image](https://user-images.githubusercontent.com/15062548/34467949-21980b6a-ef39-11e7-9806-3ffc92ad3383.png)
![image](https://user-images.githubusercontent.com/15062548/34467951-25f65964-ef39-11e7-832d-5e574bbda559.png)
![image](https://user-images.githubusercontent.com/15062548/34467954-38aada94-ef39-11e7-9469-9e3feec3efe5.png)
![image](https://user-images.githubusercontent.com/15062548/34467955-3e16747a-ef39-11e7-96d9-8ccccdd8c500.png)
emm感觉好像还没下午的识别率高。。不知道是微信更新了还是新算法的问题

**Comment by lstk520** [comment]
![1514807642_d](https://user-images.githubusercontent.com/7270898/34467999-d3aac1d0-ef39-11e7-92b6-3ba5824cabac.png)
![1514807646_d](https://user-images.githubusercontent.com/7270898/34468000-d62373ee-ef39-11e7-83c9-7ada4dad4df5.png)

最新的是不是有bug

**Comment by AurosG** [comment]
![1514812877_d](https://user-images.githubusercontent.com/35000515/34468032-696b3bf0-ef3a-11e7-852c-558fb17a12d8.png)

**Comment by cxgreat2014** [comment]
新算法。。五盘成绩：
30
155
138
28
221
老算法：
129
288
161
312
。。。。
好像老算法还靠谱些。。

另外新发现。。
![image](https://user-images.githubusercontent.com/15062548/34468085-3aa1d278-ef3c-11e7-85aa-e0f4d3a4b806.png)
![image](https://user-images.githubusercontent.com/15062548/34468086-4109a4c4-ef3c-11e7-983d-204e5f725612.png)

**Comment by cxgreat2014** [comment]
老算法最新一局：308
![image](https://user-images.githubusercontent.com/15062548/34468101-b242d124-ef3c-11e7-976b-7cfdf4350987.png)
![image](https://user-images.githubusercontent.com/15062548/34468102-b68b2f60-ef3c-11e7-9e0c-081fd4b35920.png)
![image](https://user-images.githubusercontent.com/15062548/34468104-bac1bb76-ef3c-11e7-9619-1cb73c3a6817.png)
桑心。。

**Comment by Vg1ee** [comment]
@cxgreat2014 喵喵喵我连续刷到了17000+了晕，图的这个是因为sleep不够长吧你试试改下那个参数

**Comment by Vg1ee** [comment]
@cxgreat2014 等下，你的分辨率不是1080*1920？

**Comment by cxgreat2014** [comment]
不是，我的是540x960，另外新版的好像写死了是续1s？
https://github.com/wangshub/wechat_jump_game/blob/master/wechat_jump_auto.py#L284
emmm我试着增大一下。。
不过我的是老代码跑的，自己设置的是`time.sleep(random.uniform(1.1, 1.6))`，这个时候应该是落稳了呀。。

**Comment by igwen6w** [comment]
![1514801421_d](https://user-images.githubusercontent.com/24996622/34468140-866455fe-ef3d-11e7-9cab-9d1b6f84a9a7.png)
从左往右跳的时候，一直都无法计算到正确的中心点；
因为开局都是从左往右，所以一直都是0分；
谷歌6儿子，1440*2560；
当我手动跳到，从右往左的时候，就可以正常识别中心点；
如图：
![1514814702_d](https://user-images.githubusercontent.com/24996622/34468170-387c3e78-ef3e-11e7-98a0-527ac5527361.png)
![1514814706_d](https://user-images.githubusercontent.com/24996622/34468171-38bcb8e0-ef3e-11e7-83f7-2e60d6946826.png)

**Comment by cxgreat2014** [comment]
![image](https://user-images.githubusercontent.com/15062548/34468196-ad957eae-ef3e-11e7-8aef-6444555c8054.png)
![image](https://user-images.githubusercontent.com/15062548/34468200-b43c23fc-ef3e-11e7-85ac-f59928e570ac.png)
好险。。
要不上tensorflow来训练一波？（滑稽）

**Comment by cxgreat2014** [comment]
最新版本算法。。：
![image](https://user-images.githubusercontent.com/15062548/34468221-44583a16-ef3f-11e7-95f1-e487a55a2aaa.png)
![image](https://user-images.githubusercontent.com/15062548/34468223-49981faa-ef3f-11e7-93c7-d6b15e8602f3.png)
![image](https://user-images.githubusercontent.com/15062548/34468226-4f05979c-ef3f-11e7-9c4b-124cf1f3e635.png)
GG
另外有支付宝收款码吗？或者红包码也行，来一波
