### ISSUE TITLE
cp不是内部命令？

### ISSUE THREAD

**Issue by SbyXlmm** [wangshub/wechat_jump_game#52]
![ke reko4oamv2x007 fv49](https://user-images.githubusercontent.com/18278015/34451429-4f231776-ed60-11e7-9c29-d5f42a1fd94e.png)

**Comment by mayaxcn** [comment]
这个可以直接注释掉，只是作者作为调试之用

**Comment by sin-x** [comment]
windows下应为 'copy'

**Comment by xulinfu** [comment]
为什么我改完还是没用，求大佬指教

**Comment by xulinfu** [comment]
执行到“运行python wechat_jump_auto.py”，请问然后怎么弄？分数没有变化啊
![snipaste_20171230_144321](https://user-images.githubusercontent.com/33155648/34451970-47786926-ed70-11e7-9543-64c5517943d2.png)

**Comment by binderclip** [comment]
https://github.com/wangshub/wechat_jump_game/pull/67
