### ISSUE TITLE
请安装ADB及驱动并配置环境变量

### ISSUE THREAD

**Issue by elileo1** [wangshub/wechat_jump_game#523]
这个要怎么配置

**Comment by yiranzai** [comment]
这种也要提交个issues的吗?[点击这里](http://www.baidu-x.com/?q=%E6%B7%BB%E5%8A%A0%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

**Comment by MrLevo520** [comment]
这个问题目前正在解决，资源已上传，稍晚时候会更新
