### ISSUE TITLE
优化安卓自动跳的代码（wechat_jump_auto.py）

### ISSUE THREAD

**Issue by redone2000** [wangshub/wechat_jump_game#525]
- 优化跳跃距离过短时，不容易跳到中心点的问题
 - 优化完+调参后，（小米6）根本不会死

**Comment by redone2000** [comment]
顺便附上小米6的不会死参数

{
    "under_game_score_y": 300,
    "press_coefficient": 1.39,
    "piece_base_height_1_2": 20,
    "piece_body_width": 75,
    "swipe" : {
      "x1": 560,
      "y1": 1550,
      "x2": 560,
      "y2": 1550
    }
}

要注意看程序调用的是哪个目录下的哪个json，修改对应的

**Comment by redone2000** [comment]
已提交Pull request #532

**Comment by wjycom** [comment]
改了之后也没跳到中间唉，你这参数是试出来的吗？还是怎么得来的
