### ISSUE TITLE
adb device offline，不是数据线的问题。。

### ISSUE THREAD

**Issue by WhitLor** [wangshub/wechat_jump_game#527]
cmd里总是offline，
![image](https://user-images.githubusercontent.com/34998894/34468057-65b5ffd0-ef3b-11e7-941e-f4b565421e1a.png)，
但进到文件夹里就没有了，
![image](https://user-images.githubusercontent.com/34998894/34468063-9cdc0a7c-ef3b-11e7-8307-eb88e4adc7dc.png)
但最后还是不行..
![image](https://user-images.githubusercontent.com/34998894/34468069-c1b7b95e-ef3b-11e7-9a28-f2047db8f461.png)
小白求教~~

**Comment by WhitLor** [comment]
换手机也是这样，应该不是数据线的问题  之前完成了添加环境变量

**Comment by liangxinhui** [comment]
手机点击允许usb调试了吗？

**Comment by WhitLor** [comment]
点了的，进文件夹的时候有device，直接cmd就会offline

**Comment by wangshub** [comment]
建议先百度试试
