### ISSUE TITLE
1440x2560分辨率如何设置参数啊，总是个位数就结束

### ISSUE THREAD

**Issue by pplps** [wangshub/wechat_jump_game#53]
身边就一台lg v31，分辨率1440x2560，参数总是搞不对，哪位帮下参数设置多少合适啊

**Comment by wangqq335** [comment]
2560x1440像素怎么设置参数同求三星note4

**Comment by hiyoi** [comment]
我是锤子M1L，2K分辨。用这些参数

under_game_score_y = 390  
press_coefficient = 1.04 
piece_base_height_1_2 = 26  
piece_body_width = 110

**Comment by dugu0808** [comment]
三星s6edge试了上面的参数，不行呀。。

**Comment by V1sk** [comment]
三星S7 Edge同求，楼上参数也不行

**Comment by supernb123** [comment]
荣耀v9 按上面的参数调整 到66分就死了 囧

**Comment by binderclip** [comment]
@hiyoi 帮忙贴在那边吧 [好用的参数发到这里 · Issue #61 · wangshub/wechat_jump_game](https://github.com/wangshub/wechat_jump_game/issues/61)

**Comment by binderclip** [comment]
[参数没设置好的发这里 · Issue #62 ](https://github.com/wangshub/wechat_jump_game/issues/62)

**Comment by huimumua** [comment]
求1440x2560参数啊，谢谢大神。
