### ISSUE TITLE
小米手机请关闭浮悬球，否则会影响图像分析

### ISSUE THREAD

**Issue by YxxY** [wangshub/wechat_jump_game#533]
版本日期：Mon Jan 1 19:50:56 2018 +0800
算法还是有不严谨的地方，向左跳时成功率极低，无关近远。向右基本没问题。

![](http://opxo4bto2.bkt.clouddn.com/1514814145_d.png)
![](http://opxo4bto2.bkt.clouddn.com/1514814122_d.png)

**Comment by Vg1ee** [comment]
你屏幕左边那个是啥，能关掉不？

**Comment by igwen6w** [comment]
我这里是向左跳，没问题，向右跳全部GG；

**Comment by YxxY** [comment]
上传之后就看到我的浮悬球了，我关掉再试试 :laughing:

**Comment by YxxY** [comment]
浮悬球影响了图像分析
