### ISSUE TITLE
发现个小问题但是我不会玩GayHub所以等大佬们修改吧

### ISSUE THREAD

**Issue by guolaopi** [wangshub/wechat_jump_game#535]
在自动执行的那个脚本里，
行号202 处报错，无法将float转为int，我print了一下发现循环时候传的参数board_x_start, board_x_end不知道为什么我这里是个小数。

所以我在前面为board_x_start, board_x_end赋值时候都对结果进行了int转换，然后正常了。

如果不是BUG的话求大佬解释

**Comment by Vg1ee** [comment]
#501
