### ISSUE TITLE
关于distance 与 press_time的函数关系

### ISSUE THREAD

**Issue by Alienover** [wangshub/wechat_jump_game#536]
源代码上是直接用了线性关系，但测试多次过后，发现，当距离短的时候，程序跳的距离比较短，当距离比较远的时候，程序跳的距离预想的还远，因此，如果按压时间与距离的函数关系没有确切的函数表达式出来之前，可以对其线性关系进行修复。
下面是我使用的一个简易的办法
``` python
def fix_press_time(press_time):
    if press_time > 1000:
        press_time = press_time - 70
    elif press_time < 700:
        press_time = press_time + 70
    return press_time
```
思路就是，当按压时间超过1000ms时，将其减少，防止其跳出去；当按压时间小于700ms，增加按压时间，防止其跳不过去。
当然，上面700ms 和1000ms 是我个人测试时用的，具体，还应详细测试

**Comment by Vg1ee** [comment]
简单粗暴，实用性待考究

**Comment by cxgreat2014** [comment]
要不把小程序源码读一遍？看看到底怎么实现的这一部分，（滑稽

**Comment by ddgboy** [comment]
的确简单粗暴，不过经过我验证后非常NB，之前一直过不去300分，就是因为这些非常短距离的跳少了。Very Very Nice！估计真的不是线性关系，这个简单粗暴的修复能解决大问题！！
