### ISSUE TITLE
自动的那个程序出现这个问题，求教大神，谢谢

### ISSUE THREAD

**Issue by Jasper2018** [wangshub/wechat_jump_game#541]
C:\Users\1\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/1/Desktop/untitled0.py
Traceback (most recent call last):
  File "C:/Users/1/Desktop/untitled0.py", line 61, in <module>
    config = open_accordant_config()
  File "C:/Users/1/Desktop/untitled0.py", line 44, in open_accordant_config
    with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\1\\Desktop/config/default.json'

Process finished with exit code 1

**Comment by Jasper2018** [comment]
求帮助

**Comment by zengke123** [comment]
C:\Users\1\Desktop/config/default.json

这个目录下有这个文件吗

**Comment by Jasper2018** [comment]
@zengke123 没有，可是这个文件哪里来的？

**Comment by zengke123** [comment]
config目录下，取下来放到对应目录中

**Comment by AlienMarkWang** [comment]
解压下载下来的zip，config文件夹中按照你的分辨率选取适当的config.json，默认的是default.json。
你可以把config这个文件夹直接全部copy到你.py脚本的运行目录。
