### ISSUE TITLE
小米4c基本跳不到中心点，最高260分

### ISSUE THREAD

**Issue by 286471320** [wangshub/wechat_jump_game#542]
机型：小米4c
分辨率：1920 * 1080
电脑系统：win 10
问题描述：小米4c基本跳不到中心点，最高260分，平均80 90 分左右
press_coefficient: 试了1.392，1.475，1.50 都不行
![1514816974_d](https://user-images.githubusercontent.com/34777741/34468439-e040c0ac-ef43-11e7-91a6-63f8c66c08d1.png)
![1514816970_d](https://user-images.githubusercontent.com/34777741/34468440-e4e918b6-ef43-11e7-8422-f2ac0709ecab.png)

**Comment by 286471320** [comment]
额。。。press_coefficient调成1.47成功破500了。。。

**Comment by PantomZ** [comment]
你现在配置是什么样的。我也是小米4c，最多35.求配置噢。

**Comment by 286471320** [comment]
press_coefficient 1.47-1.475成绩最好，但是现在基本上突破不了150.。。。。我用舍友的三星，把把正中靶心，一下子3000+。。。。

**Comment by PantomZ** [comment]
`{
    "under_game_score_y": 300,
    "press_coefficient": 1.393,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}`.我用这个突破400了

**Comment by 286471320** [comment]
我用1.393一下子就GG了。。。

**Comment by PantomZ** [comment]
https://github.com/burningcl/wechat_jump_hack.用java版本的。
