### ISSUE TITLE
求几个因为音符出错的截图,尝试修复一下

### ISSUE THREAD

**Issue by Sowevo** [wangshub/wechat_jump_game#543]

**Comment by Vg1ee** [comment]
缩窄x搜索范围之后好像就没遇到过这样的问题了

**Comment by bytew021** [comment]
![1514905545](https://user-images.githubusercontent.com/34959513/34488155-6592d140-f012-11e7-8443-2eec3dde7274.png)
![1514905545_d](https://user-images.githubusercontent.com/34959513/34488156-65c1a15a-f012-11e7-8b62-5ddde9fa141c.png)
