### ISSUE TITLE
求教 anaconda里面自带的编辑器Spyder怎么和adb命令行联系起来

### ISSUE THREAD

**Issue by Jasper2018** [wangshub/wechat_jump_game#546]
我的pycharm，电脑shell输入adb有反应，环境运行正常，可以运行这个wechat_jump的程序，没问题

我想用Spyder这个，anaconda里面不是自己有命令行嘛，输入adb没反应，所以这个python的程序运行不了

就想知道anaconda如何把adb环境配置好
还请大神教一教，困扰好多天了，谢谢啦

**Comment by Jasper2018** [comment]
求帮助

**Comment by cxgreat2014** [comment]
你可以试下把adb放到anaconda能找到的位置？

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
