### ISSUE TITLE
红米5

### ISSUE THREAD

**Issue by xuegaomian** [wangshub/wechat_jump_game#550]
分辨率1440*720

**Comment by xuegaomian** [comment]
不知道这是怎么计算的！求教

**Comment by wangshub** [comment]
源码以及基本操作：
[https://github.com/wangshub/wechat_jump_game](https://github.com/wangshub/wechat_jump_game)
- 视频详解https://www.bilibili.com/video/av17796840/?redirectFrom=h5
- 第一：确保电脑有Python环境以及Python的环境变量（建议Python3版本，不会装暂时先谷歌哦！ pip的环-境变量一定要设置好！ Python下载: https://www.python.org/downloads/）
- 第二：通过pip install -r requerest.txt 安装Python的运行库（确保是在你解压或者git clone下来的目录下）
- 第三：确保adb安装，详情看github文档
- 第四：确保手机的 usb调试功能打开
- 第五，不要直接双击打开，在终端(cmd )里 python xx.y运行

**Comment by SomnusWu** [comment]
红米5 一步也跳不了~~~
