### ISSUE TITLE
请求开发人员尽快解决 谢谢！

### ISSUE THREAD

**Issue by bosspanda01** [wangshub/wechat_jump_game#551]
机型：小米 note4x
分辨率（具体到宽高）：1920X1080
电脑系统：win10
问题描述：不稳定一会跳100多一会200-400就失败了
这是现在的参数，还算跳的稳点，最多400多，不然只能100多：
{
    "under_game_score_y": 300,
    "press_coefficient": 1.492,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1602
    }
}
![问题图片](https://t1.picb.cc/uploads/2018/01/01/RX4YK.png)

**Comment by forilux** [comment]
@bosspanda01 我也是4X，和你一样情况，然而另一部NOTE4正常。应该是手机的问题，或者升级了MIUI9.0?

**Comment by bosspanda01** [comment]
@forilux 可能是手机系统问题，但也不应该呀

**Comment by VitalyAnkh** [comment]
代码最核心的计算跳跃时间的一行用了误差比较大的函数，请参考这个pr https://github.com/wangshub/wechat_jump_game/pull/229/files

**Comment by bosspanda01** [comment]
@VitalyAnkh 非常感谢，通过你的方法优化后分数可以到500多了

**Comment by zoyeal** [comment]
不行啊，不到100就死了
