### ISSUE TITLE
BlueStacks运行显示当前设备系统不支持小程序

### ISSUE THREAD

**Issue by zl20154312** [wangshub/wechat_jump_game#552]
如题，是在源代码里屏蔽了？

**Comment by yzqin** [comment]
并没有屏蔽，是因为版本的问题。
点击微信中右下角的“我”，在“设置”里手动更新到微信最新版即可

**Comment by MrLevo520** [comment]
请更新到最新版微信即可

**Comment by Ryan2Archibald** [comment]
直接在微信官网下最新版6.6.1的apk，然后安装。 不要安装Bluestacks市场里自带的apk。我遇到这个问题，亲测有效
