### ISSUE TITLE
问题及建议

### ISSUE THREAD

**Issue by Sleepincoffee** [wangshub/wechat_jump_game#553]
1.目前有些格子的彩蛋目前的停顿时间可以触发，但音乐盒的识别效果很差(音乐盒识别的跳跃点在表面最高点)，
2.其次短时间的跳跃出现了截图并没有在跳跃完成阶段，可以在很短时间内截图俩张然后对比图片来判断是否完成了跳跃动作
3.看了几次失败都是蘑菇头的凳子点计算很不准，可以改进下算法
谢谢

**Comment by Vg1ee** [comment]
1. 的确目前的算法对音乐盒的识别很差，但如果中心有白点就能准确识别中心，而音乐盒面积比较大一般也不会掉下去
2. 截图pull上来的速度好像也不快，可以考虑考虑
3. 有没有截图提供来学习一下？

**Comment by Sleepincoffee** [comment]
嗯~昨天图片没上传成功，而且删除了、等下看看、

**Comment by Sleepincoffee** [comment]
https://github.com/zhanyongsheng/LetsJump 这个项目里有判断游戏是否结束方法，这样是可以先把最后失败的图片单独放一个文件夹，需要我push嘛
`# 判断是否游戏失败到分数页面
def has_die(x_in):
    # 判断左上右上左下右下四个点的亮度
    if (x_in[0][0][0][0] < 0.4) and (x_in[0][0][len(x_in[0][0]) - 1][0] < 0.4) and (
        x_in[0][len(x_in[0]) - 1][0][0] < 0.4) and (x_in[0][len(x_in[0]) - 1][len(x_in[0][0]) - 1][0] < 0.4):
        return True
    else:
        return False`

**Comment by Sleepincoffee** [comment]
嗯~昨天图片没上传成功，而且删除了、等下看看、
[https://github.com/zhanyongsheng/LetsJump](url)
这个项目里有判断游戏是否结束方法，这样是可以先把最后失败的图片单独放一个文件夹，需要我push嘛
`# 判断是否游戏失败到分数页面
def has_die(x_in):
    # 判断左上右上左下右下四个点的亮度
    if (x_in[0][0][0][0] < 0.4) and (x_in[0][0][len(x_in[0][0]) - 1][0] < 0.4) and (
        x_in[0][len(x_in[0]) - 1][0][0] < 0.4) and (x_in[0][len(x_in[0]) - 1][len(x_in[0][0]) - 1][0] < 0.4):
        return True
    else:
        return False`
