### ISSUE TITLE
小米6的参数 win7

### ISSUE THREAD

**Issue by Evenever** [wangshub/wechat_jump_game#559]
{
    "under_game_score_y": 300,
    "press_coefficient": 1.420,
    "piece_base_height_1_2": 25,
    

"piece_body_width": 78,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
"y2": 

- 1602

   }
}
![1514824476_d](https://user-images.githubusercontent.com/12467751/34469255-beadba82-ef55-11e7-8aed-662021b72870.png)

      

跳到正中心的不多 这是七百多的参数，中间正在调的时候改了，不知道有没有生效

**Comment by fu9852531** [comment]
调整了   正在试
