### ISSUE TITLE
[讨论]] 关于长距离跳跃讨论

### ISSUE THREAD

**Issue by 918Wu** [wangshub/wechat_jump_game#562]
跳一跳按压时会伴随着音乐，实地上手玩的时候感觉在第二个八度之后音调的变化会逐渐变快，跳同样距离所需的按压时间会缩短，运行程序跳的时候也发现超长距离跳跃时会超过中心，靠近边缘的情况。不知是否有这方面的影响。

**Comment by VitalyAnkh** [comment]
不是音乐的影响。代码中计算时间是用的是线性函数，但实际上跳跃距离与按压时间是非线性的关系，按得时间越长跳跃距离增加速度越大，所以越远越偏离中心。参考这个pr https://github.com/wangshub/wechat_jump_game/pull/229/files
