### ISSUE TITLE
哈哈，计算公式已搞出！

### ISSUE THREAD

**Issue by baolw** [wangshub/wechat_jump_game#564]
现在combo到飞起，导致最后死的原因是因为combo的波纹影响到取中心点了

**Comment by Vg1ee** [comment]
求pull？

**Comment by qiyv00** [comment]
？

**Comment by baolw** [comment]
@Vg1ee 晚点Pull一个，估计pull完，官方都知道了

**Comment by binderclip** [comment]
是根据 JS 源码推的？

**Comment by HJH12315** [comment]
求思路～

**Comment by baolw** [comment]
@binderclip 是的，昨晚看了很久

**Comment by binderclip** [comment]
@baolw 求 pull 😂

**Comment by chloechj** [comment]
拟合出来的？

**Comment by baolw** [comment]
@chloechj 拟合是啥意思啊。反正我是看了js代码，算出来的

**Comment by HJH12315** [comment]
@baolw 求pull~

**Comment by chloechj** [comment]
根据数据算呗，距离跟时间的数据集，线性拟合出函数关系，非线性神经网络拟合

**Comment by baolw** [comment]
@chloechj 好吧，不太懂这个，我就是根据js代码里的东西算的，现在在公司上班，不太好搞这个，晚上回家了，我整理一下，说不定以后可以不需要试那几个参数了。

**Comment by binderclip** [comment]
@baolw 继续求整理思路

**Comment by kajweb** [comment]
怎么获得js?

**Comment by simonsmh** [comment]
@kajweb 帮大家拆包上传了一份
https://github.com/simonsmh/wechat-jump-source
V5加密了，可以用V4分析

**Comment by maxlv7** [comment]
# tes

**Comment by baolw** [comment]
@binderclip pull了，你看一下，昨天比较忙没整理好

**Comment by baolw** [comment]
@HJH12315 pull了，你看一下

**Comment by baolw** [comment]
@Vg1ee pull了，你看一下

**Comment by baolw** [comment]
@binderclip 可以帮忙验证一下其他机型是否有效

**Comment by Eacaen** [comment]
增加一点延时在截图时可以错过波纹，连击大概10到１５次会有一次不准，不知道是不是误差的累计，
请问有没有什么好办法快速找到原因。手机是　小米mix２,　有一次最高跳过１００００＋，大概是运气好。
