### ISSUE TITLE
红米3 支持？

### ISSUE THREAD

**Issue by txy2539** [wangshub/wechat_jump_game#567]
**********
Screen: /system/bin/wm[6]: app_process: can't execute: Permission denied
Density: /system/bin/wm[6]: app_process: can't execute: Permission denied
DeviceType: Redmi 3
OS: win32
Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
**********
暂不支持当前设备

**Comment by xinghee** [comment]
亲测，支持

**Comment by mmdet** [comment]
Screen: /system/bin/wm[6]: app_process: can't execute: Permission denied
Density: /system/bin/wm[6]: app_process: can't execute: Permission denied
DeviceType: Redmi 3
OS: win32
Python: 3.5.4 (v3.5.4:3f56838, Aug 8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]

**Comment by mmdet** [comment]
也是不支持
