### ISSUE TITLE
模拟器1920*1080，用wechat_jump_auto.py完全就是瞎跳，不懂为什么。。

### ISSUE THREAD

**Issue by HarveyEL** [wangshub/wechat_jump_game#569]
Load default config
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1920x1080
Density: Physical density: 240
DeviceType: SAMSUNG-SM-N900A
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
**********
采用方式1获取截图
scan_start_y:  310
1514835662 800 346 1394.5 498
adb shell input swipe 960.0 891 960.0 891 854
scan_start_y:  310
1514835680 839 413 1414.0 498
adb shell input swipe 960.0 891 960.0 891 809

**Comment by HarveyEL** [comment]
![1514835905_d](https://user-images.githubusercontent.com/35004950/34470577-9ec0349c-ef6f-11e7-8ec5-3966f5371049.png)
![1514835908_d](https://user-images.githubusercontent.com/35004950/34470578-9ef49778-ef6f-11e7-9429-127f743dc6a3.png)
![1514835914_d](https://user-images.githubusercontent.com/35004950/34470579-9f25f3c2-ef6f-11e7-8e63-f1363800b6a8.png)

**Comment by DipperStar** [comment]
在模拟器设置里，自定义分辨率，把横轴和纵轴交换

**Comment by Leo0618** [comment]
模拟器默认的dpi一般都很低，可以根据真实手机配置dpi 光是分辨率是不够的，密度也会影响像素量

**Comment by HarveyEL** [comment]
谢谢 已解决
