### ISSUE TITLE
一直报“Failed to establish a new connection”

### ISSUE THREAD

**Issue by GhostClock** [wangshub/wechat_jump_game#57]
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116590b70>: Failed to establish a new connection: [Errno 61] Connection refused',))
`
我是iOS，在本地浏览器上打开http://localhost:8100/status
能看见json数据，也做了端口转发 `iproxy 8100 8100` ，一直运行不成功

**Comment by SiliconZou** [comment]
我的是因为Max retries exceeded with url: /status 报的这个错，不懂为什么

**Comment by RickeyBoy** [comment]
@GhostClock 
你重新运行一下 WDA 试试呢？有时候之前一次崩了，下一次就运行不起来

**Comment by GhostClock** [comment]
@RickeyBoy @SiliconZou 
WDA是运行起来的，IP都打印了
```
Test Suite 'UITestingUITests' started at 2017-12-30 18:09:22.609
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.11s Start Test at 2017-12-30 18:09:22.721
    t =     0.11s Set Up
2017-12-30 18:09:22.737756+0800 WebDriverAgentRunner-Runner[13156:4215209] Built at Dec 30 2017 13:26:07
2017-12-30 18:09:22.781472+0800 WebDriverAgentRunner-Runner[13156:4215209] ServerURLHere->http://192.168.0.102:8100<-ServerURLHere
```
还是报错
<img width="1227" alt="2017-12-30 18 15 54" src="https://user-images.githubusercontent.com/10014166/34453348-ab2b8d46-ed8d-11e7-823d-6a900bee0d61.png">

**Comment by everyu** [comment]
@SiliconZou  我也是跑wechat_jump_iOS_py3这个脚本就报这个Max retries exceeded with url: /status错误，你怎么解决的？

**Comment by PrincipalsOffice** [comment]
我的wda test一直跑不起来，请问你是用的付费的苹果developer account吗

**Comment by everyu** [comment]
@PrincipalsOffice 免费的就行，需要把工程里的几个target都改一下id。
