### ISSUE TITLE
如果使用华为手机，需要安装华为手机助手才可正常使用ADB相关功能。

### ISSUE THREAD

**Issue by zzzzzigzag** [wangshub/wechat_jump_game#570]

**Comment by wingmeng** [comment]
亲测无需安装（华为畅玩版X5），装好 adb 工具及驱动，华为手机接入后，等待硬件识别，然后在手机通知栏选择 **USB模式**为 **管理文件**，运行 `adb devices` 如返回设备编号说明环境搭建成功，此时运行 python 脚本无误。

**Comment by axxxxa** [comment]
list of devievces attached
WTKDU16829008551     devieces
这是成功了吧
但是仍然出错，可以帮我看看不，之前问，评论还是说我的adb没弄好。错误如下
Traceback (most recent call last):
  
File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 61, in <module>
    config = open_accordant_config()
  
File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 34, in open_accordant_config
    screen_size = _get_screen_size()
  
File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 50, in _get_screen_size
    size_str = os.popen('adb shell wm size').read()
  
File "D:\Program Files\lib\os.py", line 978, in popen
    bufsize=buffering)
  
File "D:\Program Files\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  
File "D:\Program Files\lib\subprocess.py", line 990, in _execute_child
    
startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zzzzzigzag** [comment]
@axxxxa 这是适配屏幕分辨率时产生的问题
不妨注释掉screen_size相关的值
并将config_file的值做相应修改（手动选择config.json所在目录）
![image](https://user-images.githubusercontent.com/13139121/34472388-27a77550-ef9c-11e7-97c5-50d92ee10181.png)
这里我直接将所需的json文件放在了工作目录下

**Comment by zzzzzigzag** [comment]
@wingmeng 我是Mate 10 开USB调试后一直失败，折腾了好久
最后安装华为手机助手解决的
华为的ADB似乎有别于其他安卓设备
（HDB），具体我也没搞懂原因

**Comment by axxxxa** [comment]
按你那么改，没改好，又错了

**Comment by axxxxa** [comment]
顾得了头，顾不了尾啊，可以加个qq吗🐶

**Comment by mozjiang** [comment]
uFileNotFoundError: [WinError 2] 系统找不到指定的文件。
很多人都是这个报错，有时间看代码的可以修改一下代码然后提交个 pull request.

**Comment by YjWoo** [comment]
>uFileNotFoundError: [WinError 2] 系统找不到指定的文件。
很多人都是这个报错，有时间看代码的可以修改一下代码然后提交个 pull request.

我也遇到这种问题，退出IDE环境，直接在命令行里执行py脚本就可以了
