### ISSUE TITLE
小米5S最多跳到200多

### ISSUE THREAD

**Issue by wizholy** [wangshub/wechat_jump_game#571]
试了多个帖子里的参数，小米5S最多跳到200多，有没有好用的参数

**Comment by Testlyy** [comment]
看看执行时候读取的参数是不是你换的，我的小米5开始默认读取1920*1080文件夹下面的，我把小米里面对应机型的参数拿出来替换了就稍微好点，但是也只能5-600，估计还要优化

**Comment by brady2037** [comment]
同是，替换了1080下面的配置，也是只能600多

**Comment by Miao-K** [comment]
600多可以了，够别人追一段时间了，我都不敢刷高多，只是到了100多久手动暂停了

**Comment by Miao-K** [comment]
600多可以了，够别人追一段时间了，我都不敢刷高分，只是到了400多就手动暂停了

**Comment by yuyu0411** [comment]
求问600多分的配置〒_〒每次100多就停了

**Comment by Askooo** [comment]
改了一下代码
def jump(distance):
    if distance < 400:
        distance = 0.9 * distance + 60
    else:
        distance = 0.9 * distance + 80
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200 ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
        duration=press_time
    )
    print(cmd)
    os.system(cmd)
    return press_time

配置文件
{
"under_game_score_y": 300,
"press_coefficient": 1.47,
"piece_base_height_1_2": 25,
"piece_body_width": 80
}

亲测1000+就自杀了

**Comment by Niefee** [comment]
@Askooo  请问代码是在wechat_jump_auto.py里面改吗

**Comment by Askooo** [comment]
@Niefee 嗯呐嗯呐

**Comment by Niefee** [comment]
不会Python，但照着改可以了。现在还在跑，已经五百多，之前从没有上200.。谢谢 @Askooo

**Comment by yuyu0411** [comment]
为啥我改过后打开就闪退了_(:з」∠)_仔细对照过了没改错

**Comment by Ryan-Miao** [comment]
按照楼上的修改了，管用。https://github.com/Ryan-Miao/wechat_jump_game

**Comment by zkl99999** [comment]
Askooo ，厉害，小米5s和小米note3，改了之后从以前都不能到200，现在随便1000多

**Comment by knoxhy** [comment]
@Askooo 这四行代码太实用了

**Comment by AsNidhogg** [comment]
刷了个666就自杀了

**Comment by nicholeemma** [comment]
缩进怎么改啊

**Comment by nicholeemma** [comment]
@Askooo  太棒了！厉害！谢谢

**Comment by Niefee** [comment]
@Askooo 为啥你不提交pull request的，这个代码在其他电脑的兼容性怎样啊，
