### ISSUE TITLE
运行python wechat_jump_auto.py出现以下报错是因为什么呢？

### ISSUE THREAD

**Issue by Hasaki1997** [wangshub/wechat_jump_game#572]
`OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 15, in <module>
    template = cv2.resize(template, (0, 0), fx=scale, fy=scale)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize`

**Comment by sykiewang** [comment]
我也是这个错误

**Comment by Qiuliuyang** [comment]
这个好像是opencv没读到图

**Comment by sykiewang** [comment]
用auto脚本是可以用的

**Comment by wuxiaoxi** [comment]
应该是图片路径的问题吧，我改成绝对路径好像就可以执行了
template = cv2.imread('C:/Users/Administrator/Desktop/wechat_jump_game-master/train_data/character.png')
