### ISSUE TITLE
三星s8这是什么意思

### ISSUE THREAD

**Issue by DarlyLi** [wangshub/wechat_jump_game#573]
**********
Screen: Physical size: 1440x2960
Density: Physical density: 640
Override density: 560
DeviceType: SM-G9500
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********

**Comment by DarlyLi** [comment]
。。。

**Comment by binderclip** [comment]
请提供更多有用的信息
