### ISSUE TITLE
在跳一跳界面截图失败

### ISSUE THREAD

**Issue by ChangZihao** [wangshub/wechat_jump_game#577]
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 34, in <module>
    pull_screenshot()
  File "wechat_jump_iOS_py3.py", line 23, in pull_screenshot
    c.screenshot('autojump.png')
  File "/Users/CZH/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wda/__init__.py", line 295, in screenshot
    value = self.http.get('screenshot').value
  File "/Users/CZH/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/CZH/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/CZH/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

(
	0   CoreFoundation                      0x0000000187f72ff8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001869d4538 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000187f72eb4 <redacted> + 0
	3   Foundation                          0x0000000188a0b760 <redacted> + 112
	4   XCTest                              0x00000001001cc06c -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192
	5   XCTest                              0x00000001001cbf38 -[XCUIScreen screenshotDataForQuality:rect:error:] + 108
	6   WebDriverAgentLib                   0x0000000101de32c0 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 624
	7   WebDriverAgentLib                   0x0000000101dc4da0 +[FBScreenshotCommands handleGetScreenshot:] + 132
	8   WebDriverAgentLib                   0x0000000101dd19f4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	9   WebDriverAgentLib                   0x0000000101dc9620 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	10  RoutingHTTPServer                   0x0000000101e823cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	11  RoutingHTTPServer                   0x0000000101e82b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	12  libdispatch.dylib                   0x0000000186e2a9a0 <redacted> + 16
	13  libdispatch.dylib                   0x0000000186e3b7a8 <redacted> + 304
	14  libdispatch.dylib                   0x0000000186e2a9a0 <redacted> + 16
	15  libdispatch.dylib                   0x0000000186e2f5e8 _dispatch_main_queue_callback_4CF + 996
	16  CoreFoundation                      0x0000000187f210c8 <redacted> + 12
	17  CoreFoundation                      0x0000000187f1ece4 <redacted> + 1572
	18  CoreFoundation                      0x0000000187e4eda4 CFRunLoopRunSpecific + 424
	19  Foundation                          0x0000000188969db4 <redacted> + 304
	20  WebDriverAgentLib                   0x0000000101dc8614 -[FBWebServer startServing] + 424
	21  WebDriverAgentRunner                0x00000001018bbbe4 -[UITestingUITests testRunner] + 132
	22  CoreFoundation                      0x0000000187f78e80 <redacted> + 144
	23  CoreFoundation                      0x0000000187e6e2c4 <redacted> + 292
	24  XCTest                              0x00000001001b6654 __24-[XCTestCase invokeTest]_block_invoke.275 + 48
	25  XCTest                              0x0000000100204208 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 56
	26  XCTest                              0x00000001001b6404 __24-[XCTestCase invokeTest]_block_invoke + 680
	27  XCTest                              0x00000001001fc9d8 -[XCUITestContext performInScope:] + 208
	28  XCTest                              0x00000001001b614c -[XCTestCase invokeTest] + 136
	29  XCTest                              0x00000001001b7224 __26-[XCTestCase performTest:]_block_invoke.382 + 48
	30  XCTest                              0x0000000100201a78 +[XCTContext runInContextForTestCase:block:] + 164
	31  XCTest                              0x00000001001b6c20 -[XCTestCase performTest:] + 596
	32  XCTest                              0x00000001001b2e14 __27-[XCTestSuite performTest:]_block_invoke + 288
	33  XCTest                              0x00000001001b283c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	34  XCTest                              0x00000001001b2a4c -[XCTestSuite performTest:] + 236
	35  XCTest                              0x00000001001b2e14 __27-[XCTestSuite performTest:]_block_invoke + 288
	36  XCTest                              0x00000001001b283c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	37  XCTest                              0x00000001001b2a4c -[XCTestSuite performTest:] + 236
	38  XCTest                              0x00000001001b2e14 __27-[XCTestSuite performTest:]_block_invoke + 288
	39  XCTest                              0x00000001001b283c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	40  XCTest                              0x00000001001b2a4c -[XCTestSuite performTest:] + 236
	41  XCTest                              0x000000010020b484 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44
	42  XCTest                              0x00000001001c5994 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 420
	43  XCTest                              0x000000010020b300 -[XCTTestRunSession runTestsAndReturnError:] + 292
	44  XCTest                              0x00000001001a23d4 -[XCTestDriver runTestsAndReturnError:] + 312
	45  XCTest                              0x0000000100200c20 _XCTestMain + 620
	46  CoreFoundation                      0x0000000187f2130c <redacted> + 20
	47  CoreFoundation                      0x0000000187f20b28 <redacted> + 288
	48  CoreFoundation                      0x0000000187f1e998 <redacted> + 728
	49  CoreFoundation                      0x0000000187e4eda4 CFRunLoopRunSpecific + 424
	50  GraphicsServices                    0x00000001898b9074 GSEventRunModal + 100
	51  UIKit                               0x000000018e109c9c UIApplicationMain + 208
	52  WebDriverAgentRunner-Runner         0x0000000100088444 WebDriverAgentRunner-Runner + 33860
	53  libdyld.dylib                       0x0000000186e5d59c <redacted> + 4
))

**Comment by hhuizhang** [comment]
@ChangZihao  请问楼主你这个问题解决了吗？如何解决的呀？
