### ISSUE TITLE
小药瓶落点计算错误

### ISSUE THREAD

**Issue by lhtdeg** [wangshub/wechat_jump_game#580]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]

每次到小药瓶这里就跳不过去，看了下落点计算的图，好像偏下了，应该怎么设置呢

![1514860516_d](https://user-images.githubusercontent.com/7857624/34473094-5201b542-efa9-11e7-95ab-5844d9b8423f.jpg)

**Comment by marblemm** [comment]
是的啊，我现在最高就399

**Comment by HJH12315** [comment]
我也是

**Comment by GHAARON** [comment]
MI6这个怎么解决呀
