### ISSUE TITLE
红米NOTE3

### ISSUE THREAD

**Issue by mjchow** [wangshub/wechat_jump_game#583]
**********        
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 3
OS: linux2
Python: 2.7.13+ (default, Jul 19 2017, 18:15:03) 
[GCC 6.4.0 20170704]
**********

竖着跳没问题，横着跳直接跳出界了

**Comment by rrrttc** [comment]
横着跳直接跳出界了

**Comment by mjchow** [comment]
应该是沿着右上跳没问题，左上跳就出界
