### ISSUE TITLE
正常运行 但是手机游戏没有反应

### ISSUE THREAD

**Issue by Yidazhang** [wangshub/wechat_jump_game#586]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: darwin
Python: 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
**********
采用方式1获取截图
('scan_start_y: ', 690)
(1514862196, 338, 1109, 788, 849)

游戏里面不跳

**Comment by yuzhouallin** [comment]
我也遇到过，你把开发者选项里面的传输协议，改成别的，再改回MTP，试试。

**Comment by scc897577** [comment]
哥们你的手机里面游戏跳动吗?我的小米5 不跳...

**Comment by hncboy** [comment]
打开模拟点击

**Comment by Yidazhang** [comment]
改了mtp 一样没跳动 也没看到需要权限确认的操作

**Comment by scc897577** [comment]
> Load config file from D:\google下载\wechat_jump_game-master\wechat_jump_game-master/config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5
OS: win32
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
**********
采用方式2获取截图
scan_start_y:  690
1514862833 338 1109 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 767
我的是这个样子的...没有跳动

**Comment by yhongm** [comment]
开发者选项里面，USB调试（安全设置） 打开才可以模拟点击，否则没用

**Comment by Yidazhang** [comment]
@yuzhouallin 可以了

**Comment by edwardju1010** [comment]
@Yidazhang 怎么调试的？我的也是游戏里不跳

**Comment by Johnathanofficial** [comment]
@scc897577  哥们儿，解决了吗  我也是小米5，前面对照视频所有步骤都OK，最后运行auto时没反应。。咋回事呀，USB安全模式已经开启，游戏也打开了

**Comment by edwardju1010** [comment]
@Johnathanofficial 把【USB安全权限】打开就ok了，我是Vivo X20

**Comment by Johnathanofficial** [comment]
@edwardju1010 很遗憾，我打开了，还是不行，崩溃。。
今天上午弄了一上午了，对照视频做的，就最后一步不行，有点僵。。

**Comment by Johnathanofficial** [comment]
@edwardju1010  anyway, thanks.
