### ISSUE TITLE
运行程序之后不动...

### ISSUE THREAD

**Issue by scc897577** [wangshub/wechat_jump_game#587]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5
OS: win32
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]

**Comment by hncboy** [comment]
打开模拟点击

**Comment by edwardju1010** [comment]
模拟点击怎么打开？我也是点击“开始游戏”后，不跳，截的图总是同一张图（初始位置）。

**Comment by hncboy** [comment]
开发者模式里有模拟点击的。

**Comment by edwardju1010** [comment]
@hncboy 没看到“模拟点击”呢？（vivo x20）。我的【开发者选项】中，关于“模拟”的字样只有【选择模拟位置信息应用】。

**Comment by hncboy** [comment]
我的小米5，你试试在CMD中输入adb shell, input text "hello"，看有没有反应

**Comment by edwardju1010** [comment]
@scc897577 @hncboy 谢谢！弄好了！我把【USB安全权限】打开就ok了。
