### ISSUE TITLE
小米4c，1080p，自动脚本 只能跳个位数，各种改参数都没用

### ISSUE THREAD

**Issue by bestTao** [wangshub/wechat_jump_game#59]
![1](https://user-images.githubusercontent.com/16660255/34451614-1bb1aa14-ed66-11e7-9a3f-1fc94faec921.png)

**Comment by binderclip** [comment]
1. 更新最新的代码
2. 提供具体分辨率，以及最后一次使用的参数
3. 上传一张 `screenshot_backups` 目录下的画了线的图

**Comment by binderclip** [comment]
改发在那里吧 [参数没设置好的发这里 · Issue #62 · wangshub/wechat_jump_game](https://github.com/wangshub/wechat_jump_game/issues/62)

**Comment by liqiangzhao** [comment]
小米4C  参数
{
    "under_game_score_y": 320,
    "press_coefficient": 1.524,
    "piece_base_height_1_2": 25,
    "piece_body_width": 80,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1600
    }
}


同时 在 wechat_jump_auto.py 中 在main （）中  的jump之前插入

distance = math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2)
        print("start-------- distance --------start: ", distance)
        tmp = 0
        if distance < 220:
            tmp = 38
            print("200-------- distance --------200:",tmp)
        elif distance < 380:
            tmp = 30
            print("350-------- distance --------350:",tmp)
        elif distance < 480 :
            tmp = 25
            print("465-------- distance --------465:",tmp)
        elif distance < 515 :
            tmp = 14
            print("500-------- distance --------500:",tmp)
        elif distance < 580 :
            tmp = 12
            print("540-------- distance --------540:",tmp)
        elif distance < 635 :
            tmp = 5
            print("630-------- distance --------630:",tmp)
        distance = distance + tmp
        print("end-------- distance --------end: ", distance)
        jump(distance)
     把jump注释了。。就ok。。亲测3000+。。

**Comment by lubin007** [comment]
“同时 在 wechat_jump_auto.py 中 在main （）中 的jump之前插入”，请问这个代码在哪里呢，在源代码中没有找到位置，还请赐教

**Comment by liqiangzhao** [comment]
就在wechat_jump_auto.py中的main()中   没法截图  在代码中的后面 大概应该268行是main（）. 在
set_button_position(im)  之后插入。屏蔽作者的jump()函数。。ok
