### ISSUE TITLE
小米4

### ISSUE THREAD

**Issue by behome** [wangshub/wechat_jump_game#593]
小米4
1080x1920
win10
只能到300多

**Comment by yeming1001** [comment]
这个配置能到560多
不知有没有更高的配置
{
    "under_game_score_y": 300,
	"press_coefficient": 1.475, 
    "piece_base_height_1_2": 20,
    "piece_body_width": 73,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1602
    }
}

**Comment by melooooooo** [comment]
"under_game_score_y": 285, 
    "press_coefficient": 1.420, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70,
其他参数默认，跳了将近1000不过不要太高，微信会检测到
