### ISSUE TITLE
安卓模拟器是不是不能用了？试了几个都打不开跳一跳！

### ISSUE THREAD

**Issue by terrybogez** [wangshub/wechat_jump_game#596]
目前测试了bluestack ，逍遥，雷神，在不同的电脑上都试过，win7和win10都试过，打开微信没问题，但是一开跳一跳，就提示“运行环境加载失败”，是腾讯把模拟器都封掉了吗？有没有可用的模拟器玩跳一跳的？

**Comment by zl20154312** [comment]
从微信官网下载之后直接安装apk，安装时会提示是否使用市场版本，选择“不，谢谢！”，之后第一次进入程序是可以进行跳一跳的

**Comment by Leiwanyu** [comment]
进设置里面进行更新，在模拟器安装的不是最新版本

**Comment by terrybogez** [comment]
@zl20154312 @Leiwanyu 谢谢，我已经用手机测试成功了！
