### ISSUE TITLE
关于adb弹窗

### ISSUE THREAD

**Issue by ShenEnQ** [wangshub/wechat_jump_game#6]
每次执行adb命令都要弹个黑窗口，虽然会自动关闭，但还是不爽。用subprocess.call('adb shell screencap -p /sdcard/1.png', shell=True) 代替os.system调用可解决。

**Comment by wangshub** [comment]
好的，我加进去试试

**Comment by wangshub** [comment]
@ShenEnQ

**Comment by MrLevo520** [comment]
0. 请使用最新版代码
1. 使用adb免配置版本
2. 使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
下次请规范提交issue，谢谢
