### ISSUE TITLE
防ban设定

### ISSUE THREAD

**Issue by rufengsuixing** [wangshub/wechat_jump_game#600]
点击位置加入随机
点击延时加入随机
计算出的点击时间也可以在小范围内变化

**Comment by mozjiang** [comment]
支持。因为霸占排行榜问题，制作团队可能会修改游戏代码并加入相关判定，固定的点击位置等很容易被检测出来。

**Comment by binderclip** [comment]
啊，这个赶紧去加一下。

**Comment by feistar** [comment]
我加了点击位置， 好像还是不行
