### ISSUE TITLE
希望改进距离算法 

### ISSUE THREAD

**Issue by HJH12315** [wangshub/wechat_jump_game#602]
bug出现有点多。

https://i.loli.net/2018/01/02/5a4affcc7f0af.png

单纯的靠y轴找x轴 在棋子偏离正中间时并且方块很小时，极易出界。

**Comment by ZedeX** [comment]
![image](https://user-images.githubusercontent.com/394198/34485660-b28c9212-f006-11e7-89dc-0c6a0dfc0250.png)
如图橙色所示，这样改进应该可以，请@binderclip @F-loat 找人帮忙看下，多谢~

**Comment by xia0ming** [comment]
个人感觉这个这游戏每次跳的时候默认是从当前的正中央计算的 这次跳的落点不影响下次的跳跃

**Comment by ZedeX** [comment]
@xia0ming 这里不是确认落点的，这里是要计算那个橙色的距离，然后转化成按压时长。
