### ISSUE TITLE
红米4A 能运行，但是不会自动跳

### ISSUE THREAD

**Issue by leeggco** [wangshub/wechat_jump_game#604]
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: Redmi 4A
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
**********

**Comment by tobealion** [comment]
打开USB调试（安全设置）试试？

**Comment by 951240778** [comment]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4X
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 b
it (AMD64)]
**********

**Comment by 951240778** [comment]
每次   能运行  但是  不跳

**Comment by mingo1996** [comment]
打开USB调试(安全设置)!!!
