### ISSUE TITLE
运行之后，计算出的横纵坐标一直保持不变是什么问题？

### ISSUE THREAD

**Issue by zl20154312** [wangshub/wechat_jump_game#605]
![error](https://user-images.githubusercontent.com/22730443/34474307-3d5418c4-efb8-11e7-8156-b9d833dee6ae.PNG)
如题，辛苦各位解答

**Comment by Alienover** [comment]
那个是模拟的按压坐标，这个游戏跟按压坐标是没关系的，只是根据按压时间来确定跳的距离，所以那个按压坐标固定的话，是没问题的
