### ISSUE TITLE
MAC下的config.json具体应该放在哪里？

### ISSUE THREAD

**Issue by Jessefrom1997** [wangshub/wechat_jump_game#606]
**********
OS: Mac OS
Python: 3.6
**********
遇到问题：with open('config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
这问题是被提过了，但是还是不清楚config.json具体应该放在哪里，希望能给个稍微清楚一点的答案，谢谢！
改进和建议：无

**Comment by VictorChow** [comment]
.py文件在哪 config就在哪 cd到.py的路径下执行

**Comment by Jessefrom1997** [comment]
懂了，十分感谢！🙏

**Comment by Jessefrom1997** [comment]
@VictorChow 懂了，十分感谢！🙏
