### ISSUE TITLE
距离过近

### ISSUE THREAD

**Issue by LWJcoder** [wangshub/wechat_jump_game#609]
**********
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1440x2560
Override size: 1080x1920
Density: Physical density: 560
Override density: 420
DeviceType: SM-G9280
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
**********
遇到问题：一直距离过近
![]()
改进和建议：无

**Comment by Vg1ee** [comment]
屏幕尺寸不匹配的问题吧

**Comment by LazyPhper** [comment]
将/config文件夹中  ，1920*1080文件夹下的config文件覆盖到2560*1440 文件夹下。
