### ISSUE TITLE
No module named 'WechatJump'

### ISSUE THREAD

**Issue by IcySaint** [wangshub/wechat_jump_game#610]
mate10pro

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wechat_jump_auto.py", line 28, in <module>
    from WechatJump import Debug, Config
ModuleNotFoundError: No module named 'WechatJump'
>>>

**Comment by icysaintdx** [comment]
win7系统，adb已安装及配置变量，usb调试已打开，文件在桌面，起初闪退，桌面建立config文件夹放入json命名default.json

**Comment by IcySaint** [comment]
@LNDmufasa 建立父级文件夹命名WechatJump 但是会出现新的问题
