### ISSUE TITLE
依赖已安装 但是提示 No module named 'WechatJump'

### ISSUE THREAD

**Issue by GonyMaster** [wangshub/wechat_jump_game#611]
**********

**********
遇到问题：依赖已安装 但是提示 No module named 'WechatJump'
使用环境 : 模拟器 
用adb shell input swipe x y x y time(ms)命令 可以模拟点击 但是启动py脚本就提示找不到WechatJump模块

**Comment by leniy** [comment]
您用的是python3还是2？

**Comment by GonyMaster** [comment]
Python 3.6.4 @leniy

**Comment by leniy** [comment]
当前文件夹下面，有WechatJump这个文件夹么？

**Comment by GonyMaster** [comment]
明白了 感谢 @leniy

**Comment by icysaintdx** [comment]
@GonyMaster 怎么解决了？

**Comment by LNDmufasa** [comment]
同问怎么解决了？ @leniy @GonyMaster

**Comment by leniy** [comment]
@LNDmufasa @IcySaint 
你们把代码更新一下。源代码包含一个py文件，一个config文件夹，一个WechatJump文件夹

**Comment by leniy** [comment]
最好的办法是下载最新的[master.zip](https://github.com/wangshub/wechat_jump_game/archive/master.zip)

**Comment by IcySaint** [comment]
@leniy  下载了你链接的zip   
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wechat_jump_auto.py", line 31, in <module>
    config = Config.open_accordant_config()
AttributeError: module 'WechatJump.Config' has no attribute 'open_accordant_config'

**Comment by leniy** [comment]
方便提供个远程方式么？用你的环境比较方便检查故障

**Comment by hahahahahaa** [comment]
你好 我的下载了你的压缩包后运行出现name error name raw_input is not defined

**Comment by leniy** [comment]
@hahahahahaa 
你运行的哪个脚本？安卓版的没有用到raw_input……

**Comment by hahahahahaa** [comment]
wechat_jump_auto @leniy

**Comment by hahahahahaa** [comment]
C:\Users\Administrator>python C:\Users\Administrator\Desktop\wechat_jump_game-ma
ster\wechat_jump_auto.py
Load config file from C:\Users\Administrator\Desktop\wechat_jump_game-master/con
fig/1920x1080/config.json
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wechat_jump_game-master\wechat_jump_auto.
py", line 248, in <module>
    main()
  File "C:\Users\Administrator\Desktop\wechat_jump_game-master\wechat_jump_auto.
py", line 225, in main
    op = yes_or_no('请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳游戏再用本
程序，确定开始？')
  File "C:\Users\Administrator\Desktop\wechat_jump_game-master\wechat_jump_auto.
py", line 209, in yes_or_no
    i = raw_input(prompt)
NameError: name 'raw_input' is not defined @leniy

**Comment by ShannonWandered** [comment]
@hahahahahaa 我跟你的问题完全一样

**Comment by IcySaint** [comment]
@ShannonWandered @hahahahahaa 这是你们更新了最新的   半小时前作者修改了代码  现在是这种问题

**Comment by IcySaint** [comment]
@hahahahahaa @ShannonWandered 把raw_input修改成input即可

**Comment by albertofwb** [comment]
请问在 windows 中的这个 exe 是如何打包的？stop_jump1_1_2.exe

**Comment by MrLevo520** [comment]
@albertofwbpyinstaller

**Comment by leniy** [comment]
？？
