### ISSUE TITLE
mix分数太低

### ISSUE THREAD

**Issue by blademainer** [wangshub/wechat_jump_game#612]
**********
Screen: Physical size: 1080x2040
Density: Physical density: 440
DeviceType: MIX
OS: darwin
Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
**********
遇到问题：mix分数很低，最多100
改进和建议：无

**Comment by wangshub** [comment]
建议你更新最新代码，或者尝试修改参数试试 @blademainer

**Comment by admxj** [comment]
我的跳跃系数 1.45 1000分

**Comment by chenzuoyuan** [comment]
@admxj 老哥，稳
