### ISSUE TITLE
执行python3 wechat_jump_auto_iOS.py 报这个错误

### ISSUE THREAD

**Issue by tulermos** [wangshub/wechat_jump_game#613]
localhost:wechat_jump_game-master tulermos$ python3 wechat_jump_auto_iOS.py
Traceback (most recent call last):
File "wechat_jump_auto_iOS.py", line 6, in 
import wda
ModuleNotFoundError: No module named 'wda'
localhost:wechat_jump_game-master tulermos$
执行python3 wechat_jump_auto_iOS.py 报这个错误，请问有大神知道是什么原因吗

**Comment by YanTongLiang** [comment]
No module named 'wda'
pip install --pre facebook-wda

**Comment by Jessefrom1997** [comment]
应该是openatx/facebook-wda没装好

**Comment by 101hanbin** [comment]
你是没装fackbook的那个库吧

**Comment by zzhoouxin** [comment]
试下 sudo pip3 install --pre facebook-wda      不要用pip 就可以了

**Comment by Sycooo** [comment]
我到这里也出了问题，但是报错不一样
➜  wechat_jump_game-master python3 wechat_jump_auto_iOS.py
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 6, in <module>
    import wda
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wda/__init__.py", line 16, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by zmjios** [comment]
我的是看本地已经安装了wda，但是仍然提示ModuleNotFoundError: No module named 'wda'
![image](https://user-images.githubusercontent.com/2563684/34870177-4f813c70-f7c4-11e7-93ec-4d20fd1d9f29.png)
![image](https://user-images.githubusercontent.com/2563684/34870192-5b323858-f7c4-11e7-8a07-0277b469c4a8.png)
