### ISSUE TITLE
No module named WechatJump

### ISSUE THREAD

**Issue by ASguy** [wangshub/wechat_jump_game#614]
ImportError: No module named WechatJump

**Comment by binderclip** [comment]
什么操作系统？
执行代码的路径是啥？
怎么执行的？

**Comment by chenangxuan0123** [comment]
@binderclip win10 依赖已安装 已经把改成default.json放到config中 报错
Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\wechat_jump_auto.py", line 22, in <module>
    from WechatJump import Debug, Config
ModuleNotFoundError: No module named 'WechatJump'

**Comment by binderclip** [comment]
@chenangxuan0123  你不会只下载了 wechat_jump_auto.py 吧？要整个在原来的项目里运行

**Comment by ASguy** [comment]
@binderclip 要整个在原来的项目里运行,这是指什么,我是按视频l
