### ISSUE TITLE
mi6 适配有问题

### ISSUE THREAD

**Issue by godlinchong** [wangshub/wechat_jump_game#617]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen: Physical size: 1080x1920        
Density: Physical density: 480        
DeviceType: MI 6        
OS: darwin        
Python: 3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
**********
{
    "under_game_score_y": 300,
    "press_coefficient": 1.45,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,

    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1600
    }
}
150步就死了

**Comment by qtvspa** [comment]
**试试这个**
{
    "under_game_score_y": 300,
    "press_coefficient": 1.44,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}

**Comment by xiong5201314** [comment]
这个跳着跳着就下去了

**Comment by tangjw** [comment]
MIUI用户自行修改 按压时间大约 +50ms ，亲测跳到400步不掉
cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time+50)
