### ISSUE TITLE
三星S8+ 开启USB调试模式后adb无法找到连接设备。

### ISSUE THREAD

**Issue by DomainCollection** [wangshub/wechat_jump_game#618]
请问三星S8+开启USB调试模式了之后执行adb devices 之后连接设备列表为空是怎么回事？
`> adb devices`
`List of devices attached`

**Comment by wangshub** [comment]
查阅
https://github.com/wangshub/wechat_jump_game#%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4

**Comment by DomainCollection** [comment]
已解决，谢谢

**Comment by Sphinxone** [comment]
怎么解决的，我还是没解决

**Comment by DomainCollection** [comment]
用电脑管家连接手机吧
