### ISSUE TITLE
凸起来的跳台,判断有误

### ISSUE THREAD

**Issue by aikunzhe** [wangshub/wechat_jump_game#619]
![---1514871109_d](https://user-images.githubusercontent.com/9932394/34474988-c36265a2-efc1-11e7-9b3d-dba9950d01ef.png)
![---1514871113_d](https://user-images.githubusercontent.com/9932394/34474989-cea2f0bc-efc1-11e7-8739-a7427f5ff476.png)
![----1514870853_d](https://user-images.githubusercontent.com/9932394/34475001-fec6d01a-efc1-11e7-8929-541347840b4b.png)

识别正确的:
![---1514870980_d](https://user-images.githubusercontent.com/9932394/34474994-daacc004-efc1-11e7-8128-81f21ac9962f.png)

**Comment by Vg1ee** [comment]
图2的情况的确很少见，限制x方向搜索范围的代码虽然可以很大程度上避免音符bug但是会出现图2的那种短距离bug。
音乐盒按照目前的算法的确会识别到顶部去，偶尔识别正确是因为中间有白点识别到白点上面去了。
