### ISSUE TITLE
ios用户可以运行wechat_jump_auto.py？  后缀无ios的py脚本，两者有什么区别

### ISSUE THREAD

**Issue by HJH12315** [wangshub/wechat_jump_game#620]
wechat_jump_auto.py  与  wechat_jump_auto——iOS.py    有什么区别，ios用户是否都能运行？

**Comment by one-smiling** [comment]
@HJH12315 不带iOS的是给安卓用的

**Comment by HJH12315** [comment]
@one-smiling  所以ios用了会报错？  我看ios自动化脚本好久没更新了。。。

**Comment by 101hanbin** [comment]
wechat_jump_auto.py是个Android用的，ios的是个苹果手机用的。ios那边是用wda这个自动测试工具来截图的，截图后识别，计算，模拟点击

**Comment by paradises** [comment]
iOS的自动化脚本配置文件对了基本上没啥问题感觉 稍微改一下停留时间到1.4左右就差不多了

**Comment by HJH12315** [comment]
@paradises  差不多400分以上就有bug失败。距离算法不完美，定位容易失败。

**Comment by HJH12315** [comment]
@101hanbin 
 多谢
