### ISSUE TITLE
三星s8+亲测可用参数

### ISSUE THREAD

**Issue by whosyourdady110** [wangshub/wechat_jump_game#622]
虽然不是完全准确的跳，不过刷个1000没什么问题
{
    "under_game_score_y": 460,
    "press_coefficient": 1.0935,
    "piece_base_height_1_2": 70,
    "piece_body_width": 75
}

**Comment by DomainCollection** [comment]
我刷了1029步，三星S8+，但是只有自己排行榜上是第一，好友微信上还是我自己手动跳的285步。

**Comment by whosyourdady110** [comment]
你自己先跳个几十步 然后再跑脚本就检测不到作弊了

**Comment by Fifi1996** [comment]
参数在哪修改呢？

**Comment by whosyourdady110** [comment]
config目录下 default.json文件

**Comment by Fifi1996** [comment]
找到了找到了谢谢

**Comment by demidroid** [comment]
一个都刷不了呢，跳到边缘

**Comment by whosyourdady110** [comment]
手机型号是s8+么？是的话 估计是文件改的不对，要改config目录下 default.json文件

**Comment by DomainCollection** [comment]
用的什么分辨率，FHD＋还是WQHD+,曲面侧屏关了吗？

**Comment by thatman6666** [comment]
找到了，终于找到了参数。

**Comment by lupengwei** [comment]
分辨率选哪一个

**Comment by JoffreyN** [comment]
谢谢，改了参数后可以用了
