### ISSUE TITLE
mi6跳的不准

### ISSUE THREAD

**Issue by godlinchong** [wangshub/wechat_jump_game#623]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: darwin
Python: 3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
********
![1514815412](https://user-images.githubusercontent.com/28970240/34475013-2a74bcc2-efc2-11e7-9cd3-71feda7a7237.png)
跳的不太准

**Comment by qtvspa** [comment]
**试试这个参数**
{
    "under_game_score_y": 300,
    "press_coefficient": 1.44,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}

**Comment by tangjw** [comment]
MIUI用户自行修改 按压时间大约 +50ms ，亲测跳到400步不掉
cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time+50)

**Comment by godlinchong** [comment]
楼上，修改成+40可以跳的更高

**Comment by scholar095** [comment]
在哪个数据后加40哦？press_coefficient？
