### ISSUE TITLE
MI 6不跳

### ISSUE THREAD

**Issue by qingfengmuzhu0** [wangshub/wechat_jump_game#626]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 b
it (AMD64)]
**********
遇到问题：没有任何反应，不蓄力，也不跳，一直在刚开始的界面

改进和建议：无

**Comment by chloechj** [comment]
试试除了打开usb调试，还要打开底下的usb调试（安全）

**Comment by qingfengmuzhu0** [comment]
打开usb调试外，还要打开底下的usb调试（安全）就可以了

**Comment by tangjw** [comment]
MIUI用户自行修改 按压时间大约 +50ms ，亲测跳到400步不掉 
cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time+50)
