### ISSUE TITLE
我的数据被微信封了，才三百多

### ISSUE THREAD

**Issue by Xiasm** [wangshub/wechat_jump_game#630]
**********
Screen: Physical size: 1080x2160
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：一直在蓄力，无法起跳，截图如下
![]()
改进和建议：无

**Comment by 101hanbin** [comment]
其实人和程序的区别就在于，程序太规律

**Comment by shimminZ** [comment]
我刚刚弄好 跑了一次，朋友看不到我的成绩 ，伤心啊

**Comment by Ryan-Miao** [comment]
被封的条件是啥，200多也被封了
