### ISSUE TITLE
同志们不用试了，微信已经开始封了

### ISSUE THREAD

**Issue by songweite** [wangshub/wechat_jump_game#631]
用这个玩多少分都不更新到排行榜了，我现在跳一跳直接是已封禁。
估计微信官方早早也看到这个贴

**Comment by cwwise** [comment]
我试过了 的确是。。微信怎么检测的

**Comment by immoker** [comment]
╮(╯▽╰)╭阻止了正在安装的步伐

**Comment by 951240778** [comment]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4X
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 b
it (AMD64)]
**********

**Comment by 951240778** [comment]
我的还没开始跳呢

**Comment by binderclip** [comment]
@songweite @cwwise 你们的到多少分了？

**Comment by songweite** [comment]
代码都开源了，微信官网完全可以找到其中一个途径屏蔽：
1.每次起跳间隔都是1s
2.每次起跳都截图
3.准确率太高

**Comment by cwwise** [comment]
@songweite 可以调整间隔时间和准确率 至于截图怎么办 这个就不知道了

**Comment by cwwise** [comment]
@binderclip 都试过 300 500 1000的。。都不行。。
看看作者有没有解决办法吧

**Comment by songweite** [comment]
@cwwise 截图这个我不知道能不能检测到。我把准确率调低了是可以调到300+没问题的，但是有很小的方块就跳不上去了

**Comment by songweite** [comment]
解决的方法肯定有，感觉作者在更新的可能行不大了。项目有点火，官方肯定也看过了

**Comment by sugarAndsugar** [comment]
800+ ，已经不行了

**Comment by ZhangTong17** [comment]
截图应该检测不到吧，可以改成手动版的，用鼠标来点，这样可以控制时间和距离

**Comment by MahatmaSun** [comment]
我还在下anaconda呢....    看来我没尝上鲜啊

**Comment by songweite** [comment]
@MahatmaSun 不用下anaconda

**Comment by MahatmaSun** [comment]
@songweite 那怎么用啊.

**Comment by athosss** [comment]
@MahatmaSun 用virtualenv的虚拟环境美滋滋

**Comment by MahatmaSun** [comment]
@songweite 我个安卓程序猿.. 不太懂phython

**Comment by github410117** [comment]
600以下可以！上600就不行了，还是手动的

**Comment by whosyourdady110** [comment]
手动跳个几十分，在跑脚本就行了

**Comment by hyndaniel** [comment]
真的阔以。。这项目周榜第六能不封？？？

**Comment by leeggco** [comment]
封？ 我都还没运行啊！

**Comment by hoanX** [comment]
测试nexus 6p，跑了半个多小时，吃个饭回来8000多分，还没被封

**Comment by songweite** [comment]
@hoanX 我不信。。。肯定分数提交不上去

**Comment by MahatmaSun** [comment]
@hoanX ....  你控制控制.   8000多. 没朋友

**Comment by hoanX** [comment]
@songweite 微信小号，非要我上图
![31514877288_ pic](https://user-images.githubusercontent.com/16273543/34476878-b213bf72-efcf-11e7-97bd-9722f8ce5e2a.jpg)

**Comment by whosyourdady110** [comment]
个人榜没用 你得去群排行看看

**Comment by hoanX** [comment]
@whosyourdady110 我用另一个账号也可以看到啊，还有什么地方有排行？

**Comment by binderclip** [comment]
@hoanX 点排行榜里的查看群排行，分享到微信群

**Comment by zuijiusi** [comment]
@hoanX 大哥流弊

**Comment by Chanven** [comment]
真的是失效了 =。=

**Comment by 951240778** [comment]
@Chanven 我还没开始跳呢

**Comment by 951240778** [comment]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4X
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 b
it (AMD64)]
**********
采用方式2获取截图
scan_start_y:  690
1514879854 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879857 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879860 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879863 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879876 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879879 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879882 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879884 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690

**Comment by Chanven** [comment]
@951240778 不用跳了哈哈哈

**Comment by 951240778** [comment]
@Chanven   哎呦  不要  起码能让跳起来嘛

**Comment by unix2dos** [comment]
哈哈  微信上显示每周一才更新  数据还没更新呢

**Comment by 951240778** [comment]
@Chanven 这个是不是 执行完 auto.py 那个文件就 自动跳了？？？？

**Comment by Chanven** [comment]
@951240778 对，执行完就自动跳了

**Comment by 951240778** [comment]
@Chanven   跳到  100多就gg  了  有没有  优化的   方案  或者 调试数据什么的

**Comment by shzxd** [comment]
@unix2dos  mei zhou yi shua xin ba

**Comment by 951240778** [comment]
@Chanven   你跳到多少了？   我的这个为什么  不能破百？

**Comment by Chanven** [comment]
@951240778  我可以一直跳，不过分数提交不上去的，被和谐了。你换个手机试试？

**Comment by 951240778** [comment]
@Chanven 我的   现在没有过100

**Comment by MahatmaSun** [comment]
我的没弄太多. 1186分.  我到1000多一点的时候我就开始自己玩了. 是可以上传上去的. 亲测 just now

**Comment by 951240778** [comment]
我的没到100 @MahatmaSun

**Comment by zq019633** [comment]
http://blog.csdn.net/zq019/article/details/78952896

**Comment by MahatmaSun** [comment]
@951240778 不需要  你把整个项目都下载下来. 我的Python版本高. 有两个函数名称无法识别. 改了一下 你能正常运行 就不用改参数.

**Comment by MahatmaSun** [comment]
@951240778 我这个是到1000多是我手动停止了 否则还继续跳呢.

**Comment by 951240778** [comment]
我的可以正常运行  但是每次都没到  100 感觉好怪哦 @MahatmaSun

**Comment by 951240778** [comment]
我用的是 python 3.6.4  那个版本的 @MahatmaSun

**Comment by KorwinBanana** [comment]
还在试参数的怎么办哈哈哈

**Comment by zhqingyong** [comment]
手动和自动穿插，离得近的手动点，离得远的开程序自动跳。开始先自己跳个百八十分，停止程序能跳几个再跳几个。1月2号18点47亲测可以上榜。

**Comment by hznupeter** [comment]
https://v.qq.com/x/page/e05270ybfo3.html
这个是我昨晚做的，应该不会被屏蔽

**Comment by zcjerry229** [comment]
刚跑完 还没被封

**Comment by HustZhang** [comment]
900被封了

**Comment by zcjerry229** [comment]
额 我刚才对分数也被封了

**Comment by CoXier** [comment]
被封的截图是啥呀

**Comment by mikuily** [comment]
修改一下起跳间隔时间试一下

**Comment by xianxingg** [comment]
可以学习一下吃鸡外挂嘛，另外可不可以使用AccessibilityService绕过截图啊

**Comment by wjr22** [comment]
这个是拿来学习的不是来刷分的。。。。。

**Comment by ZhiGuoZheng** [comment]
同学上周刷到4500，被清空后，这周不管怎么跳一会就被清零=。=估计黑名单了
