### ISSUE TITLE
board检测有问题

### ISSUE THREAD

**Issue by agan123** [wangshub/wechat_jump_game#635]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI 5s Plus
OS: win32
Python: 3.5.4（v3.5.4:3f56838, Aug 8 2017, 02:17:05）[MSC v.1900 64 bit ()]
**********
遇到问题：board中心检测有问题，截图如下
![1514874887_d](https://user-images.githubusercontent.com/26434267/34476753-82a4101c-efce-11e7-8e83-f9df86edea5a.png)

改进和建议：无

**Comment by hxzqlh** [comment]
这个是由于 tan 30 度导致度bug，已经被我fix，稍后我上fix后的版本，目前已经跳到2277分了。

**Comment by Vg1ee** [comment]
请使用最新版本的脚本
