### ISSUE TITLE
详细图文教程

### ISSUE THREAD

**Issue by lyrical1991** [wangshub/wechat_jump_game#636]
适合没有编程经验的超详细图文教程，写得一般，大神勿喷
http://www.52aite.cn

**Comment by 951240778** [comment]
可以，我终于发现自己哪里  有问题了！！

**Comment by lyrical1991** [comment]
@951240778
嘿嘿

**Comment by 951240778** [comment]
嗯嗯

**Comment by 951240778** [comment]
我的没有安装依赖安装包    就奇怪了   一直不跳

**Comment by 951240778** [comment]
我知道现在还能自动跳吗

**Comment by lyrical1991** [comment]
@951240778
能啊 就是好像太高会被清空分数

**Comment by 951240778** [comment]
我还在安装包   想尝个鲜

**Comment by lyrical1991** [comment]
我去，太可怕了，写个教程，服务器差点崩了

**Comment by 951240778** [comment]
怎么了？

**Comment by 951240778** [comment]
@lyrical1991

**Comment by lyrical1991** [comment]
@951240778
好多人进来看~ 我的服务器配置很低的 哈哈~ 一下资源就快占满了~

**Comment by 951240778** [comment]
用的阿里云吗？

**Comment by 951240778** [comment]
你这个教程还是蛮好的

**Comment by lyrical1991** [comment]
@951240778
慢慢看~~ 我先去搬砖了。。。

**Comment by 951240778** [comment]
恩，好，我先操作着

**Comment by 951240778** [comment]
@lyrical1991  我的都没问题了环境都搭建好了  就是执行wechat_jump_auto.py  文件时，没有跳  而且一直在截图，截的图都是0分的那个页面

**Comment by TEENSTITAN** [comment]
Screen:         
Density:         
DeviceType:         
OS: win32        
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)

**Comment by TEENSTITAN** [comment]
这个是什么情况

**Comment by 951240778** [comment]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4X
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 b
it (AMD64)]
**********
采用方式2获取截图
scan_start_y:  690
1514879854 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879857 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879860 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879863 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879876 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879879 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879882 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690
1514879884 362 1095 788.5 849
adb shell input swipe 540.0 1584 540.0 1584 685
scan_start_y:  690

**Comment by 951240778** [comment]
@TEENSTITAN 你的   环境没搭建好吧

**Comment by TEENSTITAN** [comment]
@951240778   环境OK了 为什么读取不到我的手机 信息

**Comment by Chanven** [comment]
@TEENSTITAN config复制一下？

**Comment by 951240778** [comment]
cmd  里面试试   

adb   devices   看行不行  有没有设备信息

**Comment by 951240778** [comment]
@TEENSTITAN

**Comment by TEENSTITAN** [comment]
adb的信息

C:\Users\OY>adb devices
List of devices attached

**Comment by 951240778** [comment]
@TEENSTITAN   这个是不是  执行完  auto.py   那个文件就  自动跳了？？？？

**Comment by TEENSTITAN** [comment]
config：
{
    "under_game_score_y": 300,
    "press_coefficient": 1.392,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1602
    }
}



日志：

Load config file from F:\Download\Chrome\wechat_jump_game-master/config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen:         
Density:         
DeviceType:         
OS: win32        
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
**********
暂不支持当前设备

**Comment by 951240778** [comment]
@Chanven  这个是不是 执行完 auto.py 那个文件就 自动跳了？？？？

**Comment by 951240778** [comment]
@TEENSTITAN   你的  adb  安装的有问题

**Comment by 951240778** [comment]
C:\Users\Administrator.SKY-20171031NGP>adb  devices
List of devices attached
4879c6549904    device


C:\Users\Administrator.SKY-20171031NGP>

**Comment by 951240778** [comment]
@TEENSTITAN

**Comment by TEENSTITAN** [comment]
@951240778  
我换一个手机试试

**Comment by TEENSTITAN** [comment]
确实是手机问题  不知为什么这个魅族手机连不上  小米手机可以

@951240778

**Comment by burryxie** [comment]
@TEENSTITAN 魅族确实麻烦 看看这个http://blog.csdn.net/wispy316/article/details/43022349

**Comment by TEENSTITAN** [comment]
@burryxie   嗯嗯 连上了  不过跑了500分 似乎被微信给清了

**Comment by 951240778** [comment]
我跑到  400多分  这个程序就自动  条失败了 @TEENSTITAN

**Comment by TEENSTITAN** [comment]
@951240778    不敢跑太高的分数， 手动一下，然后结束！

**Comment by 951240778** [comment]
我也想手动结束啊，只不过  跳不到  400分  自己就跳下来了 @TEENSTITAN

**Comment by 951240778** [comment]
我改了一下按压系数 "press_coefficient": 1.52,   昨天100都破不了  我的手机是  1920X1080的

**Comment by 951240778** [comment]
@TEENSTITAN

**Comment by 951240778** [comment]
我现在看博主昨天  改的代码 里面加了 时间随机数 @TEENSTITAN

**Comment by TEENSTITAN** [comment]
@951240778   试过一次 确实有这种情况  代码没改过 直接运行的  在 **魅蓝note3** 上
