### ISSUE TITLE
被和谐，排行榜只有自己能看到~

### ISSUE THREAD

**Issue by NinoWang** [wangshub/wechat_jump_game#638]
别人的排行榜里没有

**Comment by nanixiaoseng** [comment]
是的，上了500分基本是要被和谐，只有自己看的到，在别人那里看不到。

**Comment by 951240778** [comment]
就是用的楼主的方法吗？python

**Comment by SouperGeng** [comment]
能看到啊

**Comment by upSheng** [comment]
本来自己可以看到，几分钟后就没了

**Comment by NinoWang** [comment]
@951240778  是的啊

**Comment by kandy-he** [comment]
停止脚本后，手动跳几步

**Comment by jiwuming** [comment]
不能把 我这里排行榜第一的10w分...

**Comment by NinoWang** [comment]
周榜第一了，过于火爆。。。
https://github.com/trending?since=weekly

**Comment by StrZeroNight** [comment]
先手动跳几次，然后跑程序，到达一定分数后停止运行，再手动跳一会儿就行，目前这个方法可行

**Comment by 951240778** [comment]
我的为什么不跳呢？运行完  anto.py 文件后  每次截图 都是 0分的那个

**Comment by 951240778** [comment]
wechat_jump_auto.py

**Comment by wangshub** [comment]
先关闭了哦，别把分数搞得太高了 @NinoWang
