### ISSUE TITLE
希望用7p的大家来讨论下参数问题，我这一直是挑不准，而且最多200多

### ISSUE THREAD

**Issue by mkblbj** [wangshub/wechat_jump_game#639]

**Comment by lsc272** [comment]
同求，目前press_coefficient": 1.185

**Comment by syd24** [comment]
'RoutingHTTPServer/RoutingConnection.h' file not found 有木有遇到这个问题啊 运行 WebDriver。。时候

**Comment by mkblbj** [comment]
@lsc272 现在好了吗，，我的是默认配置。。还不行。

**Comment by mkblbj** [comment]
@syd24 你的环境没搭建完全，按教程一步一步来，我也遇到过这个问题
