### ISSUE TITLE
按压不是线性的，只有一个参数不合适

### ISSUE THREAD

**Issue by VitalyAnkh** [wangshub/wechat_jump_game#64]
我观察了好长时间运行结果，发现在我手机上设置比较好的参数（小米5s Plus，参数设置为1.418），在中远距离很完美，最高连续八九次跳到中心，然后距离较近时跳的不够远，掉了下来。这说明按压不是线性的，按压时间越长跳的距离增加速度越快。所以乘以一个参数不够，要用一个二次函数或者对数函数模拟吧。

**Comment by hiyoi** [comment]
确实是这样，有时候是两点到两点都是中心点。如果目标距离太远落点就会偏远于中心

**Comment by binderclip** [comment]
要出去搬砖了，求帮忙实现一下非线性的吧 😂 @VitalyAnkh

**Comment by VitalyAnkh** [comment]
@binderclip 要期末考试了老哥，赶快复习我的运筹学😂
想抱您的大腿，在朋友圈一鸣惊人😂

**Comment by binderclip** [comment]
@VitalyAnkh 去加我的微信小号吧 Wythe-Zhou

**Comment by VitalyAnkh** [comment]
@binderclip 嘿嘿

**Comment by mg459046365** [comment]
@VitalyAnkh 抛物线的原理吗

**Comment by F-loat** [comment]
最新版安卓微信安装包解压后搜索 `wxapkg` 就能找到跳一跳小程序的代码包，用[unweapp](https://github.com/moqi2011/unweapp)可以解包，然后就可以看到压缩后的js文件啦，虽然格式化后还是没法看。。但是算法应该还是找得到的😅

**Comment by F-loat** [comment]
图片资源可能更有用一点

**Comment by F-loat** [comment]
![i](https://user-images.githubusercontent.com/16759376/34453219-5e92f34c-ed89-11e7-9386-3e2c7534c00e.png)
![replay](https://user-images.githubusercontent.com/16759376/34453231-7c1e934e-ed89-11e7-8a64-208b7410f246.png)
