### ISSUE TITLE
小米Max2 计算距离不是很准

### ISSUE THREAD

**Issue by FTExplore** [wangshub/wechat_jump_game#640]
遇到几次都是在边缘的地方，掉下来了。
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI MAX 2
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]

**Comment by tangjw** [comment]
MIUI 修改 按压时间大约 +50ms ，亲测跳到400步不掉😁
cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time+50)
