### ISSUE TITLE
Screen: Physical size: 1080x1920 Density: Physical density: 480 DeviceType: FRD-AL00 OS: win32 Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

### ISSUE THREAD

**Issue by JoyGitHubPlace** [wangshub/wechat_jump_game#642]
**********
Screen: Physical size: 1080x2160
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：参数不准确
![]()
改进和建议：无

**Comment by TEENSTITAN** [comment]
Screen:         
Density:         
DeviceType:         
OS: win32        
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)
