### ISSUE TITLE
红米手机运行了没有报错，但是界面一直没动adb devices正常 

### ISSUE THREAD

**Issue by nature1991** [wangshub/wechat_jump_game#646]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: 2014813
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)
]
**********
采用方式1获取截图
scan_start_y:  476
1514880585 225 739 525.5 566
adb shell input swipe 360.0 1056 360.0 1056 727
scan_start_y:  476
1514880587 225 739 525.5 566
adb shell input swipe 360.0 1056 360.0 1056 727
scan_start_y:  476
1514880589 225 739 525.5 566
adb shell input swipe 360.0 1056 360.0 1056 727

**Comment by 951240778** [comment]
我的和你的问题 一模一样

**Comment by 951240778** [comment]
我是  note  4X

**Comment by 951240778** [comment]
每次截图 都是封面的截图

**Comment by nature1991** [comment]
一直在跑adb shell input。。。。。一点报错都没有 界面却不动

**Comment by binderclip** [comment]
你们确定是游戏开始了才启动程序的吗？

**Comment by nature1991** [comment]
...那是怎样 我是按照教程进入游戏界面再运行脚本的

**Comment by binderclip** [comment]
@nature1991 点了“开始游戏”吗？

**Comment by Sowevo** [comment]
小米的除了usb调试需要打开还有一个usb安全选项需要打开,然后才能模拟触摸 @951240778 @nature1991

**Comment by iTimeTraveler** [comment]
@nature1991 @951240778 你们没有打开开发者选项中的【USB调试（安全设置）】吧，需要允许模拟点击

**Comment by nature1991** [comment]
开了

**Comment by 951240778** [comment]
为什么只跳了到了  13

**Comment by 951240778** [comment]
可以跳了 @binderclip    谢谢

**Comment by nature1991** [comment]
我擦 咋搞

**Comment by 951240778** [comment]
@iTimeTraveler    可以了  谢谢

**Comment by 951240778** [comment]
@nature1991   你要打开  里面有个安全选项

**Comment by nature1991** [comment]
@951240778 usb调试（安全设置）?

**Comment by 951240778** [comment]
嗯呢   对 @nature1991

**Comment by nature1991** [comment]
终于搞定了，要把米柚优化关闭了才能开启安全设置 蛋疼  终于跑起来了 ok了

**Comment by 951240778** [comment]
嗯嗯  你看看  能跑到多少？ @nature1991   我的还没破百

**Comment by nature1991** [comment]
400+就挂了。。。。。又自动重新跑起来了

**Comment by DouglasYe** [comment]
usb调试里面开启安全设置那个就可以了，我的是小米6，开启玩自动跑了
