### ISSUE TITLE
向坐上方近距离跳跃定位出错

### ISSUE THREAD

**Issue by fgksgf** [wangshub/wechat_jump_game#647]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: win32
Python: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
**********
截图如下
![](http://i2.bvimg.com/603298/2e6db73813ccc015.png)
![](http://i2.bvimg.com/603298/35ae2797ec621710.png)
![](http://i2.bvimg.com/603298/ccf8640ccfc78b77.png)
![](http://i2.bvimg.com/603298/b6bc60fa9bc30b8a.png)

**Comment by Vg1ee** [comment]
关闭悬浮球！！！
