### ISSUE TITLE
raw_input 未定义

### ISSUE THREAD

**Issue by xqch12345** [wangshub/wechat_jump_game#648]
**********
Screen: Physical size: 1080x2160
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by dingdayu** [comment]
raw_input() 被改名为 input()

**Comment by dingdayu** [comment]
据说3.5和3.6的问题

**Comment by dingdayu** [comment]
同样的问题：

NameError: name 'xrange' is not defined

**Comment by xqch12345** [comment]
那要下低版本python吗

**Comment by Trigon** [comment]
不用下低版本  
把raw_input 改成input
xrange 改成range就可以了
这2个应该是py2的写法

**Comment by xqch12345** [comment]
改了之后显示 inconsistent use of tabs and spaces in indentation

**Comment by xqch12345** [comment]
重新复制了遍代码好了

**Comment by binderclip** [comment]
已经修复
