### ISSUE TITLE
求解 运行报错

### ISSUE THREAD

**Issue by ykBear** [wangshub/wechat_jump_game#649]
C:\Users\Administrator\Desktop\wechat_jump_game>python wechat_jump_auto.py
Load config file from C:\Users\Administrator\Desktop\wechat_jump_game/config/192
0x1080/config.json
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 260, in <module>
    main()
  File "wechat_jump_auto.py", line 227, in main
    op = yes_or_no('请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳游戏再用本
程序，确定开始？')
  File "wechat_jump_auto.py", line 211, in yes_or_no
    i = raw_input(prompt)
NameError: name 'raw_input' is not defined
怎么解决各位python程序员

**Comment by LawAias** [comment]
[#648](https://github.com/wangshub/wechat_jump_game/issues/648)raw_input改成input

**Comment by binderclip** [comment]
已经修了
