### ISSUE TITLE
dump_device_info()出现问题

### ISSUE THREAD

**Issue by athosss** [wangshub/wechat_jump_game#651]
Screen: Physical size: 1080x1920
Density: Physical density: 440
DeviceType: MI NOTE LTE
OS: win32
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
**********Traceback (most recent call last):
  File "wechat_jump_auto1.py", line 356, in <module>
    main()
  File "wechat_jump_auto1.py", line 339, in main
    dump_device_info()
  File "wechat_jump_auto1.py", line 321, in dump_device_info
    python=sys.version
IOError: [Errno 0] Error

用的是virtualenv python2.7

**Comment by binderclip** [comment]
重试可以通过吗？

**Comment by athosss** [comment]
@binderclip 是的，重拾还是这个情况

**Comment by binderclip** [comment]
这已经是旧代码了，更新一下最新的试试

**Comment by athosss** [comment]
@binderclip 新代码也是这样
