### ISSUE TITLE
报错OSError: cannot identify image file './autojump.png'

### ISSUE THREAD

**Issue by fu19900808** [wangshub/wechat_jump_game#652]
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: HM NOTE 1LTE
OS: win32
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
**********
List of devices attached
cb18ba1a        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "C:\Python35\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'
**********
遇到问题：运行程序的时候报的，是什么原因呢？
改进和建议：无

**Comment by binderclip** [comment]
重新运行后还有问题吗？

**Comment by fu19900808** [comment]
还是不行，是不是版本太老的问题？手动模式的能正常用，不知道什么原因

**Comment by fu19900808** [comment]
欧了！更新最新代码可以了，还有一个问题是安卓版本太低了！解决了！
