### ISSUE TITLE
能不能加入图形识别模式

### ISSUE THREAD

**Issue by everhopingandwaiting** [wangshub/wechat_jump_game#653]
改进和建议：python 有没有可以识别图片中各种形状的库呢？ 查了下没找到， 如果有这个库的话， 识别出图片中的 矩形、圆形 等， 然后就可以根据这个算出 图片中各形状的中心坐标点， 这比目前的 自动识别像素的方式好点。

**Comment by binderclip** [comment]
[一次不成功的深度学习实践 - 微信跳一跳](https://mp.weixin.qq.com/s/Y6i-1skF8QHEDa8L8D2oNw)

这里有用到 OpenCV 的方案，看起来不错的

**Comment by cxgreat2014** [comment]
赞同，现在识别的确容易出错。
![image](https://user-images.githubusercontent.com/15062548/34484122-aaf380fa-effd-11e7-8a14-10791b7801d5.png)
