### ISSUE TITLE
刷了一次500+，一次1000+，分数都被屏蔽了，现在刷了一次400+ ，分数留下了

### ISSUE THREAD

**Issue by afinal** [wangshub/wechat_jump_game#654]
**********
Screen: Physical size: 1080x2160
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by SmileWoXing** [comment]
哈哈 我刷了500+留下来了
