### ISSUE TITLE
跳完的分数显示问题

### ISSUE THREAD

**Issue by wzjs** [wangshub/wechat_jump_game#656]
跳完之后排行版刷新了， 重新退出游戏再进去之后又是之前的记录?

**Comment by Sowevo** [comment]
微信现在有检测的样子

**Comment by binderclip** [comment]
打到了多少分？用的什么时候更新的代码？

**Comment by wzjs** [comment]
从1000降到600 都这样 ,刚从git上下的

**Comment by TheViperS** [comment]
今天的代码，一次1000+被砍，二次499被砍，三次77时手动断掉，跳了几下之后gg，留在了排行榜。四次122时手动控制跳了一会儿，分数留榜。基本上，建议跳一次500+的，然后手动玩一会儿，过10分钟再看结果。

**Comment by TokuraZCJ** [comment]
1220分 还在榜，退了微信在进 试试

**Comment by wangyingang** [comment]
1209分 被砍
