### ISSUE TITLE
出现错误 Error: Invalid arguments for command: swipe ，求教大佬！

### ISSUE THREAD

**Issue by terrybogez** [wangshub/wechat_jump_game#657]
环境：Win7 旗舰版 ，Python 3.6.4 ，安卓手机分辨率720*1280
**
C:\Users\zhangxing\Desktop\wechat_jump_game-master>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
**

依赖环境通过pip install -r requirements.txt 已经全部都安装好了 ，
ADB已经连接好。
**
C:\Users\zhangxing\Desktop\wechat_jump_game-master>adb kill-server
C:\Users\zhangxing\Desktop\wechat_jump_game-master>adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached
1ad7be70        device
**

环境变量设置：
系统变量名：Android
系统变量值：C:\adb

运行的时候一直有个报错：Error: Invalid arguments for command: swipe
**
C:\Users\zhangxing\Desktop\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from C:\Users\zhangxing\Desktop\wechat_jump_game-master/config/
1280x720/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: SM-N7508V
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)
]
**********
采用方式1获取截图
scan_start_y:  476
1514881543 496 721 239.5 575
adb shell input swipe 360.0 1056 360.0 1056 619
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [d
uration(ms)]
       input trackball press
       input trackball roll <dx> <dy>
scan_start_y:  476
1514881546 496 721 239.5 575
adb shell input swipe 360.0 1056 360.0 1056 619
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [d
uration(ms)]
       input trackball press
**
然后就一直循环重复上面的内容。

虽然不太懂python，但是网上有很多教程，我一般也是先自己琢磨这看看，依葫芦画瓢应该还是会的，但是确实碰到了不知道是哪里的问题的问题，所以把自己的环境写清楚，让大佬们诊断一下，谢谢！

**Comment by JERRYisME0330** [comment]
同报错，等解救中。。。

**Comment by binderclip** [comment]
adb shell input swipe 360.0 1056 360.0 1056 619 这里的数字应该都是整形，我去改一下

**Comment by binderclip** [comment]
好像没问题，请问是最新的代码吗？

**Comment by JERRYisME0330** [comment]
刚换最新的代码，同样问题，大佬

**Comment by terrybogez** [comment]
@binderclip 我又再去试了一次最新代码，报错还是一样的

C:\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from C:\wechat_jump_game-master/config/1280x720/config.json
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确
定开始？ y/n [y]: y
如果你的脚本无法工作，上报 issue 时请 copy 如下信息：
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: SM-N7508V
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)
]
**********
采用方式 1 获取截图
scan_start_y: 476
1514884700 259 720 471.0 597
adb shell input swipe 326 1065 326 1065 514
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [d
uration(ms)]
       input trackball press
       input trackball roll <dx> <dy>
scan_start_y: 476
1514884703 259 720 471.0 597
adb shell input swipe 336 1060 336 1060 514
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [d
uration(ms)]
       input trackball press
       input trackball roll <dx> <dy>
scan_start_y: 476
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 261, in <module>
    main()
  File "wechat_jump_auto.py", line 240, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 129, in find_piece_and_board
    if (50 < pixel[0] < 60) and (53 < pixel[1] < 63) and (95 < pixel[2] < 110):
KeyboardInterrupt


以上

**Comment by JERRYisME0330** [comment]
@binderclip 
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: GT-I9508
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********
采用方式 1 获取截图
scan_start_y: 690
1514886190 338 1109 788.5 849
adb shell input swipe 583 1589 583 1589 724
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [duration(ms)]
       input trackball press
       input trackball roll <dx> <dy>
scan_start_y: 690
1514886194 338 1109 788.5 849
adb shell input swipe 552 1578 552 1578 724
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [duration(ms)]
       input trackball press
       input trackball roll <dx> <dy>
scan_start_y: 690
1514886197 338 1109 788.5 849
adb shell input swipe 561 1574 561 1574 724
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [duration(ms)]
       input trackball press
       input trackball roll <dx> <dy>

**Comment by binderclip** [comment]
你们的系统版本是多少？

[tasker shell input 模拟长按操作_tasker吧_百度贴吧](http://tieba.baidu.com/p/3682205129?traceid=)

似乎是这个问题

**Comment by JERRYisME0330** [comment]
@binderclip 我是用我的老安卓在试，是三星的S4的i9508
系统是4.3

**Comment by binderclip** [comment]
@JERRYisME0330 感觉是太旧了，你们可能需要改一下那个 ADB 命令

**Comment by JERRYisME0330** [comment]
@binderclip 我感觉也可能太旧了，不过我现在新的问题了。。。
PS C:\Users\JERRY\AppData\Local\Programs\Python\Python36> python wechat_jump_auto.py
请在项目根目录中运行脚本

**Comment by BruceGui** [comment]
你先在CMD下面运行如下命令：
```bash
adb shell input touchscreen swipe 300 300 300 300 3
```
看看有没有错误，如果没有的话就把源码里面的按压命令加上  touchscreen

**Comment by binderclip** [comment]
@JERRYisME0330 所以在按提示操作啊

**Comment by JERRYisME0330** [comment]
@BruceGui 执行没有任何结果，就是没错误是吧，大哥

**Comment by BruceGui** [comment]
是的，你的安卓是 4.3 的，长按的话命令有所改变，可以看一下[ input ](https://android.googlesource.com/platform/frameworks/base/+/android-4.3.1_r1/cmds/input/src/com/android/commands/input/Input.java)的源码就知道了

**Comment by BruceGui** [comment]
找到源码里面的如下函数：
```python
def jump(distance):
```
然后把里面的：
```python
cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'
```
这个里面的 adb shell input 命令后面加上 touchscreen 就行了
然后运行一下看看有没有错误

**Comment by JERRYisME0330** [comment]
@BruceGui OK了，感谢大哥

**Comment by z-jingjie** [comment]
Android 4.2.2版本，touchscreen swipe的参数不支持延时，无法模拟长按效果，要如何解决呢？谢谢

>adb shell input swipe 300 300 300 300 3

`Error: Invalid arguments for command: keyevent
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad] tap <x> <y>
       input [touchscreen|touchpad] swipe <x1> <y1> <x2> <y2>
       input trackball press
       input trackball roll <dx> <dy>`

**Comment by terrybogez** [comment]
@BruceGui 感谢你优化的touchscreen代码，确实可以在我的安卓4.3（三星NOTES LITE SM-N7508V）上运行了，但是还是出现了问题，差不多跳几下会停下来。
@binderclip 大佬请看以下报错。
C:\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from C:\wechat_jump_game-master/config/1280x720/config.json
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确
定开始？ y/n [y]: y
如果你的脚本无法工作，上报 issue 时请 copy 如下信息：
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: SM-N7508V
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)
]
**********
采用方式 1 获取截图
scan_start_y: 526
1514942718 258 702 477.0 594
adb shell input touchscreen swipe 329 1056 329 1056 512
scan_start_y: 526
1514942722 436 678 322.5 623
adb shell input touchscreen swipe 350 1056 350 1056 264
scan_start_y: 526
1514942725 311 682 432.5 620
adb shell input touchscreen swipe 337 1055 337 1055 286
scan_start_y: 476
1514942728 552 750 202.5 554
adb shell input touchscreen swipe 351 1055 351 1055 841
scan_start_y: 526
1514942732 215 727 520.0 569
adb shell input touchscreen swipe 393 1049 393 1049 720
scan_start_y: 476
1514942735 577 743 196.0 550
adb shell input touchscreen swipe 390 1049 390 1049 896
scan_start_y: 526
1514942739 176 739 548.5 553
adb shell input touchscreen swipe 405 1065 405 1065 873
已经连续打了 7 下，休息 6s
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 261, in <module>
    main()
  File "wechat_jump_auto.py", line 251, in main
    for j in xrange(next_rest_time):
NameError: name 'xrange' is not defined

然后我必须重新运行命令，
以上，
谢谢！

**Comment by z-jingjie** [comment]
@terrybogez
> NameError: name 'xrange' is not defined

找到wechat_jump_auto.py的第251行，把xrange改成range试试

**Comment by terrybogez** [comment]
更新一下，我把刚才的python版本由3.6.4（32bit）换成了2.7.14（64bit），就可以正常运行了。

@z-jingjie 谢谢，我没有改这个参数，只是把python版本换低了一些就行了。

刷了800多分就暂停了，技术问题解决了心里比刷高分更爽。
