### ISSUE TITLE
ModuleNotFoundError: No module named 'WechatJump'

### ISSUE THREAD

**Issue by allen2424** [wangshub/wechat_jump_game#658]
运行脚本提示：

============ RESTART: C:\Users\allen\Desktop\wechat_jump_auto.py ============
Traceback (most recent call last):
  File "C:\Users\allen\Desktop\wechat_jump_auto.py", line 22, in <module>
    from WechatJump import Debug, Config
ModuleNotFoundError: No module named 'WechatJump'

**********
Screen: Physical size: 1080x2160
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by binderclip** [comment]
代码请在项目目录中运行
