### ISSUE TITLE
【萌新不太懂】这些是什么意思

### ISSUE THREAD

**Issue by ArthurFung1998** [wangshub/wechat_jump_game#659]
**********
Screen: Physical size: 1920*1080
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 3.6.5 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：C:\Users\ArthurFung\Downloads\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from C:\Users\ArthurFung\Downloads\wechat_jump_game-master/config/1920x1080/config.json
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 248, in <module>
    main()
  File "wechat_jump_auto.py", line 225, in main
    op = yes_or_no('请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳游戏再用本程序，确定开始？')
  File "wechat_jump_auto.py", line 209, in yes_or_no
    i = raw_input(prompt)
NameError: name 'raw_input' is not defined
改进和建议：无

**Comment by TheViperS** [comment]
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳游戏再用本程序

**Comment by AlexLove77** [comment]
Windows 请运行python3的 `wechat_jump_py3.py`

**Comment by Cxiaoqiang** [comment]
NameError: name 'raw_input' is not defined
raw_input未被定义，请去掉raw，改为input

**Comment by binderclip** [comment]
是个 bug，已经修复了，请更新代码 https://github.com/wangshub/wechat_jump_game/pull/663
