### ISSUE TITLE
wechat_jump_auto.py文件打开后闪退，手机没有反应

### ISSUE THREAD

**Issue by Shurrik13** [wangshub/wechat_jump_game#66]

**Comment by F-loat** [comment]
`python wechat_jump_auto.py` Readme里有写的。

**Comment by yangmingxin2016** [comment]
文件放到administrator下了吗，提示找不到文件

**Comment by Shurrik13** [comment]
@F-loat 我是按着那个步骤来的，可是一点开那个程序就会闪退

**Comment by pplps** [comment]
python装好了嘛， 依赖装好了没。

**Comment by Shurrik13** [comment]
python和pip都下了

**Comment by binderclip** [comment]
@Shurrik13 你目录不对啊，要去项目目录下执行

**Comment by Shurrik13** [comment]
@binderclip 哥。。咋弄啊

**Comment by binderclip** [comment]
@Shurrik13 去学一下基础的东西吧。。[CMD命令进入某个目录 - CSDN博客](http://blog.csdn.net/aidenliu/article/details/5390113)

**Comment by zengke123** [comment]
@Shurrik13 切换到wechat_jump_auto.py所在目录，然后python wechat_jump_auto.py 执行
最好检测下你的环境变量，有没有设置python的路径

**Comment by Shurrik13** [comment]
@binderclip 好的

**Comment by Shurrik13** [comment]
@zengke123 嗯嗯，谢啦

**Comment by Shurrik13** [comment]
@binderclip 哥！已经能打开了，但是他说
![g _7i ep k2 nouv 1g n](https://user-images.githubusercontent.com/34955638/34452207-4c6622b6-ed75-11e7-9d7f-55c7f12a7993.png)

**Comment by F-loat** [comment]
@Shurrik13 安装下依赖

**Comment by abcd106** [comment]
pip install -r requirements.txt 这个怎么安装，但是报pip不是内部或外部命令

**Comment by as00v1** [comment]
pip估计没加到path吧。。

**Comment by Shurrik13** [comment]
@as00v1 我是按着网上说的去下pip解压的，请问怎么算把它加到python里啊？

**Comment by as00v1** [comment]
你要没啥经验，建议你先卸载你现在的python版本，然后从官网下载安装包重新安装，在安转的界面勾选一个添加到系统环境变量的复选框，然后一路next安装就好了。

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
