### ISSUE TITLE
（三星s6）运行wechat_jump_auto.py报错

### ISSUE THREAD

**Issue by AAAAAbox** [wangshub/wechat_jump_game#660]
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]                                  **********Traceback (most recent call last):                                                                              File ".\wechat_jump_auto.py", line 260, in <module>                                                                       main()                                                                                                                File ".\wechat_jump_auto.py", line 231, in main                                                                           Debug.dump_device_info()                                                                                              File "C:\Users\yangz\Desktop\wechat_jump_game\WechatJump\Debug.py", line 65, in dump_device_info                          python=sys.version                                                                                                  IOError: [Errno 0] Error

**Comment by 631942372** [comment]
我运行时直接闪退了

**Comment by binderclip** [comment]
这个重复还是报这个错？
@631942372 闪退原因太多了，请提供更多有用信息。

**Comment by 631942372** [comment]
不好意思，python小白，原因应该是print之后就窗口关闭了，我反复打开多次，报的错是rawInput not defined

**Comment by 631942372** [comment]
更新之后没问题了。
