### ISSUE TITLE
这里有Mac配合安卓机型的使用方式

### ISSUE THREAD

**Issue by zq019633** [wangshub/wechat_jump_game#661]
http://blog.csdn.net/zq019/article/details/78952896

**Comment by binderclip** [comment]
[Android 和 iOS 操作步骤 · wangshub/wechat_jump_game Wiki](https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4)

wiki 里有类似的了，回头链接到 readme
