### ISSUE TITLE
请教大佬们：powershell显示”请安装ADB及驱动并配置环境变量“，但我已经安装成功，路径也已配置完成。

### ISSUE THREAD

**Issue by JerryLiuBing** [wangshub/wechat_jump_game#665]
![image](https://user-images.githubusercontent.com/35018099/34478792-d55ed094-efdd-11e7-896b-29460aa49ec4.png)
powershell显示的内容
![image](https://user-images.githubusercontent.com/35018099/34478908-798809a6-efde-11e7-9750-fa052859e5ed.png)
cmd显示的内容，但最后一行没有”XXXXX   device“
并且手机已经打开USB调试功能
请问这是何原因呢

**Comment by qicunshang** [comment]
看看手机调试模式是否打开，电脑是否能读到手机，或者重启一下adb服务，或者下载手机的官方手机助手修复一下

**Comment by Trigon** [comment]
换个usb口 再试一下 最好是装手机自己的adb驱动再试试

**Comment by JerryLiuBing** [comment]
![image](https://user-images.githubusercontent.com/35018099/34479125-c33f1c1e-efdf-11e7-8425-207e5bbfa6d1.png)
手机为一加5，网络ADB调试需要打开吗？还有请问手机自己的adb驱动怎么安装呢？

**Comment by qicunshang** [comment]
看看 选择usb设置是不是MTP，如果不是就改成MTP，如果已经是MTP，可以试试下载一加手机usb驱动，参考http://www.oneplusbbs.com/forum.php?mod=viewthread&tid=456162

**Comment by Trigon** [comment]
惊了 居然和我手机一样 你直接装一加自带的驱动就ok了

**Comment by TokuraZCJ** [comment]
多半是因为没有手机驱动，不排除数据线和USB接口问题

**Comment by ykBear** [comment]
你这手机没有显示出来  在list of devices下面有一行才会成功  可以在网上找下adb 不显示手机 有答案

**Comment by skolly** [comment]
小米手机遇到一摸一样的情况，求解答，谢谢

**Comment by lDaisy847800926** [comment]
E:\Wechat_jumpy\ADB>adb devices
List of devices attached
TWGDU16A11004967        device

明明已经找到了设备，为什么在运行代码的时候还是显示：请安装ADB及驱动并配置环境变量

**Comment by skolly** [comment]
@lDaisy847800926  我把任务进程里的  adb.exe  kill 掉，然后重新打开，就可以运行了。

**Comment by GdZ** [comment]
把设备的vid加入到.android/usb.ini试试

**Comment by qicunshang** [comment]
@lDaisy847800926 是不是adb没有配置环境变量

**Comment by chloechj** [comment]
确定下载了ADB(首页有)，下载完之后解压，在py程序需要执行shell的前面转到ADB所在文件夹命令是os.chdir()。看看手机ADB调试是不是都开开了

**Comment by JerryLiuBing** [comment]
@Trigon 一加自带的驱动是啥啊。。安装完楼上给的链接试完还是不行。一加MTP模式怎么开呢，是这种吗？
BTW  老哥选手机的眼光不错
![image](https://user-images.githubusercontent.com/35018099/34520524-eda5c07c-f0c3-11e7-98e6-1ada36812e66.png)

![image](https://user-images.githubusercontent.com/35018099/34520487-cace1cfc-f0c3-11e7-8450-d5aa789ec09a.png)

**Comment by mengDTT** [comment]
提供另外一个思路，把 adb.exe，AdbWinApi.dll，AdbWinUsbApi.dll 三个文件放在wechat_jump_auto.py的目录下，程序就可以运行了，避免了设置路径的问题。

**Comment by mengDTT** [comment]
@JerryLiuBing 可以去 Android 官网进行下载SDK进行尝试 https://developer.android.com/studio/releases/platform-tools.html，本人手机一加3，链接里的adb可以使用，论坛下载adb的可能无法使用。USB连接模式选择**传输文件**即可。

**Comment by Trigon** [comment]
手机插上电脑 会有一个一加符号的磁盘 点开里面有自带的驱动  MTP就是传输文件那个选项

**Comment by renhuan2015** [comment]
有没有安装Python环境啊

**Comment by Code6666** [comment]
你可以 试一下 将你 电脑上的  adb。exe  覆盖掉  这个 项目中的  adb.exe  ，  可能是 因为 adb 的版本 不兼容的问题  ，  我也遇到这样的问题了  ，  然后 替换成  自己电脑上 就好了

**Comment by sfeipo** [comment]
没装ADB驱动，搜一下就知道了，要另外装的。ADB Driver Installer
