### ISSUE TITLE
提示休息几秒之后不会继续自动运行

### ISSUE THREAD

**Issue by allen2424** [wangshub/wechat_jump_game#666]
如果你的脚本无法工作，上报 issue 时请 copy 如下信息：
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OD103
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********
采用方式 0 获取截图
scan_start_y: 740
1514883892 770 1104 350.0 852
adb shell input swipe 550 1592 550 1592 681
scan_start_y: 740
1514883897 737 1078 395.5 878
adb shell input swipe 548 1580 548 1580 550
scan_start_y: 740
1514883901 767 1096 350.5 854
adb shell input swipe 588 1586 588 1586 670
scan_start_y: 690
1514883906 795 1112 331.0 841
adb shell input swipe 493 1586 493 1586 747
scan_start_y: 690
1514883911 814 1122 250.5 795
adb shell input swipe 571 1579 571 1579 906
scan_start_y: 690
1514883915 703 1058 249.5 799
adb shell input swipe 561 1588 561 1588 726
scan_start_y: 790
1514883920 414 1078 723.0 882
adb shell input swipe 573 1589 573 1589 509
已经连续打了 7 下，休息 8s
Traceback (most recent call last):
  File "C:\Users\allen\Desktop\wechat_jump_game-master\wechat_jump_auto.py", line 261, in <module>
    main()
  File "C:\Users\allen\Desktop\wechat_jump_game-master\wechat_jump_auto.py", line 251, in main
    for j in xrange(next_rest_time):
NameError: name 'xrange' is not defined

**Comment by xzhlksh** [comment]
把251行的xrange改为range（即去掉x）即可，是个python兼容性老坑

**Comment by ArthurFung1998** [comment]
谢了，改了之后可以了
