### ISSUE TITLE
不能连续跳，跳几下就死掉了

### ISSUE THREAD

**Issue by city4north** [wangshub/wechat_jump_game#668]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: 1607-A01
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
**********

不能连续跳，跳几下就死掉了

**Comment by xzhlksh** [comment]
1分钟之前的最新版已修，请更新

**Comment by binderclip** [comment]
请试试找一个合适的 config，然后自己调一调参数

**Comment by xie654516593** [comment]
已经将config下的分辨率复制到根目录，效果好像没明显增加。

**Comment by xie654516593** [comment]
已经将config下的分辨率复制到根目录，效果好像没明显增加。

感觉每次蓄力较大，
请教，调参数要怎么调？
