### ISSUE TITLE
这什么问题大佬们

### ISSUE THREAD

**Issue by fishlegss** [wangshub/wechat_jump_game#669]
![default](https://user-images.githubusercontent.com/34986206/34479359-3c998da0-efe1-11e7-9d69-a26317f524a7.png)

**Comment by leeggco** [comment]
ADB 还没装吧，按步骤来。

**Comment by fishlegss** [comment]
装了啊

**Comment by fishlegss** [comment]
跪求！！

**Comment by Vg1ee** [comment]
adb没配置好吧

**Comment by binderclip** [comment]
参考 wiki 一步一步来
[Android 和 iOS 操作步骤 · wangshub/wechat_jump_game Wiki](https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4)

**Comment by fishlegss** [comment]
自己的问题怎么删除啊。。大佬
