### ISSUE TITLE
休息时NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by MusiGuan** [wangshub/wechat_jump_game#671]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: M6 Note
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
**********
遇到问题：休息时闪退，错误信息：Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: M6 Note
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
![]()
改进和建议：无

**Comment by jacknonebug** [comment]
我这边也遇到过这个问题,是不是微信反作弊整的!

**Comment by MusiGuan** [comment]
> 我这边也遇到过这个问题,是不是微信反作弊整的!

应该是为了防止检测，所以休息，但是休息时有个参数非法，可能和之前问题一样因为PY版本不一样的兼容问题？

**Comment by cls1991** [comment]
py3只有range

**Comment by Vg1ee** [comment]
#666
