### ISSUE TITLE
Android + win 7 运行自动跳转脚本问题

### ISSUE THREAD

**Issue by Xing94** [wangshub/wechat_jump_game#672]
**********
Screen: Physical size: 1080x2160
Density: Physical density: 400
Override density: 480
DeviceType: OS105
OS: darwin
Python: 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

![image](https://user-images.githubusercontent.com/16348290/34479695-42236596-efe3-11e7-9a1d-61645bb97fae.png)

**Comment by MusiGuan** [comment]
更新代码，作者已经更新兼容这个问题了

**Comment by Xing94** [comment]
我下载没多久啊

**Comment by binderclip** [comment]
刚才更新的 @Xing94 你更新下试试

**Comment by MusiGuan** [comment]
> 我下载没多久啊

已经更新解决这个问题了，我之前也是这个问题现在已经解决了，你更新下那个文件试试

**Comment by Xing94** [comment]
谢谢，我刚刚更新，可以了

**Comment by Xing94** [comment]
已经连续打了五下，休息7s什么鬼
