### ISSUE TITLE
自己手动跳了几十步，然后运行脚本继续，排行榜不记录。

### ISSUE THREAD

**Issue by DomainCollection** [wangshub/wechat_jump_game#673]
自己手动跳了几十步，然后运行脚本继续，排行榜不记录。在朋友的排行榜上看还是原来的最高次数。

**Comment by hncboy** [comment]
等你失败以后才会更新

**Comment by DomainCollection** [comment]
刚刚自动跳到了505步后，自只有自己排行榜更新了，其他朋友还是原来的排行。

**Comment by fu19900808** [comment]
试下自己跳一会，脚本跑一会，自己再跳一会，或者用手动跳的脚本！不太清楚微信是什么检测算法来判断的。我刚才自己跳一会，手动脚本跳一会，最后再手动跳一会，分数没有被和谐。不过不是很高，才三百多分

**Comment by DomainCollection** [comment]
应该是超过多少步就会被检测，或者是连续跳中中心点的次数。

**Comment by amesshen** [comment]
我也碰到一样的问题，手动跳几步，脚本跑起来到100多一点的时候结束脚本，手动跳几步结束游戏。
虽然只有120多分，但还是未被记录。

**Comment by AlienMarkWong** [comment]
同样碰到了这个问题，可以跳一会切出微信，休息一会，再手动玩几把，应该就可以同步了

**Comment by fu19900808** [comment]
我刚才跑了个一千多，一个多小时，记录都还在，搞不懂了！用最新更新的版本跑的

**Comment by lupengwei** [comment]
游戏模式下怎么配置
