### ISSUE TITLE
python wechat_jump_auto.py 出错

### ISSUE THREAD

**Issue by Gx952743985** [wangshub/wechat_jump_game#674]
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 8, in <module>
    from PIL import Image, ImageDraw
ImportError: No module named PIL

**Comment by binderclip** [comment]
按步骤来，记得装依赖 [Android 和 iOS 操作步骤 · wangshub/wechat_jump_game Wiki](https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4)

**Comment by Gx952743985** [comment]
我看你们都是说 没装这个  pip install -r requirements.txt   


Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/cycler.py'


我会遇到这样的错误

**Comment by yeleiyu** [comment]
安装requirements的时候遇到以下错误。。

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/backports'

**Comment by yeleiyu** [comment]
可能是pip版本低的关系，先更新下pip 然后多试几次安装这个requirements文件。
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

pip install --upgrade pip

**Comment by baccachen** [comment]
配置环境的过程中，出现以下问题，各位大神能否帮忙看下是哪里的问题
C:\Users\Administrator\Downloads\wechat_jump_game-master>pip install -r requirements.txt
Downloading/unpacking backports.functools-lru-cache==1.4 (from -r requirements.txt (line 1))
  Downloading backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Downloading/unpacking cycler==0.10.0 (from -r requirements.txt (line 2))
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Downloading/unpacking matplotlib==2.1.1 (from -r requirements.txt (line 3))
  Running setup.py (path:C:\Users\ADMINI~1\AppData\Local\Temp\pip_build_Administrator\matplotlib\setup.py) egg_info for package matplotlib
    ============================================================================

    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.1]
                    python: yes [3.4.0 (v3.4.0:04f714765c13, Mar 16 2014,19:25:23) [MSC v.1600 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.14.0rc1]
                       six: yes [using six version 1.11.0]
                  dateutil: yes [using dateutil version 2.4.2]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [pytz was not found. pip/easy_install may attempt to install it after matplotlib.]
                    cycler: yes [cycler was not found. pip/easy_install may attempt to install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the WebAgg backend. pip/easy_install may attempt to install it after matplotlib.]
                 pyparsing: yes [using pyparsing version 2.0.3]
                    libagg: yes [pkg-config information for 'libagg' could not be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be found.  You may need to install the development package.]
                     qhull: yes [pkg-config information for 'libqhull' could not be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]

                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl / Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================

                            * The following required packages can not be built:
                            * freetype, png * Please check http://gnuwin32.sourc

                            * eforge.net/packages/freetype.htm for instructions
                            * to install freetype * Please check http://gnuwin32

                            * .sourceforge.net/packages/libpng.htm for
                            * instructions to install png
    Complete output from command python setup.py egg_info:
    ============================================================================


Edit setup.cfg to change the build options



BUILDING MATPLOTLIB

            matplotlib: yes [2.1.1]

                python: yes [3.4.0 (v3.4.0:04f714765c13, Mar 16 2014,19:25:23) [MSC v.1600 64 bit (AMD64)]]

              platform: yes [win32]



REQUIRED DEPENDENCIES AND EXTENSIONS

                 numpy: yes [version 1.14.0rc1]

                   six: yes [using six version 1.11.0]

              dateutil: yes [using dateutil version 2.4.2]

backports.functools_lru_cache: yes [Not required]

          subprocess32: yes [Not required]

                  pytz: yes [pytz was not found. pip/easy_install may attempt to install it after matplotlib.]

                cycler: yes [cycler was not found. pip/easy_install may attempt to install it after matplotlib.]

               tornado: yes [tornado was not found. It is required for the WebAgg backend. pip/easy_install may attempt to install it after matplotlib.]

             pyparsing: yes [using pyparsing version 2.0.3]

                libagg: yes [pkg-config information for 'libagg' could not be found. Using local copy.]

              freetype: no  [The C/C++ header for freetype

                        (freetype2\ft2build.h) could not be found.  You may need to install the development package.]

                   png: no  [The C/C++ header for png (png.h) could not be found.  You may need to install the development package.]

                 qhull: yes [pkg-config information for 'libqhull' could not

                        be found. Using local copy.]



OPTIONAL SUBPACKAGES

           sample_data: yes [installing]

              toolkits: yes [installing]

                 tests: no  [skipping due to configuration]

        toolkits_tests: no  [skipping due to configuration]



OPTIONAL BACKEND EXTENSIONS

                macosx: no  [Mac OS-X only]

                qt5agg: no  [PySide2 not found; PyQt5 not found]

                qt4agg: no  [PySide not found; PyQt4 not found]

               gtk3agg: no  [Requires pygobject to be installed.]

             gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]

                gtkagg: no  [Requires pygtk]

                 tkagg: yes [installing; run-time loading from Python Tcl /  Tk]

                 wxagg: no  [requires wxPython]

                   gtk: no  [Requires pygtk]

                   agg: yes [installing]

                 cairo: no  [cairocffi or pycairo not found]

             windowing: yes [installing]



OPTIONAL LATEX DEPENDENCIES

                dvipng: no

           ghostscript: no

                 latex: no

               pdftops: no



OPTIONAL PACKAGE DATA

                  dlls: no  [skipping due to configuration]



============================================================================

                        * The following required packages can not be built:

                        * freetype, png * Please check http://gnuwin32.sourc

                        * eforge.net/packages/freetype.htm for instructions

                        * to install freetype * Please check http://gnuwin32

                        * .sourceforge.net/packages/libpng.htm for

                        * instructions to install png

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\ADMINI~1\A
ppData\Local\Temp\pip_build_Administrator\matplotlib
Storing debug log for failure in C:\Users\Administrator\pip\pip.log

C:\Users\Administrator\Downloads\wechat_jump_game-master>python wechat_jump_auto
.py
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 20, in <module>
    from PIL import Image
ImportError: No module named 'PIL'

**Comment by athosss** [comment]
PIL这个包只有对应py2的版本，没有py3的版本，并且py2版本需要自动去官网安装。

**Comment by zhouxshen** [comment]
sudo pip install pillow

**Comment by baccachen** [comment]
运行pip install pillow以后出现以下问题
copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\OleFileIO.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\TarIO.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\version.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\_binary.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\_util.py -> build\lib.win-amd64-3.4\PIL

copying src\PIL\__init__.py -> build\lib.win-amd64-3.4\PIL

running egg_info

writing src\Pillow.egg-info\PKG-INFO

writing top-level names to src\Pillow.egg-info\top_level.txt

writing dependency_links to src\Pillow.egg-info\dependency_links.txt

C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option:
 'python_requires'

  warnings.warn(msg)

warning: manifest_maker: standard file '-c' not found



reading manifest file 'src\Pillow.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no files found matching '*.c'

warning: no files found matching '*.h'

warning: no files found matching '*.sh'

no previously-included directories found matching 'docs\_static'

warning: no previously-included files found matching '.coveragerc'

warning: no previously-included files found matching 'codecov.yml'

warning: no previously-included files found matching '.editorconfig'

warning: no previously-included files found matching '.landscape.yaml'

warning: no previously-included files found matching '.travis'

warning: no previously-included files found matching '.travis\*'

warning: no previously-included files found matching 'appveyor.yml'

warning: no previously-included files found matching 'build_children.sh'

warning: no previously-included files found matching 'tox.ini'

warning: no previously-included files matching '.git*' found anywhere in distrib
ution

warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution

warning: no previously-included files matching '*.so' found anywhere in distribu
tion

writing manifest file 'src\Pillow.egg-info\SOURCES.txt'

running build_ext





The headers or library files could not be found for zlib,

a required dependency when compiling Pillow from source.



Please see the install instructions at:

   https://pillow.readthedocs.io/en/latest/installation.html



Traceback (most recent call last):

  File "C:\Users\ADMINI~1\AppData\Local\Temp\pip_build_Administrator\pillow\setu
p.py", line 792, in <module>

    zip_safe=not (debug_build() or PLATFORM_MINGW), )

  File "C:\Python34\lib\distutils\core.py", line 149, in setup

    dist.run_commands()

  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()

  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 54, i
n run

    return _install.run(self)

  File "C:\Python34\lib\distutils\command\install.py", line 554, in run

    self.run_command('build')

  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()

  File "C:\Python34\lib\distutils\command\build.py", line 126, in run

    self.run_command(cmd_name)

  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()

  File "C:\Python34\lib\distutils\command\build_ext.py", line 348, in run

    self.build_extensions()

  File "C:\Users\ADMINI~1\AppData\Local\Temp\pip_build_Administrator\pillow\setu
p.py", line 580, in build_extensions

    raise RequiredDependencyException(f)

__main__.RequiredDependencyException: zlib



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\ADMINI~1\AppData\Local\Temp\pip_build_Administrator\pillow\setu
p.py", line 804, in <module>

    raise RequiredDependencyException(msg)

__main__.RequiredDependencyException:



The headers or library files could not be found for zlib,

a required dependency when compiling Pillow from source.



Please see the install instructions at:

   https://pillow.readthedocs.io/en/latest/installation.html





----------------------------------------
Cleaning up...
Command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Use
rs\\ADMINI~1\\AppData\\Local\\Temp\\pip_build_Administrator\\pillow\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pi
p-5ebcpegq-record\install-record.txt --single-version-externally-managed --compi
le failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip_build_Ad
ministrator\pillow
Storing debug log for failure in C:\Users\Administrator\pip\pip.log

C:\Users\Administrator\Downloads\wechat_jump_game-master>
