### ISSUE TITLE
成功运行，MAC + iOS + iPhone6 auto脚本部分参数参考

### ISSUE THREAD

**Issue by Jessefrom1997** [wangshub/wechat_jump_game#675]
MAC + iOS + iPhone6 auto脚本成功运行，平均分数在200到400分之间，最高为726分
部分参数参考：
在config.json文件中：
`"press_coefficient": 1.99485,`
auto脚本中：
` time.sleep(random.uniform(1,1.5)) `
![1514880584_d](https://user-images.githubusercontent.com/30253166/34480073-46df6aba-efe5-11e7-9e41-9b8af1273f85.png)
![1514885093_d](https://user-images.githubusercontent.com/30253166/34480074-4880fbe0-efe5-11e7-9d14-9417ffb53868.png)
![1514885432_d](https://user-images.githubusercontent.com/30253166/34480076-49880dbc-efe5-11e7-9e72-b98de757a32d.png)
![1514885669_d](https://user-images.githubusercontent.com/30253166/34480077-4ac54046-efe5-11e7-9791-5c54eab1813e.png)

**Comment by binderclip** [comment]
谢谢分享，配置文件里已经有了，有更好参数欢迎 PR
https://github.com/wangshub/wechat_jump_game/blob/master/config/iPhone/6_config.json

**Comment by Jessefrom1997** [comment]
配置文件的press_coefficient是2，在iPhone6上并不准
