### ISSUE TITLE
不工作

### ISSUE THREAD

**Issue by jokeroller** [wangshub/wechat_jump_game#677]
如果你的脚本无法工作，上报 issue 时请 copy 如下信息：
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5s
OS: linux
Python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
 不工作，有输出但是屏幕没变还

### 如果代码能运行，但是达不到想要的效果

请贴出：
1. 代码版本号，代码中的 VERSION 变量
2. 使用环境 (运行脚本中已包含自动识别功能，复制即可)
3. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）
具体实例如下，按照该例进行提交 issue
-->

程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by binderclip** [comment]
请提供更多有用的信息
