### ISSUE TITLE
已经在项目根目录运行脚本，但还是提示请在项目根目录中运行脚本报错退出

### ISSUE THREAD

**Issue by MusiGuan** [wangshub/wechat_jump_game#679]
程序版本号：x.x.x
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: M6 Note
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
**********
遇到问题：已经在项目根目录运行脚本，但还是提示请在项目根目录中运行脚本报错退出
![]()
改进和建议：无

**Comment by binderclip** [comment]
啥错误提示你得给出来啊！！！！！

**Comment by MusiGuan** [comment]
> 啥错误提示你得给出来啊！！！！！

错误提示就是”请在项目根目录中运行脚本“，只有这几个字，没了

**Comment by binderclip** [comment]
@MusiGuan 给个完整的命令行里的截图吧，尽量多给点信息

**Comment by MusiGuan** [comment]
![_20180102181637](https://user-images.githubusercontent.com/35027070/34480733-175511a6-efe9-11e7-8df9-26f8e0a78f1b.png)
只有这样一行提示

**Comment by ljhsdu** [comment]
上一个版本运行的没问题，我也遇到这个问题了。

**Comment by MusiGuan** [comment]
> 上一个版本运行的没问题，我也遇到这个问题了。

我也是上个版本只有xtange的问题但是问题不大，现在这个版本就新出现这个问题。

**Comment by ljhsdu** [comment]
我刚看了下代码，我只更新了wechat_jump_auto.py这个文件，其实还新增了common模块需要下载。

**Comment by MusiGuan** [comment]
> 我刚看了下代码，我只更新了wechat_jump_auto.py这个文件，其实还新增了common模块需要下载。

原来是这样，粗心了，没看到新增了一个文件夹

**Comment by MusiGuan** [comment]
> 请提供一下你是怎么执行的

漏更新common目录，补上后没这个问题了，谢谢
