### ISSUE TITLE
运行脚本，屏幕无反应

### ISSUE THREAD

**Issue by BigBigerWolf** [wangshub/wechat_jump_game#680]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 4LTE
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Inte
]
**********
采用方式 1 获取截图
scan_start_y: 690
1514887624 338 1109 788.5 849
adb shell input swipe 525 1574 525 1574 724
scan_start_y: 690
1514887628 338 1109 788.5 849
adb shell input swipe 544 1578 544 1578 724
scan_start_y: 690
1514887632 338 1109 788.5 849
adb shell input swipe 515 1578 515 1578 724
scan_start_y: 690
1514887636 338 1109 788.5 849
adb shell input swipe 549 1576 549 1576 724
scan_start_y: 690
1514887640 338 1109 788.5 849
adb shell input swipe 526 1577 526 1577 724
scan_start_y: 690
1514887644 338 1109 788.5 849
adb shell input swipe 492 1577 492 1577 724
scan_start_y: 690
1514887649 338 1109 788.5 849
adb shell input swipe 502 1593 502 1593 724
已经连续打了 7 下，休息 7s
程序将在 1s 后继续
继续
scan_start_y: 690
1514887660 338 1109 788.5 849
adb shell input swipe 568 1589 568 1589 724
scan_start_y: 690
1514887664 338 1109 788.5 849
adb shell input swipe 534 1582 534 1582 724

反复如此，屏幕上没有反应，请问这是怎么回事。

**Comment by binderclip** [comment]
是不是需需要再另外勾上允许模拟点击权限？

**Comment by sheep0704** [comment]
运行auto

**Comment by BigBigerWolf** [comment]
@binderclip待有时间我重新验证一下，多谢

**Comment by BigBigerWolf** [comment]
@sheep0704是运行auto的结果。

**Comment by 8311431967** [comment]
因为usb的调试没有开启安全模式吧，我的当初也是这样。

**Comment by binderclip** [comment]
部分新机型可能需要再另外勾上允许模拟点击权限

**Comment by BigBigerWolf** [comment]
thx! @binderclip
