### ISSUE TITLE
代码运行成功，命令行有输出，屏幕不跳动

### ISSUE THREAD

**Issue by jokeroller** [wangshub/wechat_jump_game#683]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5s
OS: linux
Python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
**********

**********
遇到问题：代码可以顺利执行，但是屏幕上不跳动，我没写过python 觉得可能是
    cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
        duration=press_time
    )
    print(cmd)
    os.system(cmd)
这几行代码的问题，我也不太懂。。。
![]()
改进和建议：无

**Comment by binderclip** [comment]
部分新机型可能需要再另外勾上允许模拟点击权限

**Comment by jujukkkjuju** [comment]
手机USB调试安全设置，允许通过USB模拟点击 打开就行了

**Comment by jokeroller** [comment]
按照楼上的设置可以啦
