### ISSUE TITLE
不知道什么问题运行出错

### ISSUE THREAD

**Issue by Gx952743985** [wangshub/wechat_jump_game#686]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: vivo X9i
OS: darwin
Python: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
**********
/sdcard/autojump.png: 1 file pulled. 11.8 MB/s (62396 bytes in 0.005s)
暂不支持当前设备

**Comment by BruceGui** [comment]
在 CMD 下运行 adb shell screencap -p /sdcard/autojump.png 看有没有错误

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
