### ISSUE TITLE
iPhone 6的config.json 给出的‘再玩一局’坐标不对

### ISSUE THREAD

**Issue by leegang** [wangshub/wechat_jump_game#688]
更新：算了下，坐标应该是对的。但是为什么每次都不能【再玩一局】而是直接到了【发起挑战】
======
iPhone 6的config.json 给出的‘再玩一局’坐标不对
每次都自动点击了“发起挑战”

**Comment by HJH12315** [comment]
ios都这样好像  @Vg1ee

**Comment by binderclip** [comment]
iOS 那里代码没和安卓的统一，可能把自动计算的代码抽一下。
或者你们自己提交一下可用的坐标。

**Comment by Vg1ee** [comment]
我手头上没有ios的设备哇，你们谁调对了去改改ios版本里面的吧
