### ISSUE TITLE
一直提示少文件 default.json 但文件夹中是有这个文件的

### ISSUE THREAD

**Issue by SEKKOO** [wangshub/wechat_jump_game#689]
File "E:\Anakonda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/class/android/wechat_jump_game-master/wechat_jump_auto.py", line 44
    with open('{}/config/default.json'.format(sys.path[0])

**Comment by binderclip** [comment]
这是个改出来的 bug。。你可以先按 wiki 里创建一个 config.json

**Comment by SEKKOO** [comment]
wiki是什么

**Comment by binderclip** [comment]
项目 wiki
https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4

**Comment by leniy** [comment]
我感觉是不是执行的文件不是当前文件夹

**Comment by leniy** [comment]
spyder打开文件的时候，有个工作文件夹，要设置一下

**Comment by leniy** [comment]
建议直接在当前目录运行py文件，没必要打开ide
