### ISSUE TITLE
老铁们这步怎么操作

### ISSUE THREAD

**Issue by hakrtt** [wangshub/wechat_jump_game#69]
用matplot显示截图；
用鼠标点击起始点和目标位置，计算像素距离

**Comment by VitalyAnkh** [comment]
这是原理，不需要你来操作

**Comment by hakrtt** [comment]
@VitalyAnkh python wechat_jump_auto.py
不行，会闪退怎么办

**Comment by Shurrik13** [comment]
同会闪退

**Comment by wangshub** [comment]
闪退有报错吗？可以发一下定位问题

**Comment by wangshub** [comment]
@hakrtt

**Comment by hakrtt** [comment]
![_20171230145012](https://user-images.githubusercontent.com/34955698/34451986-a901ed5c-ed70-11e7-810b-42ead341712f.png)

**Comment by hakrtt** [comment]
@wangshub 现在是这个情况

**Comment by pplps** [comment]
闪退有好多种可能，我的一开始闪退是因为手机不一样，截图存储位置不一样，我改了下路径就好了。具体你先定位下问题，你是 adb驱动没装好吧，

**Comment by hakrtt** [comment]
没有，adb已经装好的

**Comment by hakrtt** [comment]
![_20171230145328](https://user-images.githubusercontent.com/34955698/34452002-07d43d76-ed71-11e7-8218-f5e1ee72b937.png)
@

**Comment by hakrtt** [comment]
@wangshub 到位怎么看

**Comment by hakrtt** [comment]
@wangshub 定位怎么看

**Comment by pplps** [comment]
我感觉你的问跟我一样，手机内的存储位置不一样。我的默认位置是/storage/emulated/0  你看下你手机的存储吧

**Comment by hakrtt** [comment]
@pplps 要改是吗

**Comment by hakrtt** [comment]
![default](https://user-images.githubusercontent.com/34955698/34452040-b250fd70-ed71-11e7-8240-d6fa3901c2a8.png)
@pplps 改这里是吗

**Comment by pplps** [comment]
@hakrtt 你先去你手机看下，你的手机的存储位置啊，多数手机是sdcard，我的是韩版手机所以默认它改了。

**Comment by hakrtt** [comment]
/storage/emulated/0我看了下确实是/storage/emulated/0

**Comment by pplps** [comment]
@hakrtt嗯，现在应该可以运行了吧

**Comment by hakrtt** [comment]
@pplps 还是不行提示adb......

**Comment by pplps** [comment]
@hakrtt 你现看电脑设备管理器里看下，adb驱动装好没，我当时这个问题是，装了adb驱动不行，谷歌sdk装也不行，后来单独去下的lg官方的usb驱动和adb驱动，然才解决。你根据你手机去下载。

**Comment by xxxlfu** [comment]
![snipaste_20171230_144321](https://user-images.githubusercontent.com/33155648/34452098-d010ee78-ed72-11e7-8ba0-250ae71a84dc.png)
大佬现在咋弄，分数不变啊，一直0

**Comment by hakrtt** [comment]
@xiongyihui 我都没玩上

**Comment by hakrtt** [comment]
![default](https://user-images.githubusercontent.com/34955698/34452120-3387452e-ed73-11e7-9fe0-226630a044db.png)
@pplps

**Comment by hakrtt** [comment]
![_20171230145012](https://user-images.githubusercontent.com/34955698/34452140-99f5da32-ed73-11e7-9e7c-463f469fc5b7.png)
@pplps

**Comment by pplps** [comment]
@hakrtt 对啊 ，忘了你上面adb devices显示了。 你要cmd运行，不要在python里运行adb试试。

**Comment by hakrtt** [comment]
都是泪鼓捣半天没成功

**Comment by xxxlfu** [comment]
@pplps 大佬，指点一下我呗，我快完成了，就是成绩不增加，先谢过了
![snipaste_20171230_144321](https://user-images.githubusercontent.com/33155648/34452155-f2b786c0-ed73-11e7-951c-d188b080b372.png)

adb shell input swipe 320 410 320 410 200
4342 KB/s (208481 bytes in 0.046s)
1514617941 0 0 0 0
adb shell input swipe 320 410 320 410 200
2172 KB/s (208481 bytes in 0.093s)
1514617947 0 0 0 0

**Comment by hakrtt** [comment]
![default](https://user-images.githubusercontent.com/34955698/34452156-04f0018c-ed74-11e7-802a-19816902b3f9.png)
@pplps

**Comment by hakrtt** [comment]
还是不成功 @pplps

**Comment by hakrtt** [comment]
![default](https://user-images.githubusercontent.com/34955698/34452167-4e7eecdc-ed74-11e7-8f3d-17649a8f26a0.png)
@pplps

**Comment by pplps** [comment]
@hakrtt   有时第一次装完adb驱动，重启下电脑也会解决一些问题，不行的话你去搜 adb不是内部或外部命令解决吧，这不是这个py脚本的问题了。  最后一个图片还是说的图片存储问题 ，没有读到截图啊。你再试试吧，我要出门了。

**Comment by xxxlfu** [comment]
@pplps 大佬，求指点一下我吧，前面都是我自己弄明白了，就是最后一步执行分数不增加。

**Comment by pplps** [comment]
@xxxlfu 去看，有具体参数设置，issues里面有参数设置

**Comment by xxxlfu** [comment]
@pplps 好，感谢大佬

**Comment by kkkkuang** [comment]
大佬，运行ruby文件找不到1.png那个文件，不过我好像没装Python Matplot @pplps

**Comment by xxxlfu** [comment]
@pplps 大佬，主要是它自己不跳啊，参数有默认设置的，起码也要跳一跳吧，死了可以改参数，关键是我这边运行python wechat_jump_auto.py没动静，screenshot_backups下倒是一直有截图

**Comment by abcd106** [comment]
pip install -r requirements.txt 这个命令在哪执行

**Comment by mjzcyhp** [comment]
我也是遇到这个问题，解决了，先安装好java,然后安装installer_r24.4.1-windows这个软件，之后这个软件有page需要安装的，好像挺大的。。然后再在我的电脑》属性》环境变量中的path，中添加adb.exe的路径，如果path有别的路劲了，添加adb.exe的路径的时候记得在前面添加“；”冒号。。。

**Comment by hakrtt** [comment]
可以让我看看变量值吗 @

**Comment by hakrtt** [comment]
Python Matplot绘图 @pplps 这个要下载吗
