### ISSUE TITLE
分段时间系数

### ISSUE THREAD

**Issue by agan123** [wangshub/wechat_jump_game#690]
***
Screen: Physical size: 1080*1920
Density: Physical density: 440
DeviceType: MI 5s Plus
OS: win32
Python: 3.5.3
**********
遇到问题：之前无论怎么调（时间系数在1.45-1.48之间），分数大概在200+，最高到400+，死亡基本是由于在短距离时时间过短，没有到下一个台子上
改进和建议：不使用统一的时间系数，而是根据距离来施加不同的时间系数。我目前设置的距离判断阈值是450，小于它，时间系数为1.6，大于它，时间系数为1.45。目前可以到1000+。

**Comment by zyxbcde** [comment]
1080很容易死，我是去掉了最小按压时间，再做了个判断距离小于200手输距离，比较少再出现这种情况。
