### ISSUE TITLE
速度参数怎么调？？？？

### ISSUE THREAD

**Issue by JJdog** [wangshub/wechat_jump_game#692]
速度参数怎么调？？？？每次调的好慢

**Comment by Vg1ee** [comment]
别瞎调，现在的参数刚好能保证截图的时候画面上的动画效果完全停止，保证识别的准确性。自动跳肯定要比人跳慢的。

**Comment by zsm1703** [comment]
延迟是因为要保证截图时机正确，否则会影响识图效果。

**Comment by leegang** [comment]
`        time.sleep(random.uniform(0.9, 2))   # 为了保证截图的时候应落稳了，多延迟一会儿
`

这句话，默认是1到1.1，但这样我担心频率太规则会更容易被风控掉，所以提升了随机值的范围。看上去更像是真人。

**Comment by JJdog** [comment]
擦擦擦

**Comment by JJdog** [comment]
@leegang 找你这样说，高分不会被屏蔽或者清零了？？？？？？

**Comment by leegang** [comment]
@JJdog   当然不是。
我的意思是说，在不知道他的屏蔽规则的情况下， 可以各方面尽量显得像人一样。

**Comment by JJdog** [comment]
@leegang  wechat官方：你糊弄鬼呢？？？？=======哈哈
