### ISSUE TITLE
执行 python3 wechat_jump_auto_iOS.py 报错求解ModuleNotFoundError: No module named 'wda'

### ISSUE THREAD

**Issue by zzhoouxin** [wangshub/wechat_jump_game#693]
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 6, in <module>
    import wda
ModuleNotFoundError: No module named 'wda'

**Comment by MemoryReload** [comment]
@zzhoouxin 在您的虚拟python环境中，`python install facebook-wda` 安装wda for python。require.text文件中缺失了对这大重要库的依赖，不知道为什么。你需要自己手动安装一下。

**Comment by binderclip** [comment]
pip install facebook-wda

**Comment by binderclip** [comment]
请按文档好好走下来

[Android 和 iOS 操作步骤 · wangshub/wechat_jump_game Wiki](https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4)
