### ISSUE TITLE
请在项目根目录中运行脚本

### ISSUE THREAD

**Issue by chenangxuan0123** [wangshub/wechat_jump_game#694]
win10  “请在项目根目录中运行脚本”是什么情况？ py3.6 version 1.1.1 已有common和config.json

**Comment by binderclip** [comment]
请问你是怎么运行的？
能给个完整的终端里的截图吗？

**Comment by BruceGui** [comment]
要在下载的根木里面运行，里面有一个 common 目录里的两个模块，如果在其他目录运行，就找不到这两个模块了，出现 ImportError

**Comment by 761157897** [comment]
![qq 20180103012707](https://user-images.githubusercontent.com/35039058/34493074-3ad99d18-f025-11e7-9e94-3122c329d5dc.png)

**Comment by chenangxuan0123** [comment]
@binderclip 
![default](https://user-images.githubusercontent.com/31478733/34505915-70517694-f063-11e7-84f3-e65a2aa3775c.JPG)
![default](https://user-images.githubusercontent.com/31478733/34505920-76b74dec-f063-11e7-8760-8ed425438a6c.JPG)
![22](https://user-images.githubusercontent.com/31478733/34505924-794506da-f063-11e7-96a2-8ed616a63b87.JPG)
![1](https://user-images.githubusercontent.com/31478733/34505926-7a7f1e78-f063-11e7-9fc7-245be014228a.JPG)

**Comment by 1204TMax** [comment]
我也是同样的问题，楼主解决了吗

**Comment by chenangxuan0123** [comment]
@1204TMax 成功了 要把所有文件全下载下来 不要像视频一样只下载几个

**Comment by 761157897** [comment]
clone  全下载出现如图的错误怎么办

**Comment by verils** [comment]
![default](https://user-images.githubusercontent.com/14834095/34640150-3ef48240-f328-11e7-8557-3ecbdfffd007.png)

完整克隆了，然而执行时缺包

```
F:\github\wechat_jump_game (master)
λ wechat_jump_auto.py
Traceback (most recent call last):
  File "F:\github\wechat_jump_game\wechat_jump_auto.py", line 24, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by MrLevo520** [comment]
请直接使用release版本app，无需配置环境，双击即可

**Comment by verils** [comment]
谢谢指教。我不是想简单粗暴的拿这个来刷分，而是想通过这个项目学习如何通过adb控制android终端，同时我也是个Python新手。希望能在手册里补充一下依赖下载和构建的过程。

BTW，刚刚试了Release版本，Unfortunately= =：

![default](https://user-images.githubusercontent.com/14834095/34640302-0f738c16-f32b-11e7-8475-ec335a75bac8.png)

本地是已经配置好adb环境的
