### ISSUE TITLE
第一步跳的准确，第二步就直接跳出。

### ISSUE THREAD

**Issue by starryj** [wangshub/wechat_jump_game#697]
程序版本号：1.1.1
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: 3.6
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by binderclip** [comment]
请提供更多有用信息
