### ISSUE TITLE
请大家尝试一下能不能绕过VAC

### ISSUE THREAD

**Issue by ChristianSwift** [wangshub/wechat_jump_game#698]
def jump(distance):
    press_time = distance * 1.35
    press_time = int(press_time)
    cmd = 'adb shell input swipe ' + str(random.randint(310,330)) + ' ' + str(random.randint(400,420)) + ' ' + str(random.randint(310,330)) + ' ' + str(random.randint(400,420)) + ' ' + str(press_time)
    print(cmd)
    os.system(cmd)

**Comment by ChristianSwift** [comment]
忘记开头加个import random了

**Comment by binderclip** [comment]
现在代码里已经有随机数字了

**Comment by ChristianSwift** [comment]
貌似只在auto里加了随机位置变量

**Comment by binderclip** [comment]
那是想在哪里加？
比较合适的是把相同的代码抽出来公用。

**Comment by zyxbcde** [comment]
这个功能有了，代码不在这里而已
