### ISSUE TITLE
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area

### ISSUE THREAD

**Issue by jcluan** [wangshub/wechat_jump_game#701]
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 199, in <module>
    main()
  File "wechat_jump_auto_iOS.py", line 177, in main
    pull_screenshot()
  File "wechat_jump_auto_iOS.py", line 61, in pull_screenshot
    c.screenshot('1.png')
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 295, in screenshot
    value = self.http.get('screenshot').value
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

(
	0   CoreFoundation                      0x0000000183c92dc8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001832f7f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183c92c80 <redacted> + 0
	3   Foundation                          0x0000000184618154 <redacted> + 112
	4   XCTest                              0x0000000100095320 -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192
	5   XCTest                              0x00000001000951ec -[XCUIScreen screenshotDataForQuality:rect:error:] + 108
	6   WebDriverAgentLib                   0x0000000106947278 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 624
	7   WebDriverAgentLib                   0x0000000106928d58 +[FBScreenshotCommands handleGetScreenshot:] + 132
	8   WebDriverAgentLib                   0x00000001069359ac -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	9   WebDriverAgentLib                   0x000000010692d5d8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	10  RoutingHTTPServer                   0x00000001069e63cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	11  RoutingHTTPServer                   0x00000001069e6b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	12  libdispatch.dylib                   0x00000001836dd47c <redacted> + 16
	13  libdispatch.dylib                   0x00000001836ecae8 <redacted> + 644
	14  libdispatch.dylib                   0x00000001836dd47c <redacted> + 16
	15  libdispatch.dylib                   0x00000001836e2b84 _dispatch_main_queue_callback_4CF + 1844
	16  CoreFoundation                      0x0000000183c48d50 <redacted> + 12
	17  CoreFoundation                      0x0000000183c46bb8 <redacted> + 1628
	18  CoreFoundation                      0x0000000183b70c50 CFRunLoopRunSpecific + 384
	19  Foundation                          0x0000000184580cfc <redacted> + 308
	20  WebDriverAgentLib                   0x000000010692c5cc -[FBWebServer startServing] + 424
	21  WebDriverAgentRunner                0x000000010691bbe4 -[UITestingUITests testRunner] + 132
	22  CoreFoundation                      0x0000000183c98a60 <redacted> + 144
	23  CoreFoundation                      0x0000000183b90488 <redacted> + 284
	24  XCTest                              0x000000010007f908 __24-[XCTestCase invokeTest]_block_invoke.275 + 48
	25  XCTest                              0x000000010007f6b8 __24-[XCTestCase invokeTest]_block_invoke + 680
	26  XCTest                              0x00000001000c527c -[XCUITestContext performInScope:] + 208
	27  XCTest                              0x000000010007f400 -[XCTestCase invokeTest] + 136
	28  XCTest                              0x00000001000804d8 __26-[XCTestCase performTest:]_block_invoke.382 + 48
	29  XCTest                              0x00000001000ca31c +[XCTContext runInContextForTestCase:block:] + 164
	30  XCTest                              0x000000010007fed4 -[XCTestCase performTest:] + 596
	31  XCTest                              0x000000010007c0c8 __27-[XCTestSuite performTest:]_block_invoke + 288
	32  XCTest                              0x000000010007baf0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	33  XCTest                              0x000000010007bd00 -[XCTestSuite performTest:] + 236
	34  XCTest                              0x000000010007c0c8 __27-[XCTestSuite performTest:]_block_invoke + 288
	35  XCTest                              0x000000010007baf0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	36  XCTest                              0x000000010007bd00 -[XCTestSuite performTest:] + 236
	37  XCTest                              0x000000010007c0c8 __27-[XCTestSuite performTest:]_block_invoke + 288
	38  XCTest                              0x000000010007baf0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	39  XCTest                              0x000000010007bd00 -[XCTestSuite performTest:] + 236
	40  XCTest                              0x00000001000d3d28 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44
	41  XCTest                              0x000000010008ec48 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 420
	42  XCTest                              0x00000001000d3ba4 -[XCTTestRunSession runTestsAndReturnError:] + 292
	43  XCTest                              0x000000010006b730 -[XCTestDriver runTestsAndReturnError:] + 312
	44  XCTest                              0x00000001000c94c4 _XCTestMain + 620
	45  CoreFoundation                      0x0000000183c48f84 <redacted> + 20
	46  CoreFoundation                      0x0000000183c488bc <redacted> + 308
	47  CoreFoundation                      0x0000000183c46820 <redacted> + 708
	48  CoreFoundation                      0x0000000183b70c50 CFRunLoopRunSpecific + 384
	49  GraphicsServices                    0x0000000185458088 GSEventRunModal + 180
	50  UIKit                               0x0000000188e5e088 UIApplicationMain + 204
	51  WebDriverAgentRunner-Runner         0x0000000100034444 WebDriverAgentRunner-Runner + 33860
	52  libdyld.dylib                       0x000000018370e8b8 <redacted> + 4
))

**Comment by whisper-bye** [comment]
+1

**Comment by jcluan** [comment]
求解答，卡这好久了(>_<)

**Comment by whisper-bye** [comment]
@jcluan 
我估计wechat热更新封堵了

**Comment by jcluan** [comment]
iOS的现在还有成功的么？

**Comment by jcluan** [comment]
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted

**Comment by MemoryReload** [comment]
@jcluan   昨天晚上10点我还给我媳妇儿刷了分，确认可用。如果你非常想要刷分，我可以给你我配置好的项目的压缩包。包括wda跟这个python测试用例。不过我觉得，你如果真的有兴趣，可以去搞搞这个东西的工作原理，基于webdriver协议的远程控制。

**Comment by MemoryReload** [comment]
@whisper-bye 
`wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area`
从这句错误信息来看，wad截图的时候，发现被截图的视图frame是0，抛出了异常。具体你可能需要debug一下。
`6 WebDriverAgentLib 0x0000000106947278 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 624`
原生端这个错误信息，貌似没有传截图的frame，那么就很有可能是微信做了处理，让被截图的图层frame变成了0？
`4 XCTest 0x0000000100095320 -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192`
断点看看这里的rect有没有问题，就知道了，如果不是传递的参数有问题，那么就是微信做了更新。

**Comment by XMliberty** [comment]
应该是iphone的系统没有更新，升级到11吧

**Comment by Kmiracler** [comment]
应该是WDA的问题，我重新编译WDA后就没有这个错误了

**Comment by neyangg** [comment]
找到一个偏门的解决办法：先随便起一个wda的session，不要close，手动切到冲顶大会的答题页面，然后再截图，就不会报错了，亲测有效
