### ISSUE TITLE
2960x1440屏幕，每次跳都是蓄力到极限的状态

### ISSUE THREAD

**Issue by KEYART** [wangshub/wechat_jump_game#702]
三星Note8 2960x1440屏幕，每次跳都是蓄力到极限的状态，是不是这个分辨率适配有问题？

**Comment by binderclip** [comment]
有开屏幕上的浮动插件吗？
另外打开 debug 传个截图

**Comment by wizholy** [comment]
设置里的悬浮按钮关掉

**Comment by zyxbcde** [comment]
非标准分辨率要改参数吧？

**Comment by KEYART** [comment]
恩，昨天测试很久，应该是参数问题，关掉悬浮通知和侧面屏，改成之前别人说S8可以的那些参数还是不行的。

最后降低分辨率改成了2220X1080后测试成功。
参数：{ "under_game_score_y": 619, "press_coefficient": 1.392, "piece_base_height_1_2": 20, "piece_body_width": 70, "swipe" : { "x1": 530, "y1": 1730, "x2": 530, "y2": 1730 } }
