### ISSUE TITLE
一加五

### ISSUE THREAD

**Issue by dlhf** [wangshub/wechat_jump_game#703]
Screen: Physical size: 1080x1920
Density: Physical density: 420
Override density: 380
DeviceType: ONEPLUS A5000
OS: darwin
Python: 3.6.4 (default, Jan  2 2018, 19:32:51) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

已经连续打了 7 下，休息 9s
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 257, in <module>
    main()
  File "wechat_jump_auto.py", line 247, in main
    for j in xrange(next_rest_time):
NameError: name 'xrange' is not defined

**Comment by Vg1ee** [comment]
#666
