### ISSUE TITLE
能否根据跳跃结果自学习得出按压时间和距离的关系曲线以及应用到长短跳上？

### ISSUE THREAD

**Issue by cxgreat2014** [wangshub/wechat_jump_game#704]
![image](https://user-images.githubusercontent.com/15062548/34484038-2c685b98-effd-11e7-8f21-1805b04a9da2.png)
![image](https://user-images.githubusercontent.com/15062548/34484042-323d7f30-effd-11e7-9718-25fc9dfd860c.png)

对于短跳或长跳在不同机型、不同屏幕型号上的差异这可能是一个比较好的解决方案

**Comment by zyxbcde** [comment]
2k屏比1080屏幕稳太多了

**Comment by chloechj** [comment]
如果是实时的DQN可以实现，如果要得出时间距离函数，直接根据训练数据拟合出函数关系即可
