### ISSUE TITLE
小米5 参数

### ISSUE THREAD

**Issue by aca16zc** [wangshub/wechat_jump_game#705]
小米5 参数 实测  400+目前，应该可以上千 （1920*1080）
{
    "under_game_score_y": 300,
    "press_coefficient": 1.477,
    "piece_base_height_1_2": 25,
    "piece_body_width": 80,
    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1602
    }
}

**Comment by aca16zc** [comment]
小米5参数

**Comment by Vg1ee** [comment]
觉得合适的话请移步PR

**Comment by gongzelong0718** [comment]
请问能详细说说如何调的参数吗
