### ISSUE TITLE
为什么我跳第一下就掉下去了，求解

### ISSUE THREAD

**Issue by JamesMarts** [wangshub/wechat_jump_game#709]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: M2 Note
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
**********

{
  "under_game_score_y": 340,
  "press_coefficient": 2.27,
  "piece_base_height_1_2": 25,
  "piece_body_width": 80,
  "swipe": {
    "x1": 500,
    "y1": 1600,
    "x2": 500,
    "y2": 1602
  }
}

**Comment by wizholy** [comment]
你把设置里面悬浮窗关掉

**Comment by JamesMarts** [comment]
可是我手机上没有悬浮球啊

**Comment by MrLevo520** [comment]
尝试先手动跳几次，然后再用脚本

**Comment by vtwr** [comment]
一样的问题 手动跳几次也不奏效
