### ISSUE TITLE
更新了新的代码，CMD命令提示乱码，求解！

### ISSUE THREAD

**Issue by DevXue** [wangshub/wechat_jump_game#710]
Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd..

C:\Users>cd..

C:\>wechat_jump_auto.py
璇峰湪椤圭洰鏍圭洰褰曚腑杩愯鑴氭湰

C:\>

我把代码换成最新的，提示乱码···  完全看不懂，尝试解决乱码，网上的方法不靠谱，有哪位大佬会，帮忙看看  多谢啦！

**Comment by zxh326** [comment]
cmd UTF-8中文字符不兼容问题
cmd里执行
chcp 65001
或者用powershell

**Comment by MrLevo520** [comment]
请使用 python3，中文支持会比较好。python2在cmd的中文显示就是乱码
