### ISSUE TITLE
print('程序版本号：{}'.format(VERSION)) IOError: [Errno 0] Error

### ISSUE THREAD

**Issue by fanliugen** [wangshub/wechat_jump_game#711]
**********
C:\Users\Administrator>python E:\wechat_jump_game-master\wechat_jump_auto.py
Load config file from E:\wechat_jump_game-master/config/1920x1080/config.json
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: yyyy
Please input y or n: y
���序版本号：1.1.1Traceback (most recent call last):
  File "E:\wechat_jump_game-master\wechat_jump_auto.py", line 263, in <module>
    main()
  File "E:\wechat_jump_game-master\wechat_jump_auto.py", line 233, in main
    print('程序版本号：{}'.format(VERSION))
IOError: [Errno 0] Error

**Comment by rrwhx** [comment]
我也出现过这个问题
有没有配置好adb的环境变量？
在cmd中能不能用 adb advices看到你的设备，还有尝试用adb shell wm size看到分辨率
还有就是开发者选项要设置好

**Comment by athosss** [comment]
我也是这个问题，py2版本，目测应该不是adb原因，昨天老代码没有问题，更新了之后就出现了。
