### ISSUE TITLE
MX4 跑到20左右停止，请问如何解决这个问题?分辨率1920x1152 

### ISSUE THREAD

**Issue by enfangzhong** [wangshub/wechat_jump_game#712]
Load default config
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1152x1920
Density: Physical density: 480
DeviceType: MX4
OS: win32
Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
**********

遇到问题：大概跑了23步左右就停止了，跳远了（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by Oscar-Pro** [comment]
MX4，你可以去修改一下config\MI\下的config.json，选用1080*1920的参数，press_coefficient 是线性的，请自己试着二分调整一下，跳到几百分不是问题。

**Comment by MrLevo520** [comment]
请调节参数后，提交config给大家一块适配

**Comment by enfangzhong** [comment]
@Oscar-Pro我的是魅族4
