### ISSUE TITLE
很强大 ，我实现了改分版本，借楼推广

### ISSUE THREAD

**Issue by naah69** [wangshub/wechat_jump_game#716]
https://github.com/naah69/wx_dump_change_score

也有网络版供大家使用
关注公众号
xyl-tech查看网络版

**Comment by ddgboy** [comment]
这也太暴力了，直接改包！只要他检测每一步的成绩，不就没用了？

**Comment by lovecn** [comment]
666

**Comment by naah69** [comment]
要是每一次请求都检测每一步  那性能影响太大了  微信指数显示700多万呢  再就是检测每一步  我在实现每一步就好了
