### ISSUE TITLE
系数调整时分数只能几百分左右的解决方法

### ISSUE THREAD

**Issue by Oscar-Pro** [wangshub/wechat_jump_game#719]
时间与距离的关系不是线性的，无论怎么调都是上不去的。

非线性跳跃时间参数拟合
给pr的
press_time = math.pow(distance,0.85) * press_coefficient
的修改提供参照（自行查看PR日志，有一位大佬已经PR了）

只需要修改press_coefficient即可，其他遵照原来的config.json文件
小米MIX 系数是 3.7，可以跳1200分，手动关停，目测应该一直+32下去，不想被封

**Comment by ITcrazywgy** [comment]
我也觉得不是线性关系，2d 的直线转化到3d中的场景，应该存在一个矩阵变换，而且这个矩阵变阵也很可能不是唯一的

**Comment by chenzuoyuan** [comment]
MIX亲测，挺有用的，目测1000+以上
