### ISSUE TITLE
Iphone6s IOS11.2.1 完美运行 

### ISSUE THREAD

**Issue by wadekun** [wangshub/wechat_jump_game#721]
如题，就是想感谢各位大佬，帮我实现了新年第一波装逼的愿望

**Comment by hi-noikiy** [comment]
你是手动还是自动？可以发下配置吗？

**Comment by wadekun** [comment]
@hi-noikiy 没有改任何配置，唯一需要的改动就是把 /config/iPhone/6_config.json 重命名为config.json 到项目根目录下

**Comment by hi-noikiy** [comment]
6s跟7是一样大小的吧？

**Comment by wadekun** [comment]
@hi-noikiy 应该是一样的。。你可以试下，如果发现问题可以试着修改config里的参数

**Comment by hi-noikiy** [comment]
你跳了多少？

**Comment by wadekun** [comment]
@hi-noikiy 跳到500多的时候我给掐了。。没想到最后分数还是被清了。。。

**Comment by binderclip** [comment]
@wadekun 是最新的代码吗？

**Comment by wadekun** [comment]
@binderclip 大概是今晚8点左右的代码，刚pull了下，又merge到有新的commit。

**Comment by githuanl** [comment]
我的6s 最远自动跳到50多。。。是什么参数没修改对么。。。。

**Comment by wadekun** [comment]
@githuanl 如果前面几步都跳到中心位置的话参数应该不需要修改了。如果跳的位置比较偏，调下config.json中的press_coefficient。再多跑几次试试

**Comment by lucyios** [comment]
我的6s也是，自动跳，不超过50分，使用的默认的6_config的参数，但是，看了下截图，截图不完整，导致中心点计算错误，晚上还得看下，修改了脚本的sleep的时间；还没试

**Comment by githuanl** [comment]
@wadekun   press_coefficient你设置的参数是多少？

**Comment by leon0204** [comment]
同问 6s 只能跳一点点

**Comment by lucyios** [comment]
自动508，呵呵

**Comment by Suimengshu** [comment]
请问你是怎么打开开发者模式的？

**Comment by SmilingHeart** [comment]
兄弟，你11.2.1怎么装上WDA的，我Xcode版本没有11.2.1的真机包啊。

**Comment by wadekun** [comment]
Xcode要升级到最新版。直接在AppStore上更新，就有11.2的sdk了。。




发自网易邮箱大师


在2018年01月9日 14:23，Await<notifications@github.com> 写道：

兄弟，你11.2.1怎么装上WDA的，我Xcode版本没有11.2.1的真机包啊。

**Comment by wadekun** [comment]
开发者模式啥意思。。照着教程来，iphone连上电脑，Xcode运行WDA的时候需要在手机中信任一下开发者。




发自网易邮箱大师


在2018年01月5日 18:34，Suimengshu<notifications@github.com> 写道：

请问你是怎么打开开发者模式的？

**Comment by wadekun** [comment]
这个。。我前两天最高也只跳到1000多分。。参数：1.98






发自网易邮箱大师


在2018年01月4日 10:37，githuanl<notifications@github.com> 写道：

@wadekun press_coefficient你设置的参数是多少？

**Comment by SmilingHeart** [comment]
现在最新的Xcode，真机包版本只有11.2啊，我的手机是11.2.1的。所以装不上WDA

**Comment by wadekun** [comment]
最近的Xcode版本是9.2的。你确定你的是最新的吗。。我也是11.2.1的亲测可用。




发自网易邮箱大师


在2018年01月9日 15:15，Await<notifications@github.com> 写道：

现在最新的Xcode，真机包版本只有11.2啊，我的手机是11.2.1的。所以装不上WDA

**Comment by SmilingHeart** [comment]
是最新的啊，我的Deployment Target 最高只有11.2，没有11.2.1。所以直接装不上

**Comment by wadekun** [comment]
https://stackoverflow.com/questions/44381860/use-xcode-8-with-ios-11


maybe can help you.




发自网易邮箱大师


在2018年01月9日 15:20，Await<notifications@github.com> 写道：

是最新的啊，我的Deployment Target 最高只有11.2，没有11.2.1。所以直接装不上

**Comment by SmilingHeart** [comment]
感谢，感谢。这个方法确实可以，我就是缺那个11.2.1的真机包。😂

**Comment by wadekun** [comment]
@SmilingHeart 客气。。不是专业的IOS开发，不知道11.2的sdk好不好找。。这里有个11.2的sdk 你看看可不可用 [ https://www.jianshu.com/p/061889cf0452]( https://www.jianshu.com/p/061889cf0452)

**Comment by SmilingHeart** [comment]
感谢你的帮助，我用了公司10.3的手机运行成功了。就是分数最高370😂，丢人了
