### ISSUE TITLE
iPhone SE +ios10 完美运行 +参数分享

### ISSUE THREAD

**Issue by HJH12315** [wangshub/wechat_jump_game#724]
{
    "under_game_score_y": 190,
    "press_coefficient": 2.25,
    "piece_base_height_1_2": 12,
    "piece_body_width": 50,
    "swipe" : {
      "x1": 325,
      "y1": 950,
      "x2": 325,
      "y2": 950
    }
    }

**Comment by Kryssss** [comment]
5s不行呀 老哥

**Comment by ZYSzys** [comment]
SE配置已经有啦，上200基本没问题

**Comment by zhuweideng** [comment]
@Kryssss 5s参数是对的，因为手机性能，截图出现偏差，在截图的时候需要让它睡眠1秒左右
`def pull_screenshot():`
`     time.sleep(1)  #这是我添加的`
`    c.screenshot('1.png')`

**Comment by Kryssss** [comment]
👍🏻赞 我去试试@zhuweideng

**Comment by Gx952743985** [comment]
为什么我的SE 不行,一步就死了?
