### ISSUE TITLE
有windows+IOS环境的方法吗

### ISSUE THREAD

**Issue by alphazhangnan** [wangshub/wechat_jump_game#728]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by MemoryReload** [comment]
没有xcode不能驱动wda的手机端测试用例，wda是个远程控制的自动化服务器，需要xcode才能启动，在iOS平台。但是，windows是无法安装xcode开发环境的，所以，简单的说。。。没有～详细的信息，你可以去facebook的WDA项目了解。
