### ISSUE TITLE
能说下这几个参数吗？

### ISSUE THREAD

**Issue by F5F5** [wangshub/wechat_jump_game#73]
### under_game_score_y = 300    # 截图中刚好低于分数显示区域的 Y 坐标
![image](https://user-images.githubusercontent.com/15978277/34452058-22d8b132-ed72-11e7-89dc-ef3e531692c4.png)

### piece_base_height_1_2 = 20   # 二分之一的棋子底座高度，可能要调节
这个我没看明白，不知道哪个接近40？

### piece_body_width = 70       # 棋子的宽度，比截图中量到的稍微大一点比较安全，可能要调节
![image](https://user-images.githubusercontent.com/15978277/34452054-0b39a522-ed72-11e7-9e60-6c45dc670871.png)

**Comment by binderclip** [comment]
@F5F5 
under_game_score_y 你说的对
piece_base_height_1_2 你给的是 40 除以 2 不就是了。。那样才是中点
piece_body_width 你说的也对，可能 70 小了点，改成 80 也成

**Comment by F5F5** [comment]
@binderclip 第二个默认代码里面是20，能截个图告诉我是从哪取的吗？

**Comment by binderclip** [comment]
@F5F5 
![image](https://user-images.githubusercontent.com/8187479/34452132-6f3d2cd2-ed73-11e7-81d7-ef00a998b041.png)
最新的改成 25 了

**Comment by F5F5** [comment]
@binderclip 谢谢 :)
