### ISSUE TITLE
无法运行脚本

### ISSUE THREAD

**Issue by IngresWu** [wangshub/wechat_jump_game#731]
adb等已确认连接
运行脚本显示 “请在项目根目录中运行脚本”

**Comment by cmazxiaoma** [comment]
把源代码下载，然后进根目录执行脚本即可

**Comment by IngresWu** [comment]
已下载，在cmd内运行，显示请在项目根目录中运行脚本

**Comment by 761157897** [comment]
我也是这个问题 今天突然有的

**Comment by IngresWu** [comment]
遇到“请在项目根目录中运行脚本”的问题，请把页面中common下三个文件下载下来，新建common文件夹，放到里面就OK了。
