### ISSUE TITLE
蓄力过猛bug

### ISSUE THREAD

**Issue by cmazxiaoma** [wangshub/wechat_jump_game#732]
手机是三星，型号是SM-J3109，分辨率是1280*720 
1.下一个出现的方块和之前的方块不是直线排列， 就会蓄力过猛，然后gg。
2.相邻很近的方块，会跳出去，然后gg

**Comment by MrLevo520** [comment]
请按提交issue规范提交，这样我们可以看机器型号和系统型号，方便解决问题
