### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by maihao14** [wangshub/wechat_jump_game#733]
Error: Command failed to execute!

==> Failed command:
/bin/ln -h -f -s -- /usr/local/Caskroom/android-platform-tools/27.0.1/platform-tools/adb /usr/local/bin/adb

==> Standard Output of failed command:

==> Standard Error of failed command:
ln: /usr/local/bin/adb: Permission denied
![image](https://user-images.githubusercontent.com/28862378/34491946-867571d4-f020-11e7-8faf-3fda556850c0.png)

==> Exit status of failed command:
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by MemoryReload** [comment]
Try this `sudo chown -R $(whoami)`,  and then `brew install` again

**Comment by wangshub** [comment]
环境安装还请google一下  @maihao14
