### ISSUE TITLE
荣耀V9按照2560x1440参数运行，第一步失败

### ISSUE THREAD

**Issue by woyaolib** [wangshub/wechat_jump_game#737]
程序版本号：x.x.x
**********
Screen: Physical size: 2569*1440
Density: Physical density: x
Override density: x
DeviceType: 华为荣耀v9
OS: android
Python: 3
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by MrLevo520** [comment]
尝试自己跳几步，然后启动脚本。如有问题，请按照issue规范提交

**Comment by woyaolib** [comment]
程序版本号：1.1.1
**********
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: DUK-AL20
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]

配置文件为  /config/2560x1440/config.json

**Comment by Doinbe** [comment]
程序版本号：1.1.1
**********
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: SM-G9250
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

重来没跳上过，都是蓄力过大

**Comment by Doinbe** [comment]
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: SM-G9250
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

都换了好几个config文件都是蓄力过大
三星S6edge

**Comment by SindaYan** [comment]
1440x2560 都不可以 蛋疼啊

**Comment by woyaolib** [comment]
配置文件里面的huawei/  note8 的配置可以



woyaolib@163.com
 
发件人： 宅小达
发送时间： 2018-01-03 21:21
收件人： wangshub/wechat_jump_game
抄送： woyaolib; Author
主题： Re: [wangshub/wechat_jump_game] 荣耀V9按照2560x1440参数运行，第一步失败 (#737)
1440x2560 都不可以 蛋疼啊
