### ISSUE TITLE
依赖文件无法安装

### ISSUE THREAD

**Issue by vtwr** [wangshub/wechat_jump_game#738]
C:\Windows\System32>pip install -r C:\Users\Desktop\wechat_jump_game-master\requirements.txt
'pip' 不是内部或外部命令，也不是可运行的程序或批处理文件。

是这样的，请问该如何解决？其他步骤都没什么问题，这步在网上查了好久也没解决办法。。

**Comment by GdZ** [comment]
这里有两种方法，推荐第一种。
方法一：
安装python是选中“Add Python to environment”，具体如下图。
![python_install](https://user-images.githubusercontent.com/1638910/34500773-75481830-f00c-11e7-8ace-b1c492d9a224.png)
方法二：
或者在“我的电脑”-》“属性”-》“高级系统设置”-》“环境变量”-》“系统变量”的方框内找到Path，在里面增加python目录。

**Comment by vtwr** [comment]
十分感激GdZ的回复！ 实际上Add Python to环境变量是默认勾选的，我尝试重新安装以后，勾选了上一步的Add Python to Path，问题就解决了!

**Comment by MrLevo520** [comment]
请使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
