### ISSUE TITLE
No module named 'wda'

### ISSUE THREAD

**Issue by Kaiser-11** [wangshub/wechat_jump_game#741]
x$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ImportError: No module named 'wda'

请问这个问题该怎么解决？
 
该装的也都安装了
x$ pip install --pre facebook-wda
Requirement already satisfied: facebook-wda in /usr/local/lib/python3.5/site-packages
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)

到底问题出在哪呢？

**Comment by vbonluk** [comment]
+1

**Comment by vbonluk** [comment]
我的可以了。请运行pip3的安装

**Comment by Kaiser-11** [comment]
没有用，还是不行

`$ pip3 install facebook-wda
Requirement already satisfied: facebook-wda in /usr/local/lib/python3.5/site-packages
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)`


`$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ImportError: No module named 'wda'`

**Comment by Kaiser-11** [comment]
没有用，还是不行

$ pip3 install facebook-wda
Requirement already satisfied: facebook-wda in /usr/local/lib/python3.5/site-packages
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)


结果一样

$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ImportError: No module named 'wda'

**Comment by zzhoouxin** [comment]
sudo pip3 install --pre facebook-wda   用这个命令可以解决

**Comment by Kaiser-11** [comment]
$ sudo -H pip3 install --pre facebook-wda
Requirement already satisfied: facebook-wda in /usr/local/lib/python3.5/site-packages
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (from facebook-wda)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests>=2.9.1->facebook-wda)


结果一样
$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ImportError: No module named 'wda'

**Comment by singleD** [comment]
+1，上面方法（不论是用pip3，还是sudo）都试过了，还是不行

**Comment by singleD** [comment]
并且运行其他的py文件，也是找不到对应的module，但是requirement.txt和facebook-wda都安装好了
