### ISSUE TITLE
拟合曲线方程

### ISSUE THREAD

**Issue by agan123** [wangshub/wechat_jump_game#744]
多个拟合方程
press_time = 1.3042*distance+79.878（线性拟合）
press_time = -0.000002*pow(distance,2)+1.3023*distance+80.226（多项式拟合）
应该没有之前有人提出的
press_time = pow(distance,0.85)*3.7（幂函数拟合）
效果好

**Comment by billzbh** [comment]
press_time = pow(distance,0.85)*3.26（幂函数拟合） 在note5上测试比较符合。

目前感知是，圆筒的WZC格子 距离太近，接近320，基本就挂。

**Comment by zgcbj** [comment]
press_time = pow(distance,0.85)*3.7（幂函数拟合）
小米5测试，轻轻松松4000+，步步中心。

**Comment by 0x5a686f75** [comment]
press_time = pow(distance,0.85)*3.7（幂函数拟合）
经测试，超级好用！！！！

**Comment by chloechj** [comment]
终于有人拟合出来了

**Comment by HughSalvatore** [comment]
用了都说好，感觉会被封号呢

**Comment by zgcbj** [comment]
怎么得到的公式？
