### ISSUE TITLE
iphone8 用Iphone6 的config_json， 一步就死.

### ISSUE THREAD

**Issue by 329463417** [wangshub/wechat_jump_game#745]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by wadekun** [comment]
修改下 config.json中的press_coefficient 慢慢试，如果跳近了值改大点，跳远了值改小些
