### ISSUE TITLE
关于目前分数被清空的可行解之一以及改进提议

### ISSUE THREAD

**Issue by HandleCoding** [wangshub/wechat_jump_game#746]
昨天还在用，自己也仿照写了一个，但是今天用的时候发现自动被清除了，通过多次试验发现如下操作可以避免清空。首先人工玩跳一跳到10分左右，然后利用程序调到想要的分数段，最后在用人工成功跳几下，最后几个格子一定要人工跳。 

提议后续可以改进的方法（讨论）：
1.能让用户事前输入期望分数值，到达目标之后改变按压系数或者加入一点随机噪声，使其每次不落入中心点或者故意落偏直至几次后自动掉落。
2. 每次的延时不要固定，也加入随机值，每次随机延时起跳时间，让间隔不固定。

**Comment by Banbooliu** [comment]
我觉得最可能检测会不会还是按压位置？
现在是“再玩一局”位置+左右随机50上下随机10，但是还是在重新开始的格子里，可不可以从截图里分辨出当前是否已失败，失败的话再set_button_position到“再玩一局”位置，正常游戏时在其他位置按压？
从个人游戏经验来说，“再玩一局”的位置偏下，正常情况是按不到那个位置的

**Comment by zhqingyong** [comment]
我是手动加自动，修改距离系数，让他不那么容易跳中心且不会掉下去，遇到挨得近的就停止程序手动跳。腾讯应该检测的时间间隔和跳中心的连续次数，太多次肯定被办！

**Comment by HandleCoding** [comment]
@zhqingyong 你这样做应该也可行吧，我今天实验的时候只是最后用手跳了几下就可以计入排行榜了，但是全程程序跳的话，我用小号就算是100多分也被清空计入不到排行榜，所以我怀疑检测的是最后几下的间隔。

**Comment by HandleCoding** [comment]
@zhqingyong 你这样做应该也可行吧，我今天实验的时候只是最后用手跳了几下就可以计入排行榜了，但是全程程序跳的话，我用小号就算是100多分也被清空计入不到排行榜，所以我怀疑检测的是最后几下的间隔。

**Comment by HandleCoding** [comment]
@WokoLiu 我实验好像和按压位置没太大关系，不过也可以试着每次都在那个附近随机波动几个像素位置。。

**Comment by DevXue** [comment]
我觉得，讨论方案不能放在GitHub上，应该在QQ群中讨论， 微信那帮鸟人肯定也在关注这个项目！

**Comment by HandleCoding** [comment]
@DevXue QQ群中肯定也有...

**Comment by MemoryReload** [comment]
@DevXue 如果在stackoverflow上，至少有5分之一的问题和回答都会被移除。

**Comment by DevXue** [comment]
![sa](https://user-images.githubusercontent.com/9455329/34507540-ffb50798-f071-11e7-879f-4ee7160dd11f.png)
!!!心塞

**Comment by MemoryReload** [comment]
@DevXue This one will be removed too. ⬆️😊

**Comment by qtvspa** [comment]
我试了一下，开始人工跳，然后结束时候再跳几步，可是都被清除了，是因为分数太高了吗。。（我试的都是2000+）

**Comment by HandleCoding** [comment]
@qtvspa ...Maybe,确实太高了...现在检测的内容应该越来越多了

**Comment by mikuily** [comment]
别忘了qq也是tx的23333在哪里讨论都一样

**Comment by JJdog** [comment]
@mikuily 不是一个部门的

**Comment by DevXue** [comment]
但是，别忘了   代码是开源的，  腾讯随时可以看···  所以说呢，  讨论出来屌爆的方案，也是会被修复的···

**Comment by JJdog** [comment]
@HandleCoding  你分数段调到多少？

**Comment by HandleCoding** [comment]
@JJdog 目前1000以内我都是可以的 再高的还没试过

**Comment by JJdog** [comment]
我特么只要超过400就提交不了

**Comment by HandleCoding** [comment]
@JJdog 试试最后自己跳几下，或者渐进的刷高成绩

**Comment by JJdog** [comment]
@HandleCoding 我再试下，mmp 被经理抓到就屌了

**Comment by JJdog** [comment]
@HandleCoding  这个偏移量怎么调， 使其每次都不落入中心点

**Comment by JJdog** [comment]
@HandleCoding  能吧你源码发我吗？^_^

**Comment by chy9002** [comment]
我怀疑是每次点压的位置一样导致的，所以稍微改了一下代码

```python
def jump(distance):
    x=swipe['x1']+random.randint(1,100)
    y=swipe['y1']+random.randint(1,100)
    press_time = distance * time_coefficient / 1000
    print('press time: {}'.format(press_time))
    print('(%s,%s)'% (x,y))
    s.tap_hold(x,y,press_time) #这里的s.tap_hold(200,200,press_time)改成了一个更随机的值)
```

**Comment by Lewiskong** [comment]
这个问题解决了，详见这篇文章https://zhuanlan.zhihu.com/p/32594563

**Comment by WokoLiu** [comment]
看完知乎帖子，要不要考虑下我之前说的，检测当前游戏状态，再决定按压位置？

**Comment by yslad** [comment]
就现在这个方案刷一千五以下不会封的

**Comment by HandleCoding** [comment]
嗯，就简单的把按压位置和按压时间调整了一下。现在只自己一次性测试到832就没测试了，现在上传成功。
```
x1=swipe_x1+random.randint(-100,150),
        y1=swipe_y1+random.randint(-100,150),
        x2=swipe_x2+random.randint(-100,150),
        y2=swipe_y2+random.randint(-100,150),
        duration=press_time+random.randint(-5,5)
```

**Comment by kannidekan** [comment]
感觉这就像是一场游戏，这边项目给出答案，微信就再换题目，可以一直玩下去，哈哈
