### ISSUE TITLE
 config 文件 for mi5 的路径有问题（bug reporter）

### ISSUE THREAD

**Issue by heishanmao** [wangshub/wechat_jump_game#747]
Load config file from D:\Desktop\github\wechat_jump_game/config/1920x1080/config.json
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: y
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
**********
遇到问题： config 文件 for mi5 的路径有问,不能正确选择

**Comment by fu9852531** [comment]
你按照我的路径改一下     C:\Users\liulin\Desktop\config\default.json

**Comment by xzhlksh** [comment]
机子是标准1080p分辨率，程序本来就识别不进机型分辨率配置文件夹

**Comment by fu9852531** [comment]
开发者模式打开了吗？


2018-01-03 12:54 GMT+08:00 xzhlksh <notifications@github.com>:

**Comment by heishanmao** [comment]
@xzhlksh 说的是对的，所以感觉是个bug。

**Comment by xzhlksh** [comment]
@fu9852531  就现在，在master分支的./common/config.py文件中的open_accordant_config()函数里，告诉我哪句话能读取到除分辨率和default.json以外的配置？尤其是那几个机型文件夹里？代码可从来不说谎的
不要问我开发者模式开没开，没开那玩意的话连USB调试都开不了，更别说adb了
