### ISSUE TITLE
python 新手不会运行 pip install -r requirements.txt 这句脚本？

### ISSUE THREAD

**Issue by zhangkehu** [wangshub/wechat_jump_game#749]
说的就是我，Windows下不“能”运行这个脚本，尴尬，Windows下的正确用法：

`python -m pip install -r requirements.txt`

**Comment by athosss** [comment]
D:\virtualenv\wechat>pip install -n requirements.txt

**Comment by AngrylLittleFurryBalls** [comment]
直接命令行运行pip命令,需要先添加一下环境变量

**Comment by DoubleRayWang** [comment]
根目录下直接执行即可

**Comment by MemoryReload** [comment]
@DoubleRayWang 为啥要在根目录下执行？pip安装有固定的安装位置的，你可以在任何目录执行安装。只要你的requirements.txt文件路径是正确的。

**Comment by mozjiang** [comment]
@MemoryReload  因为一般是虚拟环境，所以在工作目录安装依赖。😂

**Comment by MrLevo520** [comment]
请使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
