### ISSUE TITLE
为什么定位不准确。 iphone7，如图。

### ISSUE THREAD

**Issue by xylin123** [wangshub/wechat_jump_game#753]
![1514899446_d](https://user-images.githubusercontent.com/17720797/34507506-ad150218-f071-11e7-889b-f88cff6db4e4.png)
![1514899446](https://user-images.githubusercontent.com/17720797/34507508-ae5a994e-f071-11e7-8b81-3e88790e296b.png)
使用的是 `wechat_jump_auto_iOS.py`

**Comment by Beavan** [comment]
我的iphone7也是，

**Comment by mkblbj** [comment]
一样的，iOS的取中点逻辑稍微有点问题，安卓已经领先好几个版本了。

**Comment by Smeegol** [comment]
这个红蓝线条怎么样出来的呢
