### ISSUE TITLE
tools/adb目录下运行wechat_jump_auto.py

### ISSUE THREAD

**Issue by AngrylLittleFurryBalls** [wangshub/wechat_jump_game#755]
免adb环境变量配置时,tools/adb目录下运行wechat_jump_auto.py文件时,提示必须在根目录下运行脚本.这个该怎么调整了?

**Comment by telenewbie** [comment]
你应该在根目录上面,运行python tools/adb/wechat_jump_auto.py 这样就可以了吧.

**Comment by hanzehua521** [comment]
不行啊，提示这个Traceback (most recent call last):
  File "tools/adb/wechat_jump_auto.py", line 20, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by Seanon** [comment]
是因为缺少PIL包啊，用pip install image安装下就好了
