### ISSUE TITLE
报错Traceback (most recent call last):   File "wechat_jump_auto.py", line 20, in <module>     from PIL import Image ImportError: No module named PIL

### ISSUE THREAD

**Issue by OOOOOldZhu** [wangshub/wechat_jump_game#756]
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 20, in <module>
    from PIL import Image
ImportError: No module named PIL

**Comment by DoubleRayWang** [comment]
在根目录下执行pip install -r requirements.txt

**Comment by OOOOOldZhu** [comment]
command not found

**Comment by OOOOOldZhu** [comment]
命令行运行python 和python3， 都可以显示python版本

**Comment by a122996325** [comment]
我和你是同一个问题 没有PIL这个模块，初始化install完成

**Comment by OOOOOldZhu** [comment]
pip install -r requirements.txt 这行安装完了。安装了一堆文件。运行 python wechat_jump_auto.py还是报错。Traceback (most recent call last): File "wechat_jump_auto.py", line 20, in <module> from PIL import Image ImportError: No module named PIL

**Comment by MemoryReload** [comment]
Follow my steps:
1、If you use `virtualenv` (You do better use a virtual env)、`pyenv` or `conda`, start your  virtual env.
2、`pip install -r`  requirements.text to install all dependencies except facebook-wda.
3、As you imagine, `pip install facebook-wda`.

**Comment by StriveCheng** [comment]
我也是，你怎么解决的

**Comment by OOOOOldZhu** [comment]
按照MemoryReload的做法，还是不能解决问题。

**Comment by StriveCheng** [comment]
@OOOOOldZhu 我的也是这个错，应该是缺失什么依赖，但不知道怎么安装，你是怎么解决的？

**Comment by wirechen** [comment]
@OOOOOldZhu @StriveCheng 你们是执行`pip install -r requirements.txt`还是`pip3 install -r requirements.txt` 我用第一个安装了半天报错。  
```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/backports'
```

**Comment by StriveCheng** [comment]
@wirechen 第一个，你这个是没权限，前面加个sudo就行了

**Comment by OOOOOldZhu** [comment]
@StriveCheng 
pip3 install -r requirements.txt 解决问题了，但是这个项目跑着跑着分数就挂掉了。

**Comment by NathansLiu** [comment]
pip3 install -r requirements.txt 改成这样
Requirement already satisfied: backports.functools-lru-cache==1.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/liuxiaoliang/Desktop/wechat_jump_game-master/requirements.txt (line 1))
Requirement already satisfied: cycler==0.10.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/liuxiaoliang/Desktop/wechat_jump_game-master/requirements.txt (line 2))
Requirement already satisfied: matplotlib==2.1.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/liuxiaoliang/Desktop/wechat_jump_game-master/requirements.txt (line 3))
Requirement already satisfied: numpy==1.13.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/liuxiaoliang/Desktop/wechat_jump_game-master/requirements.txt (line 4))
Requirement already satisfied: olefile==0.44 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/liuxiaoliang/Desktop/wechat_jump_game-master/requirements.txt (line 5))
Requirement already satisfied: opencv-python==3.4.0.12 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/liuxiaoliang/Desktop/wechat_jump_game-master/requirements.txt (line 6))

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
下次请规范提交issue，谢谢
