### ISSUE TITLE
依赖文件下载失败

### ISSUE THREAD

**Issue by hu-qi** [wangshub/wechat_jump_game#757]
您好，我的问题是：
通过pip安装requirements.txt文件中依赖时，每次跑到一定的百分比就报错了。请各位大牛帮忙看看，是哪里问题。
`
PS E:\download\wechat_jump_game-master\wechat_jump_game-master> pip install -r .\requirements.txt
Collecting backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Could not find a version that satisfies the requirement backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1)) (from versions: )
No matching distribution found for backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1))
PS E:\download\wechat_jump_game-master\wechat_jump_game-master> pip install -r .\requirements.txt
Collecting backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10053, ''))': /simple/backports-functools-lru-cache/
  Could not find a version that satisfies the requirement backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1)) (from versions: )
No matching distribution found for backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1))
PS E:\download\wechat_jump_game-master\wechat_jump_game-master> pip install -r .\requirements.txt
Collecting backports.functools-lru-cache==1.4 (from -r .\requirements.txt (line 1))
  Using cached backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Collecting cycler==0.10.0 (from -r .\requirements.txt (line 2))
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting matplotlib==2.1.1 (from -r .\requirements.txt (line 3))
  Downloading matplotlib-2.1.1-cp27-cp27m-win32.whl (8.2MB)
    87% |████████████████████████████    | 7.2MB 4.3kB/s eta 0:04:05Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\python27\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\python27\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "c:\python27\lib\site-packages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 139, in iter
    for x in it:
  File "c:\python27\lib\site-packages\pip\download.py", line 560, in resp_read
    decode_content=False):
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 324, in read
    flush_decoder = True
  File "c:\python27\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 246, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
`

1. 2017-12-30版本
2. 使用环境（win10、Python 2.7）

  
![tim 20180103104002](https://user-images.githubusercontent.com/17986122/34507691-88790fc4-f073-11e7-8241-281bfba2621a.png)

**Comment by cczhong11** [comment]
应该是墙的问题

**Comment by hu-qi** [comment]
已解决 的确是网络的问题
