### ISSUE TITLE
小米5s每次都是跳到第3下的时候用力过猛

### ISSUE THREAD

**Issue by Ryan-Miao** [wangshub/wechat_jump_game#758]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5s
OS: darwin
Python: 3.6.4 (default, Dec 25 2017, 14:57:46)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
**********

遇到问题：前两个正确，第3个就挂了。每次都是，根据config配置，把mi5s的配置放到最外层了，同样不管用
![]()
改进和建议：无

**Comment by xzhlksh** [comment]
唔，试着把你的悬浮球功能关掉，可能是那玩意影响了判断

**Comment by Ryan-Miao** [comment]
@xzhlksh 厉害，确实是

**Comment by Ryan-Miao** [comment]
找到了合适的参数了： https://github.com/Ryan-Miao/wechat_jump_game
