### ISSUE TITLE
三星 note5在 1440x2560 完美运行

### ISSUE THREAD

**Issue by billzbh** [wangshub/wechat_jump_game#759]
config.json
{
    "under_game_score_y": 410,
    "press_coefficient": 1.475,
    "piece_base_height_1_2": 28,
    "piece_body_width": 110,
    "swipe": {
        "x1": 320,
        "y1": 410,
        "x2": 320,
        "y2": 410
    }
}

主要是根据修改了程序中的press_time的方法：
def jump(distance):
    '''
    跳跃一定的距离
    '''
    print('需要跳跃的距离= {}'.format(distance))
    press_time = pow(distance,0.85)*2.76
    press_time = int(press_time)
    print('需要按压的时间= {}ms'.format(press_time))

    cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
        duration=press_time
    )
    print(cmd)
    os.system(cmd)
    return press_time

**Comment by hezengliang** [comment]
赞！在锥子 m1l 中测试也相当完美！

**Comment by hceasy** [comment]
我去...这个是我在MIX2 上测试的参数更新错了配置文件,你们怎么跑的.....

**Comment by huhuno1** [comment]
太失败了 第一次就飞了 。。mi note pro亲测

**Comment by kaiattrib** [comment]
Samsung S7 perfect run.Give my ass to u for thx
