### ISSUE TITLE
三星s6 edge，跳两下后停止

### ISSUE THREAD

**Issue by forevermalin** [wangshub/wechat_jump_game#760]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by MrLevo520** [comment]
请使用最新版release app或者查看cmd命令窗，看是否是因为触发随机延迟导致
