### ISSUE TITLE
求米6参数配置，我默认参数跳不过200

### ISSUE THREAD

**Issue by fu9852531** [wangshub/wechat_jump_game#761]

**Comment by scyACE** [comment]
求python怎么配置啊
Traceback (most recent call last):
  File "wechat_jump_py3.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
我的一直报这个错

**Comment by hu-qi** [comment]
我的mi6无问题 就是排行榜不显示

**Comment by fu9852531** [comment]
你的python  没有 安装 numpy这个库

打开cmd命令行
输入 pip install numpy

2018-01-03 11:19 GMT+08:00 scyACE <notifications@github.com>:

**Comment by qtvspa** [comment]
试试这个

{
    "under_game_score_y": 300,
    "press_coefficient": 1.44,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}

**Comment by fu9852531** [comment]
ok

**Comment by fu9852531** [comment]
米6     刷到500-650  这个区间就好了  ，不要刷太高，会被检测

**Comment by 951240778** [comment]
米6  是 1920X1080的吗？

**Comment by fu9852531** [comment]
是的

2018-01-03 11:59 GMT+08:00 951240778 <notifications@github.com>:

**Comment by hu-qi** [comment]
我用的作者推荐的mi6配置
![tim 20180103120033](https://user-images.githubusercontent.com/17986122/34508745-c153c438-f07d-11e7-89d7-d7246c506fa7.png)
在config/mi 目录下  把 mi6_config.json 放到 .py  文件同级目录

**Comment by scyACE** [comment]
运行起来之后点击不跳，求助啊

**Comment by 951240778** [comment]
@fu9852531   你可以 修改一下  按压系数  改成 1.5  左右吧  我是 红米 note 4 x  1920X 1080的

**Comment by 951240778** [comment]
目前跳到 500分左右 @fu9852531

**Comment by 951240778** [comment]
可能需要修改其他参数吧  还 @fu9852531

**Comment by scyACE** [comment]
用adb shell 的那个命令不好使，求解答

**Comment by 951240778** [comment]
@scyACE  这个 只是安装一下adb  而已 添加环境变量

**Comment by scyACE** [comment]
那如果用免adb的方法呢？ @951240778

**Comment by Li-Allen** [comment]
300  1.475  20  70，试试这个，我给同学一次就刷了六百多

**Comment by hu-qi** [comment]
不知道什么原因 只显示第一次的分数 第一次287分就挂了  后面再怎么刷都不能更新分数

**Comment by htl1104** [comment]
只能跳两百多分
