### ISSUE TITLE
求老铁有高分的三星S7的参数配置

### ISSUE THREAD

**Issue by HuangJunXiong** [wangshub/wechat_jump_game#764]
S7使用1440x2560分辨率的配置。最高也只能调到100多。还不如我手动呢。求一发高分可用配置

**Comment by nobabe** [comment]
@HuangJunXiong 貌似我用默认配置，只改了一个参数，感觉能跳1000。我最高跑到了555

**Comment by hceasy** [comment]
最高可以8000+,不过配置在家里那台电脑上,要晚上回去才能给你.

**Comment by songshenma** [comment]
看我的帖子 你自己试下

**Comment by nobabe** [comment]
用最高分辨率，coefficient 改为1

**Comment by HuangJunXiong** [comment]
@hceasy 拜托了

**Comment by HuangJunXiong** [comment]
@nobabe 用最高分辨率不知道怎么回事怎么调整都是大力出奇迹，飞了。。。

**Comment by HuangJunXiong** [comment]
@songshenma 我一直都是这样做的，跳上200都难。。

**Comment by KingAckerman** [comment]
S7EDGE

**Comment by KingAckerman** [comment]
{
    "under_game_score_y": 300,
    "press_coefficient": 1,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 716,
      "y1": 2100,
      "x2": 716,
      "y2": 2100
    }
}

**Comment by KingAckerman** [comment]
s7edge

**Comment by KingAckerman** [comment]
s7edge       {
    "under_game_score_y": 300,
    "press_coefficient": 1,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 716,
      "y1": 2100,
      "x2": 716,
      "y2": 2100
    }
}

**Comment by hceasy** [comment]
{
    "under_game_score_y": 300,
    "press_coefficient": 1.035,
    "piece_base_height_1_2": 28,
    "piece_body_width": 110,
    "swipe" : {
      "x1": 320,
      "y1": 410,
      "x2": 320,
      "y2": 410
    }
}

**Comment by zkl99999** [comment]
@hceasy ，请问你最后发的这个是三星s7吗，不是s7edge把
