### ISSUE TITLE
S7edge 2560*1440分辨率不行

### ISSUE THREAD

**Issue by songshenma** [wangshub/wechat_jump_game#766]
S7edge只要把曲面侧栏 、悬浮球等关闭，然后选择（1920*1080）的分辨率
用默认 config 目录下（1920*1080）的配置就行
目前分数 1000+，没啥意思就不跳了
千万别用（2560*1440）分辨率，第一步就跳不出去就死了
上分为证

![1514950475 1](https://user-images.githubusercontent.com/19419803/34508420-1a7d6fae-f07a-11e7-8a8c-b30ff2ca87d0.jpg)

**Comment by hceasy** [comment]
抱歉那个配置我更新错了,已经改回去等确认.

**Comment by hexiangcoming** [comment]
小白想问如何更改config目录下的默认配置？我的默认配置是Load config file from D:\wechat_jump_game-master/config/2560x1440/config.json，如何改成1920x1440呢？

**Comment by KingAckerman** [comment]
把1920x1080文件夹中的default.json放置到2560x1440文件下面就是更改了

**Comment by KingAckerman** [comment]
我试了下1920x1080的配置文件，不行的

**Comment by KingAckerman** [comment]
{
    "under_game_score_y": 300,
    "press_coefficient": 1,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 716,
      "y1": 2100,
      "x2": 716,
      "y2": 2100
    }
}

**Comment by realeve** [comment]
亲测可用
{
    "under_game_score_y": 410,
    "press_coefficient": 1.035,
    "piece_base_height_1_2": 28,
    "piece_body_width": 110,
    "swipe": {
        "x1": 320,
        "y1": 410,
        "x2": 320,
        "y2": 410
    }
}
