### ISSUE TITLE
截图间隔时间太小，导致截图有白圈，在白圈和下一个跳台有重叠的时候导致坐标识别计算错误

### ISSUE THREAD

**Issue by teffy** [wangshub/wechat_jump_game#767]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: PRO 5
OS: linux
Python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
**********

![1514938864](https://user-images.githubusercontent.com/4166470/34508377-96a9b5c0-f079-11e7-986e-f562cf03c673.png)

![1514938864_dddd](https://user-images.githubusercontent.com/4166470/34508378-96dc9f80-f079-11e7-940c-7475972c78c8.png)

这样最多不过1000

改进方案：增加间隔时间
```
@@ -256,7 +256,7 @@ def main():
                 time.sleep(1)
             print('\n继续')
             i, next_rest, next_rest_time = 0, random.randrange(30, 100), random.randrange(10, 60)
-        time.sleep(random.uniform(0.9, 1.2))   # 为了保证截图的时候应落稳了，多延迟一会儿，随机值防 ban
+        time.sleep(random.uniform(1.5, 2.2))   # 为了保证截图的时候应落稳了，多延迟一会儿，随机值防 ban
```
我本地改过之后试了一次，跳到7098
1514950253_d.png
![1514950253_d](https://user-images.githubusercontent.com/4166470/34508513-2bcf4006-f07b-11e7-8d73-0c506a64499d.png)
1514950257.png
![1514950257](https://user-images.githubusercontent.com/4166470/34508514-2bff0c0a-f07b-11e7-95cb-45a9a5f41796.png)

然后这次的失败我就不知道原因了，坐标位置都是正确的，但还是扑街了，估计时间还需要再精细一下才行
```
scan_start_y: 740
1514950253 240 1152 874.0 794
adb shell input swipe 571 1584 571 1584 1013
scan_start_y: 740
1514950257 0 0 0 0
adb shell input swipe 543 1588 543 1588 200
```

**Comment by lightfight** [comment]
请教下，用的什么画图工具呢？

**Comment by teffy** [comment]
@lightfight  debug代码里有

**Comment by lightfight** [comment]
@teffy 
`
def save_debug_screenshot(ts, im, piece_x, piece_y, board_x, board_y):
    '''
    对 debug 图片加上详细的注释
    '''
    make_debug_dir(screenshot_backup_dir)
    draw = ImageDraw.Draw(im)
    draw.line((piece_x, piece_y) + (board_x, board_y), fill=2, width=3)
    draw.line((piece_x, 0, piece_x, im.size[1]), fill=(255, 0, 0))
    draw.line((0, piece_y, im.size[0], piece_y), fill=(255, 0, 0))
    draw.line((board_x, 0, board_x, im.size[1]), fill=(0, 0, 255))
    draw.line((0, board_y, im.size[0], board_y), fill=(0, 0, 255))
    draw.ellipse((piece_x - 10, piece_y - 10, piece_x + 10, piece_y + 10), fill=(255, 0, 0))
    draw.ellipse((board_x - 10, board_y - 10, board_x + 10, board_y + 10), fill=(0, 0, 255))
    del draw
    im.save('{}{}_d.png'.format(screenshot_backup_dir, ts))
`

看到了非常谢谢

**Comment by lightfight** [comment]
@teffy 看到了非常谢谢
```
def save_debug_screenshot(ts, im, piece_x, piece_y, board_x, board_y):
    '''
    对 debug 图片加上详细的注释
    '''
    make_debug_dir(screenshot_backup_dir)
    draw = ImageDraw.Draw(im)
    draw.line((piece_x, piece_y) + (board_x, board_y), fill=2, width=3)
    draw.line((piece_x, 0, piece_x, im.size[1]), fill=(255, 0, 0))
    draw.line((0, piece_y, im.size[0], piece_y), fill=(255, 0, 0))
    draw.line((board_x, 0, board_x, im.size[1]), fill=(0, 0, 255))
    draw.line((0, board_y, im.size[0], board_y), fill=(0, 0, 255))
    draw.ellipse((piece_x - 10, piece_y - 10, piece_x + 10, piece_y + 10), fill=(255, 0, 0))
    draw.ellipse((board_x - 10, board_y - 10, board_x + 10, board_y + 10), fill=(0, 0, 255))
    del draw
    im.save('{}{}_d.png'.format(screenshot_backup_dir, ts))
```
