### ISSUE TITLE
小米note顶配2560#1440一直100多自杀相同配置的也可发一下参数 共享

### ISSUE THREAD

**Issue by huhuno1** [wangshub/wechat_jump_game#768]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by huhuno1** [comment]
距离时而不够 100左右必死 用的 2560*1440config

**Comment by Moonlightshining** [comment]
老哥有没有适配的参数？

**Comment by huhuno1** [comment]
没有啊马飞
