### ISSUE TITLE
排行榜分数不上传服务器~~~

### ISSUE THREAD

**Issue by Joneze** [wangshub/wechat_jump_game#769]
如题，就是自动刷的分数，也不多 就400多点，然而 上不了服务器，只能自己看，过半小时 ，连自己都看不到了。

**Comment by MemoryReload** [comment]
不是实时的，我之前也是这样，等一等就更新了。反正，我是过了差不多一天，才更新上去排行榜的。

**Comment by ujffdi** [comment]
我等了几天也更新不上排行榜

**Comment by inhandWRC** [comment]
目测被封了  我昨天的也没上榜

**Comment by lsh1994** [comment]
同

**Comment by jone-2016** [comment]
数据被过滤了，这个方法这么火，腾讯肯定出了应对方案

**Comment by Joneze** [comment]
@MemoryReload 估计应该是被过滤了，反而让我研究出了，手动爬分的规律。。。我也是醉了 。

**Comment by helloLI4015** [comment]
@Joneze    这个方法被封了？

**Comment by Joneze** [comment]
@helloLI4015 我也不知道啊，反正有人成功有人失败吧！！

**Comment by Joneze** [comment]
刚刚试了下 先手动跳了100分左右，然后跑自动，280分吧，上传成功，这个脚本时间的序列是正弦的，所以可能是通过这个来过滤的，另外，高分段脚本都很难跳上去啊，，纠结！~
