### ISSUE TITLE
请在项目根目录中运行脚本   脚本里面怎么改？

### ISSUE THREAD

**Issue by NathansLiu** [wangshub/wechat_jump_game#770]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by lena9017** [comment]
我也遇到了这个问题。
try:
    from common import debug, config
except ImportError:
    print('请在项目根目录中运行脚本')
    exit(-1)

是这一段报的错误，我已经把config.json和*.py文件放在同一个文件夹了。"请在项目根目录中运行脚本"是什么意思？ 另外，import common 没有问题，from common import debug，结果是 “AttributeError: module 'common' has no attribute 'debug'”。不知道这段代码的作用是什么，望指教~
