### ISSUE TITLE
跳不过200.。。

### ISSUE THREAD

**Issue by weileiChina** [wangshub/wechat_jump_game#775]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by weileiChina** [comment]
小米6手机，跳不过200

{
    "under_game_score_y": 300,
    "press_coefficient": 1.44,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe": {
        "x1": 500,
        "y1": 1600,
        "x2": 500,
        "y2": 1602
    }
}

**Comment by superchen1990** [comment]
同样，153扑街

**Comment by Rothschild17** [comment]
我经常跳过200。。。 多试试那个参数 我现在用的1.475
