### ISSUE TITLE
红米note4 不能自动运行

### ISSUE THREAD

**Issue by liuxianzhong** [wangshub/wechat_jump_game#776]
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: y
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4
OS: win32
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
**********
采用方式 1 获取截图
scan_start_y: 690
1514955370 338 1109 788.5 849
adb shell input swipe 538 1582 538 1582 724
scan_start_y: 690
1514955373 338 1109 788.5 849
adb shell input swipe 566 1583 566 1583 724
scan_start_y: 690
1514955376 338 1109 788.5 849
adb shell input swipe 567 1580 567 1580 724
scan_start_y: 690
1514955390 338 1109 788.5 849
adb shell input swipe 543 1580 543 1580 724

**Comment by AnnaYe** [comment]
确定手机和adb连上了？小米手机打开USB调试要打开USB调试（安全）

**Comment by huangxunyi** [comment]
还要打开模拟触摸.

**Comment by LSD-T** [comment]
1.看看手机USB调试和USB调试（安全）
2.看看adb devices 看看手机和adb 正确连接了么

哥就是用的note4，昨晚刷的，刷一会儿就是报erange 错误，再重新跑一下脚本就好了。

**Comment by caokaifa** [comment]
红米note4参数怎么设置？
