### ISSUE TITLE
小米note3，press_coefficient改为1.47后能跑500多分

### ISSUE THREAD

**Issue by AnnaYe** [wangshub/wechat_jump_game#778]
![image](https://user-images.githubusercontent.com/15603637/34509599-ba642f24-f086-11e7-9d7d-51e1a2f02690.png)

**Comment by UsingMisz** [comment]
你的会出现 请在项目根目录中运行脚本这个吗？

**Comment by AnnaYe** [comment]
@UsingMisz 对的，我把1920x1080的config.jsion放到auto.py目录下了

**Comment by nshen** [comment]
我跳最多400多

**Comment by chloechj** [comment]
presstime加50，用默认的config不会死

**Comment by swallowsonny** [comment]
mi note 用原始的只能跳200多，改为1.47后能跳800多

**Comment by baininghan** [comment]
@swallowsonny 最新的已经是1.47了,但是我的mi note最多跳到187-_-||
