### ISSUE TITLE
在这两天使用，发现一个有趣的现象。手机在竖着和横着，跳的精度不一样

### ISSUE THREAD

**Issue by WinSon-Zhao** [wangshub/wechat_jump_game#779]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Pro
OS: win32
Python: 3.5.4rc1 (v3.5.4rc1:385b368, Jul 24 2017, 14:37:10) [MSC v.1900 64 bit (AMD64)]
**********
采用方式 1 获取截图
scan_start_y: 690
1514954682 338 1109 788.5 849
adb shell input swipe 581 1578 581 1578 724
scan_start_y: 690
1514954686 292 1136 819.0 826
adb shell input swipe 558 1586 558 1586 851
scan_start_y: 790
1514954691 678 1047 446.0 908
adb shell input swipe 543 1583 543 1583 376
scan_start_y: 690
1514954694 832 1133 300.5 824
adb shell input swipe 531 1578 531 1578 855

遇到问题：在手机竖着的状态下，跳的精度是随机的，只有偶尔一次跳到中心，分数上去比较慢，十几分钟都上不去分；手机是横着的状态下，跳的非常精准，可以一致连续的跳到中心，分数上去很快，几分钟就可以了。这是什么情况？
![]()
改进和建议：无

**Comment by WinSon-Zhao** [comment]
adb配置在环境变量中，命令窗口中运行

**Comment by Paladinfeng** [comment]
感觉iOS上也是, 横着会跳的非常准

**Comment by WinSon-Zhao** [comment]
这就很神奇了

**Comment by WokoLiu** [comment]
好神奇，请问竖着横着，分别是指哪种状态？
1. 手机与桌面垂直，底边触碰桌面
2. 手机与桌面垂直，侧边触碰桌面
3. 手机与桌面平行，整个贴在桌面上

**Comment by WinSon-Zhao** [comment]
横着，手机侧边触碰桌面；竖着，手机底部接触桌面、整个贴在桌面

**Comment by WangLeto** [comment]
确实~小米6 原来刷分只能到 600 左右，手机横放以后轻松上千了
