### ISSUE TITLE
跳出来的分数并不能显示在朋友排行榜上，微信是怎么判断是用脚本跳的啊 

### ISSUE THREAD

**Issue by 329463417** [wangshub/wechat_jump_game#781]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by 329463417** [comment]
能绕过微信么

**Comment by 329463417** [comment]
不上传服务器，怎么知道我作弊了？凭什么不显示我的分数

**Comment by liroBoy** [comment]
分数没那么快更新，有延时，我昨天就是2个小时才显示最新分数

**Comment by NeowuqiLee** [comment]
玩跳一跳时就分析你的操作行为，代码跳的和手跳的还是有很大区别，判断你是代码跳时就不上传。好比人点击时操作曲线是离散的点，代码跳是正弦。

**Comment by helloLI4015** [comment]
那就是这个方法被封了，是吗？

**Comment by 329463417** [comment]
不是的，一开始显示，过一会就不显示了

**Comment by Joneze** [comment]
为了不正弦曲线，可以尝试中断程序，中间穿插手动，目前280分正常上传。

**Comment by chloechj** [comment]
我2000分以上上传会清零，1000以下没有问题

**Comment by Lewiskong** [comment]
解决了，详见这篇文章～https://zhuanlan.zhihu.com/p/32594563

**Comment by StriveCheng** [comment]
@Lewiskong 抓包那个怎么改，能说的详细一点吗

**Comment by Lewiskong** [comment]
@StriveCheng 已经更新https://zhuanlan.zhihu.com/p/32594563，欢迎交流😄
