### ISSUE TITLE
readme别再改来改去了好吗

### ISSUE THREAD

**Issue by mundane799699** [wangshub/wechat_jump_game#782]
现在的这份readme不清楚, Android手机那两种手动和自动的操作方式根本没写清楚, 倒是iOS的操作方式分两种情况写清楚了.
建议修正, 然后不要给太多人修改readme的权限, 我看之前有人写的关于怎么操作虚拟环境的挺好的, 结果后面一个人又给它删了

**Comment by WinSon-Zhao** [comment]
开源就是这样，没人管

**Comment by telenewbie** [comment]
我是看提交记录的,觉得之前的虚拟环境还是不错的.

**Comment by MrLevo520** [comment]
具体操作步骤放在wiki中，请查看：https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4

**Comment by binderclip** [comment]
@mundane799699 @WinSon-Zhao  新的 Readme 是几个人讨论后才改的。
帮助信息放在了 wiki 里，因为想好好整理下，把尽量多的情况都写清楚。
