### ISSUE TITLE
锤子 M1L 2k屏幕 每次都是轻轻跳一下，怎么改参数也没用

### ISSUE THREAD

**Issue by AlkeneSun** [wangshub/wechat_jump_game#783]
**********        
Screen: Physical size: 1440x2560
Density: Physical density: 560
DeviceType: SM919
OS: darwin
Python: 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
**********
锤子 M1L 2k屏幕 每次都是轻轻跳一下，怎么改参数也没用

**Comment by asseywang** [comment]
我就这个手机，你需要把大爆炸关掉。

**Comment by Lanme** [comment]
我也是轻轻挑一下，根本不知道怎么改参数啊，第一步都跳不成功

**Comment by sealoner** [comment]
大爆炸已关，还是不行。参数识别的都是正确的，但就是在第一步过不去

**Comment by asseywang** [comment]
那我也不清楚了，我跑了一遍是成功的，你确保一下自己更换了config文件选用2K分辨率的配置
