### ISSUE TITLE
RoutingConnection.h 文件缺失？？？

### ISSUE THREAD

**Issue by pengshengsongcode** [wangshub/wechat_jump_game#784]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by pengshengsongcode** [comment]
<img width="295" alt="2018-01-03 1 44 13" src="https://user-images.githubusercontent.com/18256030/34510140-391958a8-f08c-11e7-8e8e-51755538de48.png">

**Comment by Beyond-Chao** [comment]
确保你下载了Carthage (brew install carthage)，WebDriverAgent 使用Carthage下载所有的依赖

**Comment by pengyou200902** [comment]
下了homebrew，下了carthage，但还是提示RoutingConnection.h缺失，相同问题，vmware pro 14装的mac os x，刚新装的xcode
