### ISSUE TITLE
小白运行python时没失败，出现乱码。是不是安装的py文件少了？

### ISSUE THREAD

**Issue by haohao1238** [wangshub/wechat_jump_game#786]
前面都成功了，各模块都可以加载，adb也调试好了。出现如下：是不是py下少了，缺哪个？
![default](https://user-images.githubusercontent.com/30686847/34510543-a398d7f0-f08f-11e7-9fe8-570cadd360a3.png)
![default](https://user-images.githubusercontent.com/30686847/34510548-a84a31ae-f08f-11e7-804b-0e9288f226c5.png)

**Comment by F-loat** [comment]
目前建议使用 py3，乱码问题之后会再修复 #788

**Comment by haohao1238** [comment]
谢谢
