### ISSUE TITLE
三星S8+ FHD+模式 1509步后报错。

### ISSUE THREAD

**Issue by DomainCollection** [wangshub/wechat_jump_game#789]
程序版本号：1.1.1
**********
Screen: Physical size: 2220*1080 三星S8+ FHD+模式 曲面侧屏: off
Density: Physical density: 529
DeviceType: SM-G9550
OS: Android 7.1
Python: 3.5.2
**********
跑到1509步后，出现下面报错，求解决，谢谢
1514959356 379 1235 788.5 999
adb shell input swipe 556 1832 556 1832 657
^CTraceback (most recent call last):
  File "wechat_jump_auto.py", line 263, in <module>
    main()
  File "wechat_jump_auto.py", line 246, in main
    jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
  File "wechat_jump_auto.py", line 94, in jump
    os.system(cmd)

**Comment by soysaucemo** [comment]
确定不是按了Ctrl+C?

**Comment by DomainCollection** [comment]
确定，出现报错代码终止了我才按的Ctrl+C.
