### ISSUE TITLE
已安装 numpy ,运行脚本时却报没有该module，如图

### ISSUE THREAD

**Issue by longitachi** [wangshub/wechat_jump_game#791]
![16821712-e1c2-453b-9f87-5fbb12fc2cd6](https://user-images.githubusercontent.com/11711768/34510951-16c9b07a-f093-11e7-8e25-8ce87aeff592.png)

**Comment by cxyfreedom** [comment]
错误写得很清楚了，你的numpy是安装在2.7下的，但是你运行的脚本又是python3，但你python3下并没有安装numpy

**Comment by longitachi** [comment]
多谢，那我应该执行下`pip3 install numpy`这个吗？
