### ISSUE TITLE
pip 依赖文件安装失败，在线等😂  

### ISSUE THREAD

**Issue by zhaochongliang** [wangshub/wechat_jump_game#792]
pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

**Comment by F-loat** [comment]
[wiki](https://github.com/wangshub/wechat_jump_game/wiki/Android-%E5%92%8C-iOS-%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4)

**Comment by WinSon-Zhao** [comment]
beautifulsoup4 (4.6.0)
certifi (2017.7.27.1)
chardet (3.0.4)
cycler (0.10.0)
Django (2.0.1)
idna (2.6)
image (1.5.17)
lxml (3.8.0)
matplotlib (2.1.1)
numpy (1.13.3)
olefile (0.44)
opencv-python (3.4.0.12)
Pillow (5.0.0)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
python-docx (0.8.6)
pytz (2017.3)
requests (2.18.4)
setuptools (28.8.0)
six (1.11.0)
urllib3 (1.22)
这是我的依赖，你看看你还缺啥

**Comment by zhaochongliang** [comment]
我是  运行不了pip install -r

**Comment by F-loat** [comment]
原则上来说 pip 模块的安装问题，自行搜索解决就好

> pip install [options] -r <requirements file> [package-index-options]

我的输出是这样的，requirements file 为必需参数，有差异的话请更新 pip 版本

**Comment by F-loat** [comment]
`pip install -r requirements.txt`

**Comment by zhaochongliang** [comment]
我是个小白，能不能更清楚一点   😊

**Comment by F-loat** [comment]
你执行 `pip install -r requirements.txt` 这个命令的完整输出发一下

**Comment by zhaochongliang** [comment]
Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

**Comment by F-loat** [comment]
在有 `requirments.txt` 这个文件的目录里执行啊。。

**Comment by zhaochongliang** [comment]
具体要怎么来做？

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/34511488-f8f6177e-f096-11e7-9c39-ceb4beece44e.png)

**Comment by zhaochongliang** [comment]
我把这个文件放在了桌面上

**Comment by zhaochongliang** [comment]
然后怎么办
