### ISSUE TITLE
执行文件wechat_jump_auto.py文件报错WindowsError: [Error 32] ????????????,???????: 'autojump.png'

### ISSUE THREAD

**Issue by Vegeta-D** [wangshub/wechat_jump_game#794]
Load config file from E:\wechat_jump_game-master/config/1920x1080/config.json
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: 程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: HUAWEI GRA-UL00
OS: win32
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
**********
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 263, in <module>
    main()
  File "wechat_jump_auto.py", line 235, in main
    check_screenshot()
  File "wechat_jump_auto.py", line 207, in check_screenshot
    check_screenshot()
  File "wechat_jump_auto.py", line 197, in check_screenshot
    os.remove('autojump.png')
WindowsError: [Error 32] ????????????,???????: 'autojump.png'

**Comment by wujian72** [comment]
我也是这个错

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
