### ISSUE TITLE
MI 5跳几十下就死了

### ISSUE THREAD

**Issue by UsingMisz** [wangshub/wechat_jump_game#795]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by chloechj** [comment]
之前有人说了，程序的presstime加50，config不变，miui效果不错

**Comment by lauriehjb** [comment]
@chloechj 亲测有效，改执行的python文件

**Comment by Earl-chen** [comment]
![default](https://user-images.githubusercontent.com/29749997/34650571-314d9b46-f3fe-11e7-9bc4-28e48da33d81.png)

这是什么情况啊？始终连接不上，我也是mi5，两个调试都打开了

**Comment by MrLevo520** [comment]
请尝试使用免adb配置的版本，也可以使用release的app版本

**Comment by zicanli** [comment]
加50果然有用
