### ISSUE TITLE
ios xcode product->Test  bulid succeeded Test failed WebDriverAgent应用无法启动

### ISSUE THREAD

**Issue by wylemonys** [wangshub/wechat_jump_game#798]
iphoneX ios11.2.1 mac
配置好WebDriverAgent的证书，test时bulid没问题Test failed
![image](https://user-images.githubusercontent.com/12773363/34511939-e10e098e-f099-11e7-9822-31e8d792459f.png)

**Comment by KevinZK** [comment]
把targets  中的team 全都选好

**Comment by wylemonys** [comment]
刚试过了还是不行

**Comment by jiwuming** [comment]
控制台输出什么啊

**Comment by wylemonys** [comment]
问题已解决，重启手机就可以了不再报这个错[捂脸]
