### ISSUE TITLE
ios + windows如何设置呢

### ISSUE THREAD

**Issue by Bigwode** [wangshub/wechat_jump_game#799]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by truebit** [comment]
iOS没有Mac电脑是行不通的，用windows+genymotion吧

**Comment by Henry-YN** [comment]
iOS没有Mac电脑是行不通的，用windows+genymotion吧

**Comment by Bigwode** [comment]
All right，thank you very much !

**Comment by MrLevo520** [comment]
除了装黑苹果，目前还未解，请关注下次更新，谢谢
