### ISSUE TITLE
我那边实现了一个简单的自动化的版本

### ISSUE THREAD

**Issue by binderclip** [wangshub/wechat_jump_game#8]
大概思路是靠颜色来定位棋子和板子的坐标。

代码在这里：
https://github.com/binderclip/wechat_jump_game/blob/master/wechat_jump_auto.py

可以 PR 一下吗？

**Comment by binderclip** [comment]
现在最该 966 分了

**Comment by Bingshuli** [comment]
screencap出的图片方向是横着的怎么搞。。。

**Comment by binderclip** [comment]
@Bingshuli 啊，adb 这里我不是很懂，求 @wangshub 解答下吧

**Comment by wangshub** [comment]
稍等，我先看下你的代码 @binderclip

**Comment by LoveqLRC** [comment]
希望能兼容到3.0以后

**Comment by wangshub** [comment]
麻烦你那里提交一下，我把代码提交进去 @binderclip

**Comment by binderclip** [comment]
@wangshub OK

**Comment by binderclip** [comment]
![image](https://user-images.githubusercontent.com/8187479/34439713-e1dd06c4-ecea-11e7-9652-211634fb2c93.png)
最近一次终结于 2816

**Comment by wangshub** [comment]
小心没有朋友~  ^_^

**Comment by binderclip** [comment]
@wangshub 专门用的小号哈哈哈，不然真的没朋友了。。

**Comment by wangshub** [comment]
@binderclip 在知乎上加上你的github地址啦，以示感谢
![image](https://user-images.githubusercontent.com/20924010/34439829-b97fe31c-eceb-11e7-9c92-95069f31d379.png)

**Comment by binderclip** [comment]
@wangshub 多谢 🙏
