### ISSUE TITLE
adb: error: remote object '/sdcard/1.png' does not exist

### ISSUE THREAD

**Issue by zhang07208** [wangshub/wechat_jump_game#80]
总是隔一次就出现 remote object '/sdcard/1.png' does not exist
导致这次跳还是根据上一次的数据来的
有大佬知道这是什么情况么？

在issue区搜目前没找到解决办法

/sdcard/1.png: 1 file pulled. 2.1 MB/s (56994 bytes in 0.026s)
(1514618952, 338, 1109, 788, 851)
adb shell input swipe 320 410 320 410 722
adb: error: remote object '/sdcard/1.png' does not exist
(1514618961, 338, 1109, 788, 851)
adb shell input swipe 320 410 320 410 722
/sdcard/1.png: 1 file pulled. 3.0 MB/s (68862 bytes in 0.022s)
(1514618970, 795, 1111, 431, 902)
adb shell input swipe 320 410 320 410 584
adb: error: remote object '/sdcard/1.png' does not exist
(1514618979, 795, 1111, 431, 902)
adb shell input swipe 320 410 320 410 584
/sdcard/1.png: 1 file pulled. 0.1 MB/s (57771 bytes in 0.640s)

**Comment by 897902334** [comment]
我的也是这个问题，成功过一次 但是会提醒 adb: error: remote object '/sdcard/1.png' does not exist， 然后我把GitHub上的代码重新下载了一遍，重新执行， 直接提示adb: error: remote object '/sdcard/1.png' does not exist   游戏都没有起跳了！！  求教啊 好不容易成功了  就是这个图片问题了！  大神！  Iesses 里头翻遍了  解决不了，我的是小米手机小米Note1

**Comment by zhang07208** [comment]
@897902334 我也是小米，小米5s plus。
直接提示does not exist 应该和上面问题一样。不清楚是不是小米手机的权限问题

**Comment by Mrlilili** [comment]
把代码里面的图片名称改下，把1.png都改成test.png，1.png在小米手机里面显示的都是1_xxxxx.png
所以找不到图片传到电脑上

**Comment by 897902334** [comment]
@Mrlilili  老哥  代码中有好多地方都是1.png  都改成test.png吗？？？

**Comment by 897902334** [comment]
哈哈哈哈  改成test.png 成功了，  速度好慢啊，  怎么能让速度变快点呢？？？？

**Comment by zhang07208** [comment]
@Mrlilili 多谢老哥！
@897902334 下面有个参数是时间，135行。另外是全部改么，我这边查看了一下，手机存储的照片名字还是test_xxxx，这就比较烦了。。

**Comment by 897902334** [comment]
@zhang07208   不懂Python代码   time.sleep(random.uniform(1, 1.1))   这个怎么修改就变快了？？？

**Comment by zhang07208** [comment]
@897902334 应该是他随机取了1~1.1的数，你可以设小一点把。

**Comment by abcd106** [comment]
老哥 pip install -r requirements.txt 执行的时候 报pip不是命令，咋回事

**Comment by zhang07208** [comment]
@abcd106 在path里添加路径E:\Python27\Scripts

**Comment by 897902334** [comment]
@zhang07208  老铁 这个1~1.1是啥意思？？    你改了没？

**Comment by Mrlilili** [comment]
@abcd106 
https://www.cnblogs.com/yuanzm/p/4089856.html
看这个，得安装pip

**Comment by zhang07208** [comment]
@897902334 还没有，我还是报 adb: error: remote object '/sdcard/test.png' does not exist，你这个问题完全解决了么？

**Comment by 897902334** [comment]
@zhang07208   嗯嗯 解决了  上面那个老哥的方法 该成test.png  就好了  还有我把这个 wechat_jump_auto.py 文件单独放到了 C盘根目录下了

**Comment by zhang07208** [comment]
@897902334 好的，谢谢。是所有都改是把。

那个1~1.1，因为前面是time.sleep，然后又是random.uniform，所以我猜测是取1s~1.1s的随机数。你可以改成0.5~0.6，试一下。或者等会我成功了试一下

**Comment by zhang07208** [comment]
@897902334 好的，谢谢。是所有都改是把。

那个1-1.1，因为前面是time.sleep，然后又是random.uniform，所以我猜测是取1s-1.1s的随机数。你可以改成0.5~0.6，试一下。或者等会我成功了试一下

**Comment by 897902334** [comment]
嗯嗯 谢谢你哥们， 我 试试去！，  祝你成功啊

**Comment by zhang07208** [comment]
@897902334 还是不行，我哭了/。/  

/sdcard/test.png: 1 file pulled. 1.1 MB/s (57288 bytes in 0.049s)
(1514621353, 338, 1109, 788, 851)
adb shell input swipe 320 410 320 410 722
adb: error: remote object '/sdcard/test.png' does not exist
(1514621361, 338, 1109, 788, 851)
adb shell input swipe 320 410 320 410 722

**Comment by 897902334** [comment]
代码是最新的吗？还有就是那个 开发者里头的安全权限开了没？

**Comment by zhang07208** [comment]
@897902334 应该是最新的，我中午刚下的代码。等会我再重新下一个。

另外开发者里没有找到安全权限....miui版本 8.0

**Comment by 897902334** [comment]
@zhang07208   
![sa](https://user-images.githubusercontent.com/9455329/34452632-4323725e-ed7e-11e7-84fe-dadffc62060f.png)
是这个 （USB调试）安全设置

**Comment by zhang07208** [comment]
@897902334 谢谢老哥给我截图。   不过我这里没有这个，太伤了。。
![qq 20171230162939](https://user-images.githubusercontent.com/22976539/34452642-af1360d2-ed7e-11e7-8fb7-d4e7b0e348cd.jpg)

**Comment by 897902334** [comment]
@zhang07208 老铁，没事，多关注ieusss把，问题肯定能解决的，另外我把时间改了下   发现没有啥变化，而且每次都是挑到102步就死了，  我自个都玩到199   哈哈哈   ， good luck

**Comment by zhang07208** [comment]
@897902334 没有变化么，这就比较坑了，可能是计算时间比较长吗，哈哈

**Comment by aqxa** [comment]
@zhang07208 我和你一样的情况

**Comment by zhang07208** [comment]
@aqxa 握个手，哈哈

**Comment by aqxa** [comment]
@zhang07208 如果 sdcard 已经存在 test.png 了，再进行截图，文件名就会变。然后我改了下代码，每次生成不同的文件名，就解决了

**Comment by zhang07208** [comment]
@aqxa 谢谢老哥，我想到的也是这个问题。但对python和安卓都不熟。。。。。。

**Comment by aqxa** [comment]
@zhang07208 我也没写过 Python，自己网上临时搜的。改后的代码，要不你看看
https://gist.github.com/aqxa/c7263109e54a70c346c23f9802b7aa56

**Comment by zhang07208** [comment]
@aqxa 既然老哥是自己改的，那我也先尝试一下自己改hhhhhhhh。希望有好消息！
多谢了！

**Comment by aqxa** [comment]
@zhang07208 不过那个文件名最好用随机的

**Comment by Mebigger** [comment]
我的小米 5s 怎么改了也不行呢，我用的anaconda，自带的python3.6但是没有报错但是不能运行总出现：FileNotFoundError: [Errno 2] No such file or directory: './1.png'  test改完了根目录都不出现截图了

**Comment by abcd106** [comment]
@aqxa 老哥，是不是把/sdcard/1.png 改成 /storage/emulated/0就行了

**Comment by zhang07208** [comment]
@aqxa 谢谢。我现在用自增实现了。。不过这样会不会很浪费存储，23333333

**Comment by aqxa** [comment]
@zhang07208 我加了一行执行删除文件的代码

**Comment by zhang07208** [comment]
@abcd106 不是，你可以先看一下相册中存储的照片名字是不是1_xxx.png这样的格式，是的话尝试把1.png改成 test.png试一下。如果还有同样的问题，需要自己定义文件名。

**Comment by zhang07208** [comment]
@aqxa 233333 每次老哥都提前想到并主动实现了。多谢~

**Comment by Mebigger** [comment]
@zhang07208 我的小米 5s 怎么改了也不行呢，我用的anaconda，自带的python3.6但是没有报错但是不能运行总出现：FileNotFoundError: [Errno 2] No such file or directory: './1.png' test改完了根目录都不出现截图了

**Comment by aqxa** [comment]
@zhang07208 我也是瞎搞的，现在 1000 多分了，哈哈。不过发现一个问题，如果中断了，然后文件没被删除，下次执行时遇到相同文件名又 GG 了，还得去原来的目录删除那个文件再运行。

**Comment by zhang07208** [comment]
@Mebigger  这个问题在issues区我好像看到了，等会帮你找一下

**Comment by zhang07208** [comment]
@aqxa 哈哈哈，我发现后面跳中心比较少啊，跳边缘很悬乎，可能还要调一下参数

**Comment by Mebigger** [comment]
@zhang07208   好的，感谢，我正打算安装2.7呢

**Comment by 897902334** [comment]
@aqxa   老哥  你怎么上去的1000多分啊， 为啥我就连102都突破不了呢？   还有你那个随机的名字咋改得？？？  能提供一下 ？

**Comment by 897902334** [comment]
@zhang07208   老哥 怎么实现自增的 ？  求代码啊！  我现在又出现这个test.png不存在的问题了

**Comment by zhang07208** [comment]
@Mebigger 你完整的输出能贴一下么？

**Comment by Mebigger** [comment]
@zhang07208 
C:\Softwares\anaconda\python.exe C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py", line 137, in <module>
    main()
  File "C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py", line 124, in main
    im = Image.open("./%s.png" % (screenshot_no))
  File "C:\Softwares\anaconda\lib\site-packages\PIL\Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './1.png'
不知道为哈会有乱码

**Comment by 897902334** [comment]
C:\>wechat_jump_auto.py
adb: error: remote object '/sdcard/sa.png' does not exist
(1514624861, 0, 0, 0, 0)
adb shell input swipe 320 410 320 410 200
 直接提示这个    跳动一步直接死，  我把名字改成sa了

**Comment by aqxa** [comment]
@897902334 https://gist.github.com/aqxa/c7263109e54a70c346c23f9802b7aa56 搜索 screenshot_no 的位置

**Comment by Mebigger** [comment]
@zhang07208 
C:\Softwares\anaconda\python.exe C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py", line 138, in <module>
    main()
  File "C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py", line 126, in main
    im = Image.open("./1.png")
  File "C:\Softwares\anaconda\lib\site-packages\PIL\Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './1.png'

进程已结束,退出代码1

**Comment by zhang07208** [comment]
@897902334 在前面定义了一个全局变量name=0，然后每次循环自增
`def main():
    global name
    while True:
        name = name+1`

生成命令的时候
`def pull_screenshot():
    os.system('adb shell screencap -p /sdcard/' + bytes(name) + '.png')`

**Comment by aqxa** [comment]
@zhang07208 还发现一个问题，项目根目录的文件没删。。。pull 下来的目标文件名可以固定。

**Comment by 897902334** [comment]
@zhang07208   老哥  能否把wechat_jump_auto.py 这个文件的全部代码贴出  哈哈哈哈  我不会Python代码。。。。。

**Comment by zhang07208** [comment]
@Mrlilili 应该是你adb没装好把。看报错应该是没有把'./1.png'pull到本地。你检查一下adb装好了没

**Comment by zhang07208** [comment]
@897902334 好，代码比较简陋。。。怕被嘲笑，哈哈
`# coding: utf-8
import os
import shutil
import time
import math
from PIL import Image, ImageDraw
import random


# === 思路 ===
# 核心：每次落稳之后截图，根据截图算出棋子的坐标和下一个块顶面的中点坐标，
#      根据两个点的距离乘以一个时间系数获得长按的时间
# 识别棋子：靠棋子的颜色来识别位置，通过截图发现最下面一行大概是一条直线，就从上往下一行一行遍历，
#         比较颜色（颜色用了一个区间来比较）找到最下面的那一行的所有点，然后求个中点，
#         求好之后再让 Y 轴坐标减小棋子底盘的一半高度从而得到中心点的坐标
# 识别棋盘：靠底色和方块的色差来做，从分数之下的位置开始，一行一行扫描，由于圆形的块最顶上是一条线，
#          方形的上面大概是一个点，所以就用类似识别棋子的做法多识别了几个点求中点，
#          这时候得到了块中点的 X 轴坐标，这时候假设现在棋子在当前块的中心，
#          根据一个通过截图获取的固定的角度来推出中点的 Y 坐标
# 最后：根据两点的坐标算距离乘以系数来获取长按时间（似乎可以直接用 X 轴距离）


# TODO: 解决定位偏移的问题
# TODO: 看看两个块中心到中轴距离是否相同，如果是的话靠这个来判断一下当前超前还是落后，便于矫正
# TODO: 一些固定值根据截图的具体大小计算
# TODO: 直接用 X 轴距离简化逻辑


# Magic Number，不设置可能无法正常执行，请根据具体截图从上到下按需设置
under_game_score_y = 300     # 截图中刚好低于分数显示区域的 Y 坐标，300 是 1920x1080 的值，2K 屏、全面屏请根据实际情况修改
press_coefficient = 1.392    # 长按的时间系数，请自己根据实际情况调节
swipe_x1, swipe_y1, swipe_x2, swipe_y2 = 320, 410, 320, 410     # 模拟按压的起始点坐标，需要自动重复游戏请设置成“再来一局”的坐标
piece_base_height_1_2 = 25   # 二分之一的棋子底座高度，可能要调节
piece_body_width = 80       # 棋子的宽度，比截图中量到的稍微大一点比较安全，可能要调节
# 下面的 (353, 859) 和 (772, 1100) 是游戏截图里的两个台子的中点坐标，主要用来算角度，可能要调节
sample_board_x1, sample_board_y1, sample_board_x2, sample_board_y2 = 353, 859, 772, 1100
name = 0

screenshot_backup_dir = 'screenshot_backups/'
if not os.path.isdir(screenshot_backup_dir):
        os.mkdir(screenshot_backup_dir)


def pull_screenshot():
    os.system('adb shell screencap -p /sdcard/' + bytes(name) + '.png')
    os.system('adb pull /sdcard/' + bytes(name) + '.png .')

def backup_screenshot(ts):
    # 为了方便失败的时候 debug
    if not os.path.isdir(screenshot_backup_dir):
        os.mkdir(screenshot_backup_dir)
    shutil.copy(bytes(name) + '.png', '{}{}.png'.format(screenshot_backup_dir, ts))

def save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y):
    draw = ImageDraw.Draw(im)
    draw.line((piece_x, piece_y) + (board_x, board_y), fill=2, width=3)
    del draw
    im.save("{}{}_d.png".format(screenshot_backup_dir, ts))


def jump(distance):
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200 ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time)
    print(cmd)
    os.system(cmd)


def find_piece_and_board(im):
    w, h = im.size

    piece_x_sum = 0
    piece_x_c = 0
    piece_y_max = 0
    board_x = 0
    board_y = 0

    for i in range(h):
        for j in range(w):
            pixel = im.getpixel((j, i))
            # 根据棋子的最低行的颜色判断，找最后一行那些点的平均值，这个颜色这样应该 OK，暂时不提出来
            if (50 < pixel[0] < 60) and (53 < pixel[1] < 63) and (95 < pixel[2] < 110):
                piece_x_sum += j
                piece_x_c += 1
                piece_y_max = max(i, piece_y_max)

    if not all((piece_x_sum, piece_x_c)):
        return 0, 0, 0, 0
    piece_x = piece_x_sum / piece_x_c
    piece_y = piece_y_max - piece_base_height_1_2  # 上移棋子底盘高度的一半

    for i in range(h):
        if i < under_game_score_y:
            continue
        last_pixel = im.getpixel((0, i))
        if board_x or board_y:
            break
        board_x_sum = 0
        board_x_c = 0

        for j in range(w):
            pixel = im.getpixel((j, i))
            # 修掉脑袋比下一个小格子还高的情况的 bug
            if abs(j - piece_x) < piece_body_width:
                continue

            # 修掉圆顶的时候一条线导致的小 bug，这个颜色判断应该 OK，暂时不提出来
            if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 10:
                board_x_sum += j
                board_x_c += 1
        if board_x_sum:
            board_x = board_x_sum / board_x_c
    # 按实际的角度来算，找到接近下一个 board 中心的坐标
    board_y = piece_y - abs(board_x - piece_x) * abs(sample_board_y1 - sample_board_y2) / abs(sample_board_x1 - sample_board_x2)

    if not all((board_x, board_y)):
        return 0, 0, 0, 0

    return piece_x, piece_y, board_x, board_y


def main():
    global name
    while True:
        name = name+1
        pull_screenshot()
        im = Image.open("./" + bytes(name) + ".png")
        # 获取棋子和 board 的位置
        piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
        ts = int(time.time())
        print(ts, piece_x, piece_y, board_x, board_y)
        jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
        save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y)
        backup_screenshot(ts)
        time.sleep(random.uniform(1, 1.1))   # 为了保证截图的时候应落稳了，多延迟一会儿


if __name__ == '__main__':
    main()
`

**Comment by Mebigger** [comment]
@zhang07208   第一次还能在根目录看到照片，现在不能了

**Comment by zhang07208** [comment]
@897902334 怎么传，我试了一次显示错误。。。

**Comment by zhang07208** [comment]
@897902334 先凑活看吧，我有事可能要出去一趟。回来再传好的。

`# coding: utf-8
import os
import shutil
import time
import math
from PIL import Image, ImageDraw
import random


# === 思路 ===
# 核心：每次落稳之后截图，根据截图算出棋子的坐标和下一个块顶面的中点坐标，
#      根据两个点的距离乘以一个时间系数获得长按的时间
# 识别棋子：靠棋子的颜色来识别位置，通过截图发现最下面一行大概是一条直线，就从上往下一行一行遍历，
#         比较颜色（颜色用了一个区间来比较）找到最下面的那一行的所有点，然后求个中点，
#         求好之后再让 Y 轴坐标减小棋子底盘的一半高度从而得到中心点的坐标
# 识别棋盘：靠底色和方块的色差来做，从分数之下的位置开始，一行一行扫描，由于圆形的块最顶上是一条线，
#          方形的上面大概是一个点，所以就用类似识别棋子的做法多识别了几个点求中点，
#          这时候得到了块中点的 X 轴坐标，这时候假设现在棋子在当前块的中心，
#          根据一个通过截图获取的固定的角度来推出中点的 Y 坐标
# 最后：根据两点的坐标算距离乘以系数来获取长按时间（似乎可以直接用 X 轴距离）


# TODO: 解决定位偏移的问题
# TODO: 看看两个块中心到中轴距离是否相同，如果是的话靠这个来判断一下当前超前还是落后，便于矫正
# TODO: 一些固定值根据截图的具体大小计算
# TODO: 直接用 X 轴距离简化逻辑


# Magic Number，不设置可能无法正常执行，请根据具体截图从上到下按需设置
under_game_score_y = 300     # 截图中刚好低于分数显示区域的 Y 坐标，300 是 1920x1080 的值，2K 屏、全面屏请根据实际情况修改
press_coefficient = 1.392    # 长按的时间系数，请自己根据实际情况调节
swipe_x1, swipe_y1, swipe_x2, swipe_y2 = 320, 410, 320, 410     # 模拟按压的起始点坐标，需要自动重复游戏请设置成“再来一局”的坐标
piece_base_height_1_2 = 25   # 二分之一的棋子底座高度，可能要调节
piece_body_width = 80       # 棋子的宽度，比截图中量到的稍微大一点比较安全，可能要调节
# 下面的 (353, 859) 和 (772, 1100) 是游戏截图里的两个台子的中点坐标，主要用来算角度，可能要调节
sample_board_x1, sample_board_y1, sample_board_x2, sample_board_y2 = 353, 859, 772, 1100
name = 0

screenshot_backup_dir = 'screenshot_backups/'
if not os.path.isdir(screenshot_backup_dir):
        os.mkdir(screenshot_backup_dir)


def pull_screenshot():
    os.system('adb shell screencap -p /sdcard/' + bytes(name) + '.png')
    os.system('adb pull /sdcard/' + bytes(name) + '.png .')

def backup_screenshot(ts):
    # 为了方便失败的时候 debug
    if not os.path.isdir(screenshot_backup_dir):
        os.mkdir(screenshot_backup_dir)
    shutil.copy(bytes(name) + '.png', '{}{}.png'.format(screenshot_backup_dir, ts))

def save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y):
    draw = ImageDraw.Draw(im)
    draw.line((piece_x, piece_y) + (board_x, board_y), fill=2, width=3)
    del draw
    im.save("{}{}_d.png".format(screenshot_backup_dir, ts))


def jump(distance):
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200 ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input swipe {} {} {} {} {}'.format(swipe_x1, swipe_y1, swipe_x2, swipe_y2, press_time)
    print(cmd)
    os.system(cmd)


def find_piece_and_board(im):
    w, h = im.size

    piece_x_sum = 0
    piece_x_c = 0
    piece_y_max = 0
    board_x = 0
    board_y = 0

    for i in range(h):
        for j in range(w):
            pixel = im.getpixel((j, i))
            # 根据棋子的最低行的颜色判断，找最后一行那些点的平均值，这个颜色这样应该 OK，暂时不提出来
            if (50 < pixel[0] < 60) and (53 < pixel[1] < 63) and (95 < pixel[2] < 110):
                piece_x_sum += j
                piece_x_c += 1
                piece_y_max = max(i, piece_y_max)

    if not all((piece_x_sum, piece_x_c)):
        return 0, 0, 0, 0
    piece_x = piece_x_sum / piece_x_c
    piece_y = piece_y_max - piece_base_height_1_2  # 上移棋子底盘高度的一半

    for i in range(h):
        if i < under_game_score_y:
            continue
        last_pixel = im.getpixel((0, i))
        if board_x or board_y:
            break
        board_x_sum = 0
        board_x_c = 0

        for j in range(w):
            pixel = im.getpixel((j, i))
            # 修掉脑袋比下一个小格子还高的情况的 bug
            if abs(j - piece_x) < piece_body_width:
                continue

            # 修掉圆顶的时候一条线导致的小 bug，这个颜色判断应该 OK，暂时不提出来
            if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 10:
                board_x_sum += j
                board_x_c += 1
        if board_x_sum:
            board_x = board_x_sum / board_x_c
    # 按实际的角度来算，找到接近下一个 board 中心的坐标
    board_y = piece_y - abs(board_x - piece_x) * abs(sample_board_y1 - sample_board_y2) / abs(sample_board_x1 - sample_board_x2)

    if not all((board_x, board_y)):
        return 0, 0, 0, 0

    return piece_x, piece_y, board_x, board_y


def main():
    global name
    while True:
        name = name+1
        pull_screenshot()
        im = Image.open("./" + bytes(name) + ".png")
        # 获取棋子和 board 的位置
        piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
        ts = int(time.time())
        print(ts, piece_x, piece_y, board_x, board_y)
        jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
        save_debug_creenshot(ts, im, piece_x, piece_y, board_x, board_y)
        backup_screenshot(ts)
        time.sleep(random.uniform(1, 1.1))   # 为了保证截图的时候应落稳了，多延迟一会儿


if __name__ == '__main__':
    main()
`

**Comment by 897902334** [comment]
@zhang07208   哥们 我按照这个改了 报错了！
C:\Users\Administrator>cd..

C:\Users>cd..

C:\>wechat_jump_auto.py
  File "C:\wechat_jump_auto.py", line 127
    while True:
              ^
IndentationError: unindent does not match any outer indentation level

C:\>

**Comment by Mebigger** [comment]
@zhang07208 @aqxa  我装上2.7版本了，还是不行。
C:\Python27\python2.exe C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py", line 139, in <module>
    main()
  File "C:/0Docments/python_practise/Wechat_game/wechat_jump_auto.py", line 127, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

是不是adb的事儿，你们的没有乱码吗？我已经把权限都打开了，驱动显示有ADB interfere，adb devices也正常，情绪要崩了。。。

**Comment by zhang07208** [comment]
@897902334 这个问题是python的格式对齐问题，按照提示仔细找一下。估计简单的复制导致空格等出现问题了，。

**Comment by 897902334** [comment]
@zhang07208   老表，  你把文件直接上传上来，   有Google浏览器么？  或者你截个图 我按照你的来写！

**Comment by zhang07208** [comment]
@Mebigger
我前面猜测的也是你adb没装好...你可以试试adb advice，看能检测到手机吗？
乱码问题是ide的原因，需要你设置一下，我用的命令行直接执行的。

**Comment by zhang07208** [comment]
@897902334 嗯，老哥要不等等晚上怎么样^_^。或者对比前面上传的代码，修改的地方不是很多。
被实验室派出来占座，放假也不得安生，，现在只能在这里扣手机。。。非常抱歉啊老哥

**Comment by 897902334** [comment]
@zhang07208   哈哈哈 哥们你先忙吧，不打扰你了！  我先照着你的代码改改！

**Comment by Mebigger** [comment]
@zhang07208 
List of devices attached
e215dbf device  这就是adb没问题吧，我找到另一个和我一样的帖子，正在尝试

**Comment by Mebigger** [comment]
@zhang07208 直接windows powershell 跑就行，但是分不高，只有十几分，不知道为什么

**Comment by Mebigger** [comment]
@zhang07208 终于知道原因了，是因为权限不高，管理员身份运行就行了，但是分数不高，打算调一下系数

**Comment by zhang07208** [comment]
@Mebigger 嗯，好吧，解决了就好^_^
调参数你可以参考有个专门的帖子。

**Comment by 897902334** [comment]
@zhang07208    作者更新代码了，1.png也能用了，  我的就是突破不到130以上，不知道咋回事，   你现在多少分了？

**Comment by Mebigger** [comment]
@zhang07208   正在调，我在尝试读懂这个程序，但是对于初学者的我来说，有点吃力， @897902334 我的最高跑到了400 多，被一个电话中断了

**Comment by 897902334** [comment]
@Mrlilili   哥们 你很666，   你的手机分辨率是？  手机型号？   还有 你修改代码的参数了吗？

**Comment by michelle6147** [comment]
@zhang07208 看你和Mebigger干着急。。。。我也是这和他一样的错误。他说管理员运行就行。这怎么运行啊？我是在Windows上的pycharm运行的。

**Comment by zhang07208** [comment]
@897902334 400多，应该还可以往后跑，我有事先出来了。更新代码怎么解决的呢，这么6

**Comment by michelle6147** [comment]
@zhang07208 我也艾特不了Mebigger他 ， 好想知道怎么弄权限管理员运行

**Comment by zhang07208** [comment]
我参数没变

**Comment by Mebigger** [comment]
@897902334 你是在问我吗，要是的话好像你@错了，那我就假装是，然后手机是米5s，那会参数是1.48
@michelle6147 我一直是pycharm，只是偶然看到了，就试了一下，你以管理身份运行软件就行了。哈哈

**Comment by 897902334** [comment]
@Mebigger   哈哈哈哈  谢谢啦哥们，  突破了我的130大关了  感谢！！！

**Comment by michelle6147** [comment]
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\python.exe E:/wechat_jump_game-master/wechat_jump_auto.py
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "E:/wechat_jump_game-master/wechat_jump_auto.py", line 162, in <module>
    main()
  File "E:/wechat_jump_game-master/wechat_jump_auto.py", line 149, in main
    im = Image.open("./test.png")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './test.png'

Process finished with exit code 1


@zhang07208 我重新打开，管理员运行了 还是和那个谁一样的错误。。。。

**Comment by michelle6147** [comment]
@zhang07208 怎么艾特其他人 ，我这网页端只能艾特你

**Comment by zhang07208** [comment]
@michelle6147 艾特后面跟名字就好

**Comment by michelle6147** [comment]
@Mebigger 求？

**Comment by Mebigger** [comment]
@michelle6147 你把他名字粘贴过来，还不行我真不知道怎么弄了，可能你adb没装好

**Comment by michelle6147** [comment]
@Mebigger 设备管理器上在哪一栏看adb  ？ 我在便携设备和调制解调器这两栏都看到我的手机连上去了“位置 在 SAMSUNG Mobile USB Composite Device  上”

**Comment by Mebigger** [comment]
@michelle6147   https://github.com/wangshub/wechat_jump_game/issues/28
看看这个帖子，网上自己搜搜，我也是新手

**Comment by michelle6147** [comment]
@zhang07208 解决了 是吧adb.exe 和py文件放在C:\Users\Administrator>路径下。用cmd 直接运行就行了。。但是！ 重点！ 我就只有0分。0分啊。我手机是三星S8+  ，18.5:9的比例，这是需要改参数的吧？？？

**Comment by zhang07208** [comment]
@michelle6147 跳了多远呢，有没有输出。我看这个帖子也是说S8不好使 [https://github.com/wangshub/wechat_jump_game/issues/81](url)

**Comment by zhang07208** [comment]
@897902334 兄弟，我回来了。这下不用代码了把，哈哈。我xiaomi 5s plus，1080分辨率，参数没动。基本可以一直跳

**Comment by Mebigger** [comment]
@zhang07208 我再也上不去400了，一直在300一下，米5s，方便加个企鹅吗？1048892788，更好的交流，哈哈

**Comment by zhang07208** [comment]
@Mebigger 用的最新代码吗？哈哈。稍等一下我测试一下。

**Comment by michelle6147** [comment]
@zhang07208 楼主大大 我在改数值，那个二分之一棋子的高度是什么意思，数值都是按像素点数量来的吗？模拟按压的起始坐标为什么是两对x y值，不是开始游戏时棋子的落点坐标xy吗？

**Comment by zhang07208** [comment]
@897902334 兄弟，我看了一下，我的参数这样的。。
![qq 20171230213930](https://user-images.githubusercontent.com/22976539/34454621-effcb06e-eda9-11e7-8251-9f521efb1647.png)

**Comment by michelle6147** [comment]
突然看到了是因为三星手机还可以在设置里该屏幕分辨率。有2K 和1080P 两种，我之前是2K，刚刚改成1080后运行 结果不一样了，成绩还是0，但是第一下蹦的更远了

**Comment by zhang07208** [comment]
@michelle6147  应该都是按像素点来算的。起始坐标不太清楚。我前面看到有模拟器可以显示长度的，但是刚刚找了一下找不到了。

是的，不同分辨率的参数是不同的。你可以参考作者推荐的以及[https://github.com/wangshub/wechat_jump_game/issues/61](url)这个帖子里的

**Comment by michelle6147** [comment]
@zhang07208 404error。。。。。。。。

**Comment by zhang07208** [comment]
@michelle6147 你试一下直接复制。。。

[](https://github.com/wangshub/wechat_jump_game/issues/61)

**Comment by F-loat** [comment]
新版本应该没这个问题了 #288
