### ISSUE TITLE
Traceback (most recent call last):   File "wechat_jump_py3.py", line 1, in <module>     import numpy as np ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by hanzehua521** [wangshub/wechat_jump_game#800]
程序版本号：python wechat_jump_py3.py 免添加adb环境变量
**********
Screen: Physical size: 1080x1920
Density: Physical density: x
Override density: x
DeviceType: 华为荣耀9
OS: Android
Python: 3.6.4
**********
Traceback (most recent call last):
  File "wechat_jump_py3.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

截图![image](https://user-images.githubusercontent.com/30396590/34511910-c5c7e2a8-f099-11e7-9169-0daeebfc8107.png)

改进和建议：无

**Comment by hanzehua521** [comment]
？？？？？？？？？？！！！！！！

**Comment by jiwuming** [comment]
安装这个模块就可以了啊 pip3 install numpy

**Comment by hanzehua521** [comment]
老铁，
这个怎么下不成功？
C:\Users\hanhan\Desktop\wechat_jump_game-master\Tools\adb>pip3 install PIL
Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL

**Comment by bilmeng** [comment]
目前PIL的官方最新版本为1.1.7，支持的版本为python 2.5, 2.6, 2.7，并不支持python3，因此我们用pillow代替，进入DOS命令行窗口，敲入以下代码
pip install pillow就可以了

**Comment by MrLevo520** [comment]
建议使用release打包好的app一键操作

**Comment by wangshub** [comment]
已发布 releases
