### ISSUE TITLE
运行wechat_jump_auto.py会出现一行乱码  但是wechat_jump_py3.py可以正常运行  为什么啊

### ISSUE THREAD

**Issue by wxz199631** [wangshub/wechat_jump_game#802]
2. win10 
3.运行后显示如下
 F:\python\wechat_jump_game-master>python wechat_jump_auto.py
璇峰畨瑁?ADB 鍙婇┍鍔ㄥ苟閰嶇疆鐜鍙橀噺

**Comment by Li-Allen** [comment]
一样是乱马上，但不影响运行

**Comment by Li-Allen** [comment]
一样是乱码，但不影响运行

**Comment by laoluan** [comment]
编码问题

**Comment by wxz199631** [comment]
又人回答一下嘛  编码已经改了

**Comment by MrLevo520** [comment]
请使用最新版代码，当时或许存在2，3兼容性问题，下个版本会进行更新
或者使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases

**Comment by huashanms** [comment]
我的也是有乱码， 应该是编码问题，错误提示是“请安装 ADB 及驱动并配置环境变量".
