### ISSUE TITLE
iPhone6第一步跳出，修改press_coefficient活不过6步

### ISSUE THREAD

**Issue by KevinZK** [wangshub/wechat_jump_game#805]
程序版本号：x.x.x
**********

size: 750, 1334
scan_start_y:  150
1514965510 234.0458452722063 770 684.4404761904761 509.9645385977748
press time: 1.0401418456089009
size: 750, 1334
scan_start_y:  150
1514965513 0 0 0 0

Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x

{
    "under_game_score_y": 200,
    "press_coefficient": 2.0,
    "piece_base_height_1_2": 13,
    "piece_body_width": 49,
    "swipe": {
        "x1": 375,
        "y1": 1055,
        "x2": 375,
        "y2": 1055
    }
}

OS:10.13.1
python:3.6

**********
遇到问题：源config.json 第一步就会跳死，之后修改press_coefficient后第一步能跳到中心，但是跳不过6步就死了

**Comment by Jessefrom1997** [comment]
看这个#675

**Comment by KevinZK** [comment]
@Jessefrom1997    试了一下没有用的

**Comment by Jessefrom1997** [comment]
@KevinZK 你用的那个json文件名是default.json还是iPhone6的json？

**Comment by xiaoxm** [comment]
第一步检测挺准的，接下来就。。
![1514981699_d](https://user-images.githubusercontent.com/11755897/34520344-3abf97c6-f0c3-11e7-96cf-25601e8b1535.png)

![1514981701_d](https://user-images.githubusercontent.com/11755897/34520277-080fee84-f0c3-11e7-9a2a-b249910c0403.png)

![1514981703](https://user-images.githubusercontent.com/11755897/34520304-1f2117c4-f0c3-11e7-9385-05ed7d91da28.png)

**Comment by KevinZK** [comment]
@Jessefrom1997 是6_config.json,按照你的配置修改了里面参数
