### ISSUE TITLE
用手和脚本结合现在也不能上榜了！！！

### ISSUE THREAD

**Issue by t1mkeeper** [wangshub/wechat_jump_game#806]
老铁们，讨论下微信是检测的什么来判断是否将分数上传服务器

**Comment by zzq56** [comment]
不不不，先用手玩到个10几分，然后在运行可以1000多

**Comment by Erimus-Koo** [comment]
上传时候无非就是玩了几局/这局多少分/跳了几下/有没有破纪录
过程当中就不知道了
反正一次跑个几千没有被ban 朋友圈第一就收手了
但如果你没事连着跑8小时 可能就危险了吧

**Comment by t1mkeeper** [comment]
然而，我试过开始用手玩，中间用手玩，结束用手玩，混合花式旋转360度用手和脚本玩，只显示在自己的榜单，好友榜单并没有刷新

**Comment by t1mkeeper** [comment]
然而，我试过开始用手玩，中间用手玩，结束用手玩，混合花式旋转360度用手和脚本玩，只显示在自己的榜单，好友榜单并没有刷新

**Comment by t1mkeeper** [comment]
然而，我试过开始用手玩，<br>中间用手玩，<br>结束用手玩，<br>混合花式旋转360度用手和脚本玩，结果只显示在自己的榜单，好友榜单并没有刷新<br>

**Comment by t1mkeeper** [comment]
如果有兄弟说是显示延迟隔一会就刷新了<br>
抱歉我用另一个微信纯手玩大概20分钟左右就可以刷新<br>
只要加了脚本过一会还是不会刷新在好友的榜单[摊手]

**Comment by helloLI4015** [comment]
不要贪多，500分就可以收手了。

**Comment by huangguozhen** [comment]
@t1mkeeper 程序需要稍微修改一下。改变一下按下位置，还有每次暂停的时间间隔。

**Comment by t1mkeeper** [comment]
@huangguozhen 
没用的，手都加上去了，位置首先不一样了，
我没用自动的，不存在时间间隔相等的问题

**Comment by fzzf0618** [comment]
有谁知道该怎么破，我怀疑是连续命中中心点次数过多，这个要怎么配置好？我是auto的。

**Comment by Lewiskong** [comment]
找到原因了，稍等

**Comment by terieqin** [comment]
@Lewiskong  原因是什么呀？求助

**Comment by Lewiskong** [comment]
@terieqin 详见这篇文章https://zhuanlan.zhihu.com/p/32594563

**Comment by Canace22** [comment]
这每周都会清零的，没玩的话，要想霸榜就得每周刷一次
