### ISSUE TITLE
运行pip install -r requirements.txt的时候出错

### ISSUE THREAD

**Issue by renyi666** [wangshub/wechat_jump_game#809]
![qq 20180103162144](https://user-images.githubusercontent.com/23871827/34513252-5b43e3ec-f0a2-11e7-8e73-8eeed35acea2.png)
运行上边那句代码时，出现这个错误，请问是为什么

**Comment by HughSalvatore** [comment]
实在不行，将common文件夹和对应的wechar_jump*.py复制在Tools\adb目录下,win+r,CMD中切换目录到adb,python *.py即可

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
