### ISSUE TITLE
三星s8测试一步都跳不中

### ISSUE THREAD

**Issue by Gczw** [wangshub/wechat_jump_game#81]
三星s8测试一步都跳不中

**Comment by F5F5** [comment]
要改的参数太多，自动脚本最高跑到了4分，暂时放弃等大牛了

**Comment by wangshub** [comment]
麻烦看一下相关issue哦，里面已经有统计安卓机型的参数啦

**Comment by wangshub** [comment]
https://github.com/wangshub/wechat_jump_game/issues/84

**Comment by Gczw** [comment]
swipe_x1, swipe_y1, swipe_x2, swipe_y2
这四个参赛什么意思麻烦说下我自己测试下

**Comment by peekabooovo** [comment]
我的也是，请问你弄好了吗？

**Comment by Gczw** [comment]
没弄好啊。 @peekabooovo

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
