### ISSUE TITLE
小米Max2的个人修正建议（源码修正，仅限小米max2）

### ISSUE THREAD

**Issue by terieqin** [wangshub/wechat_jump_game#812]
代码版本：不知道怎么查看
使用环境：windows +小米max2
错误：使用给的小米max2的配置文件最多到700+ 。而且什么也改过了。

我发现距离和按压时间不是严格线性的。所以我直接改的源代码。
配置文件里面的press系数改成了1.49。原本是1.5不过应该没有影响。
主要在jump函数里面，添加了以下几行
if press_time < 500:
        press_time += 20
    elif press_time < 600:
        press_time += 10
 以前基本都是很近的距离的时候，并且物体很小的时候容易死。现在好很多。分数上升到了1500.然后死在了一个长距离上面。给出的按压时间大致为970.所以我觉得我还会添加成这样
if press_time < 500:
        press_time += 20
    elif press_time < 600:
        press_time += 10
    elif press_time > 850:
        press_time -= 8
多了对长距离( press_time > 850)的判断。

**Comment by MrLevo520** [comment]
配置文件可以pull request，谢谢
