### ISSUE TITLE
iphone8 自己设置了参数跳到600多，但是其他人看不到记录，只有自己能看到，呵呵

### ISSUE THREAD

**Issue by kakalote2008** [wangshub/wechat_jump_game#813]
程序版本号：1.1.1
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: ios 11
Python: 3.6
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by huangguozhen** [comment]
@kakalote2008 你应该是被微信判断为外挂行为了。所以分数不会显示到朋友得分榜。

**Comment by qq475281441** [comment]
建议添加触摸点随机功能
`cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=random.uniform(100,980),
        y1=random.uniform(300,1400),
        x2=random.uniform(100,980),
        y2=random.uniform(300,1400),
        duration=press_time
    )`
原理：由原来的长按一个点变成了滑动操作。（可能这样不容易被检测）
这行代码位于wechat_jump_auto.py  line91
本人小米5，目前分数1200+，排名正常别人能看见
iphone调成自己对应的分辨率即可。

Y轴对应上方和下方几百像素要去掉，防止点击到最小化和分享按钮。

**Comment by LiXirong** [comment]
@kakalote2008  微信现在有简单的检测功能，防止机器自动刷分。你把延时和滑动位置设置为随机值就可以了，最新版本的就有此功能。

**Comment by kakalote2008** [comment]
多谢各位，我试一下

**Comment by 329463417** [comment]
解决了吗，我也遇到这种情况了

**Comment by chenzuoyuan** [comment]
@qq475281441 验证有效

**Comment by pedoc** [comment]
@kakalote2008 请问你参数怎么设置的

**Comment by kakalote2008** [comment]
增加了随机按压位置，已经修复了，可以绕过微信反作弊，谢谢各位建议

**Comment by qq475281441** [comment]
@chenzuoyuan 我的跳一跳已经被ban了，没法测试。
