### ISSUE TITLE
pip安装那一步出错，requirements文件是完整克隆无编码问题

### ISSUE THREAD

**Issue by liang990219** [wangshub/wechat_jump_game#815]
Could not find a version that satisfies the requirement opencv-python==3.4.0.1
2 (from -r C:\Users\Administrator\Desktop\wechat_jump_game-master\requirements.t
xt (line 6)) (from versions: 3.1.0.5, 3.2.0.6, 3.2.0.7, 3.2.0.8, 3.3.0.9, 3.3.0.
10)
No matching distribution found for opencv-python==3.4.0.12 (from -r C:\Users\Adm
inistrator\Desktop\wechat_jump_game-master\requirements.txt (line 6))

**Comment by chenjiandongx** [comment]
不指定版本安装 opencv-python 试试

**Comment by AzDj** [comment]
重新安装多一次试下，之前也是这样，第二次安装没问题

**Comment by layiw** [comment]
把requirement.text里面的 opencv-python==3.4.0.1 换成下面有的 3.3.0.9版本就好的

**Comment by zkl99999** [comment]
hon==3.3.0.9
Downloading/unpacking opencv-python==3.3.0.9
  Could not find any downloads that satisfy the requirement opencv-python==3.3.0.9
Cleaning up...
No distributions at all found for opencv-python==3.3.0.9
Storing debug log for failure in /root/.pip/pip.log
