### ISSUE TITLE
可以截图，但不会动--已解决

### ISSUE THREAD

**Issue by demonxian3** [wangshub/wechat_jump_game#816]
程序版本号：1.1.1
**********
Screen: Physical size: 1280x720
Density: Physical density: unknow
Override density: unknow
DeviceType: Redmi 4X
OS: MIUI 9.1.1(Windows 7-x86_64)
Python: 3.6.4
**********
遇到问题：如标题在project目录下有截图，但是手机没有反应，执行了的命令如下：
![default](https://user-images.githubusercontent.com/24609511/34513834-3c5041da-f0a5-11e7-9c69-7b33ae41b1b0.png)

后面猜测是否adb的shell input 没有执行，于是手动运行，果然没有反应
![default](https://user-images.githubusercontent.com/24609511/34513898-864b6436-f0a5-11e7-9b21-adda1cb9b8be.png)

所以想请教各位这是因为驱动没安装好，还是缺少了某步骤的配置

【更新】找到原因了

小米的MIUI系统不仅需要开启USB调试，还需要开启USB调试（安全设置），否则无法模拟点击，如下图

![tim 20180103172238](https://user-images.githubusercontent.com/24609511/34514935-bb6a227e-f0aa-11e7-8636-82152a0e9941.png)

开启后会弹出两次警告，点击下一步即可

**Comment by huangguozhen** [comment]
@demonxian3 运行下adb devices看看

**Comment by demonxian3** [comment]
@huangguozhen 
有的，出现结果是ok的不然也不能截图成功
C:\Users\dcn>adb devices
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully
1256dc437d14    device

**Comment by demonxian3** [comment]
我好像知道什么问题了

**Comment by rennianqing** [comment]
小米的MIUI在打开了USB调试后，通过ADB模拟操作的功能还是关闭的，需要打开才可以。

**Comment by demonxian3** [comment]
@rennnianqing
没错就是这个问题，现在解决了，谢谢，刚刚在手机上看了下也发现了

**Comment by demonxian3** [comment]
@huangguozhen 你知道怎么调整成合适自己的 default.json吗，误差有点大，我想自己调整一下

**Comment by charliesunliu** [comment]
@demonxian3 我mix2的话是看刚开始的分辨率，去分辨率对应的文件夹下修改json file的，改成和ip x一样的可以上700
