### ISSUE TITLE
在运行wechat_jump.py文件时出现错误

### ISSUE THREAD

**Issue by Silencetmec** [wangshub/wechat_jump_game#818]
程序版本号：1.1.1
**********
  14 template = cv2.imread('character.png')
---> 15 template = cv2.resize(template, (0, 0), fx=scale, fy=scale)
     16 template_size = template.shape[:2]
     17

error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
**********
遇到问题：（在运行wechat-jump.py时出现问题。）
![]()
改进和建议：无

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
