### ISSUE TITLE
求大神详细解说谢谢啦

### ISSUE THREAD

**Issue by xiaooooooowu** [wangshub/wechat_jump_game#82]
python小白一名
安装了ADB 运行后有设备列表
![default](https://user-images.githubusercontent.com/34955216/34452422-6151fb4c-ed79-11e7-8c6b-e9e2e997ec9d.png)
我用的是python3版本
![default](https://user-images.githubusercontent.com/34955216/34452435-ae7859c0-ed79-11e7-85f0-5efb6c229473.png)
还是出现这种问题 
弄了半天了 
希望大家能耐心跟我讲一讲 跪谢！

**Comment by F5F5** [comment]
你用python3去执行python2的代码，当然会报错

**Comment by xiaooooooowu** [comment]
但是我用python3的那个代码也是这个错误
![default](https://user-images.githubusercontent.com/34955216/34452467-ba65562e-ed7a-11e7-8ea1-2a9127ae8d4a.png)
@F5F5

**Comment by LuckyJQ** [comment]
华为荣耀  同样的问题

**Comment by F5F5** [comment]
引用库装了么
```
pip3 install matplotlib
pip3 install Pillow
```

**Comment by xiaooooooowu** [comment]
安装了 还是同样的报错 @F5F5

**Comment by xiaooooooowu** [comment]
原因会不会在abd上啊

**Comment by xiaooooooowu** [comment]
error: device not found
error: device not found
Traceback (most recent call last):
  File "D:/python_work/微信跳一跳.py", line 25, in <module>
    img = np.array(Image.open('1.png'))
  File "D:\Anaconda3\lib\site-packages\PIL\Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '1.png'
现在的问题是这个了@F5F5
