### ISSUE TITLE
 WDAError(status=13, value=To screenshot a frame, it must have non-0 

### ISSUE THREAD

**Issue by Z-hui** [wangshub/wechat_jump_game#821]
raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

localhost:8100/inspector获取不到Screen 刷新好多次也获取不到

**Comment by xiaoxm** [comment]
感觉是WDA的问题，在XCUIDevice+FBHelpers.m文件的60行下边 重新赋值screenSize宽高后，我这就正常了

**Comment by fusen-github** [comment]
@xiaoxm  请问你重新赋值，screenSize赋值多少？  
我设置的这个screenSize = CGSizeMake(750, 1334);不行啊。

**Comment by xiaoxm** [comment]
@fusen-github   我是iPhone7 设置的screenSize = CGSizeMake(640, 1136); 就正常了

**Comment by xiaoxm** [comment]
对啊，你清下缓存重启Xcode试试呢
