### ISSUE TITLE
这个是什么情况，急急急

### ISSUE THREAD

**Issue by addingzb** [wangshub/wechat_jump_game#823]
MacBook-Pro:wechat_jump_game-master dingzb$ python3 wechat_jump_auto_iOS.py
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 199, in <module>
    main()
  File "wechat_jump_auto_iOS.py", line 177, in main
    pull_screenshot()
  File "wechat_jump_auto_iOS.py", line 61, in pull_screenshot
    c.screenshot('1.png')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 295, in screenshot
    value = self.http.get('screenshot').value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

(
	0   CoreFoundation                      0x00000001915581d8 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018ff9055c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000191558094 <redacted> + 0
	3   Foundation                          0x0000000191fe282c <redacted> + 112
	4   XCTest                              0x000000010016006c -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192
	5   XCTest                              0x000000010015ff38 -[XCUIScreen screenshotDataForQuality:rect:error:] + 108
	6   WebDriverAgentLib                   0x000000010244b234 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 624
	7   WebDriverAgentLib                   0x000000010242cd14 +[FBScreenshotCommands handleGetScreenshot:] + 132
	8   WebDriverAgentLib                   0x0000000102439968 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	9   WebDriverAgentLib                   0x0000000102431594 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	10  RoutingHTTPServer                   0x00000001024ea3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	11  RoutingHTTPServer                   0x00000001024eab80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	12  libdispatch.dylib                   0x00000001903e11c0 <redacted> + 16
	13  libdispatch.dylib                   0x00000001903f20c4 <redacted> + 320
	14  libdispatch.dylib                   0x00000001903e11c0 <redacted> + 16
	15  libdispatch.dylib                   0x00000001903e5d6c _dispatch_main_queue_callback_4CF + 1000
	16  CoreFoundation                      0x0000000191505f2c <redacted> + 12
	17  CoreFoundation                      0x0000000191503b18 <redacted> + 1660
	18  CoreFoundation                      0x0000000191432048 CFRunLoopRunSpecific + 444
	19  Foundation                          0x0000000191f40b1c <redacted> + 304
	20  WebDriverAgentLib                   0x0000000102430588 -[FBWebServer startServing] + 424
	21  WebDriverAgentRunner                0x000000010241fbe4 -[UITestingUITests testRunner] + 132
	22  CoreFoundation                      0x000000019155e160 <redacted> + 144
	23  CoreFoundation                      0x0000000191451c3c <redacted> + 284
	24  XCTest                              0x000000010014a654 __24-[XCTestCase invokeTest]_block_invoke.275 + 48
	25  XCTest                              0x000000010014a404 __24-[XCTestCase invokeTest]_block_invoke + 680
	26  XCTest                              0x00000001001909d8 -[XCUITestContext performInScope:] + 208
	27  XCTest                              0x000000010014a14c -[XCTestCase invokeTest] + 136
	28  XCTest                              0x000000010014b224 __26-[XCTestCase performTest:]_block_invoke.382 + 48
	29  XCTest                              0x0000000100195a78 +[XCTContext runInContextForTestCase:block:] + 164
	30  XCTest                              0x000000010014ac20 -[XCTestCase performTest:] + 596
	31  XCTest                              0x0000000100146e14 __27-[XCTestSuite performTest:]_block_invoke + 288
	32  XCTest                              0x000000010014683c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	33  XCTest                              0x0000000100146a4c -[XCTestSuite performTest:] + 236
	34  XCTest                              0x0000000100146e14 __27-[XCTestSuite performTest:]_block_invoke + 288
	35  XCTest                              0x000000010014683c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	36  XCTest                              0x0000000100146a4c -[XCTestSuite performTest:] + 236
	37  XCTest                              0x0000000100146e14 __27-[XCTestSuite performTest:]_block_invoke + 288
	38  XCTest                              0x000000010014683c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	39  XCTest                              0x0000000100146a4c -[XCTestSuite performTest:] + 236
	40  XCTest                              0x000000010019f484 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44
	41  XCTest                              0x0000000100159994 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 420
	42  XCTest                              0x000000010019f300 -[XCTTestRunSession runTestsAndReturnError:] + 292
	43  XCTest                              0x00000001001363d4 -[XCTestDriver runTestsAndReturnError:] + 312
	44  XCTest                              0x0000000100194c20 _XCTestMain + 620
	45  CoreFoundation                      0x0000000191506160 <redacted> + 20
	46  CoreFoundation                      0x000000019150595c <redacted> + 288
	47  CoreFoundation                      0x00000001915037b0 <redacted> + 788
	48  CoreFoundation                      0x0000000191432048 CFRunLoopRunSpecific + 444
	49  GraphicsServices                    0x0000000192eb5198 GSEventRunModal + 180
	50  UIKit                               0x000000019740c628 <redacted> + 684
	51  UIKit                               0x0000000197407360 UIApplicationMain + 208
	52  WebDriverAgentRunner-Runner         0x0000000100010444 WebDriverAgentRunner-Runner + 33860
	53  libdyld.dylib                       0x00000001904145b8 <redacted> + 4
))

**Comment by sctop** [comment]
换个版本吧，3.0和2.7的部分代码是不同的。

**Comment by addingzb** [comment]
我现在用的是3.6的版本

**Comment by Z-hui** [comment]
同问啊卡这一下午了

**Comment by addingzb** [comment]
我也是卡这儿了，实在搞不定了

**Comment by sctop** [comment]
换下2.7

**Comment by wadekun** [comment]
急，贝贝贝贝。。。

你的WebDriverAgentLib信任证书配置对了吗，WebDriverAgent启动正常吗？

**Comment by addingzb** [comment]
对了的，WebDriverAgent都能启动，在手机home界面，可以截图，一旦打开应用，执行python就会报以上的错误。我不知道什么原因。

**Comment by hhuizhang** [comment]
@addingzb 请问你描述的问题解决了吗？我碰到和你一模一样的问题。
