### ISSUE TITLE
cmd  = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format

### ISSUE THREAD

**Issue by wongdaiv** [wangshub/wechat_jump_game#826]
#版本
程序版本号：1.1.1
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: GT-N7100
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]

#问题描述
1514972312 225 739 525.5 566
adb shell input swipe 337 1051 337 1051 714
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [duration(ms)]
       input trackball press
       input trackball roll <dx> <dy>

#修改
遇到上述问题 修改cmd命令为 ：adb shell input touchscreen swipe

**Comment by binderclip** [comment]
系统版本是旧的吧？

**Comment by wongdaiv** [comment]
@binderclip 4.3的

**Comment by MrLevo520** [comment]
请尝试新版release的app，或者使用adb免安装版

**Comment by voghDev** [comment]
`adb shell input touchscreen swipe` instead of `input swipe` is your problem
