### ISSUE TITLE
default.json中这样测量对吗？

### ISSUE THREAD

**Issue by demonxian3** [wangshub/wechat_jump_game#829]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无
![default](https://user-images.githubusercontent.com/24609511/34516645-9f47876e-f0b2-11e7-885b-e3cd1951029d.png)

**Comment by moyuandian66** [comment]
我已经弄好了，你给他自己跑，开始就只能到第四步，后来就多了

**Comment by demonxian3** [comment]
66666，OK

**Comment by demonxian3** [comment]
@moyuandian66 不过我还是想知道我这样子测量正确吗？截图更新在主文当中了

**Comment by demonxian3** [comment]
我看有人有摄像头来判断，精确度很高跑到30000多分，结合人工智能感觉会屌屌的

**Comment by moyuandian66** [comment]
感觉这参数是有问题，刚测试了10分钟，多的跑70几，少的3步死，我用的1440*720分辨率。
x1,x2,y1,y2代表跳之前和之后的坐标吧
