### ISSUE TITLE
关于图片的路径

### ISSUE THREAD

**Issue by LuckyJQ** [wangshub/wechat_jump_game#83]
手机没有sd卡，华为的   需要修改图片路径吗？怎么改？

**Comment by LuckyJQ** [comment]
<img width="448" alt="_20171230161054" src="https://user-images.githubusercontent.com/23555100/34452508-192f26e8-ed7c-11e7-98cd-867450c1c96f.png">

**Comment by abcd106** [comment]
同是这个问题

**Comment by MoonChasing** [comment]
同问，找不到1.png

**Comment by pplps** [comment]
/storage/emulated/0

**Comment by LuckyJQ** [comment]
@pplps 不对啊。。

**Comment by abcd106** [comment]
@pplps 你那个路径完整是咋样的

**Comment by xiaooooooowu** [comment]
一模一样的错误

**Comment by ZZYuting** [comment]
windows的话改成d:\1.png

**Comment by kokozeng** [comment]
这样改
def pull_screenshot():
    #os.system('adb shell screencap -p /sdcard/1.png')
    #os.system('adb pull /sdcard/1.png .')
    os.system("adb shell screencap -p | sed 's/\r$//' > 1.png")

**Comment by LuckyJQ** [comment]
最后发现不是路径错误  是我adb没配好   把adb路径加到环境变量里就好了
