### ISSUE TITLE
adb: error: failed to get feature set: no devices/emulators found 暂不支持当前设备

### ISSUE THREAD

**Issue by wzx011011** [wangshub/wechat_jump_game#830]
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确
定开始？ y/n [y]: y
程序版本号：1.1.1
**********
Screen: Physical size: 1440x2560
Override size: 1080x1920
Density: Physical density: 640
Override density: 480
DeviceType: SM-G9350
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)
]
**********
error: no devices/emulators found
error: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
暂不支持当前设备
请问已经检测到了设备类型，为什么还是会提示不支持当前设备呢

**Comment by wzx011011** [comment]
没执行过呢，是哪个命令

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases

**Comment by wzx011011** [comment]
打开one_step_auto_beta1.exe之后，过一会adb.exe停止工作；

**Comment by hejun041** [comment]
这个一键，找不到device 然而源码版就可以跳
