### ISSUE TITLE
暂不支持当前设备

### ISSUE THREAD

**Issue by Sniper970119** [wangshub/wechat_jump_game#833]
https://github.com/wangshub/wechat_jump_game/pull/825 
 之前的很多版本都可以用，但是这个AI的就不可以，显示暂不支持当前设备，我改过文件，也从客户端直接下了一个，都是这个提示

**Comment by Sniper970119** [comment]
@F-loat

**Comment by F-loat** [comment]
你之前是使用方法几获取截图的，AI版的这个函数有些修改，导致不兼容

**Comment by Sniper970119** [comment]
额 方法几？ 我用过初始版本的wechat_jump_auto.py  之后用的几个版本应该都是这个方法的衍生版

**Comment by F-loat** [comment]
获取截图的方式，不同电脑会有一些差异，目前的程序运行时会输出可行的方式是哪个

**Comment by Sniper970119** [comment]
def pull_screenshot()  (wechat_jump_game-master - wechat_jump_auto.py     51)
def pull_screenshot()  (wechat_jump_game-master - wechat_jump_py3.py       9  )

**Comment by Sniper970119** [comment]
我知道你说的是啥了 之前是3 现在是2

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/34517259-42dfa0f8-f0b5-11e7-9d34-9bff6057d67b.png)
可以运行的版本提供下这个信息

**Comment by F-loat** [comment]
你想测试可以自己修改试下

**Comment by Sniper970119** [comment]
额 是采取方式1 获取截图 那现在是还不支持方式1是么
@F-loat

**Comment by F-loat** [comment]
现在兼容处理覆盖不完全

**Comment by Sniper970119** [comment]
在哪能看到版本更新说明啊  底下的conversation会说吗
@F-loat

**Comment by F-loat** [comment]
[changelog](https://github.com/wangshub/wechat_jump_game/blob/master/changelog.md) AI版合并之后会更新下，这个目前好像也不是新的。。

**Comment by F-loat** [comment]
文档到时会更新的
