### ISSUE TITLE
依赖安装失败

### ISSUE THREAD

**Issue by dabingrunning** [wangshub/wechat_jump_game#838]
Command python setup.py egg_info failed with error code 1 in /private/var/folders/zg/yvy_b6sn0wj9cg41x_w4ypcr0000gp/T/pip_build/matplotlib

不清楚什么问题

**Comment by mkblbj** [comment]
@dabingrunning 你装了matplotlib依赖了嘛

**Comment by dabingrunning** [comment]
@mkblbj 就是在安装这一步出错了

**Comment by xinlehou** [comment]
sudo python -m pip install --upgrade pip
http://blog.csdn.net/soindy/article/details/71108356
