### ISSUE TITLE
自从用了这个程序，我的两个微信号的跳一跳都被封掉了

### ISSUE THREAD

**Issue by StormPhoenix** [wangshub/wechat_jump_game#845]
入坑需谨慎。

**Comment by haohaitao** [comment]
你跳了多少？

**Comment by StormPhoenix** [comment]
一个号跳了１４５５，另外一个号跳了５３５。。。之后不管我跳了多少分数，都无法上排行榜了。从你好友的排行榜上看，是没有你的排名显示的。

**Comment by yyl10** [comment]
你跳的太多了

**Comment by Canace22** [comment]
2800多。。坐等被封号

**Comment by coderchaser** [comment]
真的会被封号吗？我挑了1200，只是想试一试。

**Comment by WokoLiu** [comment]
前天跳了3000，我就及时收手了，现在都是用小号测试的...

**Comment by LiXirong** [comment]
兄弟，我昨天跳了个1W多的，今天跳了个3W多的，虽然都没在排行榜上更新，但是晚上刷了两个四千多一个五千多都更新了，没你说的被封号啊。自己把延时和触点改成随机值就行了。

**Comment by Canace22** [comment]
刚刚去看了看别人的手机，2800+在排行榜上，暂时没有出现封号现象，不过同学说这个游戏每周都会清零，重新开始，所以要想霸榜就得每周都刷一次

**Comment by jangdelong** [comment]
何必呢

**Comment by yuyu0411** [comment]
小白求问怎么设置延时和触电成随机值ಥ_ಥ

**Comment by gkgy** [comment]
我一会能连上，一会连不上。。。。

**Comment by codewpf** [comment]
跳一跳应该做了屏幕检测，如果发现有作弊就不让你上传分数。我的号现在只有使用脚本弄的就都上传不了分数了，我也就跳了500多。
