### ISSUE TITLE
OSError: cannot identify image file './autojump.png' ![]()错误

### ISSUE THREAD

**Issue by a1953176613** [wangshub/wechat_jump_game#847]
程序版本号：x.x.x(我不知道是什么, 请谅解 , 新手...)
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OPPO R9 Plusm A
OS: win32
Python: 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
**********
遇到问题：
打印错误:
OSError: cannot identify image file './autojump.png'![]()
改进和建议：无

整个命令行过程:
Microsoft Windows [版本 10.0.16299.125]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\19531>cd C:\Users\19531\Downloads\ 微信跳一跳\wechat_jump_game-master

C:\Users\19531\Downloads\ 微信跳一跳\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from C:\Users\19531\Downloads\ 微信跳一跳\wechat_jump_game-master/config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OPPO R9 Plusm A
OS: win32
Python: 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
**********
List of devices attached
4f29ee37        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "D:\Anaconda\Anaconda\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

C:\Users\19531\Downloads\ 微信跳一跳\wechat_jump_game-master>

**Comment by MrLevo520** [comment]
路径中不要出现中文
