### ISSUE TITLE
S7edge 怎么调也不准，我就直接观察发现每次都多跳那么几个像素点，我就直接将distance 变量减掉和增加最小跳的时间

### ISSUE THREAD

**Issue by yyl10** [wangshub/wechat_jump_game#848]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by yyl10** [comment]
def jump(distance):
    '''
    跳跃一定的距离
    '''
    distance   = distance - 35
    press_time = distance * press_coefficient
    press_time = max(press_time, 270)   # 设置 200ms 是最小的按压时间

**Comment by KingAckerman** [comment]
去掉了侧屏，{
    "under_game_score_y": 300,
    "press_coefficient": 1,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,
    "swipe" : {
      "x1": 716,
      "y1": 2100,
      "x2": 716,
      "y2": 2100
    }
}
测试s7edge可以用

**Comment by NUAA-CMEE** [comment]
楼上的可以用，但是分数不高。跳的不准
