### ISSUE TITLE
有人想过用卷积神经网络来找点吗

### ISSUE THREAD

**Issue by dayeguilaiye** [wangshub/wechat_jump_game#849]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：

是这样的，想了一下，这个东西如果用神经网络去找的话应该准确率会相当高，毕竟特征太简单了，不过问题在于标注会很麻烦。
想了一个简单的解决办法是这样：用当前的检测手段找点，然后将图片截图并将点的坐标记录下来，然后让程序跳，跳完了如果没有结束游戏，那么说明这个点应该是正确的，至少不会错太远，这样就能得到大量的带有标注训练数据，接下来就是构建网络和训练了。。。感觉好像可行性还行

**Comment by misteriers** [comment]
用DQN肯定可以

**Comment by myuanz** [comment]
不 神经网络精确度更低 ,https://github.com/zhanyongsheng/LetsJump .
不过我正在尝试使用更多更漂亮的数据来训练
