### ISSUE TITLE
求华为p10 plus 1440x2560系数

### ISSUE THREAD

**Issue by SindaYan** [wangshub/wechat_jump_game#851]
求华为p10 plus 1440x2560系数

**Comment by TianTianUp1024** [comment]
+1

**Comment by lxidea** [comment]
+1

**Comment by captorr** [comment]
press_coefficient = 1.04
piece_base_height_1_2 = 26
piece_body_width = 110

**Comment by lxidea** [comment]
{
    "under_game_score_y": 300, 
    "press_coefficient": 1.392, 
    "piece_base_height_1_2": 20, 
    "piece_body_width": 70
}
