### ISSUE TITLE
小米手机都不行，跳几步就死了

### ISSUE THREAD

**Issue by Heyxiang** [wangshub/wechat_jump_game#853]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********
遇到问题：（请说清楚自己遇到了啥问题，不然可能被 close。还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。）
![]()
改进和建议：无

**Comment by ultraxia** [comment]
小米6+Win10使用下来表示没问题

**Comment by ThinkPeace** [comment]
米4 破千

**Comment by Huoshortsun** [comment]
我的小米note2  不太行，走四十多步就不行了

**Comment by YangZhengtian** [comment]
mi6+win10 200多就over了 怎么改参数 @ultraxia

**Comment by fujianhui** [comment]
@ultraxia @YangZhengtian 我也是小米6 到200就over

**Comment by ahong007007** [comment]
我的是小米max，MIUI 9.1,100多步就挂了

**Comment by ultraxia** [comment]
没有修改过参数……直接运行跳到2000分无压力@YangZhengtian

**Comment by hoanX** [comment]
mi6 ,跳了500多没问题，没刷太多

**Comment by McJevons** [comment]
Mi4，最多150就挂了，用default和1920x1080配置都试过，大多数时候都是跳在方块边缘，提心吊胆的

**Comment by McJevons** [comment]
@ThinkPeace 你用的什么版本程序？

**Comment by zhangvoice** [comment]
Mi4 谁有配置发一下吧，最多150就要挂。。。1920x1080 配置过还是不行。

**Comment by RaeZhang0822** [comment]
Mi4c 用1920×1080配置，"press_coefficient"改成1.57，试了一下可以上250

**Comment by McJevons** [comment]
@zhangvoice 以下配置Mi4每次500没问题，最多800+后怕被ban不敢继续了
{
"under_game_score_y": 300,
"press_coefficient": 1.5,
"piece_base_height_1_2": 25,
"piece_body_width": 80
}

**Comment by zhangvoice** [comment]
@McJevons ，谢谢，我试试，我朋友的 vivo x7,使用1920*1080 配置，随便上千。

**Comment by hujlin** [comment]
米4还没两步就死了，有谁遇到过吗？最好的成绩是17。。。
