### ISSUE TITLE
有没有人教下如何调config.json里的参数，红米4x的

### ISSUE THREAD

**Issue by demonxian3** [wangshub/wechat_jump_game#854]
所有分辨率手机型号的配置文件都试过了，也尝试自己去更改，但是每次跳都是跳少（近）了，想自己调整参数来尝试，但是哪些需要调整哪些不需要，如何调，有没有人教下

**Comment by knoxhy** [comment]
我也是4x，你跳了多少

**Comment by Imcoding-optn** [comment]
"under_game_score_y": 200,
    "press_coefficient": 5.56,
    "piece_base_height_1_2": 13.5,
    "piece_body_width": 50,




press_time = math.pow(distance,0.85) * press_coefficient
上面的函数是别人的  在issue里  自己去找找吧

**Comment by willsonn** [comment]
@Imcoding-optn 不行啊，0步

**Comment by MrLevo520** [comment]
请尝试使用nightly版本，无需分辨率配置自适应

**Comment by zlx** [comment]
关注一下
