### ISSUE TITLE
阅读代码之后有几个问题想请教

### ISSUE THREAD

**Issue by cuijier** [wangshub/wechat_jump_game#857]
想咨询Author几个问题，好像只能在issues中commit了
1，扫描旗子的坐标和底座的坐标时限制了扫描范围，这个范围是根据发现的规律做限制的吗？比如为什么纵坐标是1/3 到2/3之间。
2，距离和时间的关系这个是怎么发现的，1.373这个系数是怎么发现的，根据大量测试吗？
3，train_data里面的截图是如何利用的？
4，根据颜色色差来定位底盘的坐标，这个是根据取色器发现的规律吗？

如上疑问，希望有大神能帮忙解答下奥。

**Comment by helloLI4015** [comment]
@weiqiu 
1.棋子和下一跳的一般情况下，只会出现在1/3-2/3高度的地方。减少cpu计算
2.距离和时间的关系，可以调整。不同手机的分辨率、屏幕尺寸大小不同，根据不同手机做调整，取最佳值
3.train_data里的数据，没有使用。程序扫描图片的像素点，y轴从1/3h-2/3h（由下到上），x轴从左到右，出现大量像素点为黑色，则认为是棋子。
4.跳一跳界面比较简单，元素内容颜色单调，

**Comment by Darkxiete** [comment]
我也想算算 距离=f(时间) 这个公式 
1.373我觉得更多的应该是经验公式。
棋子每次跳都会在棋盘中线的位置，然后棋盘一共有两个中线，每次跳其实都是个斜边距离，不知道我说的是不是有点懵啊。。就是想说下。。

**Comment by helloLI4015** [comment]
华为荣耀8是1.04，iPhone6是:2.0，iPhoneX 是：1.3
确实是经验公式，连上你的手机，调整这个参数，能跳中中心点，就行

**Comment by gongzelong0718** [comment]
@helloLI4015 
如何调整这个参数的呢，有test case吗？我感觉应该有个test case来根据不同的参数，然后把图片的两个点标识出来，您找到了吗？

**Comment by helloLI4015** [comment]
多试几次，就知道了。取最大值，最小值，中间值。
不用试10次就出结果了。
@gongzelong0718

**Comment by weiqiu** [comment]
@helloLI4015 @Darkxiete @simpleton 在找那个board的横坐标时，判断主要用的是如下这个条件。他是判断如果颜色和坐左边的颜色差超过10就认为是board的区域吗？
if abs(pixel[0] - last_pixel[0]) + abs(pixel[1] - last_pixel[1]) + abs(pixel[2] - last_pixel[2]) > 10:
