### ISSUE TITLE
从右向左跳的时候，不准确，求教

### ISSUE THREAD

**Issue by maxlxq** [wangshub/wechat_jump_game#86]
时间有没有影响？

**Comment by wangshub** [comment]
能详细描述一下吗，或者出问题的截图 @maxlxq

**Comment by ipocky** [comment]
@wangshub 我也是这个问题，往右跳正常，往左跳每次都是按压时间很短轻轻一跳。
像这样：
2691 KB/s (60645 bytes in 0.022s)
(1514624637, 338, 1104, 1079, 678)
adb shell input swipe 320 410 320 410 716
1956 KB/s (68106 bytes in 0.034s)
(1514624647, 774, 1093, 1079, 918)
adb shell input swipe 320 410 320 410 294

第一次向右正常，第二次向左，每次向左都只有200多

**Comment by SunMingjun** [comment]
我的情况相同，求教，向左跳计算的按压参数只有200+

**Comment by ipocky** [comment]
@wangshub 
补图
向右
![1](https://user-images.githubusercontent.com/34957898/34453286-61f502da-ed8b-11e7-8575-59014696fe93.png)

向左
![2](https://user-images.githubusercontent.com/34957898/34453288-70bfc69c-ed8b-11e7-9ed6-039ab7362f29.png)

**Comment by SunMingjun** [comment]
PS C:\Program Files\python2.7> python .\wechat_jump_auto.py
2464 KB/s (95303 bytes in 0.037s)
(1514635057, 1167, 1523, 1436, 1369)
309.962901006
adb shell input swipe 320 410 320 410 204

309是打印出来的distance

同样是 S7 edge， 右跳左有问题


![1](https://user-images.githubusercontent.com/11511937/34454014-60bd2e72-ed9c-11e7-84db-9d74af165f0a.png)

**Comment by ipocky** [comment]
@SunMingjun 
从坐标来看，就算实际下个平台在左边，计算出的坐标却是在棋子右边
要是作者把计算过程的变量也加上注释就能自己改了..
对python一窍不通看不懂
@wangshub

**Comment by gdw1986** [comment]
同s7e，右跳还可以调调，左跳就距离有问题，特别短

**Comment by SunMingjun** [comment]
右跳距离短的时候有问题，会跳出去，
左跳距离短正常，距离长就出错

**Comment by peekabooovo** [comment]
我的也是，好烦啊，请问解决了吗？

**Comment by SunMingjun** [comment]
知道原因了，由于开了侧边栏，关掉就好了！

**Comment by SunMingjun** [comment]
S7 S8 EDGE的关掉侧边栏测测参数，看下什么参数合适

**Comment by SunMingjun** [comment]
under_game_score_y = 390  
press_coefficient = 1.07  
piece_base_height_1_2 = 26 
piece_body_width = 110  

目前该的这个参数，看下能不能再调下

**Comment by ipocky** [comment]
@SunMingjun 关了侧栏果然好了
