### ISSUE TITLE
华为荣耀V8(knt-al20)使用达不到预期效果

### ISSUE THREAD

**Issue by Warframe2017** [wangshub/wechat_jump_game#860]
华为荣耀V8(knt-al20)使用新版无法成功跳到第二个方块 在第一个方块向第二个方块跳时   会因点按时间过长直接飞出第二个方块   周一的版本可以正常使用
![a](https://user-images.githubusercontent.com/31060131/34524103-394c0cbe-f0d5-11e7-8b08-bb65f0d3824f.png)
Screen: Physical size: 1440x2560
Density: Physical density: 500
DeviceType: KNT-AL20
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

**Comment by cjzhangchn** [comment]
我的也是V8，同样出现这个问题，后来发现是因为2560X1400的config被修改了，恢复原来的即可使用

{
    "under_game_score_y": 300,
    "press_coefficient": 1.035,
    "piece_base_height_1_2": 28,
    "piece_body_width": 110,
    "swipe": {
        "x1": 320,
        "y1": 410,
        "x2": 320,
        "y2": 410
    }
}
