### ISSUE TITLE
修改那个参数可以修改停留时间啊

### ISSUE THREAD

**Issue by 755966092** [wangshub/wechat_jump_game#866]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by chldong** [comment]
建议修改成范围内随机取值😈

**Comment by 755966092** [comment]
修改哪一个值啊

**Comment by amesshen** [comment]
main()中的time.sleep(random.uniform(1, 2))

**Comment by 755966092** [comment]
haode  谢谢 我试试
