### ISSUE TITLE
安装requierment.txt失败

### ISSUE THREAD

**Issue by fantasy525** [wangshub/wechat_jump_game#869]
+ **win7 64位**
+ **python:3.6.3**
+ **pip:9.0.1**
+ ## 报错截图 ##
![image](https://user-images.githubusercontent.com/22516157/34526151-86791ff2-f0dc-11e7-9b1a-10658a6c5e91.png)

**Comment by F-loat** [comment]
管理员权限执行试下

**Comment by doubleJJJJ** [comment]
我也出现错误了，好像是超时？

**Comment by totzcc** [comment]
```
pip install -r requierment.txt --user -U
```

**Comment by smilevent** [comment]
直接用anaconda吧

**Comment by fantasy525** [comment]
嗯应该是网络超时了，在公司网络好的情况下试了试没问题了。本人小米6，win10系统测试可以自动跳
