### ISSUE TITLE
小米MIUI的悬浮球会影响，会被识别成board~~~

### ISSUE THREAD

**Issue by Neutree** [wangshub/wechat_jump_game#873]
程序版本号：1.1.1
**********

**机型**：小米5

DeviceType: Android
OS: MIUI9
Python: >=3.6
**********

遇到问题：
悬浮球会影响
![image](https://user-images.githubusercontent.com/8625829/34527835-dc962ff6-f0e1-11e7-8cb2-c6635fe21d94.png)

改进和建议：看了源码，自己改很简单，所以改不改进无所（不建议改进），正好让伸手党用不了~~~

**Comment by MrLevo520** [comment]
年轻人，这种想法很危险啊😏😏

**Comment by INtEReSTiNg1234** [comment]
啊哈哈哈直接拖下去不就行了吗

**Comment by Neutree** [comment]
啊哈哈哈是滴，关闭也行，就说说而已~~~

**Comment by mikuily** [comment]
我的米4就是悬浮球没关，次次都跳到悬浮球那里23333

**Comment by datty258** [comment]
小米必须要吧悬浮球去掉才能正常跳
