### ISSUE TITLE
Xcode遇到这个问题Runner[284:11767] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230

### ISSUE THREAD

**Issue by mkblbj** [wangshub/wechat_jump_game#879]
Xcode错误，无法截图！
Runner[284:11767] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230
有遇到的吗

**Comment by meilbn** [comment]
一样的错误。

```
To screenshot a frame, it must have non-0 area.
```

试过很多次，都不行。

**Comment by LucasPiazon** [comment]
升级xcode到最新

**Comment by meilbn** [comment]
@LucasPiazon Xcode 9.2 的
