### ISSUE TITLE
图片不对，弄了一下午，蹦跶不了八下，............

### ISSUE THREAD

**Issue by wangheng001** [wangshub/wechat_jump_game#88]
![1514625125_d](https://user-images.githubusercontent.com/34469052/34452955-b4620010-ed84-11e7-821b-7f929f2d56cf.png)
![1514625053_d](https://user-images.githubusercontent.com/34469052/34452956-b4ad5128-ed84-11e7-8dc2-bc162a43ffa7.png)
![1514625063_d](https://user-images.githubusercontent.com/34469052/34452957-b4e34eae-ed84-11e7-9cb7-3476e153bfc1.png)
![1514625073_d](https://user-images.githubusercontent.com/34469052/34452958-b519e1c6-ed84-11e7-8c1d-353b4f7d7aa1.png)
![1514625083_d](https://user-images.githubusercontent.com/34469052/34452959-b54c6696-ed84-11e7-91cb-ced598188767.png)
![1514625093_d](https://user-images.githubusercontent.com/34469052/34452960-b57d607a-ed84-11e7-9ff8-069495c879e2.png)
![1514625104_d](https://user-images.githubusercontent.com/34469052/34452961-b5b011fa-ed84-11e7-952f-9392403a30ce.png)
![1514625115_d](https://user-images.githubusercontent.com/34469052/34452962-b5e320fe-ed84-11e7-9523-221e88600cd6.png)

**Comment by wangheng001** [comment]
老是重复，心累

**Comment by nicky918** [comment]
这就是他算法的缺点所在。他算错的时候会一直错下去

**Comment by wangheng001** [comment]
这个是一图片连续出现好多次，感觉它同时运行了两遍，或者两遍以上

**Comment by 1programmer2dfg3** [comment]
请问你这个图片是咋显示出来的？

**Comment by abcd106** [comment]
老哥  执行了wechat_jump_auto.py 游戏不会动，cmd也没继续执行下去怎么回事啊

**Comment by wangshub** [comment]
已经发布安卓手机免安装release，请移步这里下载 [releases](https://github.com/wangshub/wechat_jump_game/releases)
