### ISSUE TITLE
图像检测bug

### ISSUE THREAD

**Issue by hanswang** [wangshub/wechat_jump_game#880]
![image](https://user-images.githubusercontent.com/1825644/34541046-e8b8c066-f12a-11e7-9b9d-b8834a377a73.png)

程序版本号：x.x.x
**********
Screen: Physical size: 2160x1080
Density: Physical density: x
Override density: x
DeviceType: mix2
OS: MacOS
Python: 2.7
**********

遇到问题：
跳跃中心点偏差。

改进和建议：中心点检测方法进一步增强。

**Comment by helloLI4015** [comment]
白色阴影干扰的问题？
