### ISSUE TITLE
是不是用这代码对android版本有要求

### ISSUE THREAD

**Issue by fanliugen** [wangshub/wechat_jump_game#882]
程序版本号：1.1.1
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: android4.2
Python: 2.7
**********

遇到问题：我的系统版本是4.2的，现在跑的时候，老是提示swipe命令参数不对？
还有是adb shell wm size 也无法识别。

改进和建议：无

**Comment by mengDTT** [comment]
@fanliugen 先用`adb devices`看一下手机是否连接成功

**Comment by z-jingjie** [comment]
是的，至少需要4.3版本的安卓系统，4.2版本的安卓input不支持duration参数，无法通过该命令直接模拟出长按效果，请看[本人此前反馈的issue，内附相关Java源码](https://github.com/wangshub/wechat_jump_game/issues/657#issuecomment-354844797)
