### ISSUE TITLE
小米6卫生纸识别位置错误

### ISSUE THREAD

**Issue by ychda** [wangshub/wechat_jump_game#884]
![1515027109_d](https://user-images.githubusercontent.com/3352014/34546574-b9c97822-f12f-11e7-8440-bdbf1b80bd99.png)
![1515028154_d](https://user-images.githubusercontent.com/3352014/34546575-ba0a27d2-f12f-11e7-91e5-9f1c19846444.png)

**Comment by wres13** [comment]
你的参数是多少
