### ISSUE TITLE
小米5s自己不跳

### ISSUE THREAD

**Issue by czfSaber** [wangshub/wechat_jump_game#886]
代码能启动成功,也能找到设备,就是游戏不自己跳;手机是小米5s的;请问怎么回事

**Comment by superlagrange** [comment]
没开启模拟点击？

**Comment by czfSaber** [comment]
开了,是不是配置文件有问题??

**Comment by czfSaber** [comment]
我看着只有mi5,mi5x,mi6和Noto2的json文件,没有5s的

**Comment by czfSaber** [comment]
控制台是有输出的,usb调试也开了

**Comment by superlagrange** [comment]
两个USB调试模式都得打开

**Comment by superlagrange** [comment]
小米5s还得改数据，不然最多不过150

**Comment by czfSaber** [comment]
好了,谢谢大佬

**Comment by czfSaber** [comment]
大佬,貌似是屏幕大小设置的有问题,跳着跳着跳下去了

**Comment by czfSaber** [comment]
大佬,请问怎么改数据啊

**Comment by superlagrange** [comment]
我也是新手，在第六页已经有人解决了，<小米5s最多跳到200多>这个问题

**Comment by superlagrange** [comment]
我也是新手，在第六页已经有人解决了，<小米5s最多跳到200多>这个问题

**Comment by czfSaber** [comment]
你是大佬啊,不然怎么会做出这个东西

**Comment by czfSaber** [comment]
我要向你学习

**Comment by superlagrange** [comment]
要是我能做出来就好啦，多向这里的大佬们学习

**Comment by superlagrange** [comment]
在wechat_jump_auto.py这里面修改

**Comment by czfSaber** [comment]
亲,函数里的if缩进是怎么个规则,不会Python啊

**Comment by superlagrange** [comment]
那个问题下面，有人有把他的代码给出来嘛，直接复制呗，我自己手打的也不行

**Comment by czfSaber** [comment]
好像是可以了,但是那个配置文件是新加一个还是改现有的

**Comment by superlagrange** [comment]
配置文件在config文件夹下的1920*1080里面改

**Comment by ydxred** [comment]
是因为没有选择设备分辨率，python2.7也可以的。

**Comment by czfSaber** [comment]
怎么选分辨率呢???
