### ISSUE TITLE
配置文件使用优先级问题

### ISSUE THREAD

**Issue by beilly** [wangshub/wechat_jump_game#888]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
**********

遇到问题：
 不是说项目根目录有配置文件会优先使用吗？可是即使我复制了mi6的配置文件，我的mi6还是使用1080*1920的配置文件。
改进和建议：根目录有配置文件优先使用根目录的，没有就按照屏幕获取

**Comment by helloLI4015** [comment]
你的屏幕大小是多少？

**Comment by beilly** [comment]
@helloLI4015 
![image](https://user-images.githubusercontent.com/7353956/34547921-8b8375e4-f139-11e7-9d65-4c1a61067881.png)

**Comment by beilly** [comment]
@helloLI4015 并且我看代码里面是直接获取https://github.com/wangshub/wechat_jump_game/blob/5576e548b6df671e2aa5536b4a8097d3b255c35b/common/config.py#L16 config下面的配置的，如果没有获取到就会使用默认

**Comment by helloLI4015** [comment]
config_file是配置文件的地址，可以看到config文件下很多配置文件

**Comment by helloLI4015** [comment]
改成这个试试
`config_file = "{path}/config/mi/mi6_config.json".format(
        path=sys.path[0]
    )`

**Comment by beilly** [comment]
@helloLI4015 我现在是
```
config_file=""
    rootDir=sys.path[0]
    for lists in os.listdir(rootDir): 
        path = os.path.join(rootDir, lists) 
        if os.path.isfile(path) and path.endswith("config.json"):
            config_file=path
    if 0==len(config_file):    
        screen_size = _get_screen_size()
        config_file = "{path}/config/{screen_size}/config.json".format(
            path=sys.path[0],
            screen_size=screen_size
        )
```
这种方式，先判断根目录是否包含config.json，没有才使用配置检测

**Comment by helloLI4015** [comment]
厉害了
