### ISSUE TITLE
特殊块的的附加分策略

### ISSUE THREAD

**Issue by beilly** [wangshub/wechat_jump_game#889]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
**********

遇到问题：
特殊块的的附加分，没有停留更长的时间来获取，特殊块附加分策略见[微信跳一跳游戏攻略 微信跳一跳高分技巧大全](http://www.techweb.com.cn/digitallife/2018-01-03/2625205.shtml)
改进和建议：徐记士、音乐盒等特殊块，使用更长的停留时间，获取附加分。

**Comment by beilly** [comment]
我现在使用的是在找块的时候，检测到平面不是纯色就返回标志位，然后停留更长的时间。但是这个特殊块检测的代码误判性很大。比方说对于第一次跳到中心位置，下一个必定是中心白点。不过现在Mi6已经跳了1625分了

**Comment by hitechbeijing** [comment]
你把停留间隔时间设置大一点就行。
