### ISSUE TITLE
运行wechat_jump_auto.py报错，是啥问题，我截图上传

### ISSUE THREAD

**Issue by 1programmer2dfg3** [wangshub/wechat_jump_game#89]
这是报错日志：
Traceback (most recent call last):
  File "E:\WeCharGamePython\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 5, in <module>
    from PIL import Image
ImportError: No module named PIL

**Comment by DCYUFU** [comment]
我小白，刚才也碰到这问题了，是没有安装图片库。

**Comment by 1programmer2dfg3** [comment]
那这个图片库如何安装，我已经下载好了这个，但是不知道咋用

**Comment by jinyuanbaoa** [comment]
pip install -r requirements.txt 这个弄了吗

**Comment by cjy825** [comment]
pip install PIL
安装一下这个PIL库

**Comment by 1programmer2dfg3** [comment]
这个没有，这个咋依赖上去？

**Comment by 1programmer2dfg3** [comment]
在cmd上输入这个命令提示pip不是内部命令

**Comment by DCYUFU** [comment]
python pip install PIL

**Comment by 1programmer2dfg3** [comment]
还是不行，提示python不是内部命令

**Comment by mjzcyhp** [comment]
你的pip还没有安装吧。Python学习笔记（一）三步走安装pip - 悠望南山 - 博客园
https://www.cnblogs.com/NanShan2016/p/5518235.html

**Comment by 1programmer2dfg3** [comment]
我python环境变量就是配置不成功，不知道咋回事，我是直接把python的安装路径放到Path环境变量 后面的
Path

C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Python27;
