### ISSUE TITLE
ios 分数上传失败，请检查网络后重试

### ISSUE THREAD

**Issue by saminlu** [wangshub/wechat_jump_game#892]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：ios 分数上传失败，请检查网络后重试

改进和建议：无

**Comment by Jessei** [comment]
我的也是 我的分数被清过

**Comment by Jessei** [comment]
def jump(distance):
    press_time = distance * time_coefficient / 1000
    print('press time: {}'.format(press_time))
    s.tap_hold(random.uniform(0, 500), random.uniform(0, 500), press_time)

**Comment by saminlu** [comment]
@Jessei 好的，感谢，我改下试试

**Comment by saminlu** [comment]
@Jessei  我已 import random，但算出来的按压时间很短

**Comment by saminlu** [comment]
@Jessei press_time = distance * time_coefficient / 1000改成press_time = distance * time_coefficient 可以了
