### ISSUE TITLE
三星 galaxy s7 edge不自动释放

### ISSUE THREAD

**Issue by 126g** [wangshub/wechat_jump_game#893]
Screen: Physical size: 1440x2560
Density: Physical density: 640

Override density: 560
DeviceType: SM-G9350
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]

bug：一直按压不释放
使用s7edge_config.json替换default.json后蓄力过猛，释放太晚。

**Comment by mushuang2015** [comment]
s7e，标题写错了

**Comment by tingqiuyuerushui** [comment]
我也碰到这种情况   把s7的曲面侧屏功能关闭就可以了

**Comment by xushanmeng** [comment]
试试这个[WechatJumpHelper](https://github.com/xushanmeng/WechatJumpHelper)，三星s7e亲测有效

**Comment by xxfxxf** [comment]
曲面和浮球都要关闭
