### ISSUE TITLE
auto脚本落点计算出现偏差

### ISSUE THREAD

**Issue by gaoshilei** [wangshub/wechat_jump_game#895]
![1514985494_d](https://user-images.githubusercontent.com/18021638/34548732-a361cbca-f13e-11e7-87b9-55363497f88b.png)

程序版本号：x.x.x
**********
Screen: Physical size: 750*1334
Density: Physical density: 2
Override density: x
DeviceType: iPhone 6S
OS: MacOS
Python: 2.7
**********

遇到问题：落点计算出现很大的偏差

改进和建议：图像识别优化

**Comment by leon0204** [comment]
同样问题，有大神解决下吗，Density: Physical density: 改成1.99也是一样

**Comment by gongzelong0718** [comment]
请问这个调试的图是如何生成的呢？
