### ISSUE TITLE
两次致命的失误，希望修复

### ISSUE THREAD

**Issue by gaoziqi** [wangshub/wechat_jump_game#896]
![1515034742_d](https://user-images.githubusercontent.com/24381592/34548773-dab08d78-f13e-11e7-81f1-ca97864770c4.png)
adb shell input swipe 581 1592 581 1592 964
scan_start_y: 740
1515034742 459 1039 695.0 797
adb shell input swipe 539 1579 539 1579 470
scan_start_y: 840
![1515034791_d](https://user-images.githubusercontent.com/24381592/34548838-494021cc-f13f-11e7-9119-e4cf3128491f.png)
adb shell input swipe 493 1574 493 1574 383
scan_start_y: 790
1515034791 474 1032 693.5 829
adb shell input swipe 522 1584 522 1584 416
scan_start_y: 840

**Comment by gaoziqi** [comment]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 420
Override density: 480
DeviceType: ONEPLUS A3000
OS: win32
Python: 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)]
**********
采用方式 2 获取截图

**Comment by lightfight** [comment]
@gaoziqi 
```python
        # time.sleep(random.uniform(0.9, 1.2))   # 为了保证截图的时候应落稳了，多延迟一会儿，随机值防 ban
        time.sleep(random.uniform(1.5, 2.2))   # 把时间留长一点
```
