### ISSUE TITLE
执行脚本文件 python3 wechat_jump_auto_iOS.py出现错误

### ISSUE THREAD

**Issue by doubleJJJJ** [wangshub/wechat_jump_game#897]
错误如下：
niejiajundeiMac:wechat_jump_game doublejj$ python3 wechat_jump_auto_iOS.py
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103945588>: Failed to establish a new connection: [Errno 61] Connection refused',))
是连接错误了吗？？不太懂，求指教，谢谢

**Comment by nightsnack** [comment]
+1

**Comment by DoyoudoLove** [comment]
http://localhost:8100/status 有内容吗？

**Comment by Kejiasir** [comment]
@doubleJJJJ [issues885](https://github.com/wangshub/wechat_jump_game/issues/885)

**Comment by doubleJJJJ** [comment]
@DoyoudoLove 没有呢

**Comment by DoyoudoLove** [comment]
@doubleJJJJ  你可以查看3楼给你发的问题链接，应该是端口问题

**Comment by doubleJJJJ** [comment]
@DoyoudoLove 之前手机是连WiFi，现在改用4G网络，然后http://localhost:8100/status 有内容了，可是执行脚本还是出错了....

**Comment by doubleJJJJ** [comment]
@Kejiasir 谢谢，我先看下~

**Comment by Kaelzzs** [comment]
```
{
value: {
state: "success",
os: {
name: "iOS",
version: "10.3.2"
},
ios: {
simulatorVersion: "10.3.2",
ip: "192.168.1.107"
},
build: {
time: "Jan  4 2018 11:17:36"
}
},
sessionId: "CF169B54-5C09-40B3-B2FA-D8212C014BF2",
status: 0
}
```
@DoyoudoLove   8100/status 都没问题  但是跑脚本就出这问题了

**Comment by DoyoudoLove** [comment]
@doubleJJJJ 什么错误，和这个一样吗

**Comment by lawrencecai** [comment]
我也是这个错，status正常，inspector显示截图，iproxy转发也正常，一执行脚本就显示上面楼主的错，无法连接127.0.0.1 port1087

**Comment by doubleJJJJ** [comment]
解决了，按照[issues885](url)的方法，如下：
status的 URL 是 http://IP:8100/status还是 http://localhost:8100/status?
假如是 IP的, 如果你不用 iproxy 做下端口代理的话, 需要在wechat_jump_iOS_py3.py line19, 或 wechat_jump_auto_iOS.py line52:
c = wda.Client() 里指定你手机的 IP,
c = wda.Client('http://Xcode console 中打印的的 IP :8100'),
如: c = wda.Client('http://192.168.1.100:8100')
当然你也可以用iproxy 8100 8100把 iPhone 的端口转发到 Mac 上, 这样的话, 上边那两个文件就不需要修改了

**Comment by Kaelzzs** [comment]
![](https://ws2.sinaimg.cn/large/006tKfTcly1fn4gbu32oyj31ae0oydkr.jpg)
![](https://ws3.sinaimg.cn/large/006tKfTcly1fn4gcece50j30hr0bamz3.jpg)



@DoyoudoLove 网页打开查看状态 和 UI抓取 都没问题  ，但是过了一会，端口转接那块就这样来了....

然后，跑脚本就
```
retry to connect, error: HTTPConnectionPool(host='192.168.1.107', port=8100): Max retries exceeded with url: /status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1111ed400>, 'Connection to 192.168.1.107 timed out. (connect timeout=60.0)'))


```

**Comment by CrabMen** [comment]
@Kaelzzs 我也遇到跟你一样的问题，不过我用iproxy 转发了，网页上面/insepector和/status都有内容 ，报的错误跟你的一模一样，不知道你的问题解决了没，求解惑

**Comment by CrabMen** [comment]
@doubleJJJJ @nightsnack @DoyoudoLove @Kejiasir 大佬们，我遇到了问题，帮忙看一下，问题描述在这里[#1166](https://github.com/wangshub/wechat_jump_game/issues/1166)
