### ISSUE TITLE
换手机刷分需要重新安装，一次刷分不能超过上次得分太高。

### ISSUE THREAD

**Issue by yulincoder** [wangshub/wechat_jump_game#899]
2018.1.4 - 11:59 
1. 如果没有Mac，给苹果用户刷可以找一台安卓登录进行刷分，但是重新登陆苹果的时候需要卸载重新安装微信（清理缓存没试），应该是手机内会有缓存分数。同理，用自己手机给别人的安卓刷分也应该需要如此。
2. 最新的测试（2018.1.4 - 11:59 ），没两次分数之间不能相差太远，否则会出现分数不能提交的问题，至少从我这里尝试，第二次不能比前一次高于300分(我的第分是四百多，猜测且没尝试：分数越高，这个限制会变大)。

**Comment by lihuangshuaige** [comment]
有用吗？

**Comment by mojianyuan** [comment]
亲测有用

**Comment by Allen-Liang** [comment]
哈哈哈，好想研究微信团队的封挂原理。
