### ISSUE TITLE
一个优化运算

### ISSUE THREAD

**Issue by hiyoi** [wangshub/wechat_jump_game#90]
需要计算图片范围大概是屏幕高的三分一处到三分二处
![1](https://user-images.githubusercontent.com/2487038/34453016-625ef150-ed85-11e7-9511-fda5cde38c83.png)
获取目标点的范围可以大幅缩小：
```
80                  for i in range(h):
```
和
```
94                  for i in range(h):
```
可以改为
`for i in range(int(h*0.33),int(h - h*0.33)):`

这样可以减少很多无用的计算

**Comment by zenhuang** [comment]
是的，而且计算棋子的坐标的时候，也可以设置左右边界，减少计算开销。我刚提交了一个PR，在我机子上一张截图的处理时间从4s左右降低到1s以内～

**Comment by aikunzhe** [comment]
然后运行的准确率怎么杨
