### ISSUE TITLE
我的微信的跳一跳已经凉了

### ISSUE THREAD

**Issue by BMlovePanda** [wangshub/wechat_jump_game#900]
程序版本号：x.x.x
**********
Screen: Physical size: 1080*1920
Density: Physical density: x
Override density: x
DeviceType: x
OS: Android
Python: 2.7
**********

遇到问题：
只要分数超过原有的记录1000多分，就会提示“提交分数失败，检查网络连接”，通过fiddler抓包，只抓到url为settlement返回的errcode 108，没找到我提交的数据在哪。。。。
也修改了程序里面的按压位置和停留时间为随机。
改进和建议：不知道下周会不会被解封，我会随时来反馈结果的。

**Comment by LiXirong** [comment]
+1 相同提示 微信动作太快了 感觉要凉凉

**Comment by sjzjams** [comment]
改动 每次不跳到中心点，然后跳个400-500分就可以了哈哈，真的要凉 了哈哈

**Comment by BMlovePanda** [comment]
腾讯的开发人员是不是也在一直关注这个项目。。。随时应变，昨晚上没改随机提交，还没提示网络故障，只是不能上传而已，今早就变成现在这样了。

**Comment by LiXirong** [comment]
@BMlovePanda 我有个同学就是腾讯的 昨天晚上他女票还问我怎么那么高的分是不是动了什么手脚。。。

**Comment by BMlovePanda** [comment]
@LiXirong 那你的凉了没。。。我看issues里面有个400多就凉了的。。。哈哈哈哈

**Comment by LiXirong** [comment]
@BMlovePanda 之前刷过3W 刷过1W都没提交成功，昨晚改了随机量后7K提交成功排行榜显示，今天刚刷个1W+的就报错了，和这个issues一样的问题

**Comment by gaoshilei** [comment]
我的彻底凉了，post提交返回{ base_resp: { errcode: 0, ts: '1515039401770' } }成功状态，待会去看还是0分，不管怎么跳都是0分

**Comment by BMlovePanda** [comment]
大家等下一个周期再看吧。楼上0分的，你是我见过最惨的。。。

**Comment by shenyouxingyu** [comment]
一直0分，凉凉

**Comment by Frontlook** [comment]
还好我刷的早，周一刚一开始就刷了1000+，后面被周围程序员反超，然后他们凉凉了，我依然坚挺。

**Comment by qq475281441** [comment]
我的直接被删掉了排行，跳多少别人都看不到我。

**Comment by gaoshilei** [comment]
跟我的一样，拉到最下面就能看到了，0分，卸载微信重装手动跳也都是0分，好了，大家该写代码写代码，写BUG的写BUG，这个游戏到此结束。

**Comment by oneofai** [comment]
23333, 我也一样, 怎么调都提交不上去, 提示网络问题,  但我通过 POST 修改 Token 还是可以的, 早晨改成了66666, 目前发现还在榜上
![image](https://user-images.githubusercontent.com/16975429/34552954-a50343ca-f15f-11e7-980a-3d6e3cc2174c.png)

**Comment by baolw** [comment]
@oneofai 怎么修改token？？

**Comment by BMlovePanda** [comment]
@oneofai 这个不是早就修复了么？竟然还能改？

**Comment by middlexu** [comment]
@oneofai 求方法。我现在自己手动玩，玩30分也要被清

**Comment by WowJesse** [comment]
@oneofai 上传分数失败，怎么破

**Comment by BMlovePanda** [comment]
我的成绩竟然更新了，但是还是有问题，更新了我两局中一局的分数。更新分数之前，我的分数是1048。
其中第一局是1181，提交的时候没有该issues之前的网络问题了。并且显示分数是最新的。然而，我关掉跳一跳之后，再进去，发现分数还是之前的1048。
然后我在想是不是有分数刷新延迟？于是又刷了一局，然后，这局刷了1400多分，等我退出的时候，我发现，我的排行分数已经更新到上一局的1181了。所以，难道，他还有人工校验的机制？到目前为止，我的分数还是1181，之后一局的1482，到现在也没有刷新成功。上两张对比图。
![1048](https://user-images.githubusercontent.com/35089525/34592232-865718ae-f1fd-11e7-9777-8acfa913658e.jpg)
![1181](https://user-images.githubusercontent.com/35089525/34592233-86a95b1e-f1fd-11e7-8681-94c22d533a06.png)

**Comment by BMlovePanda** [comment]
两张图的来源都是朋友的跳一跳，所以不存在只在自己的跳一跳刷新的问题。

**Comment by smallLabel** [comment]
今天早上跳了1000然后报错了，自己本地能看到，别人排行版看不到，后来重新登录了微信，分数也被清了。第二次又重新跳了一次，这次在700多分的时候关了程序，自己手动跳了几下就可以了，别人排行榜也看得到

**Comment by jack1589luke** [comment]
我现在自己玩的分数都会被清零，好惨
