### ISSUE TITLE
遇到白色药瓶的时候，瓶盖的直径小于瓶底，落点会落到瓶盖边缘

### ISSUE THREAD

**Issue by JamesZBL** [wangshub/wechat_jump_game#904]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
Device: kenzo
Phone OS: 6.0.1
Host OS: win32
Python: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
**********
采用方式 1 获取截图

遇到问题：遇到白色药瓶的时候，瓶盖的直径小于瓶底，落点会落到瓶盖边缘

改进和建议：

**Comment by sjzjams** [comment]
分辨率 得改一下吧。。

**Comment by JamesZBL** [comment]
不是分辨率的问题，自动识别 1920 x 1080

**Comment by ahong007007** [comment]
同样的问题，目前只能刷100分左右。

**Comment by Frontlook** [comment]
@ahong007007 都开始清理异常分数了，刷100可以了。
