### ISSUE TITLE
微信的程序猿，我猜你正在窥屏

### ISSUE THREAD

**Issue by billzbh** [wangshub/wechat_jump_game#906]
你  正在   # 窥屏

屏蔽啥的为什么屏蔽呢？
我用技术模拟物理按压作弊，凭自己本事做弊，你干嘛要屏蔽。

哈哈哈哈哈哈哈哈

**Comment by dzyls** [comment]
不得不说，反应真快，一个不盈利的小游戏都这么重视

**Comment by gaoshilei** [comment]
一直0分，换了手机卸载微信重装再跳也是0分，手动的都不行了，看来是封号了

**Comment by LiXirong** [comment]
提个建议，窥屏可以，但是能不能把屏蔽的原理告诉我们让我们自己想办法解决？这样互相学习不也挺好吗？（手动滑稽）

**Comment by jruif** [comment]
@LiXirong 你这是想累死他们吗？

**Comment by INtEReSTiNg1234** [comment]
感觉斯诺登是从微信逃出来的

**Comment by 245375200** [comment]
微信程序员这会儿想炸github

**Comment by BMlovePanda** [comment]
主要是这个项目在github太tmd火了。。。谁都知道这个项目了。

**Comment by jruif** [comment]
反作弊的方法已经被猜出来了，就是检测点击的位置，稍微改下代码就可以了，ios的代码位置是wechat_jump_auto_iOS.py文件的67行的：

```python
s.tap_hold(random.uniform(100,200), random.uniform(100,200), press_time)
```

**Comment by MagicSaring** [comment]
那安卓的呢

**Comment by helloworld10010** [comment]
@MagicSaring press_point_x1 = random.uniform(0,1080)
    press_point_x2 = random.uniform(0,1080)
    press_point_y1 = random.uniform(0,1900)
    press_point_y2 = random.uniform(0,1900)
    cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=press_point_x1,
        y1=press_point_y1,
        x2=press_point_x2,
        y2=press_point_y2,
        duration=press_time
    )

**Comment by dzyls** [comment]
@helloworld10010 屏幕上有分享和返回微信界面的按钮，有可能会随机到
