### ISSUE TITLE
nightly

### ISSUE THREAD

**Issue by Sniper970119** [wangshub/wechat_jump_game#907]
![1515047449_d](https://user-images.githubusercontent.com/30463691/34552600-5da537a6-f15d-11e7-9b14-bf69704419d9.png)
![1515047449_d](https://user-images.githubusercontent.com/30463691/34552607-639fe78c-f15d-11e7-82da-557c81888733.png)
![1515047453](https://user-images.githubusercontent.com/30463691/34552608-63d84dc0-f15d-11e7-9125-603da5977dca.png)
![1515047453_d](https://user-images.githubusercontent.com/30463691/34552609-64106b2e-f15d-11e7-8a2a-ad7bbd7f10c9.png)

**Comment by Sniper970119** [comment]
@MrLevo520

**Comment by Sniper970119** [comment]
@MrLevo520

**Comment by Sniper970119** [comment]
![1515049088_d](https://user-images.githubusercontent.com/30463691/34553030-396cea70-f160-11e7-9675-30a5f7520860.png)
![1515049092_d](https://user-images.githubusercontent.com/30463691/34553031-3a176108-f160-11e7-9f6c-d42063713fb0.png)

**Comment by MrLevo520** [comment]
距离没问题，应该是按压系数问题

**Comment by scholar095** [comment]
求教大神，怎么设置nightly版本啊
