### ISSUE TITLE
关于系统ban的测试

### ISSUE THREAD

**Issue by DisMeo** [wangshub/wechat_jump_game#909]
**测了3个号**
auto的code和主页的code原理一样，代码有点区别。

- auto 随机坐标按压（ban）
- 手动（点图片） 随机坐标按压（ban）
- 一半手动，一半纯手动（ban）

**Comment by INtEReSTiNg1234** [comment]
难道是检测截图？只要截图就清零？

**Comment by DisMeo** [comment]
@INtEReSTiNg1234 感觉是和adb有关的，毕竟检测adb应该不是很难。

**Comment by INtEReSTiNg1234** [comment]
AUTO随机按压BAN了？确定不是用过的微信号吗？😂

**Comment by DisMeo** [comment]
@INtEReSTiNg1234 auto随机的号，周一玩了一次 1035分，昨天用随机按压的玩了一次，1050但是没更新，再玩了一次 1100，积分就被清0了。

**Comment by daoying1994** [comment]
@DisMeo 会不会是你的分数太高了，异常分数检测

**Comment by INtEReSTiNg1234** [comment]
我是周一用auto跑的，2500分今天被清零了，自己手打了几把没被清

**Comment by daoying1994** [comment]
@DisMeo 如果是adb检测的话 不使用脚本 在pc上玩 会不会清零

**Comment by DisMeo** [comment]
@daoying1994 模拟器的我没关注过，貌似夜神也有被ban的吧。

**Comment by hfenigma** [comment]
检测adb确实不难，但是微信未必给小程序开放了这个接口
如果是微信本体检测的，可以禁用微信枚举进程相关的权限，然后测试验证一下

**Comment by dosmlp** [comment]
触摸点随机就好了，刷了400+还没被ban，晚上试下刷1000看看

**Comment by daoying1994** [comment]
@dosmlp 你上次的分数是多少？

**Comment by coderchaser** [comment]
什么是系统ban？防止微信封号吗？

**Comment by dosmlp** [comment]
@daoying1994 也就几十

**Comment by Robertccl** [comment]
有没有什么方法避免被ban，各位大佬

**Comment by molvqingtai** [comment]
可是我用的javascript版本，也凉了...

**Comment by mousehaow** [comment]
随机按压点也会ban，我怀疑微信给它开放的监测硬件的接口了。。。
