### ISSUE TITLE
截图无法保存/读取的参考修改方式（ubuntu系统）

### ISSUE THREAD

**Issue by kokozeng** [wangshub/wechat_jump_game#91]
def pull_screenshot():
    #os.system('adb shell screencap -p /sdcard/1.png')
    #os.system('adb pull /sdcard/1.png .')
    os.system("adb shell screencap -p | sed 's/\r$//' > 1.png")

注释掉的两行是保存在SD卡，然后通过SD卡上传至PC。
用下面这一行，是直接截图保存在你程序运行的目录里。

**Comment by F-loat** [comment]
这个windows不支持吧

**Comment by kokozeng** [comment]
@F-loat  啊噢～应该是的，没注意到这一点。抱歉。我是用ubuntu。

**Comment by 897902334** [comment]
把代码里的所有1.png修改成 其他的名字就能行，  但是下次尝试运行  还是提示这个图片不存在。

**Comment by abcd106** [comment]
截图是保存在手机里面，地址是什么

**Comment by kokozeng** [comment]
@897902334  可以上传你的错误提示代码看看。

**Comment by 897902334** [comment]
@kokozeng 
报这个错

C:\>wechat_jump_auto.py
adb: error: remote object '/sdcard/hhh.png' does not exist
Traceback (most recent call last):
  File "C:\wechat_jump_auto.py", line 139, in <module>
    main()
  File "C:\wechat_jump_auto.py", line 127, in main
    im = Image.open("./hhh.png")
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './hhh.png'

C:\>

**Comment by kokozeng** [comment]
@abcd106 　原作者是保存在sd卡就是/sdcard

**Comment by kokozeng** [comment]
@897902334  要么是截图没截下来。。要么是你没有sd卡，无法保存在sd卡。（个人感觉大概率是你没有/sdcard这个路径　作者还提供了一个函数backup_screenshot(ts)检测路径。

**Comment by 897902334** [comment]
@kokozeng  我用的Win10   可能是系统的原因吧，   因为我改了名字之后还成功过好多次  每次都是跳到102步就死了。

**Comment by kokozeng** [comment]
@897902334 酱哦～～还要请大神解答一下啦。我对安卓和windows都不太了解呢。：）

**Comment by 897902334** [comment]
@kokozeng    哈哈，我还是继续关注issues

**Comment by hakrtt** [comment]
@897902334 老铁你的WIN10系统怎么弄成功的，我鼓捣一天都不行

**Comment by 897902334** [comment]
@hakrtt   我是按照这位老哥(@F-loat ) 教的办法！ https://github.com/wangshub/wechat_jump_game/issues/39 
你看看吧

**Comment by F-loat** [comment]
可以直接获取截图信息保存到电脑上了 #288
