### ISSUE TITLE
请教各位，这个按压时间系数怎么确定的呢？

### ISSUE THREAD

**Issue by foreverlms** [wangshub/wechat_jump_game#911]

**Comment by hao0917** [comment]
魔法数字，自己微调的吧

**Comment by coderchaser** [comment]
@hao0917 能微调到百分位，也算是辛苦了:laughing:

**Comment by mingyue6952** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Easyboy0405** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
