### ISSUE TITLE
散了散了 已经不能刷了  分数同步不上去  只能自己看

### ISSUE THREAD

**Issue by zq019633** [wangshub/wechat_jump_game#914]

**Comment by jhbxyz** [comment]
是不是有一个什么网络设置,不让上传了

**Comment by sijinglei** [comment]
刷分刷上去的都是只能自己看了。。

**Comment by jhbxyz** [comment]
什么意思.给个明白的解释啊

**Comment by jamescheng16** [comment]
应该是微信有机制检验人际吧 ？ 有没有办法做一些模拟人操作的行为，
例如不按压同一个点、按压时间间隔

**Comment by zhqingyong** [comment]
自己动手修改下啊，老铁。。。程序是死的，人是活的。改改参数不让他这么精确无误就可以了

**Comment by doubleJJJJ** [comment]
可以的，我根据里面的方法改了就行了。https://zhuanlan.zhihu.com/p/32594563
将jump函数增加随机参数， s.tap_hold(200, 200, press_time)改为s.tap_hold(random.uniform(0, 500), random.uniform(0, 500), press_time)

**Comment by Frontlook** [comment]
@zhqingyong 已经有黑名单了，我用手动跳10分都不给上榜。

**Comment by SouthOfAsia** [comment]
是啊现在手动跳把把都是最高分。。。

**Comment by dadahhhh** [comment]
上黑名单了，手动都没分了。

**Comment by gaoshilei** [comment]
@Frontlook 我也是，手动跳都上不了分，微信卸载重装也不行，已经被封了，看看下周给不给解禁

**Comment by HuRuWo** [comment]
上黑名单了 手动的分都没用

**Comment by Robertccl** [comment]
auto那个已经是随机跳的位置了吧，然而还是不行

**Comment by Li-Allen** [comment]
可以啊，我刚还给同学刷了一个六百

**Comment by yabin970** [comment]
这个并不是准确无误的，我得跳到九百多就掉下来了

**Comment by ZhaoYitong** [comment]
20000多，已经黑名单了

**Comment by chchuj** [comment]
看着真人的排行榜来刷，别跳太高

**Comment by 245375200** [comment]
完了,我也进了黑名单

**Comment by zmaxbin** [comment]
有没有大神来杠一下鹅厂，表示已经被拉黑。。。手动也清零
