### ISSUE TITLE
请问大家是如何连接上真机的？

### ISSUE THREAD

**Issue by Uni-lovenix** [wangshub/wechat_jump_game#916]
使用 iproxy 8100 8100 之后，在浏览器中输入 http://192.168.1.101:8100/inspector 显示拒绝访问

**Comment by hitechbeijing** [comment]
关掉wifi，启动WebDriverAgentRunner。

**Comment by hitechbeijing** [comment]
参考这个：https://github.com/wangshub/wechat_jump_game/issues/922

**Comment by Uni-lovenix** [comment]
解决需要同时修改runner的identifier
