### ISSUE TITLE
iphone 6 计算距离出错 

### ISSUE THREAD

**Issue by goonwzz** [wangshub/wechat_jump_game#917]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by goonwzz** [comment]
![1515053755_d](https://user-images.githubusercontent.com/18460670/34555646-d85b87ec-f16d-11e7-9f6e-e274abd541fb.png)

**Comment by Yarkable** [comment]
win10➕iPhone 可以玩吗

**Comment by zcjerry229** [comment]
据说iphone据说抗锯齿处理导致现有的距离算法有问题。我iphone6最多跑了800多

**Comment by iosHot** [comment]
在计算圆形块时有时会出现误差，希望大神解决这个问题

**Comment by goonwzz** [comment]
用了node那款半自动。。距离自己手动选择。还是被封号了
