### ISSUE TITLE
大神，你这个用完了怎么卸载？

### ISSUE THREAD

**Issue by tianyajuechen** [wangshub/wechat_jump_game#918]
大神，你这个怎么卸载？我看它下了100多兆的文件，在哪里呀，怎么删除

**Comment by z-jingjie** [comment]
冗余文件主要产生在screenshot_backups文件夹，存储了每次跳跃前进行像素识别的所需截图文件，全部删除即可

**Comment by tianyajuechen** [comment]
@z-jingjie 我下载是方法一版本，
<img width="908" alt="1" src="https://user-images.githubusercontent.com/11382955/34557434-35759d8a-f175-11e7-9f2b-69b28f14b065.png">
STOP_jump_macOS文件夹里的screenshot_backups文件夹还是些默认的截图，不知道真正的截图放在哪里

**Comment by tianyajuechen** [comment]
好像这个项目也通过git拉下来了，但是我找不到在哪。。。
