### ISSUE TITLE
adb驱动已经装好了，但还是报错

### ISSUE THREAD

**Issue by marcussssssss** [wangshub/wechat_jump_game#919]
'adb' is not recognized as an internal or external command,
operable program or batch file.
'adb' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "D:/jumpjump/jump.py", line 33, in <module>
    img = np.array(Image.open('autojump.png'))
  File "C:\Users\mlsstu\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'autojump.png'

Process finished with exit code 1

**Comment by marcussssssss** [comment]
![sshot-2](https://user-images.githubusercontent.com/34992150/34557240-8b429cb4-f174-11e7-9871-c7df1fd85bb8.png)

**Comment by marcussssssss** [comment]
这哪出错了

**Comment by MrLevo520** [comment]
请使用免配置adb版本或者下载release一键起跳
