### ISSUE TITLE
我怀疑6s以上机型加入了 3d touch判断，不能上传分数

### ISSUE THREAD

**Issue by soap-man** [wangshub/wechat_jump_game#921]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by hitechbeijing** [comment]
这游戏根本没用3d touch啊，你又不是用力按才有作用，根据屏幕触摸时长判断的
话说你怎么连上真机的？我每次都是connection refused

**Comment by Ace--Qi** [comment]
哪里有用3D。。。7随便上传，只是微信加入了几个判定条件是否辅助

**Comment by soap-man** [comment]
按照教程一步步弄了半天模拟好的，7可以随便上传妈，为啥我的一直不能上传……

**Comment by huozhenlin** [comment]
微信增加了哪几个判断条件判断是否增加了辅助？adb命令模拟点击怎样不被js检测到？

**Comment by soap-man** [comment]
@Ace--Qi  你有修改什么操作吗，为什么你可以上传，我上传不了分数

**Comment by Ace--Qi** [comment]
@soap-man 把按压位置随机化 程序sleep时间随机2-4   然后改用拟合曲线方程计算time和dis关系 分数上2000没有问题

**Comment by Ace--Qi** [comment]
@huozhenlin 连续命中中心次数 按压点位置 每次按压前间隔时间 还有就是你的分数
