### ISSUE TITLE
IOS连真机出错

### ISSUE THREAD

**Issue by hitechbeijing** [wangshub/wechat_jump_game#922]
每次都是启动模拟器才能连上，用真机就是connection refused。xcodebuild命令，xcode gui都试了。

**Comment by wizard1990** [comment]
文档里没说清楚 wda的session创建时候默认是localhost 但通过xcode启动的时候是随机分配一个ip地址的 所以每次开启时候需要设个环境变量DEVICE_URL 设成xcode console里面的值 比如export DEVICE_URL=http://169.254.195.47:8100

**Comment by hitechbeijing** [comment]
加了环境变量确实是可以了，但用模拟器ip也不是localhost，却能够连上，后来我测试了一下，模拟器的ip还真是本机IP，127.0.0.1:8100也能够访问。受教了，谢谢。

**Comment by wizard1990** [comment]
因为模拟器的server是跑在MacBook上 ip自然可以用localhost访问 真机的话就跑在device上了 需要远程访问

**Comment by AddisonGao** [comment]
环境变量怎么加 直接加到命令行zsh里面就行？？还是加到xcode的。。。？xcode怎么加呢？

**Comment by hitechbeijing** [comment]
c = wda.Client()，这行改一下加参数也行，为了这问题，专门去看了wda文档
