### ISSUE TITLE
iphone7 定位偏差

### ISSUE THREAD

**Issue by longshenjue** [wangshub/wechat_jump_game#929]
程序版本号：x.x.x
**********
Screen: Physical size: 4.7
Density: Physical density: 1334 x 750
Override density: x
DeviceType: iphone7
OS: mac
Python: 3.6.4
**********

遇到问题：定位偏差

改进和建议：
1.圆顶的柱子 色差不明显的时候，计算会出错
2.顶部图片有花纹或比较复杂时也会出错

**Comment by longshenjue** [comment]
![Uploading image.png…]()

**Comment by longshenjue** [comment]
![1515078915_d](https://user-images.githubusercontent.com/12636362/34570347-7383d5fc-f1a6-11e7-9b87-8825d5f66a8c.png)

**Comment by longshenjue** [comment]
![1515077623_d](https://user-images.githubusercontent.com/12636362/34570386-94a2aeb6-f1a6-11e7-9843-8fb83eae6bd3.png)
![image](https://user-images.githubusercontent.com/12636362/34570435-c16b6d5c-f1a6-11e7-9efe-136e7a746226.png)

**Comment by qingbofish** [comment]
你的配置参数多少

**Comment by iosHot** [comment]
iPhone普遍存在这个问题，希望大神能出面解决这个问题

**Comment by longshenjue** [comment]
@qingbofish 就是代码中提供的iphone6尺寸的参数

**Comment by doubleJJJJ** [comment]
求iphone7的优化参数，目前最高只有800+

**Comment by yinhao-f** [comment]
主要问题还是点找不准。距离时间关系已经很精确了。iOS貌似带抗锯齿，仔细看截图和安卓是不一样的，所以在找底座中心点的时候有几率出现误差。一时半会解决不了，还是用手动的刷吧
