### ISSUE TITLE
已经凉了的来报个告到..

### ISSUE THREAD

**Issue by molvqingtai** [wangshub/wechat_jump_game#931]
一直停留在182分，多一分都不行，鹅厂反作弊手段还是有一套啊

**Comment by skywhat** [comment]
凉了凉了，只能自娱自乐

**Comment by kennylbj** [comment]
一首凉凉送给我们，被拉黑了

**Comment by ventsea** [comment]
They are abnormal about the score execute Unidirectional shielding

**Comment by ventsea** [comment]
They perform unidirectional masking of unusual scores

**Comment by WuqingVika** [comment]
阔怕啊 要凉就干脆点  还把我晾在自己的世界里 。

**Comment by 245375200** [comment]
我也被拉黑了一首凉凉给自己

**Comment by ThisIszas** [comment]
举爪

**Comment by zhangsihua** [comment]
举爪，微信好友在他们的排行榜上已经看不到我了

**Comment by qianlishun** [comment]
凉了，拉黑了的，多少分都是0，别人上面不显示。

微信官方发了声明了，他们表示元旦期间一直在加班做反外挂，想捷径走高分的，看哪方的技术团队强了。

**Comment by molvqingtai** [comment]
估计不行了，说不定微信程序员一直在窥屏，和鹅厂硬杠还是有点难度...

**Comment by molvqingtai** [comment]
@qianlishun估计不行了，说不定微信程序员一直在窥屏，和鹅厂硬杠还是有点难度...

**Comment by MatriXie** [comment]
还截图给别人看，哈哈哈，然后只是在自己的世界里~
git大战鹅场程序猿····

**Comment by zhangjingxiang666** [comment]
大号和小号都凉了😂

**Comment by ziyaochen** [comment]
凉凉
