### ISSUE TITLE
感觉最新的ban方法是ban跨设备

### ISSUE THREAD

**Issue by Erimus-Koo** [wangshub/wechat_jump_game#933]
我自己是iOS，用PC加安卓模拟跑分。  

前两天成绩顺利，今天起在模拟器刷的分，到iOS端再登陆就回到了iOS之前的分。  
估计是在iOS端小程序有缓存，然后加了判断。  

目的应该是为了打击付费刷分吧。  

但直接改request，实在太无趣了点。

**Comment by hal-lucinogen** [comment]
并不是，我一直是 Android 设备，而且就是用的自己的主力机，还是被 ban 了
