### ISSUE TITLE
关于wiki里的操作步骤

### ISSUE THREAD

**Issue by francofff** [wangshub/wechat_jump_game#934]
因为对wda没有经验，所以设置的时候遇到问题，找了好久关于wda的documentation.

`c = wda.session()`这一行，这个function在没有输入的时候默认访问localhosts，如果没有把手机的8100端口转发到电脑的话（像我一样）会出现connection refused错误。

解决方法是在添加一个string, 包括设备ip和端口。

希望能够修改一下wiki让更少的人走弯路（

**Comment by hitechbeijing** [comment]
c = wda.Client()，这里加个参数，改成server地址。不然默认是localhost。
