### ISSUE TITLE
分数被清零了，刷不上了耶！

### ISSUE THREAD

**Issue by menglingkun1011** [wangshub/wechat_jump_game#935]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by IEfucker** [comment]
每天刷一次不行吗

**Comment by WhySRZ** [comment]
哈哈，刚试了，跳500都不行！然后号会被限制。。。不管跳多少分，退出重进又变成零了

**Comment by hangj** [comment]
我也遇到这种情况，昨晚刷到 800 多，今天早上起来一看还是原来的 50 多分，🙄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wangxuanlong** [comment]
我也是哎，前几天刷了1200+，然后今天朋友告诉我没有排名了，刷多少分也没有排名。。。

**Comment by Testlyy** [comment]
加一个随机间隔时间来跳跃，不知道会反ban不

**Comment by Testlyy** [comment]
刚帮别人刷了几次500+都被删除了，最后一次619没有ban，每次跳一百步停一会或者找简单的位置停下手动跳几步，暂时没删除

**Comment by IEfucker** [comment]
楼上厉害，不知道反外挂是什么算法，也许真行

**Comment by duyehong** [comment]
我自己是超过1000分就清零。可能是机器跳的太准了，可以改算法，不用最佳的步骤来跳。

**Comment by chenyunguiMilook** [comment]
改一点点算法，按压时长加上+-0.05秒内的随机值，另外按压的坐标也在某个范围内随机一下，亲测有效〜

**Comment by bigsma11** [comment]
手动都清了。。。

**Comment by AlliotTech** [comment]
同清零， 不过还是不知道检测清零的机制，好像是退出账号就会清零。
