### ISSUE TITLE
Code Signing Error: Failed to create provisioning profile. The app ID "com.facebook.WebDriverAgentLib" cannot be registered to your development team. Change your bundle identifier to a unique string to try again. Code Signing Error: No profiles for 'com.facebook.WebDriverAgentLib' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentLib'.

### ISSUE THREAD

**Issue by Uni-lovenix** [wangshub/wechat_jump_game#936]
Code Signing Error: Failed to create provisioning profile. The app ID "com.facebook.WebDriverAgentLib" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
Code Signing Error: No profiles for 'com.facebook.WebDriverAgentLib' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentLib'.
请问这个问题，咋解决？

**Comment by hitechbeijing** [comment]
Change your bundle identifier to a unique string to try again。

**Comment by Uni-lovenix** [comment]
I tried to change identifier to a unique string but it does’t worked. I don’t know what I set wrong.

**Comment by Uni-lovenix** [comment]
solved, modify the webdriveragentlib identifer also need modified the webdrivergentrunner identifier. 3ks. lol.
