### ISSUE TITLE
WDA需要开发者证书，这个没有怎么办

### ISSUE THREAD

**Issue by IEfucker** [wangshub/wechat_jump_game#937]
如题
有办法绕过这个问题吗，
没法绕过有好心人能借我用下吗

**Comment by Uni-lovenix** [comment]
我是直接使用免费的，但是也有问题

**Comment by IEfucker** [comment]
@Uni-lovenix 请问免费的证书怎么弄到的，找半天没找到答案啊

**Comment by hitechbeijing** [comment]
只调试不需要证书

**Comment by mousehaow** [comment]
说明里写的比较清楚的，参考这个https://testerhome.com/topics/8085

**Comment by Uni-lovenix** [comment]
@mousehaow 我用这个搞的，不行

**Comment by sj8023ld** [comment]
不需要证书，在XCODE首选项--account里面登陆一下，然后管理证书添加一下就行了，自动生成一个免费的。

**Comment by Uni-lovenix** [comment]
我就是使用的这种方法

**Comment by leuction** [comment]
在xcode中的target的WebDriverAgentLib和WebDriverAgentRunner里面team选择你自己的账号，然后改一下Bundle ID就可以了

**Comment by Uni-lovenix** [comment]
如何修改密码bundle ID？

**Comment by Yuecuize** [comment]
appleid 登陆为自己的team就没问题了，我的程序已经开始蹦了

**Comment by Uni-lovenix** [comment]
我使用的就是自己的appleid，显示没有profile

**Comment by Uni-lovenix** [comment]
一直显示：Failed to create provisioning profile. The app ID "com.facebook.WebDriverAgentLib" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
可是我已经将WebDriverAgentLib的identifier后面添加了后缀, com.facebook.WebDriverAgentLib.XXX的形式

**Comment by goodbyennn** [comment]
同 Failed to create provisioning profile. The app ID "com.facebook.WebDriverAgentLib" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

没解决！！

**Comment by hitechbeijing** [comment]
Try to change your bundle identifier in build setting
尝试在build srtting里修改bundle identifier，字符越多越好

**Comment by Uni-lovenix** [comment]
已经解决谢谢
solved， tks

**Comment by Uni-lovenix** [comment]
修改 webdriveragentlib的bundleID identifier和 webdriveragentrunner的bundleID identifier
在后面添加后缀：比如 com.facebook.WebDriverAgentLib.sdfsfsdfifjsk

**Comment by SionFu** [comment]
Code Signing Error: Signing for "IntegrationApp" requires a development team. Select a development team in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
iOS test 报这两个错，大神求解

**Comment by HenryWoo1229** [comment]
> Code Signing Error: Signing for "IntegrationApp" requires a development team. Select a development team in the project editor.
> Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
> iOS test 报这两个错，大神求解

Xcode 中选择 IntegrationApp 项目，然后修改一下 Team 和 Bundle Id，为你自己的 Id，即可
![image](https://user-images.githubusercontent.com/19677863/68913606-d055e380-0796-11ea-9712-c63b988549a0.png)
