### ISSUE TITLE
请问windows下虚拟机中的macos可以吗

### ISSUE THREAD

**Issue by zkl99999** [wangshub/wechat_jump_game#938]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by mousehaow** [comment]
按道理应该是可以的，但是没有试过

**Comment by terrybogez** [comment]
必须可以啊 ，以前玩过 ，但是觉得还是搞个mac比较爽

**Comment by stlfatboy** [comment]
可以的，亲身实践

**Comment by mylyxk** [comment]
没有测试成功，8100端口监听不到数据。
