### ISSUE TITLE
小米5参数还是找不到

### ISSUE THREAD

**Issue by wangzilong1997** [wangshub/wechat_jump_game#939]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by WhySRZ** [comment]
我用1.466可以，他们都说用1.475，但我测试不太行。
{
    "under_game_score_y": 300,
    "press_coefficient": 1.475,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,

    "swipe" : {
      "x1": 540,
      "y1": 1514,
      "x2": 540,
      "y2": 1514
    }
}

**Comment by wangzilong1997** [comment]
可以我试一试谢谢

**Comment by wangzilong1997** [comment]
1466不行

**Comment by mousehaow** [comment]
试着修改小米5分辨率对应的config文件，android应该是自动识别到那个文件的，改根目录下的config没用貌似

**Comment by wangzilong1997** [comment]
有用的呀 把config分辨率里面文件改 就是有用的吧

**Comment by wangzilong1997** [comment]
小圆形出错的概率很大  朝右上出错的概率很大

**Comment by WhySRZ** [comment]
g/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********

每次跑程序在提示语  “如果你的脚本无法工作，上报issue时请copy如下信息”  上面一行有显示加载的配置，你要在对应的加载的配置里面改

**Comment by wangzilong1997** [comment]
。。。。数值参数不准呀。。。

**Comment by WhySRZ** [comment]
"press_coefficient": 1.475,这个值调一调就好了，如果每次失败原因是跳远了，那就调小，跳近了就调大。我自己调的，调到两千多都没挂！

**Comment by wangzilong1997** [comment]
。。。。

**Comment by Greedysky** [comment]
我mi5 用1.475参数跳了800+

**Comment by MrLevo520** [comment]
请尝试使用nightly版本
