### ISSUE TITLE
提供一种解决被ban的思路

### ISSUE THREAD

**Issue by mousehaow** [wangshub/wechat_jump_game#940]
我觉得可以抓一下在游戏过程中发的包，看看包里有什么内容可以反映人手动操作和脚本刷分的不同。现在随机点击位置和随机停留时间都已经不好使了，有可能微信程序本身已经给了跳一跳监测android的abd或者ios的usb连接监测接口。

**Comment by zmaxbin** [comment]
妈蛋，已经被封号，玩多少分都被清零。。。。

**Comment by daoying1994** [comment]
@mousehaow 你是拿新号测试的随机点击吗

**Comment by mousehaow** [comment]
@daoying1994 老号，我前天刷670多分，可以过夜，昨天刷了1024分今天早晨只能自己看到，在别人手机上不显示，现在倒是能刷刚又刷到1314，并且别人手机也显示，但是感觉晚上还是会被清除

**Comment by qianlishun** [comment]
都被关了，刷多少都是0，人家那边直接把我们拉黑掉了

微信官方发了声明了，他们表示元旦期间一直在加班做反外挂，想捷径走高分的，看哪方的技术团队强了。

**Comment by WhySRZ** [comment]
看看微信监测哪些数据，我门外汉，来学学

**Comment by mousehaow** [comment]
抓了gameinit的包，人家已经version9了，哈哈哈哈 。

**Comment by h55l55** [comment]
遇到加分的建筑从来不停留就算吧？我一遇到音乐盒啥的就拔掉数据线，五百多分，并不会被ban

**Comment by jifferent** [comment]
自己刷的分数，在自己的排行榜里是第一。但是在别人那里已经不显示了，连你的名字都没有。这叫做无声ban，就和贴吧ban一样，被ban的人随便发各种言论 黄暴帖 都无所谓，但是别人都看不见就是了。

**Comment by mousehaow** [comment]
@jifferent 哎，提交成绩也没有错误码，只是悄悄的ban你。。挺狠的

**Comment by Testlyy** [comment]
怎样反ban啊，有什么好的规避方法？有时候上榜了又被删掉

**Comment by Testlyy** [comment]
刚帮别人刷了几次500+都被删除了，最后一次619没有ban，每次跳一百步停一会或者找简单的位置停下手动跳几步，暂时没删除

**Comment by mousehaow** [comment]
@Testlyy 你那是秒删么？秒删的话你这作弊太明显了

**Comment by hero708** [comment]
确实很好奇腾讯ban的逻辑

**Comment by JWname** [comment]
就在刚刚我的分被干掉了

**Comment by MrLevo520** [comment]
@qianlishun除非从技术角度检测到我们作弊我们服气，但如果不管手动多少都封杀，直接按列表封杀就呵呵了

**Comment by qianlishun** [comment]
@MrLevo520  我感觉是按列表...

**Comment by MrLevo520** [comment]
@qianlishun无所谓啊，哈哈哈，我早就被封杀了:wink:

**Comment by tobealion** [comment]
手动不管跳多少分关了微信重进都是0…我了个凑…我只周一刷了一次…1700+，一直都没管，刚进去才发现…

**Comment by AzureWill** [comment]
好像是检测按压屏幕位置，代码都是只压一个地方，人工操作坐标就会不同

**Comment by mousehaow** [comment]
@AzureWill 这个按压点都是随机的，而且坐标是在200，860 左右随机的，完全和手动按压的点一样。我看了大神们抓下来的包，最后成绩上传的参数多了一个steps还有每次按压的绝对时间，那就有可能是加入的这两个参数来判断是不是脚本的

**Comment by fafactx** [comment]
step可以理解。绝对时间有什么用吗？

**Comment by MemoryReload** [comment]
@mousehaow  Silly checks like that can be handled easily with adding random ingredients, friend.

**Comment by MemoryReload** [comment]
@fafactx  If you do not add randoms, the absolute time interval between each jump (or may we say step) is nicely identical. Think about it. Humans can not do that in such precision.

**Comment by mousehaow** [comment]
看到了steps下的数据类似于每次点击手指轻微滑动所记录下的点，那么就不能用tap函数了，swipe应该更合适，目前还没有测试，因为昨天刷的1314分到今天还没清，懒得再刷了

**Comment by jifferent** [comment]
@mousehaow 
实测swipe也不行。

**Comment by mousehaow** [comment]
@jifferent 确实，我是ios的设备所以用的wda，wda的swipe是开始一直按着在最后一点时间滑动一下。所以steps字段每组只能记录下一个数据，和手动玩的5个数据还是有差别。感觉现在最后的操作阶段只有物理外挂能解决问题
