### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by ewrfedf** [wangshub/wechat_jump_game#942]
2018/01/05 11:21:04 Get http://192.168.0.106:8100/screenshot: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers): goroutine 1 [running]:
runtime/debug.Stack(0xc42004daf8, 0x128f740, 0xc42007d110)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x128f740, 0xc42007d110)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:57 +0xfcb
程序已崩溃，按任意键退出

**Comment by F-loat** [comment]
go 语言版的？怎么在这里反馈。。
