### ISSUE TITLE
遇到绿色顶小圆柱必死

### ISSUE THREAD

**Issue by dujijun007** [wangshub/wechat_jump_game#944]
程序版本号：1.1.1
**********
Screen: Physical size: 1920X1080
DeviceType: 小米6
参数选用：
{
    "under_game_score_y": 300,
    "press_coefficient": 1.44,
    "piece_base_height_1_2": 20,
    "piece_body_width": 70,

    "swipe" : {
      "x1": 500,
      "y1": 1600,
      "x2": 500,
      "y2": 1600
    }
}
**********

遇到问题：
  目前最高分844，但是不管在多少分时遇到绿色顶小圆柱必死，而且每次遇到它时弹射距离只到应跳距离的一半左右

**Comment by StrongManCoder** [comment]
我的iphone7P 也是跳到小绿柱子死了

**Comment by haitaoxu** [comment]
没错，我也发现这个问题了，跳不过去，估计是图像识别的问题

**Comment by MrLevo520** [comment]
如果有小圆柱截图，请上传

**Comment by StrongManCoder** [comment]
![image](https://user-images.githubusercontent.com/8347064/34597035-2f3b25f2-f21f-11e7-92d6-26d040f7ae14.png)

**Comment by MrLevo520** [comment]
请使用nightly版本，如果遇到这个问题，请把跳跃这个图的截图和计算后的截图发issue给我们，方便我们改进，谢谢
