### ISSUE TITLE
python3 并不支持自动重开的功能

### ISSUE THREAD

**Issue by haitaoxu** [wangshub/wechat_jump_game#947]
MacOs + ios
使用： python3 wechat_jump_auto_iOS.py

使用python3执行

发现脚本不能自动重来，原因是这段代码设置的“重新挑战”的按钮的位置，根本没被调用

def set_button_position(im):
    # 将swipe设置为 `再来一局` 按钮的位置
    global swipe_x1, swipe_y1, swipe_x2, swipe_y2
    w, h = im.size
    left = w / 2
    top = 1003 * (h / 1280.0) + 10
    swipe_x1, swipe_y1, swipe_x2, swipe_y2 = left, top, left, top

这是声明和赋值的地方，但是没有看到使用的地方

**Comment by F-loat** [comment]
`swipe_x1` 等是全局变量，发送 adb 命令时会调用，具体的值可以在配置文件里修改
