### ISSUE TITLE
wechat_jump_auto文件闪退

### ISSUE THREAD

**Issue by WL-233** [wangshub/wechat_jump_game#948]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: 3.6
**********

遇到问题：wechat_jump_auto文件闪退加出错
![bandicam 2018-01-05 14-21-04-223](https://user-images.githubusercontent.com/35032929/34597781-e4422c30-f223-11e7-82ec-049b4399bfb2.jpg)

**Comment by MagicSaring** [comment]
缺少依赖文件

**Comment by WL-233** [comment]
好像是adb的问题但是不知道在哪\

**Comment by WL-233** [comment]
![bandicam 2018-01-05 15-20-26-488](https://user-images.githubusercontent.com/35032929/34599202-0d22eb96-f22c-11e7-8dc1-3db37d128c11.jpg)

**Comment by F-loat** [comment]
请确保依赖已安装，adb已配置好，手机已连接，usb调试已开启
