### ISSUE TITLE
哪位大佬能发一个视频教程？

### ISSUE THREAD

**Issue by 867466965** [wangshub/wechat_jump_game#95]
哪位大佬能发一个视频教程，对于小白，真的太难了，完全看不懂哇。

**Comment by overthehump** [comment]
同求啊， 不懂编程的小白 求教程。。。  具体怎么安装啊？

**Comment by jcmsmm** [comment]
同求视频啊，不懂怎么操作

**Comment by 897902334** [comment]
哥几个  你们可以根据这个 来  https://github.com/wangshub/wechat_jump_game/issues/39

**Comment by jcmsmm** [comment]
能大概梳理一下步骤吗？转来转去都晕了

**Comment by windbeijing** [comment]
小白教程：

![qscode](https://user-images.githubusercontent.com/34977008/34459710-0ac3a5a4-ee33-11e7-9abe-ed6151d551f6.jpeg)
