### ISSUE TITLE
windows+ios怎么刷，有教程吗？

### ISSUE THREAD

**Issue by DomainCollection** [wangshub/wechat_jump_game#951]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: 3.5.5

改进和建议：无

**Comment by zxysilent** [comment]
虚拟机

**Comment by F-loat** [comment]
macOS 目前应该是必须的

**Comment by yangdelu855** [comment]
我用的VM 装的OS 调了好几天才好 超级麻烦

**Comment by zxysilent** [comment]
模拟器
