### ISSUE TITLE
代码还有人维护吗，微信已经有很大的动作了，我们也要动起来啊，哈哈哈哈

### ISSUE THREAD

**Issue by bblzjp** [wangshub/wechat_jump_game#952]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by MrLevo520** [comment]
看dev的几个版本就知道我们还在维护:grinning:

**Comment by lujimmy** [comment]
厉害了， @MrLevo520 是不是激动得没心情上班了

**Comment by MrLevo520** [comment]
@lujimmy 学生狗上毛班:wink:起来刚腾讯啊:stuck_out_tongue_winking_eye:

**Comment by hj7020580** [comment]
@MrLevo520 想知道腾讯现在的检测手段是什么，准备自己刚一波

**Comment by MrLevo520** [comment]
目前我们分析几个原因，一是分数异常高，二是每次命中正中间加高分，三是不停歇的玩不符合人类，:smile:四是看你以前做过弊，直接封。科科

**Comment by qq1148120042** [comment]
https://juejin.im/entry/5a4edc57518825732e2f18da  看1下这个   @MrLevo520

**Comment by hj7020580** [comment]
@MrLevo520  有第四条我已经不想刚了。。 不过前几条还是可以规避的，而且都不怎么需要改代码

**Comment by MrLevo520** [comment]
@qq1148120042在dev分支中我们加入了很多随机项，但还是会出现偶尔被封的现象，目前这个feature已被加入

**Comment by hj7020580** [comment]
@MrLevo520 咨询一下dev和dev-no-config-nightly这两个分支有什么区别

**Comment by MrLevo520** [comment]
@hj7020580目前dev是团队稳定分支，比master新。no-config是nightly版本，目前用于无视分辨率的操作，自适应所有分辨率，当然目前是实验开发版本，需要不断测试改进，欢迎提交测试

**Comment by hj7020580** [comment]
@MrLevo520 明白了，有新的想法我会随时提交测试。

**Comment by zihang-wu** [comment]
可以可以，支持一下，顺便跟大神学习一下 python😊。

**Comment by zhangkaka** [comment]
很想学opencv 和pandas

**Comment by hj7020580** [comment]
@MrLevo520  刚发布的releases 版可以看源码么
