### ISSUE TITLE
已逆向出按压时间与弹跳距离的精确关系式

### ISSUE THREAD

**Issue by SaneBow** [wangshub/wechat_jump_game#957]
### 关系式
```
d = (35/12) t^2 + (105/4) t
```

### 分析
逆向源码得出
- 竖直方向初速度：Vz = 70t
- 水平方向初速度：Vy = 135 + 15t
- 重力加速度：720

由初中物理可算出水平位移与按压时间t的关系
已动态调试js验证，可无限次跳中心，且计算出距离与目标距离严格相等。
在该项目中具体实现时需根据分辨率等比例调整系数。

**Comment by F-loat** [comment]
逆向的话，可以看下小程序本身是如何适配不同分辨率的，会比较有用

**Comment by zgcbj** [comment]
这个公式没有考虑按压的压缩距离。即起跳点和落地点不是同一个水平面。这是第一个误差。
第二个问题是：
这个d是三维空间的距离，截屏是2维，有透视效果影响。

**Comment by SaneBow** [comment]
在pr #841中已有具体实现
