### ISSUE TITLE
跳一跳应该是有服务器黑名单了 （含抓包数据）

### ISSUE THREAD

**Issue by Erimus-Koo** [wangshub/wechat_jump_game#958]
## 结论
存在服务器黑名单。

## 1. 分数提交
抓包看了下，应该是这个post。  
```
https://mp.weixin.qq.com/wxagame/wxagame_bottlereport
```
提交的内容大致就是游戏的一些数据。
![](http://upload-images.jianshu.io/upload_images/1980018-60323509313a6cd7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

返回并没有报错。
![](http://upload-images.jianshu.io/upload_images/1980018-8ee2d777f843e67e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

至此，我理解是分数上传成功了。

## 2. 好友分数读取
```
https://mp.weixin.qq.com/wxagame/wxagame_getfriendsscore
```
![](http://upload-images.jianshu.io/upload_images/1980018-0413c56cc9ba3e5a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

# history_best_score=0
所以，修改后的算法也没法测了。也没小号可以用，先凉着吧。

## 3. 反作弊思路

- 检测游戏数据，点击位置，间隔时间，持续游戏时间，中心连击数，总分和跳跃次数关系，特殊方块应对，等等。
- 检测客户端，防止跨客户端代打等等。
- 检测环境，root越狱adb等等。或者按键精灵touchelf等等。

还有啥坑点？

补充两个反作弊的方法。

- 每局把跳跃系数调整下。人类玩家在数次点击后就能适应，但机器目前普遍不行。
- 改变背景填充方式，放弃垂直渐变，用圆形或者其它角度，或者混入pattern，或者雪花纸屑浮层。现在的图形识别方法全部失效。

但这两个反作弊的方法，机器学习都能破解。

**Comment by dosmlp** [comment]
分数提交不是bottlereport

**Comment by Erimus-Koo** [comment]
@dosmlp 可是我看到一共就这些请求啊
![image](https://user-images.githubusercontent.com/17139670/34604037-5f6efdd0-f241-11e7-9ee8-97dc56d51462.png)

**Comment by BMlovePanda** [comment]
settlement那个请求里面有提交之后返回的errcode，你看看是多少，如果是108，那么就是系统判定拟作弊。

**Comment by BMlovePanda** [comment]
然后你去看拟的settlement的url里面，选择textview，可以看到你提交的数据，不过是加密的，要先解密。

**Comment by Erimus-Koo** [comment]
![image](https://user-images.githubusercontent.com/17139670/34605386-6200a0f8-f246-11e7-9b8d-aafd89fb4f73.png)

看，我本地算法应该OK了。这里通过的。就是黑名单啦。

**Comment by MrLevo520** [comment]
看来，是不是只能黑掉服务器的黑名单了？喵喵喵？？？

**Comment by littlepinecone** [comment]
黑名单妥妥的是有的,我现在纯手动玩几十分都无法更新, 自己看排行榜分数是0,别人在排行榜里面看不到我

**Comment by Erimus-Koo** [comment]
想到两个反作弊的方法。
- 每局把跳跃系数调整下。人类玩家在数次点击后就能适应，但机器目前普遍不行。
- 改变背景填充方式，放弃90度渐变，用其他方式。现在的图形识别方法全部失效。

但这两个反作弊的方法，机器学习都能破解。

**Comment by yangfangqun** [comment]
发现排行榜里不显示是因为是0分，排行榜里是不会显示0分的

**Comment by Erimus-Koo** [comment]
@yangfangqun 回的吧 在最下面  
就不晓得一次封多久

**Comment by yangfangqun** [comment]
@Erimus-Koo  那就不知道了，因为排行榜里只有我一个0分，注册一个新号保持0分试试吧

**Comment by Erimus-Koo** [comment]
@yangfangqun 没手机了呀 不晓得微信号淘宝有卖不

**Comment by sunmengxiang** [comment]
早上10点刷了一次700分，分数只能自己看，过了一小时后700分被清理。
中午修改了tap函数为随机数后，再次刷550分，前半小时只能自己看，过了半小时分数出现在好友榜单中。
可以得出微信很大概率是有观察名单，若后续名单中的人员再次游戏后，判定游戏过程中点击点的随机性，来决定上榜单。希望能帮到大家
