### ISSUE TITLE
测试红米4X，经常没跳几步，就跳到棋子的边缘了，然后就挂了，什么原因？

### ISSUE THREAD

**Issue by doitbull** [wangshub/wechat_jump_game#959]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: x
OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by MrLevo520** [comment]
请尝试最新版或者nightly版本，下次提交请注意issue提交规范，谢谢

**Comment by wf2311** [comment]
@doitbull 你是不是开了桌面悬浮球，关了就好了

**Comment by doitbull** [comment]
@MrLevo520  nightly版本就是master吗？git chcekcout master?
