### ISSUE TITLE
本小白pip install -r requirements.txt这一步安装不了啊

### ISSUE THREAD

**Issue by mjzcyhp** [wangshub/wechat_jump_game#96]

**Comment by mjzcyhp** [comment]
生成requirements.txt文件
pip freeze > requirements.txt
安装requirements.txt依赖
pip install -r requirements.txt
按如上操作后，显示必须要有一个需求？怎么回事啊？大神快来啊！

提示如下，怎么搞啊
《you must give at least one requirement to install》

**Comment by wangshub** [comment]
你好，请用项目里的requirements.txt
https://github.com/wangshub/wechat_jump_game/blob/master/requirements.txt
@mjzcyhp

**Comment by mjzcyhp** [comment]
@wangshub 好的，谢谢

**Comment by Jun0413** [comment]
我这个语句无法运行 所以我手动的一个一个用pip装了
