### ISSUE TITLE
请安装adb及驱动并设置环境变量

### ISSUE THREAD

**Issue by zhangerbeng** [wangshub/wechat_jump_game#965]
<!-##**

> Python 2.7.14 (default, Sep 25 2017, 09:54:19) 
> [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
> Type "copyright", "credits" or "license()" for more information.
> >>> 
> === RESTART: /Users/ZN/Desktop/wechat_jump_game-master/wechat_jump_auto.py ===
> 请安装 ADB 及驱动并配置环境变量

**
android+mac配置，运行时出现了这样的提示。但是已经在终端安装了adb，并且adb devices 连接手机设备成功：如下所示
ZNdeMacBook-Air:~ ZN$ adb devices
List of devices attached
UEU4C16B25008137	device

求问各位大神这是什么问题啊？
感谢提交问题，提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容。
请说清楚自己遇到了什么问题，不然可能被 close。
还没有自己机型配置文件的请自己去创建一个，好用的话欢迎 PR。

### 如果代码不能启动，执行的时候直接报错

请贴出：
1. 代码版本号，代码中的 VERSION 变量
2. 使用环境（操作系统、Python 版本）
3. 尽量完整的代码执行命令，和打印的错误信息

### 如果代码能运行，但是达不到想要的效果

请贴出：
1. 代码版本号，代码中的 VERSION 变量
2. 使用环境 (运行脚本中已包含自动识别功能，复制即可)
3. 遇到问题（如有可能，请详细描述，建议附上截图。不负责的 issue 可能会被 close）
具体实例如下，按照该例进行提交 issue
-->

程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by Code6666** [comment]
你可以 试一下 将你 电脑上的  adb。exe  覆盖掉  这个 项目中的  adb.exe  ，  可能是 因为 adb 的版本 不兼容的问题  ，  我也遇到这样的问题了  ，  然后 替换成  自己电脑上 就好了

**Comment by Code6666** [comment]
@zhangerbeng
