### ISSUE TITLE
请安装 ADB 及驱动并配置环境变量

### ISSUE THREAD

**Issue by zhangerbeng** [wangshub/wechat_jump_game#966]
<!-##**

Python 2.7.14 (default, Sep 25 2017, 09:54:19)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "copyright", "credits" or "license()" for more information.

=== RESTART: /Users/ZN/Desktop/wechat_jump_game-master/wechat_jump_auto.py ===
请安装 ADB 及驱动并配置环境变量
**
android+mac配置，运行时出现了这样的提示。但是已经在终端安装了adb，并且adb devices 连接手机设备成功：如下所示
ZNdeMacBook-Air:~ ZN$ adb devices
List of devices attached
UEU4C16B25008137	device

求问各位大神这是什么问题啊？

**Comment by MrLevo520** [comment]
请使用release的app版本，或者使用adb免配置版，操作具体见wiki

**Comment by zhangerbeng** [comment]
release的app版本是哪一个？是要下载adb 的app版本吗？

**Comment by Code6666** [comment]
你可以 试一下 将你 电脑上的  adb。exe  覆盖掉  这个 项目中的  adb.exe  ，  可能是 因为 adb 的版本 不兼容的问题  ，  我也遇到这样的问题了  ，  然后 替换成  自己电脑上 就好了

**Comment by zhangerbeng** [comment]
可是我的电脑是mac，应该不会用到adb.exe～ @Code6666
