### ISSUE TITLE
闪退，PowerShell查看问题

### ISSUE THREAD

**Issue by Whyat** [wangshub/wechat_jump_game#968]
PS C:\Users\Whyat> python C:\Users\Whyat\Desktop\wechat_jump_auto.py
No module named 'common'
请将脚本放在项目根目录中运行

请问如何解决

**Comment by chenony** [comment]
命令不对

**Comment by mozjiang** [comment]
使用 cd 命令进入脚本所在的目录(在此例中为 C:\Users\Whyat\Desktop)，然后键入
```
python wechat_jump_auto.py
```

**Comment by hsj1993** [comment]
试过 还是这样的报错

**Comment by MrLevo520** [comment]
请使用release的app版本，或者使用adb免配置版
