### ISSUE TITLE
No module named 'common' 请将脚本放在项目根目录中运行 请检查项目根目录中的 common 文件夹是否存在

### ISSUE THREAD

**Issue by hsj1993** [wangshub/wechat_jump_game#971]
运行python代码时出现的报错

程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by MrLevo520** [comment]
请使用release的app版本，或者使用adb免配置版，操作具体见wiki
