### ISSUE TITLE
图像检测BUG会识别到未消失的白环上

### ISSUE THREAD

**Issue by 0x3A2B** [wangshub/wechat_jump_game#972]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
Device: HWFRD
Phone OS: 7.0
Host OS: win32
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
**********
![1515205402_d](https://user-images.githubusercontent.com/15076154/34635555-5afdd0e2-f2cc-11e7-9e13-0cacf49a42e2.png)

**Comment by MrLevo520** [comment]
请尝试使用最新的nightly版本

**Comment by zhangjingxiang666** [comment]
延长跳跃的间隔时间
在wechat_jump_auto.py里，把time.sleep(random.uniform())后面括号里的值改为（2.2,2.6），即time.sleep(random.uniform(2.2, 2.6))

**Comment by cosimahan** [comment]
同楼主 最新夜版。 
![image](https://user-images.githubusercontent.com/10095291/34638053-08c47942-f2ff-11e7-9470-86db34943271.png)

**Comment by zhangjingxiang666** [comment]
原因就是棋子刚跳上木墩，圆环还没散去就开始截屏分析。
解决方法是，延长跳跃的间隔时间呗！即让棋子在木墩上等个两秒多点以后再截屏，就行呀！
也就是编辑一下wechat_jump_auto.py这个文件，把time.sleep(random.uniform())后面括号里的值改为（2.2,2.6），即time.sleep(random.uniform(2.2, 2.6))

**Comment by 0x3A2B** [comment]
希望能在不设置延时 也就是保证速度的同时解决问题

**Comment by leon0625** [comment]
今天下载代码试了下，玩了几把分数都不过千就死了，加打印看了下，也发现这个问题，识别到扩散的白环上，把延迟改为（1.7, 2.2）好多了，现在2000多分了还没死

**Comment by MrLevo520** [comment]
@leon0625腾讯的程序员改了，给我们扩大干扰项，我记得以前的圆环没那么大，而且出现时效没那么长，不知道是不是错觉，哈哈哈

**Comment by 0x3A2B** [comment]
圆环的颜色貌似是不变的 可以吧颜色存起来做特判？
