### ISSUE TITLE
无法启动，执行的时候直接报错

### ISSUE THREAD

**Issue by Jeblqr** [wangshub/wechat_jump_game#973]
遇到问题:无法启动，执行的时候直接报错
1. 代码版本号，代码中的 VERSION 变量:1.1.1
2. 使用环境（操作系统、Python 版本）:windows10 1703,Python 3.6.2
3. 尽量完整的代码执行命令，和打印的错误信息:
>>> C:\Users\luoqi\Desktop\wechat_jump_game-master\Tools\adb\wechat_jump_py3.py
  File "<stdin>", line 1
    C:\Users\luoqi\Desktop\wechat_jump_game-master\Tools\adb\wechat_jump_py3.py
改进和建议：无

**Comment by MrLevo520** [comment]
请使用release的app版本，或者使用adb免配置版本
