### ISSUE TITLE
【反作弊】如果腾讯这么搞，怎么应对？

### ISSUE THREAD

**Issue by Erimus-Koo** [wangshub/wechat_jump_game#979]
想到几个反作弊的方法，大家探讨下。如果腾讯这么干，怎么解？

## 跳跃系数随机
现在我的算法 #969 ，棋子跳过全屏宽度大约需要1700ms。  
如果游戏每局把【跳跃系数】在一定范围随机调整下。  
人类玩家在数次点击后就能适应，但目前算法普遍不行。除非机器学习。  

## 增加截屏识别难度

- 改变背景填充方式，放弃90度渐变，改用圆形渐变或者其他角度渐变。
- 增加浮层，飘个雪花，飞个特效之类的。
- 棋子变色，combo之后给棋子点特效。

现在的图形识别方法基本全部失效。回到手动取点。或者机器学习。

## post数据加盐验证
直接改分的渠道也基本封死了。

还有其他招嘛？聊聊

**Comment by doitbull** [comment]
什么意思？按压的力度随机调整？

**Comment by Erimus-Koo** [comment]
就比如开场第一个方块，假设现在的按压需要1000ms，腾讯给个随机20%范围，比如只要800ms了。  
那么现在配置的固定config数值，就更容易跳偏移。  
而真人用户，在跳跃三五次之后，就能掌握这个变化。
人脑学习的优越性嘛。

**Comment by gugudeshubao** [comment]
模拟的触摸和手指真实触摸屏幕是肯定不一样的吧

**Comment by Erimus-Koo** [comment]
对机器来说其实是一样，就是一个像素点。
我目前的算法，也已经模拟了按下到离开这段时间的位移。

**Comment by lyx0224** [comment]
检测跳动间隔，如果连续多次间隔一样，视为机器操作。
