### ISSUE TITLE
iOS端的怎么链接被拒绝？

### ISSUE THREAD

**Issue by xiao-Warning** [wangshub/wechat_jump_game#98]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053cf0f0>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by GhostClock** [comment]
我也遇到了

**Comment by wangshub** [comment]
期待ios大神

**Comment by MrLevo520** [comment]
同样遇到

**Comment by jack80342** [comment]
同遇到😢午饭、晚饭还没吃

**Comment by zhuaizi888** [comment]
@xiao-Warning 兄弟解决了么  我也遇到这个问题  转发端口不行呀

**Comment by yuanbenkai** [comment]
WDA都装不了。。。Carthage装不上去
