### ISSUE TITLE
可以了，被ban掉的现在别人排行榜能显示了

### ISSUE THREAD

**Issue by zkl99999** [wangshub/wechat_jump_game#983]
程序版本号：x.x.x
**********
Screen: Physical size: 1920*1080
Density: Physical density: x
Override density: x
Device: mi 5s
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by MrLevo520** [comment]
下次提交请备注版本和型号，不然别的小伙伴也不知道你是什么版本什么情况成功了，谢谢

**Comment by hj7020580** [comment]
@zkl99999 我被ban了还是不能.

**Comment by baolw** [comment]
@MrLevo520 确实可以显示了，我之前小号分数被 ban了，然后手动玩了一局，去大号看小号的排名，发现没上榜，刚才手动玩了一局小号，再去大号看，发现排名有了

**Comment by littlepinecone** [comment]
亲测不行

**Comment by chchuj** [comment]
1.1.1版本刷至1600被卦
今日解封，手机和auto 1.1.1都能上排行
设备：一加A0001

**Comment by soysaucemo** [comment]
昨天解封，今天又封了，这两天都没跑过代码，看来服务器黑名单还在
