### ISSUE TITLE
adb显示attached，但是找不到devices，没有设备号

### ISSUE THREAD

**Issue by 1426860561** [wangshub/wechat_jump_game#984]
![image](https://user-images.githubusercontent.com/35169604/34640227-b6b8eae0-f329-11e7-8c9e-e19d0608e050.png)

不显示设备号，已安装adb环境，运行地时候还提示安装adb及配置环境，这是为何，请大佬指教

**Comment by soysaucemo** [comment]
手机上看看有没有提示授权计算机的弹窗，要确认授权。

**Comment by 1426860561** [comment]
之前授过了一次了，我再试试，谢谢

**Comment by Robertccl** [comment]
要是改过防火情设置了，可能需要重新添加进去

**Comment by 1426860561** [comment]
已经解决，谢谢各位

**Comment by MrLevo520** [comment]
@1426860561请说下解决方案，以免别的小伙伴出现的问题，谢谢哈

**Comment by Gaitman** [comment]
一样啊，win10，python3.5，小米5，运行脚本显示error: no devices/emulators found
请安装 ADB 及驱动并配置环境变量
adb devices也显示List

**Comment by 1426860561** [comment]
我的也是win10，python3.5，只不过是乐视手机，显示list但是不显示设备号，应该就是手机授权计算机的原因，之前可能是我把手机授权权限给关了，下了个360手机助手，首次链接时会提示授权计算机，重新授权一次就行了，最好把那个一律为此计算机授权勾上，以后就不用每次授权了。

**Comment by Gaitman** [comment]
不好意思，好久没登录，刚看到，谢谢
 

Sent: Sunday, January 07, 2018 at 10:40 AM

**Comment by nmshuishui** [comment]
我的手机是小米MAX2，但是执行 adb devices的时候，也是空列表，只显示List of devices attached。我装360手机助手也不管用，多次插拔都没有提示说授权什么的
