### ISSUE TITLE
通过在落地点的位置增加一个随机增量来防止被ban掉

### ISSUE THREAD

**Issue by walegahaha** [wangshub/wechat_jump_game#985]
在wechat_jump_auto.py中的find_piece_and_board(im)函数结尾增加如下使得每次落地不会固定，分数不会上涨过快，缺点是刷分速度较慢，个别情况容易失败。手机为一加3T，屏幕分辨率1920×1080，其他手机可以自行调试

import random
random_x = random.randint(0,25)
random_y = random.randint(0,25)

return piece_x, piece_y, board_x+random_x, board_y+random_y

**Comment by walegahaha** [comment]
random_x = random.randint(0,8)×3
random_y = random.randint(0,8)×3

效果更好

**Comment by MrLevo520** [comment]
你好，这个对于小圆柱误差太大，我们已经进行排除，谢谢反馈
