### ISSUE TITLE
关于添加『控分』功能

### ISSUE THREAD

**Issue by groaptx** [wangshub/wechat_jump_game#986]
之前有修改post方式直接定义分数，现在行不通了。想着是否可以在跳之前输入一个分数，然后就可以跳到这个分数再结束游戏。
以下为思路:
1.截屏识别并读取左上角分数
2.距离目标分数的差在32分以上时正常跳跃
3. 32分以内时两次跳跃停留时间不超过1s，最多3连靶心，10分以最多二连靶心，3分内不中靶心。
4.达到目标分数后蓄力2.5s

 有什么想法可以接着补充_(:_」∠)_

**Comment by Erimus-Koo** [comment]
想跳准有多难，想跳偏就有多难。

**Comment by grb2015** [comment]
初次使用，现在运行起来了怎么结束？只能等吗？

**Comment by Erimus-Koo** [comment]
命令行的话 ctrl+c 多按几次
其他方式的话去进程里终止python吧

**Comment by grb2015** [comment]
对，直接拔掉USB就可以了

**Comment by mingxin-yang** [comment]
命令行直接Ctrl + C就行了吧

**Comment by mingxin-yang** [comment]
命令行直接Ctrl + z 终止脚本就可以了
