### ISSUE TITLE
shell input swipe 语句不执行了好想 

### ISSUE THREAD

**Issue by huachao0410** [wangshub/wechat_jump_game#988]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by huachao0410** [comment]
点还能拾取到，但是画面不做跳转。语句不执行

**Comment by agan123** [comment]
开了usb调试（安全设置），允许通过usb调试修改权限或模拟点击 了没？
该选项一般在usb调试下面一点

**Comment by huachao0410** [comment]
@agan123 usb调试开了，adb devices 正常执行，抓屏也抓得到，拾取坐标也可以，os.system()里面的都打印了，但是手机上面不跳

**Comment by Charltsing** [comment]
安卓版本号太低吧，是不是低于4.4？

**Comment by huachao0410** [comment]
@Charltsing  安卓7.1.1   Mi6
