### ISSUE TITLE
关于算法改进的一点小意见

### ISSUE THREAD

**Issue by ga0wang** [wangshub/wechat_jump_game#989]
程序版本号：1.1.1
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
Override density: 
Device: cancro
Phone OS: 6.0.1
Host OS: win32
Python: 2.7.14
**********

每个砖块的形状基本都是关于y轴对称（长方形除外），所以是不是可以考虑只计算棋子和砖块的对称轴横坐标，然后用三角函数计算跳跃的距离？
这样的话，对于砖块，只需要在扫描到砖块所在的区域后，便可以快速计算出对称轴坐标，而不需要考虑纵坐标，从而提高计算的速度和准确度。
我在自己手机上测试修改后的代码，准确度确实有提升...
目前我只修改了主函数计算跳跃距离的代码
old: `math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2)`
new:`(abs(board_x-piece_x)+abs(board_y-piece_y))/2 * 1.414 * 1.09`

**Comment by Erimus-Koo** [comment]
不要纠结直线距离，看这个。
https://github.com/Erimus-Koo/wechat_jump_game/blob/master/wechat_jump_auto_slim.py
