### ISSUE TITLE
新抓下来的包，快来看看，脚本玩的和手动玩的还真不一样。。

### ISSUE THREAD

**Issue by mousehaow** [wangshub/wechat_jump_game#990]
这个是脚本玩之后上传的加密数据：
{"score":1014,"times":729,"game_data":"{\"seed\":1515291457364,\"action\":[[0.718,1.29,false],[0.401,1.94,false],[0.868,0.99,false],[0.513,1.7,false],[0.851,1.06,false],[0.903,0.92,false],[0.373,1.97,false],[0.903,0.99,false],[0.734,1.26,false],[0.684,1.36,false],[0.801,1.12,false],[0.435,1.87,false],[0.58,1.56,false],[0.496,1.8,false],[0.351,2.07,false],[0.416,1.9,false],[0.629,1.46,false],[0.822,1.12,false],[0.519,1.7,false],[0.534,1.67,false],[0.399,1.94,false],[0.45,1.84,false],[0.803,1.19,false],[0.433,1.87,false],[0.79,1.16,false],[0.842,1.06,false],[0.833,1.06,false],[0.365,2,false],[0.852,1.06,false],[0.543,1.67,false],[0.417,1.9,false],[0.5,1.73,false],[0.602,1.56,false],[0.751,1.23,false],[0.588,1.56,false],[0.349,2.04,false],[0.851,1.02,false],[0.526,1.67,false],[0.63,1.5,false],[0.87,0.99,false],[0.797,1.26,false],[0.694,1.43,false],[0.641,1.46,false],[0.275,2.21,false],[0.482,1.77,false],[0.809,1.19,false],[0.821,1.09,false],[0.734,1.26,false],[0.73,1.29,false],[0.503,1.7,false],[0.81,1.16,false],[0.499,1.73,false],[0.623,1.5,false],[0.564,1.6,false],[0.72,1.36,false],[0.513,1.73,false],[0.841,1.12,false],[0.683,1.36,false],[0.695,1.33,false],[0.8,1.12,false],[0.366,2,false],[0.339,2.07,false],[0.716,1.36,false],[0.566,1.6,false],[0.823,1.12,false],[0.344,2.04,false],[0.536,1.7,false],[0.466,1.84,false],[0.299,2.14,false],[0.309,2.11,false],[0.572,1.6,false],[0.815,1.16,false],[0.501,1.77,false],[0.526,1.73,false],[0.418,1.94,false],[0.465,1.8,false],[0.819,1.16,false],[0.39,1.97,false],[0.804,1.16,false],[0.284,2.17,false],[0.269,2.21,false],[0.401,1.97,false],[0.813,1.16,false],[0.505,1.73,false],[0.38,1.97,false],[0.533,1.67,false],[0.584,1.56,false],[0.702,1.36,false],[0.58,1.6,false],[0.397,1.94,false],[0.266,2.21,false],[0.433,1.87,false],[0.65,1.5,false],[0.898,0.95,false],[0.876,0.99,false],[0.723,1.33,false],[0.65,1.5,false],[0.28,2.24,false],[0.466,1.8,false],[0.888,0.99,false],[0.802,1.19,false],[0.731,1.26,false],[0.761,1.19,false],[0.43,1.87,false],[0.791,1.19,false],[0.584,1.6,false],[0.595,1.56,false],[0.566,1.6,false],[0.731,1.26,false],[0.533,1.67,false],[0.886,0.95,false],[0.666,1.39,false],[0.818,1.09,false],[0.948,0.82,false],[0.441,1.9,false],[0.284,2.17,false],[0.712,1.29,false],[0.582,1.56,false],[0.862,1.06,false],[0.342,2.04,false],[0.572,1.6,false],[0.481,1.8,false],[0.4,1.97,false],[0.33,2.07,false],[0.619,1.5,false],[1.016,0.72,false],[0.499,1.73,false],[0.557,1.63,false],[0.394,2,false],[0.449,1.84,false],[0.887,0.95,false],[0.393,1.94,false],[0.881,0.99,false],[0.291,2.14,false],[0.315,2.11,false],[0.444,1.87,false],[0.815,1.12,false],[0.531,1.67,false],[0.362,2,false],[0.566,1.63,false],[0.61,1.53,false],[0.748,1.26,false],[0.617,1.5,false],[0.311,2.11,false],[0.242,2.24,false],[0.522,1.7,false],[0.617,1.56,false],[0.18,2.38,false],[0.867,1.02,false],[0.718,1.36,false],[0.75,1.26,false],[0.196,2.34,false],[0.504,1.73,false],[0.922,0.89,false],[0.949,0.82,false],[0.79,1.16,false],[0.856,1.06,false],[0.586,1.56,false],[0.839,1.16,false],[0.565,1.6,false],[0.689,1.33,false],[0.62,1.56,false],[0.797,1.16,false],[0.478,1.77,false],[0.85,1.02,false]],\"musicList\":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],\"touchList\":[[220,517.5],[225.5,517],[227.5,518],[224,525],[223,515.5],[223,525],[219.5,523],[220.5,522.5],[226.5,521],[220,517],[220,517],[219,521],[227.5,520.5],[228,520],[218.5,520.5],[226,524],[227,520],[227.5,522],[224.5,525],[221,517.5],[224,521],[219,515.5],[220,519],[225,522.5],[221,516],[227,517],[221.5,518.5],[221.5,518],[220.5,521.5],[227,518.5],[223,522.5],[220.5,518.5],[226.5,520.5],[218.5,517],[220.5,522],[220.5,519],[226,521],[219,516.5],[227.5,517],[225,517.5],[224,523.5],[225,519],[218.5,515.5],[226.5,518.5],[227,524],[218.5,516.5],[227,517],[226.5,521],[223,516],[224.5,524],[221.5,523.5],[226.5,517],[222.5,515.5],[219,523],[223.5,519.5],[227.5,523],[225,522.5],[219.5,520],[224.5,520],[220,523.5],[221.5,517],[224.5,518.5],[223.5,517.5],[226.5,524],[219.5,520],[226.5,515],[224.5,517],[223,516],[220,515],[226.5,520.5],[219.5,522.5],[219.5,524.5],[228,518],[227,521],[219.5,517],[224.5,524.5],[222.5,522.5],[224.5,522.5],[218.5,522],[227.5,521],[220,520.5],[223,520.5],[220.5,522.5],[227,517.5],[224,515.5],[219,521],[220.5,520.5],[220.5,523],[218.5,518.5],[220.5,518.5],[220,515],[224,517.5],[218.5,515],[226,523.5],[218.5,515],[218.5,523],[224,519],[222.5,518],[221.5,519.5],[218,521],[221.5,522],[225,517],[225.5,522.5],[227,516],[221.5,517.5],[219.5,522.5],[221,521],[224.5,522.5],[218,522.5],[222,518.5],[219.5,520.5],[227,523],[218.5,515.5],[224.5,523],[225,516.5],[221.5,521.5],[224.5,523.5],[222.5,519.5],[222.5,519.5],[218.5,523],[219,519],[220,517.5],[221.5,517],[227,515.5],[227,524],[222.5,519],[221.5,518.5],[223,523],[220.5,521],[223.5,522],[227,523],[219,516],[225.5,521.5],[220.5,520],[221,522],[224,524],[222.5,523.5],[218,521],[221,521.5],[221.5,517.5],[219,523],[221,520.5],[219.5,515.5],[223.5,523.5],[221.5,515.5],[218.5,522.5],[222,524.5],[227,522.5],[222,515.5],[226.5,519.5],[225,521.5],[224,520.5],[223,517.5],[222,524.5],[223,521.5],[221,523.5],[219,520.5],[226,520],[219,517.5],[223,524.5],[222.5,525],[218.5,521.5],[225.5,524],[223.5,523],[221,518]],\"steps\":[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]],\"timestamp\":[1515291461018,1515291463936,1515291466192,1515291468946,1515291471756,1515291474843,1515291477971,1515291480474,1515291483260,1515291486129,1515291488794,1515291491796,1515291494449,1515291497348,1515291499882,1515291502450,1515291505234,1515291507914,1515291510896,1515291513597,1515291516248,1515291518947,1515291521448,1515291524264,1515291526688,1515291529552,1515291532532,1515291535599,1515291538003,1515291540889,1515291543657,1515291546416,1515291548952,1515291551766,1515291554751,1515291557502,1515291560085,1515291563179,1515291565819,1515291568402,1515291571521,1515291574236,1515291577129,1515291579872,1515291582538,1515291585054,1515291587954,1515291590839,1515291593676,1515291596584,1515291598974,1515291601706,1515291604338,1515291606990,1515291609640,1515291612493,1515291615190,1515291618106,1515291620796,1515291623523,1515291626407,1515291628751,1515291631192,1515291633861,1515291636744,1515291639769,1515291642442,1515291645127,1515291647910,1515291650516,1515291653009,1515291655778,1515291658579,1515291661265,1515291663909,1515291666645,1515291669144,1515291672246,1515291674730,1515291677779,1515291680315,1515291682846,1515291685215,1515291688289,1515291691067,1515291693546,1515291696146,1515291698850,1515291701833,1515291704617,1515291707298,1515291709864,1515291712582,1515291715222,1515291718216,1515291721117,1515291723873,1515291726700,1515291729183,1515291731578,1515291734717,1515291737603,1515291740341,1515291743287,1515291745751,1515291748568,1515291751270,1515291754036,1515291756738,1515291759703,1515291762465,1515291765805,1515291768721,1515291771607,1515291774470,1515291777254,1515291779692,1515291782655,1515291785272,1515291788296,1515291790850,1515291793607,1515291796127,1515291798676,1515291801053,1515291803523,1515291806657,1515291809093,1515291811625,1515291813976,1515291816471,1515291819681,1515291822194,1515291825267,1515291827477,1515291829918,1515291832309,1515291835227,1515291837981,1515291840411,1515291843244,1515291845998,1515291848711,1515291851632,1515291854234,1515291856532,1515291859146,1515291861948,1515291864162,1515291867198,1515291870012,1515291872883,1515291875214,1515291877882,1515291881015,1515291884059,1515291886949,1515291889930,1515291892450,1515291895485,1515291898225,1515291901050,1515291903685,1515291906671,1515291909532],\"version\":2}"}
这个是手动玩的加密数据：
{"score":143,"times":722,"game_data":"{\"seed\":1515289297048,\"action\":[[0.638,1.46,false],[0.513,1.73,false],[0.463,1.87,false],[0.487,1.8,false],[0.436,1.9,false],[0.42,1.94,false],[0.612,2.48,false],[0.573,1.63,false],[0.783,1.23,false],[0.438,1.9,false],[0.459,1.9,false],[0.629,1.53,false],[0.835,1.12,false],[0.74,1.29,false],[0.634,1.5,false],[0.849,1.06,false],[0.77,1.26,false],[0.752,1.26,false],[0.752,1.29,false],[0.826,1.12,false],[0.618,1.5,false],[0.656,1.46,false],[0.393,1.97,false],[0.782,1.23,false],[0.682,1.43,false],[0.464,1.84,false],[0.903,0.99,false],[0.729,1.29,false],[0.372,2.04,false],[0.618,1.53,false],[0.473,1.84,false],[0.666,1.39,false],[0.803,1.19,false],[0.498,1.73,false],[0.68,1.43,false],[0.853,1.09,false],[0.51,1.77,false],[0.519,1.73,false],[0.728,1.29,false],[0.786,1.19,false],[0.903,0.92,false],[0.839,1.06,false],[0.413,1.94,false],[0.351,2.04,false],[0.808,1.16,false],[0.386,2,false],[0.739,1.26,false],[0.778,1.19,false],[0.77,1.26,false],[0.556,1.67,false],[0.88,1.02,false],[0.82,1.16,false],[0.505,1.73,false],[0.92,0.95,false],[0.755,1.26,false],[0.493,1.8,false],[0.73,1.29,false],[0.504,1.77,false],[0.776,1.23,false],[0.22,2.34,true],[0.689,1.39,false],[0.819,1.12,false],[0.399,1.94,false],[0.623,1.56,false],[0.641,1.5,false],[0.857,1.06,false]],\"musicList\":[true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],\"touchList\":[[219,530.5],[222.5,515.5],[222,512.5],[222.5,511.5],[226,508.5],[226.5,509],[221.5,510],[219.5,519],[222,511],[220,509],[219,515.5],[220.5,512.5],[218.5,516.5],[216.5,515.5],[225,520.5],[228,515.5],[223,520],[225.5,521.5],[220,527],[222.5,523],[223,519],[221,518.5],[222.5,517],[221.5,517],[229.5,514.5],[227.5,513],[225,519.5],[224.5,516.5],[224,515.5],[222,519],[220,517],[222,515.5],[224,515],[222.5,516.5],[228,517],[227,518.5],[226,519.5],[220.5,519],[225.5,520],[224,510.5],[221.5,515],[223,513],[225,510.5],[227,506.5],[225.5,511.5],[224,514.5],[221,516.5],[226,518.5],[222.5,521.5],[225,513],[222,514],[228.5,513.5],[227,511],[224.5,519.5],[223,521],[225.5,515],[223,517],[226,511],[227,511.5],[227,510.5],[228,509.5],[231,508.5],[229.5,508],[231.5,509],[233,504],[231,506.5]],\"steps\":[[219,530.5,219,530.5,219,530.5,219,530.5,219,530.5],[222.5,515.5,222.5,515.5,222.5,515.5,222.5,515.5,222.5,515.5],[222,512.5,222,512.5,222,512.5,222,512.5,222,512.5],[222.5,511.5,222.5,511.5,222.5,511.5,222.5,511.5,222.5,511.5],[226,508.5,226,508.5,226,508.5,226,508.5,226,508.5],[226.5,509,226.5,509,226.5,509,226.5,509,226.5,509],[221.5,510,221.5,510,221.5,510,221.5,510,221.5,510],[219.5,519,219.5,519,219.5,519,219.5,519,219.5,519],[222,511,222,511,222,511,222,511,222,511],[220,509,220,509,220,509,220,509,220,509],[219,515.5,219,515.5,219,515.5,219,515.5,219,515.5],[220.5,512.5,220.5,512.5,220.5,512.5,220.5,512.5,220.5,512.5],[218.5,516.5,218.5,516.5,218.5,516.5,218.5,516.5,218.5,516.5],[216.5,515.5,216.5,515.5,216.5,515.5,216.5,515.5,216.5,515.5],[225,520.5,225,520.5,225,520.5,225,520.5,225,520.5],[228,515.5,228,515.5,228,515.5,228,515.5,228,515.5],[223,520,223,520,223,520,223,520,223,520],[225.5,521.5,225.5,521.5,225.5,521.5,225.5,521.5,225.5,521.5],[220,527,220,527,220,527,220,527,220,527],[222.5,523,222.5,523,222.5,523,222.5,523,222.5,523],[223,519,223,519,223,519,223,519,223,519],[221,518.5,221,518.5,221,518.5,221,518.5,221,518.5],[222.5,517,222.5,517,222.5,517,222.5,517,222.5,517],[221.5,517,221.5,517,221.5,517,221.5,517,221.5,517],[229.5,514.5,229.5,514.5,229.5,514.5,229.5,514.5,229.5,514.5],[227.5,513,227.5,513,227.5,513,227.5,513,227.5,513],[225,519.5,225,519.5,225,519.5,225,519.5,225,519.5],[224.5,516.5,224.5,516.5,224.5,516.5,224.5,516.5,224.5,516.5],[224,515.5,224,515.5,224,515.5,224,515.5,224,515.5],[222,519,222,519,222,519,222,519,222,519],[220,517,220,517,220,517,220,517,220,517],[222,515.5,222,515.5,222,515.5,222,515.5,222,515.5],[224,515,224,515,224,515,224,515,224,515],[222.5,516.5,222.5,516.5,222.5,516.5,222.5,516.5,222.5,516.5],[228,517,228,517,228,517,228,517,228,517],[227,518.5,227,518.5,227,518.5,227,518.5,227,518.5],[226,519.5,226,519.5,226,519.5,226,519.5,226,519.5],[220.5,519,220.5,519,220.5,519,220.5,519,220.5,519],[225.5,520,225.5,520,225.5,520,225.5,520,225.5,520],[224,510.5,224,510.5,224,510.5,224,510.5,224,510.5],[221.5,515,221.5,515,221.5,515,221.5,515,221.5,515],[223,513,223,513,223,513,223,513,223,513],[225,510.5,225,510.5,225,510.5,225,510.5,225,510.5],[227,506.5,227,506.5,227,506.5,227,506.5,227,506.5],[225.5,511.5,225.5,511.5,225.5,511.5,225.5,511.5,225.5,511.5],[224,514.5,224,514.5,224,514.5,224,514.5,224,514.5],[221,516.5,221,516.5,221,516.5,221,516.5,221,516.5],[226,518.5,226,518.5,226,518.5,226,518.5,226,518.5],[222.5,521.5,222.5,521.5,222.5,521.5,222.5,521.5,222.5,521.5],[225,513,225,513,225,513,225,513,225,513],[222,514,222,514,222,514,222,514,222,514],[228.5,513.5,228.5,513.5,228.5,513.5,228.5,513.5,228.5,513.5],[227,511,227,511,227,511,227,511,227,511],[224.5,519.5,224.5,519.5,224.5,519.5,224.5,519.5,224.5,519.5],[223,521,223,521,223,521,223,521,223,521],[225.5,515,225.5,515,225.5,515,225.5,515,225.5,515],[223,517,223,517,223,517,223,517,223,517],[226,511,226,511,226,511,226,511,226,511],[227,511.5,227,511.5,227,511.5,227,511.5,227,511.5],[227,510.5,227,510.5,227,510.5,227,510.5,227,510.5],[228,509.5,228,509.5,228,509.5,228,509.5,228,509.5],[231,508.5,231,508.5,231,508.5,231,508.5,231,508.5],[229.5,508,229.5,508,229.5,508,229.5,508,229.5,508],[231.5,509,231.5,509,231.5,509,231.5,509,231.5,509],[233,504,233,504,233,504,233,504,233,504],[231,506.5,231,506.5,231,506.5,231,506.5,231,506.5]],\"timestamp\":[1515289299845,1515289301463,1515289302896,1515289304145,1515289305445,1515289306709,1515289307912,1515289314569,1515289316012,1515289317645,1515289318995,1515289320297,1515289321811,1515289323465,1515289325128,1515289326811,1515289328580,1515289330312,1515289332265,1515289334134,1515289335894,1515289337412,1515289339168,1515289340516,1515289342196,1515289343898,1515289345417,1515289347262,1515289348829,1515289350013,1515289351497,1515289352813,1515289354398,1515289356114,1515289357849,1515289359399,1515289361140,1515289362533,1515289363915,1515289365480,1515289367332,1515289369098,1515289370834,1515289372131,1515289373315,1515289377878,1515289379249,1515289380984,1515289382650,1515289384317,1515289385754,1515289387702,1515289389503,1515289391018,1515289392934,1515289394569,1515289395966,1515289397567,1515289398967,1515289400619,1515289401704,1515289403220,1515289404868,1515289406094,1515289407518,1515289408965],\"version\":2}"}

**Comment by mousehaow** [comment]
脚本的数据steps里面全是空的。。。

**Comment by soysaucemo** [comment]
哪个版本的脚本？

**Comment by mousehaow** [comment]
@soysaucemo ios的脚本

**Comment by nicky918** [comment]
不错，挺厉害的。

**Comment by cqllang** [comment]
按下的位置点不一样？应该也弄个随机的区间值？

**Comment by cqllang** [comment]
还有一个怀疑是获取了手机传感器 数据，正常拿在手上玩和放在桌子上机器跑传感器数据应该不一样

**Comment by IurKwan** [comment]
安卓表示还可以

**Comment by mousehaow** [comment]
@lurKwan 安卓在一个点swipe有用么？iOS的通过wda的swipe按压时间貌似和距离有关，按压系数就要变成动态的了

**Comment by ysy950803** [comment]
step是个什么字段？表示啥意思？

**Comment by cdrlee** [comment]
steps 是这两天新加的字段？看前几天的包没这个。

**Comment by soysaucemo** [comment]
```
{var i={
seed:this.game.randomSeed,
action:this.game.actionList,
musicList:this.game.musicList,
touchList:this.game.touchList,
steps:this.game.touchMoveList,
timestamp:this.game.touchStartTime,
version:2}
```
version 6 的game.js已经有这些了

**Comment by SupremeLiam** [comment]
version 6 的版本在哪里？有链接吗

**Comment by wenll** [comment]
先自动后手动，或者先手动后自动，抓一下包，看看steps是否存在呢？

**Comment by awwwq** [comment]
@wenll  先用脚本最后手动 steps 有最后一部分，前面全是空的

**Comment by lihuangshuaige** [comment]
关注下 不明觉厉
