### ISSUE TITLE
有没有人在mac上面试过,我的华为手机在window上面是可以正常跑的,但是到了mac上面就不好使,老是跳的比预期的远

### ISSUE THREAD

**Issue by zhouruifeng** [wangshub/wechat_jump_game#991]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by MrLevo520** [comment]
请使用最新版或者nightly版本，下次提交issue请注意规范
