### ISSUE TITLE
代码执行os.system(cmd)  总是报Error Invalid arguments for command :swipe

### ISSUE THREAD

**Issue by feitiandemiaomi** [wangshub/wechat_jump_game#993]
VERSION = "1.1.1"
Screen:/system/bin/sh: wm: not found
Density:/system/bin/sh:wm:not found
Device:NX403A
Phone OS:4.2.2
Host OS:win32
Python:2.7.12 |Anaconda custom(64-bit)
<!--

遇到问题：
执行auto脚本：
def jump(distance):
    """
    跳跃一定的距离
    """
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input  swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
        duration=press_time
    )
    print(cmd)
    os.system(cmd)
    return press_time
错误信息如下：
adb shell input swipe 357 1061 357 1061 477
Error Invalid arguments for command :swipe
usage: input ...
          input text (string)
          input keyevent <key code number or name>
          ...

然后我单独在pc终端使用命令：adb shell input swipe 20 40 20 41 30,棋子就可以跳动，但是程序里面的语句没有问题，却一直提示swipe错误，这让我一直费解。
另外，我把程序中最后那个时间参数去掉，只保留四个坐标参数，棋子也可以跳动，所以是我的手机的问题吗？

**Comment by feitiandemiaomi** [comment]
def jump(distance):
    """
    跳跃一定的距离
    """
    press_time = distance * press_coefficient
    press_time = max(press_time, 200)   # 设置 200ms 是最小的按压时间
    press_time = int(press_time)
    cmd = 'adb shell input  swipe {x1} {y1} {x2} {y2} {duration}'.format(
        x1=swipe_x1,
        y1=swipe_y1,
        x2=swipe_x2,
        y2=swipe_y2,
        duration=press_time
    )
    print(cmd)
    os.system(cmd)
    return press_time

错误如下：
adb shell input swipe 320 1058 320 1058 477
Error Invalid arguments for command :swipe 
usage ：input ...
             input text <string>
             ...

我尝试改为  cmd = 'adb shell input  touchscreen swipe {x1} {y1} {x2} {y2} {duration}'.format(    ,然而依然报错，我后来直接在终端操作命令：adb shell input swipe 20 40 20 41 30 ,棋子可以跳动，但是脚本里面的死活就是不对，另外我也尝试了将最后一个时间参数去掉，保留四个坐标参数，棋子也可以跳动，但是，五个参数总是报Error Invalid arguments for command :swipe ，是因为手机android版本低的原因吗

**Comment by cloudy-liu** [comment]
@feitiandemiaomi 你的是 android  4.2.2。swipe命令应该没有duration 这个参数。你可以用如下cmd 确认一下。查看swipe 是否有 duration 这个参数。
`adb shell input swipe -h `

我的是 android 7.1

The commands and default sources are:
      text <string> (Default: touchscreen)
      keyevent [--longpress] <key code number or name> ... (Default: keyboard)
      tap <x> <y> (Default: touchscreen)
      **swipe <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)**  // 看这个duration参数是否有
      press (Default: trackball)
      roll <dx> <dy> (Default: trackball)
      tmode <tmode>

**Comment by minifive** [comment]
检查参数类型，swipe 5个参数都要是整形，可以先输出看一下
