### ISSUE TITLE
下载的win的，双击.exe，啥反应没有，也没个日志文件。确定能用？

### ISSUE THREAD

**Issue by alibbbian** [wangshub/wechat_jump_game#996]
程序版本号：x.x.x
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
Device: x
Phone OS: x
Host OS: x
Python: x
**********

遇到问题：

改进和建议：无

**Comment by coderchaser** [comment]
为什么要点exe?这是运行python脚本的啊
